-- ============================================================
-- DB-03 - INVENTARIO Y ESTADISTICAS ORACLE - SOLO LECTURA
-- Prohibido agregar DDL/DML a este archivo.
-- ============================================================

DECLARE
  v_schema VARCHAR2(128);
BEGIN
  SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
    INTO v_schema
    FROM DUAL;

  IF UPPER(v_schema) <> 'RIESGO_LAVADO' THEN
    RAISE_APPLICATION_ERROR(-20301,
      'DB-03 BLOQUEADO: CURRENT_SCHEMA debe ser RIESGO_LAVADO.');
  END IF;
END;
/

PROMPT === IDENTIDAD DEL AMBIENTE (SIN CREDENCIALES) ===
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV', 'SESSION_USER')   AS SESSION_USER,
       SYS_CONTEXT('USERENV', 'DB_NAME')        AS DB_NAME,
       SYS_CONTEXT('USERENV', 'SERVER_HOST')    AS SERVER_HOST
  FROM DUAL;

PROMPT === PLAN_TABLE DISPONIBLE ===
SELECT COUNT(*) AS PLAN_TABLE_EN_SCHEMA
  FROM USER_TABLES
 WHERE TABLE_NAME = 'PLAN_TABLE';

PROMPT === ESTADISTICAS DE TABLAS CRITICAS ===
SELECT TABLE_NAME,
       NUM_ROWS,
       BLOCKS,
       AVG_ROW_LEN,
       LAST_ANALYZED,
       STALE_STATS
  FROM USER_TAB_STATISTICS
 WHERE TABLE_NAME IN (
       'RL_MR_FAMILIAS_FORMULARIO',
       'RL_MR_VERSIONES_FORMULARIO',
       'RL_MR_RIESGOS',
       'RL_MR_EVALUACIONES_RIESGO',
       'RL_MR_PROYECCIONES_EVALUACION',
       'RL_MR_FLUJOS_EVALUACION',
       'RL_MR_CONTROLES_RIESGO',
       'RL_MR_EVALUACIONES_CONTROL',
       'RL_MR_PLANES',
       'RL_MR_ACTIVIDADES',
       'RL_MR_SENALES_ALERTA',
       'RL_MR_AUTOMONITOREO',
       'RL_MR_EVIDENCIAS',
       'RL_MR_EVIDENCIAS_VINCULOS',
       'RL_AUDITORIA')
 ORDER BY TABLE_NAME;

PROMPT === CARDINALIDAD REAL DE TABLAS DE MAYOR IMPACTO ===
SELECT 'RL_MR_EVALUACIONES_RIESGO' TABLA, COUNT(*) FILAS FROM RL_MR_EVALUACIONES_RIESGO
UNION ALL SELECT 'RL_MR_PROYECCIONES_EVALUACION', COUNT(*) FROM RL_MR_PROYECCIONES_EVALUACION
UNION ALL SELECT 'RL_MR_FLUJOS_EVALUACION', COUNT(*) FROM RL_MR_FLUJOS_EVALUACION
UNION ALL SELECT 'RL_MR_PLANES', COUNT(*) FROM RL_MR_PLANES
UNION ALL SELECT 'RL_MR_ACTIVIDADES', COUNT(*) FROM RL_MR_ACTIVIDADES
UNION ALL SELECT 'RL_MR_SENALES_ALERTA', COUNT(*) FROM RL_MR_SENALES_ALERTA
UNION ALL SELECT 'RL_MR_AUTOMONITOREO', COUNT(*) FROM RL_MR_AUTOMONITOREO
UNION ALL SELECT 'RL_AUDITORIA', COUNT(*) FROM RL_AUDITORIA
ORDER BY 1;

PROMPT === INDICES EXISTENTES EN TABLAS CRITICAS ===
SELECT i.TABLE_NAME,
       i.INDEX_NAME,
       i.UNIQUENESS,
       i.STATUS,
       i.BLEVEL,
       i.LEAF_BLOCKS,
       i.DISTINCT_KEYS,
       i.CLUSTERING_FACTOR,
       i.NUM_ROWS,
       i.LAST_ANALYZED
  FROM USER_INDEXES i
 WHERE i.TABLE_NAME IN (
       'RL_MR_FAMILIAS_FORMULARIO',
       'RL_MR_VERSIONES_FORMULARIO',
       'RL_MR_RIESGOS',
       'RL_MR_EVALUACIONES_RIESGO',
       'RL_MR_PROYECCIONES_EVALUACION',
       'RL_MR_FLUJOS_EVALUACION',
       'RL_MR_CONTROLES_RIESGO',
       'RL_MR_EVALUACIONES_CONTROL',
       'RL_MR_PLANES',
       'RL_MR_ACTIVIDADES',
       'RL_MR_SENALES_ALERTA',
       'RL_MR_AUTOMONITOREO',
       'RL_MR_EVIDENCIAS',
       'RL_MR_EVIDENCIAS_VINCULOS',
       'RL_AUDITORIA')
 ORDER BY i.TABLE_NAME, i.INDEX_NAME;

PROMPT === COLUMNAS Y ORDEN DE INDICES ===
SELECT c.TABLE_NAME,
       c.INDEX_NAME,
       c.COLUMN_POSITION,
       c.COLUMN_NAME,
       c.DESCEND
  FROM USER_IND_COLUMNS c
 WHERE c.TABLE_NAME IN (
       'RL_MR_FAMILIAS_FORMULARIO',
       'RL_MR_VERSIONES_FORMULARIO',
       'RL_MR_RIESGOS',
       'RL_MR_EVALUACIONES_RIESGO',
       'RL_MR_PROYECCIONES_EVALUACION',
       'RL_MR_FLUJOS_EVALUACION',
       'RL_MR_CONTROLES_RIESGO',
       'RL_MR_EVALUACIONES_CONTROL',
       'RL_MR_PLANES',
       'RL_MR_ACTIVIDADES',
       'RL_MR_SENALES_ALERTA',
       'RL_MR_AUTOMONITOREO',
       'RL_MR_EVIDENCIAS',
       'RL_MR_EVIDENCIAS_VINCULOS',
       'RL_AUDITORIA')
 ORDER BY c.TABLE_NAME, c.INDEX_NAME, c.COLUMN_POSITION;

PROMPT === ESTADISTICAS DE COLUMNAS USADAS EN FILTROS/ORDEN ===
SELECT TABLE_NAME,
       COLUMN_NAME,
       NUM_DISTINCT,
       NUM_NULLS,
       DENSITY,
       HISTOGRAM,
       LAST_ANALYZED
  FROM USER_TAB_COL_STATISTICS
 WHERE (TABLE_NAME = 'RL_MR_EVALUACIONES_RIESGO'
        AND COLUMN_NAME IN ('EVA_ID','EVA_RIESGO_ID','EVA_ACTIVO','EVA_FECHA_REGISTRO'))
    OR (TABLE_NAME = 'RL_MR_PROYECCIONES_EVALUACION'
        AND COLUMN_NAME IN ('PROY_EVALUACION_ID','PROY_AREA_PRINCIPAL','PROY_NIVEL_RESIDUAL','PROY_ESTADO_EVALUACION','PROY_FECHA_EVAL'))
    OR (TABLE_NAME = 'RL_MR_FLUJOS_EVALUACION'
        AND COLUMN_NAME IN ('FLU_EVALUACION_ID','FLU_ESTADO','FLU_FECHA','FLU_ID'))
    OR (TABLE_NAME = 'RL_MR_SENALES_ALERTA'
        AND COLUMN_NAME IN ('ALE_EVALUACION_ID','ALE_ESTADO','ALE_FECHA_DISPARO'))
    OR (TABLE_NAME = 'RL_MR_AUTOMONITOREO'
        AND COLUMN_NAME IN ('MON_EVALUACION_ID','MON_FECHA'))
    OR (TABLE_NAME = 'RL_AUDITORIA'
        AND COLUMN_NAME IN ('AUD_ID','AUD_ACCION','AUD_MODULO','AUD_TABLA','AUD_FECHA','AUD_USR_ID','AUD_USR_EMAIL','AUD_IP','AUD_REGISTRO_ID'))
 ORDER BY TABLE_NAME, COLUMN_NAME;

PROMPT === FIN INVENTARIO DB-03 SOLO LECTURA ===
