-- ============================================================
-- DB-03 - EXPLAIN PLAN DE CONSULTAS CRITICAS REALES
-- EXPLAIN PLAN es DML diagnostico sobre PLAN_TABLE; no ejecuta
-- las consultas explicadas ni modifica tablas RL_*.
-- El ROLLBACK final descarta las filas diagnosticas de esta sesion.
-- ============================================================

SET PAGESIZE 500
SET LINESIZE 240
SET LONG 100000
SET LONGCHUNKSIZE 100000

COLUMN DB03_RUN_ID NEW_VALUE DB03_RUN_ID NOPRINT
SELECT TO_CHAR(SYSTIMESTAMP, 'MMDDHH24MISSFF3') AS DB03_RUN_ID FROM DUAL;

VARIABLE familiaCodigo VARCHAR2(50)
VARIABLE evaId NUMBER
VARIABLE riesgoId NUMBER
VARIABLE estado VARCHAR2(30)
VARIABLE area VARCHAR2(100)
VARIABLE nivelResidual VARCHAR2(20)
VARIABLE filaFinal NUMBER
VARIABLE filaInicial NUMBER
VARIABLE evaluacionId NUMBER
VARIABLE moduloFilter VARCHAR2(100)
VARIABLE tablaFilter VARCHAR2(100)
VARIABLE accionFilter VARCHAR2(30)
VARIABLE fechaInicioFilter DATE
VARIABLE fechaFinFilter DATE
VARIABLE buscarFilter VARCHAR2(200)
VARIABLE maxRow NUMBER
VARIABLE minRow NUMBER

EXEC :familiaCodigo := 'MATRIZ_RIESGOS_LAFT';
EXEC :evaId := 1;
EXEC :riesgoId := 1;
EXEC :estado := 'APROBADA';
EXEC :area := 'AREA_REFERENCIA';
EXEC :nivelResidual := 'ALTO';
EXEC :filaFinal := 50;
EXEC :filaInicial := 0;
EXEC :evaluacionId := 1;
EXEC :moduloFilter := 'MatricesRiesgos';
EXEC :tablaFilter := 'RL_MR_EVALUACIONES_RIESGO';
EXEC :accionFilter := 'UPDATE';
EXEC :fechaInicioFilter := TRUNC(SYSDATE) - 30;
EXEC :fechaFinFilter := TRUNC(SYSDATE) + 1 - (1/86400);
EXEC :buscarFilter := '%admin%';
EXEC :maxRow := 50;
EXEC :minRow := 0;

PROMPT === DB03_Q01 VERSION VIGENTE DE FORMULARIO POR FAMILIA ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q01_&DB03_RUN_ID' FOR
SELECT v.VER_ID,
       v.VER_FAMILIA_ID,
       v.VER_CODIGO,
       v.VER_VERSION,
       v.VER_JSON,
       v.VER_HASH,
       v.VER_ESTADO,
       v.VER_VIGENTE,
       v.VER_FECHA_INICIO,
       v.VER_FECHA_FIN,
       v.VER_FECHA_CREACION,
       v.VER_USR_CREACION
  FROM RL_MR_VERSIONES_FORMULARIO v
  JOIN RL_MR_FAMILIAS_FORMULARIO f
    ON f.FAM_ID = v.VER_FAMILIA_ID
 WHERE f.FAM_CODIGO = :familiaCodigo
   AND v.VER_ESTADO = 'PUBLISHED'
   AND v.VER_VIGENTE = 1;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q01_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q02 PAGINACION DE EVALUACIONES SIN FILTROS OPCIONALES ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q02_&DB03_RUN_ID' FOR
SELECT *
  FROM (
        SELECT q.*, ROWNUM NUMERO_FILA
          FROM (
                SELECT e.EVA_ID,
                       e.EVA_RIESGO_ID,
                       e.EVA_VERSION_ID,
                       NVL(f.FLU_ESTADO, 'BORRADOR') FLU_ESTADO,
                       e.EVA_DATOS_JSON,
                       e.EVA_CALCULOS_JSON,
                       p.PROY_VRI,
                       CAST(NULL AS NUMBER) VALOR_RESERVADO,
                       p.PROY_VRR,
                       e.EVA_FECHA_REGISTRO,
                       e.EVA_USR_REGISTRO,
                       e.EVA_VERSION_ROW,
                       e.EVA_ACTIVO
                  FROM RL_MR_EVALUACIONES_RIESGO e
                  LEFT JOIN RL_MR_PROYECCIONES_EVALUACION p
                    ON p.PROY_EVALUACION_ID = e.EVA_ID
                  LEFT JOIN (
                        SELECT FLU_EVALUACION_ID, FLU_ESTADO
                          FROM (
                                SELECT FLU_EVALUACION_ID,
                                       FLU_ESTADO,
                                       ROW_NUMBER() OVER (
                                           PARTITION BY FLU_EVALUACION_ID
                                           ORDER BY FLU_FECHA DESC, FLU_ID DESC
                                       ) RN
                                  FROM RL_MR_FLUJOS_EVALUACION
                               )
                         WHERE RN = 1
                  ) f
                    ON f.FLU_EVALUACION_ID = e.EVA_ID
                 WHERE e.EVA_ACTIVO = 1
                 ORDER BY e.EVA_FECHA_REGISTRO DESC, e.EVA_ID DESC
               ) q
         WHERE ROWNUM <= :filaFinal
       )
 WHERE NUMERO_FILA > :filaInicial;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q02_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q03 PAGINACION DE EVALUACIONES CON FILTROS COMPLETOS ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q03_&DB03_RUN_ID' FOR
SELECT *
  FROM (
        SELECT q.*, ROWNUM NUMERO_FILA
          FROM (
                SELECT e.EVA_ID,
                       e.EVA_RIESGO_ID,
                       e.EVA_VERSION_ID,
                       NVL(f.FLU_ESTADO, 'BORRADOR') FLU_ESTADO,
                       e.EVA_DATOS_JSON,
                       e.EVA_CALCULOS_JSON,
                       p.PROY_VRI,
                       CAST(NULL AS NUMBER) VALOR_RESERVADO,
                       p.PROY_VRR,
                       e.EVA_FECHA_REGISTRO,
                       e.EVA_USR_REGISTRO,
                       e.EVA_VERSION_ROW,
                       e.EVA_ACTIVO
                  FROM RL_MR_EVALUACIONES_RIESGO e
                  LEFT JOIN RL_MR_PROYECCIONES_EVALUACION p
                    ON p.PROY_EVALUACION_ID = e.EVA_ID
                  LEFT JOIN (
                        SELECT FLU_EVALUACION_ID, FLU_ESTADO
                          FROM (
                                SELECT FLU_EVALUACION_ID,
                                       FLU_ESTADO,
                                       ROW_NUMBER() OVER (
                                           PARTITION BY FLU_EVALUACION_ID
                                           ORDER BY FLU_FECHA DESC, FLU_ID DESC
                                       ) RN
                                  FROM RL_MR_FLUJOS_EVALUACION
                               )
                         WHERE RN = 1
                  ) f
                    ON f.FLU_EVALUACION_ID = e.EVA_ID
                 WHERE e.EVA_ACTIVO = 1
                   AND e.EVA_RIESGO_ID = :riesgoId
                   AND f.FLU_ESTADO = :estado
                   AND p.PROY_AREA_PRINCIPAL = :area
                   AND p.PROY_NIVEL_RESIDUAL = :nivelResidual
                 ORDER BY e.EVA_FECHA_REGISTRO DESC, e.EVA_ID DESC
               ) q
         WHERE ROWNUM <= :filaFinal
       )
 WHERE NUMERO_FILA > :filaInicial;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q03_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q04 CONSOLIDADO TIPADO DE MATRICES ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q04_&DB03_RUN_ID' FOR
SELECT e.EVA_RIESGO_ID,
       p.PROY_EVALUACION_ID,
       e.EVA_VERSION_ID,
       p.PROY_CODIGO_RIESGO,
       p.PROY_AREA_PRINCIPAL,
       p.PROY_DUENO_RIESGO,
       p.PROY_VRI,
       p.PROY_NIVEL_INHERENTE,
       p.PROY_VRR,
       p.PROY_NIVEL_RESIDUAL,
       p.PROY_RESPUESTA_RIESGO,
       p.PROY_ESTADO_EVALUACION,
       p.PROY_FECHA_EVAL
  FROM RL_MR_PROYECCIONES_EVALUACION p
  JOIN RL_MR_EVALUACIONES_RIESGO e
    ON e.EVA_ID = p.PROY_EVALUACION_ID
 WHERE e.EVA_ACTIVO = 1
 ORDER BY p.PROY_FECHA_EVAL DESC, p.PROY_EVALUACION_ID DESC;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q04_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q05 HISTORIAL DE FLUJOS POR EVALUACION ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q05_&DB03_RUN_ID' FOR
SELECT FLU_ID, FLU_EVALUACION_ID, FLU_ESTADO, FLU_MOTIVO, FLU_USR_ID, FLU_FECHA
  FROM RL_MR_FLUJOS_EVALUACION
 WHERE FLU_EVALUACION_ID = :evaluacionId
 ORDER BY FLU_FECHA DESC, FLU_ID DESC;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q05_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q06 RESUMEN OPERATIVO / DASHBOARD ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q06_&DB03_RUN_ID' FOR
SELECT
  (SELECT COUNT(*) FROM RL_MR_RIESGOS WHERE RIE_ACTIVO = 1) RIESGOS_ACTIVOS,
  (SELECT COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO WHERE EVA_ACTIVO = 1) EVALUACIONES_ACTIVAS,
  (SELECT COUNT(*) FROM RL_MR_PROYECCIONES_EVALUACION WHERE PROY_ESTADO_EVALUACION = 'APROBADA') EVALUACIONES_APROBADAS,
  (SELECT COUNT(*) FROM RL_MR_PROYECCIONES_EVALUACION WHERE UPPER(PROY_NIVEL_RESIDUAL) IN ('ALTO','CRITICO')) ALTO_CRITICO,
  (SELECT COUNT(*) FROM RL_MR_SENALES_ALERTA WHERE ALE_ESTADO = 'ACTIVO') ALERTAS_ACTIVAS,
  (SELECT COUNT(*) FROM RL_MR_PLANES WHERE UPPER(PLA_ESTADO) NOT IN ('CERRADO','COMPLETADO','FINALIZADO')) PLANES_ABIERTOS,
  (SELECT COUNT(*) FROM RL_MR_ACTIVIDADES
    WHERE ACT_FECHA_FIN < TRUNC(SYSDATE)
      AND UPPER(ACT_ESTADO) NOT IN ('CERRADA','COMPLETADA','FINALIZADA')) ACTIVIDADES_VENCIDAS,
  (SELECT COUNT(*) FROM RL_MR_AUTOMONITOREO WHERE MON_FECHA >= SYSDATE - 30) MONITOREOS_30
FROM DUAL;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q06_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q07 ALERTAS POR EVALUACION ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q07_&DB03_RUN_ID' FOR
SELECT ALE_ID, ALE_EVALUACION_ID, ALE_CODIGO, ALE_INDICADOR, ALE_ESTADO, ALE_FECHA_DISPARO
  FROM RL_MR_SENALES_ALERTA
 WHERE ALE_EVALUACION_ID = :evaluacionId
 ORDER BY NVL(ALE_FECHA_DISPARO, DATE '1900-01-01') DESC, ALE_ID DESC;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q07_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q08 AUTOMONITOREO POR EVALUACION ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q08_&DB03_RUN_ID' FOR
SELECT MON_ID, MON_EVALUACION_ID, MON_ESTADO_RIESGO, MON_ESTADO_CONTR,
       MON_RESULTADO, MON_USR_ID, MON_FECHA
  FROM RL_MR_AUTOMONITOREO
 WHERE MON_EVALUACION_ID = :evaluacionId
 ORDER BY MON_FECHA DESC, MON_ID DESC;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q08_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q09 AUDITORIA PAGINADA CON FILTROS EXACTOS Y FECHA ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q09_&DB03_RUN_ID' FOR
SELECT * FROM (
    SELECT a.*, ROWNUM rnum FROM (
        SELECT AUD_ID, AUD_TABLA, AUD_REGISTRO_ID, AUD_ACCION,
               AUD_DATOS_ANT, AUD_DATOS_NVO, AUD_USR_ID,
               NVL((SELECT USR_NOMBRE || ' ' || USR_APELLIDO
                      FROM RL_USUARIOS
                     WHERE USR_ID = AUD_USR_ID), AUD_USR_EMAIL) AS AUD_USR_EMAIL,
               AUD_IP, AUD_FECHA, AUD_MODULO
          FROM RL_AUDITORIA
         WHERE AUD_ACCION = :accionFilter
           AND AUD_MODULO = :moduloFilter
           AND AUD_TABLA = :tablaFilter
           AND AUD_FECHA >= :fechaInicioFilter
           AND AUD_FECHA <= :fechaFinFilter
         ORDER BY AUD_FECHA DESC, AUD_ID DESC
    ) a WHERE ROWNUM <= :maxRow
) WHERE rnum > :minRow;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q09_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q10 AUDITORIA PAGINADA CON BUSQUEDA DE SUBCADENA ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q10_&DB03_RUN_ID' FOR
SELECT * FROM (
    SELECT a.*, ROWNUM rnum FROM (
        SELECT AUD_ID, AUD_TABLA, AUD_REGISTRO_ID, AUD_ACCION,
               AUD_DATOS_ANT, AUD_DATOS_NVO, AUD_USR_ID,
               NVL((SELECT USR_NOMBRE || ' ' || USR_APELLIDO
                      FROM RL_USUARIOS
                     WHERE USR_ID = AUD_USR_ID), AUD_USR_EMAIL) AS AUD_USR_EMAIL,
               AUD_IP, AUD_FECHA, AUD_MODULO
          FROM RL_AUDITORIA
         WHERE (LOWER(AUD_USR_EMAIL) LIKE :buscarFilter
             OR LOWER(NVL(AUD_USR_EMAIL,
                    (SELECT USR_EMAIL FROM RL_USUARIOS WHERE USR_ID = AUD_USR_ID))) LIKE :buscarFilter
             OR LOWER(AUD_TABLA) LIKE :buscarFilter
             OR LOWER(AUD_IP) LIKE :buscarFilter
             OR LOWER(AUD_REGISTRO_ID) LIKE :buscarFilter)
         ORDER BY AUD_FECHA DESC, AUD_ID DESC
    ) a WHERE ROWNUM <= :maxRow
) WHERE rnum > :minRow;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q10_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB03_Q11 METODOLOGIA DINAMICA VIGENTE ===
EXPLAIN PLAN SET STATEMENT_ID = 'D3Q11_&DB03_RUN_ID' FOR
SELECT VER_ID, VER_CODIGO, VER_VERSION, VER_JSON
  FROM (
        SELECT VER_ID, VER_CODIGO, VER_VERSION, VER_JSON
          FROM RL_MR_VERSIONES_FORMULARIO
         WHERE VER_ESTADO = 'PUBLISHED'
           AND VER_VIGENTE = 1
         ORDER BY VER_FECHA_INICIO DESC, VER_ID DESC
       )
 WHERE ROWNUM = 1;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'D3Q11_&DB03_RUN_ID', 'TYPICAL +ALIAS +PREDICATE'));

PROMPT === DB-03: DESCARTANDO FILAS DIAGNOSTICAS DE PLAN_TABLE ===
ROLLBACK;

UNDEFINE DB03_RUN_ID
PROMPT === FIN EXPLAIN PLAN DB-03 ===
