SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET PAGESIZE 300
SET LINESIZE 220
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
SPOOL C:\RIESGO_LAVADO\docs\3. Módulo Matrices de Riesgos\Fase 3 - Modelo de datos y arquitectura Oracle\Evidencia_DBA\00_preflight_20260703_131425.log
PROMPT === IDENTIFICACION DE CONEXION ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','CURRENT_USER') AS CURRENT_USER,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','SERVER_HOST') AS SERVER_HOST
  FROM DUAL;
PROMPT === COLISIONES RL_MR ===
SELECT 'TABLAS_RL_MR' OBJETO, COUNT(*) TOTAL FROM USER_TABLES WHERE TABLE_NAME LIKE 'RL_MR_%'
UNION ALL
SELECT 'SECUENCIAS_RL_MR' OBJETO, COUNT(*) TOTAL FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'SEQ_RL_MR_%'
UNION ALL
SELECT 'INDICES_RL_MR' OBJETO, COUNT(*) TOTAL FROM USER_INDEXES WHERE INDEX_NAME LIKE '%RL_MR%';
PROMPT === MODULO MATRICES ===
SELECT MOD_ID, MOD_NOMBRE, MOD_RUTA, MOD_ACTIVO FROM RL_MODULOS WHERE MOD_ID = 10 OR MOD_RUTA = '/matrices-riesgos';
PROMPT === ESTRUCTURA RL_USUARIO_MODULOS ===
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, NULLABLE FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RL_USUARIO_MODULOS' ORDER BY COLUMN_ID;
PROMPT === USUARIOS INICIALES ===
SELECT USR_ID, USR_EMAIL FROM RL_USUARIOS WHERE USR_ID IN (1,2) ORDER BY USR_ID;
SPOOL OFF
EXIT
