SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET PAGESIZE 500
SET LINESIZE 240
SET SERVEROUTPUT ON
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
SPOOL "C:\tmp\mr_dba_20260703_131705\04_validacion_post_ejecucion.log" REPLACE
PROMPT === IDENTIFICACION POSTERIOR ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','SERVER_HOST') AS SERVER_HOST
  FROM DUAL;
PROMPT === OBJETOS CREADOS ===
SELECT 'TABLAS_RL_MR' OBJETO, COUNT(*) TOTAL FROM USER_TABLES WHERE TABLE_NAME LIKE 'RL_MR_%'
UNION ALL
SELECT 'SECUENCIAS_RL_MR' OBJETO, COUNT(*) TOTAL FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'SEQ_RL_MR_%'
UNION ALL
SELECT 'INDICES_RL_MR' OBJETO, COUNT(*) TOTAL FROM USER_INDEXES WHERE INDEX_NAME LIKE '%RL_MR%';
PROMPT === TABLAS ===
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'RL_MR_%' ORDER BY TABLE_NAME;
PROMPT === SECUENCIAS ===
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'SEQ_RL_MR_%' ORDER BY SEQUENCE_NAME;
PROMPT === INDICES ===
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS FROM USER_INDEXES WHERE INDEX_NAME LIKE '%RL_MR%' ORDER BY INDEX_NAME;
PROMPT === MODULO ===
SELECT MOD_ID, MOD_NOMBRE, MOD_RUTA, MOD_ICONO, MOD_SECCION, MOD_ACTIVO FROM RL_MODULOS WHERE MOD_RUTA = '/matrices-riesgos';
PROMPT === PERMISOS INICIALES ===
SELECT USM_USR_ID, USM_MOD_ID FROM RL_USUARIO_MODULOS WHERE USM_MOD_ID = 10 ORDER BY USM_USR_ID;
PROMPT === MODELO ===
SELECT MRM_ID, MRM_NOMBRE, MRM_VERSION, MRM_ESTADO FROM RL_MR_MODELOS WHERE MRM_VERSION = '1.0';
PROMPT === FACTORES ===
SELECT MRF_CODIGO, MRF_NOMBRE, MRF_PESO_INSTITUCIONAL FROM RL_MR_FACTORES ORDER BY MRF_ORDEN;
PROMPT === VARIABLES POR FACTOR ===
SELECT MRF.MRF_CODIGO, COUNT(*) VARIABLES, SUM(MRV.MRV_PESO_INTERNO) PESO_INTERNO_TOTAL
  FROM RL_MR_FACTORES MRF
  JOIN RL_MR_VARIABLES MRV ON MRV.MRV_FACTOR_ID = MRF.MRF_ID
 WHERE MRV.MRV_ESTADO_REGISTRO = 1
 GROUP BY MRF.MRF_CODIGO
 ORDER BY MRF.MRF_CODIGO;
PROMPT === ESCALAS POR TIPO ===
SELECT MRE_TIPO, COUNT(*) TOTAL FROM RL_MR_ESCALAS GROUP BY MRE_TIPO ORDER BY MRE_TIPO;
PROMPT === ESTADO OBSERVADA EN CONSTRAINT ===
SELECT CONSTRAINT_NAME, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_RL_MR_MAT_ESTADO';
PROMPT === COMENTARIOS ===
SELECT 'COMENTARIOS_TABLAS_RL_MR' TIPO, COUNT(*) TOTAL FROM USER_TAB_COMMENTS WHERE TABLE_NAME LIKE 'RL_MR_%' AND COMMENTS IS NOT NULL
UNION ALL
SELECT 'COMENTARIOS_COLUMNAS_RL_MR' TIPO, COUNT(*) TOTAL FROM USER_COL_COMMENTS WHERE TABLE_NAME LIKE 'RL_MR_%' AND COMMENTS IS NOT NULL;
PROMPT === OBJETOS INVALIDOS RL_MR ===
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM USER_OBJECTS WHERE OBJECT_NAME LIKE 'RL_MR_%' AND STATUS <> 'VALID' ORDER BY OBJECT_TYPE, OBJECT_NAME;
SPOOL OFF
EXIT
