SET ECHO OFF
SET FEEDBACK ON
SET HEADING ON
SET PAGESIZE 500
SET LINESIZE 260
SET SERVEROUTPUT ON SIZE UNLIMITED
SPOOL C:\tmp\mr_encoding_validate_20260703_141426\06_validacion_final_encoding_20260703_141426.log REPLACE
PROMPT === VALIDACION FINAL ENCODING COMENTARIOS RL_MR ===
SELECT COUNT(*) AS TAB_COMMENTS_BAD
  FROM USER_TAB_COMMENTS
 WHERE TABLE_NAME LIKE 'RL_MR_%'
   AND (ASCIISTR(COMMENTS) LIKE '%\00BF%' OR COMMENTS LIKE '%?%');

SELECT COUNT(*) AS COL_COMMENTS_BAD
  FROM USER_COL_COMMENTS
 WHERE TABLE_NAME LIKE 'RL_MR_%'
   AND (ASCIISTR(COMMENTS) LIKE '%\00BF%' OR COMMENTS LIKE '%?%');

PROMPT === VALIDACION FINAL ENCODING DATOS RL_MODULOS ===
SELECT COUNT(*) AS MODULOS_BAD
  FROM RL_MODULOS
 WHERE (MOD_ID = 10 OR MOD_RUTA = '/matrices-riesgos')
   AND (
        ASCIISTR(MOD_NOMBRE) LIKE '%\00BF%' OR MOD_NOMBRE LIKE '%?%'
     OR ASCIISTR(MOD_DESCRIPCION) LIKE '%\00BF%' OR MOD_DESCRIPCION LIKE '%?%'
     OR ASCIISTR(MOD_SECCION) LIKE '%\00BF%' OR MOD_SECCION LIKE '%?%'
   );

PROMPT === VALIDACION FINAL ENCODING DATOS RL_MR_* ===
DECLARE
  v_count NUMBER;
  v_sql   VARCHAR2(4000);
  v_total NUMBER := 0;
BEGIN
  FOR c IN (
    SELECT TABLE_NAME, COLUMN_NAME
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME LIKE 'RL_MR_%'
       AND DATA_TYPE IN ('VARCHAR2','CHAR','NVARCHAR2','NCHAR','CLOB')
     ORDER BY TABLE_NAME, COLUMN_ID
  ) LOOP
    v_sql := 'SELECT COUNT(*) FROM ' || c.TABLE_NAME ||
             ' WHERE ASCIISTR(' || c.COLUMN_NAME || ') LIKE ''%\00BF%'' OR ' || c.COLUMN_NAME || ' LIKE ''%?%''';
    EXECUTE IMMEDIATE v_sql INTO v_count;
    IF v_count > 0 THEN
      v_total := v_total + v_count;
      DBMS_OUTPUT.PUT_LINE(c.TABLE_NAME || '.' || c.COLUMN_NAME || ' = ' || v_count);
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('TOTAL_BAD_RL_MR_TEXT_COLUMNS = ' || v_total);
END;
/

PROMPT === MUESTRAS ASCIISTR CORRECTAS ===
SELECT MOD_ID, ASCIISTR(MOD_DESCRIPCION) AS MOD_DESC
  FROM RL_MODULOS
 WHERE MOD_ID = 10 OR MOD_RUTA = '/matrices-riesgos';

SELECT ASCIISTR(MRM_NOMBRE) AS MRM_NOMBRE, ASCIISTR(MRM_DESCRIPCION) AS MRM_DESC
  FROM RL_MR_MODELOS
 WHERE MRM_VERSION = '1.0'
   AND MRM_ESTADO_REGISTRO = 1;

SELECT MRE_TIPO, ASCIISTR(MRE_NIVEL) AS MRE_NIVEL, ASCIISTR(MRE_DESCRIPCION) AS MRE_DESC
  FROM RL_MR_ESCALAS
 WHERE MRE_NIVEL IN ('Cr?tico','D?bil')
 ORDER BY MRE_TIPO, MRE_ORDEN;

SELECT TABLE_NAME, ASCIISTR(COMMENTS) AS COMMENTS_ASCIISTR
  FROM USER_TAB_COMMENTS
 WHERE TABLE_NAME IN ('RL_MR_MODELOS','RL_MR_HISTORIAL')
 ORDER BY TABLE_NAME;
SPOOL OFF
EXIT
