-- FASE 7 - Matrices de Riesgos - preflight read-only.
-- No contiene DDL, DML, COMMIT ni cambios de estado.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET VERIFY OFF
SET FEEDBACK ON
SET PAGESIZE 200
SET LINESIZE 240
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_schema VARCHAR2(128);
  v_count NUMBER;
  PROCEDURE require_count(p_sql VARCHAR2, p_expected NUMBER, p_label VARCHAR2) IS
    v_actual NUMBER;
  BEGIN
    EXECUTE IMMEDIATE p_sql INTO v_actual;
    IF v_actual <> p_expected THEN
      RAISE_APPLICATION_ERROR(-20701, p_label || ' esperado=' || p_expected || ' actual=' || v_actual);
    END IF;
    DBMS_OUTPUT.PUT_LINE(p_label || '=' || v_actual);
  END;
BEGIN
  SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') INTO v_schema FROM DUAL;
  IF UPPER(v_schema) <> 'RIESGO_LAVADO' THEN
    RAISE_APPLICATION_ERROR(-20700, 'CURRENT_SCHEMA no autorizado: ' || v_schema);
  END IF;
  DBMS_OUTPUT.PUT_LINE('CURRENT_SCHEMA=' || v_schema);

  require_count(q'[SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME IN
    ('RL_MR_FAMILIAS_FORMULARIO','RL_MR_VERSIONES_FORMULARIO','RL_MR_CATALOGOS',
     'RL_MR_ELEMENTOS_CATALOGO','RL_MR_REGLAS_CALCULO','RL_MR_RIESGOS',
     'RL_MR_EVALUACIONES_RIESGO','RL_MR_PROYECCIONES_EVALUACION','RL_MR_FLUJOS_EVALUACION',
     'RL_MR_CONTROLES_RIESGO','RL_MR_EVALUACIONES_CONTROL','RL_MR_PLANES',
     'RL_MR_ACTIVIDADES','RL_MR_EVIDENCIAS','RL_MR_EVIDENCIAS_VINCULOS',
     'RL_MR_SENALES_ALERTA','RL_MR_AUTOMONITOREO','RL_MR_FORMULAS','RL_MR_FORMULA_USOS',
     'RL_MR_FORMULA_VERSIONES','RL_MR_FUNCION_ARGUMENTOS','RL_MR_FUNCIONES',
     'RL_MR_FUNCION_VERSIONES','RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES')]', 25, 'REQUIRED_TABLES');
  require_count(q'[SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME IN ('RL_USUARIOS','RL_AUDITORIA')]', 2, 'INSTITUTIONAL_TABLES');
  require_count(q'[SELECT COUNT(*) FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'SEQ_RL_MR_%']', 25, 'REQUIRED_SEQUENCES');
  require_count(q'[SELECT COUNT(*) FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_RL_AUDITORIA']', 1, 'AUDIT_SEQUENCE');

  require_count(q'[SELECT COUNT(*) FROM RL_MR_FAMILIAS_FORMULARIO WHERE FAM_ID=22 AND FAM_CODIGO='MATRIZ_RIESGOS_LAFT' AND FAM_PREDETERMINADA=1]', 1, 'FAMILY_22');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=61 AND VER_CODIGO='MATRIZ_RIESGOS_LAFT_V1' AND VER_VERSION=1 AND VER_ESTADO='PUBLISHED' AND VER_VIGENTE=1 AND LOWER(VER_HASH)='f2f84f21b6cc46762fd6087bc41df449b31ca87b058c763689bdfb3bba961f90']', 1, 'V1_IMMUTABLE_TARGET');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=63 AND VER_CODIGO='MATRIZ_RIESGOS_LAFT_V2' AND VER_VERSION=2 AND VER_ESTADO='DRAFT' AND VER_VIGENTE=0 AND LOWER(VER_HASH)='769b5b25cd7cbb03b69782b5864828fb53155c070483b6d22ef5adf36d295651']', 1, 'V2_DRAFT_TARGET');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_CATALOGOS WHERE CAT_CODIGO IN ('MR_FRECUENCIA_1_5','MR_IMPACTO_1_5','MR_NIVEL_RIESGO','MR_RESPUESTA_RIESGO') AND CAT_ACTIVO=1]', 4, 'ACTIVE_CATALOGS');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_REGLAS_CALCULO WHERE REG_CODIGO='CALCULO_VRI_VRR' AND REG_VERSION='1.0' AND REG_ACTIVA=1]', 1, 'ACTIVE_RULE');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_RIESGOS WHERE RIE_CODIGO IS NOT NULL]', 59, 'SOURCE_RISKS');
  require_count(q'[SELECT COUNT(*) FROM (SELECT RIE_CODIGO FROM RL_MR_RIESGOS WHERE RIE_CODIGO IS NOT NULL GROUP BY RIE_CODIGO HAVING COUNT(*)>1)]', 0, 'DUPLICATE_SOURCE_RISKS');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO WHERE EVA_VERSION_ID=61]', 59, 'V1_EVALUATIONS');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_PROYECCIONES_EVALUACION p JOIN RL_MR_EVALUACIONES_RIESGO e ON e.EVA_ID=p.PROY_EVALUACION_ID WHERE e.EVA_VERSION_ID=61]', 59, 'V1_PROJECTIONS');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO e WHERE NOT EXISTS (SELECT 1 FROM RL_MR_RIESGOS r WHERE r.RIE_ID=e.EVA_RIESGO_ID)]', 0, 'ORPHAN_EVALUATIONS');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_PROYECCIONES_EVALUACION p WHERE NOT EXISTS (SELECT 1 FROM RL_MR_EVALUACIONES_RIESGO e WHERE e.EVA_ID=p.PROY_EVALUACION_ID)]', 0, 'ORPHAN_PROJECTIONS');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO e WHERE NOT EXISTS (SELECT 1 FROM RL_MR_VERSIONES_FORMULARIO v WHERE v.VER_ID=e.EVA_VERSION_ID)]', 0, 'INVALID_VERSION_BINDINGS');
  require_count(q'[SELECT COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO WHERE DBMS_LOB.GETLENGTH(EVA_DATOS_JSON)=0 OR DBMS_LOB.SUBSTR(EVA_DATOS_JSON,1,1)<>'{']', 0, 'INVALID_JSON');
  require_count(q'[SELECT COUNT(*) FROM USER_OBJECTS WHERE OBJECT_NAME LIKE 'RL_MR_%' AND STATUS<>'VALID']', 0, 'INVALID_OBJECTS');
  require_count(q'[SELECT COUNT(*) FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'RL_MR_%' AND STATUS<>'ENABLED']', 0, 'DISABLED_CONSTRAINTS');
  DBMS_OUTPUT.PUT_LINE('PREFLIGHT=PASS');
END;
/
SET DEFINE ON
