-- FASE 7 - upgrade seguro. No publica V2 ni modifica V1.
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DEFINE autorizacion = '&1'
DECLARE
  v_schema VARCHAR2(128);
  v_v1 NUMBER;
  v_v2 NUMBER;
BEGIN
  SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') INTO v_schema FROM DUAL;
  IF UPPER(v_schema) <> 'RIESGO_LAVADO' THEN
    RAISE_APPLICATION_ERROR(-20720, 'UPGRADE bloqueado fuera de RIESGO_LAVADO.');
  END IF;
  IF UPPER(TRIM(q'[&autorizacion]')) <> 'VALIDAR' THEN
    RAISE_APPLICATION_ERROR(-20721, 'UPGRADE requiere el argumento VALIDAR.');
  END IF;
  SELECT COUNT(*) INTO v_v1 FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=61 AND VER_ESTADO='PUBLISHED' AND VER_VIGENTE=1;
  SELECT COUNT(*) INTO v_v2 FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=63 AND VER_ESTADO='DRAFT' AND VER_VIGENTE=0;
  IF v_v1 <> 1 OR v_v2 <> 1 THEN
    RAISE_APPLICATION_ERROR(-20722, 'Estado de versiones incompatible; upgrade abortado.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('UPGRADE=PASS');
  DBMS_OUTPUT.PUT_LINE('UPGRADE_MODE=NO_SCHEMA_DELTA');
  DBMS_OUTPUT.PUT_LINE('V2_PUBLICATION=NOT_PERFORMED');
END;
/
@@01_preflight_release.sql
