-- DROP USER RIESGO_LAVADO;

CREATE USER RIESGO_LAVADO
-- IDENTIFIED BY <password>
;

CREATE TABLE "RIESGO_LAVADO"."RL_AUDITORIA" 
   (	"AUD_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"AUD_TABLA" VARCHAR2(50) NOT NULL ENABLE, 
	"AUD_REGISTRO_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"AUD_ACCION" VARCHAR2(10) NOT NULL ENABLE, 
	"AUD_DATOS_ANT" CLOB, 
	"AUD_DATOS_NVO" CLOB, 
	"AUD_USR_ID" NUMBER(10,0), 
	"AUD_USR_EMAIL" VARCHAR2(150), 
	"AUD_IP" VARCHAR2(45), 
	"AUD_FECHA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"AUD_MODULO" VARCHAR2(50), 
	 CONSTRAINT "PK_RL_AUDITORIA" PRIMARY KEY ("AUD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CK_RL_AUD_ACCION" CHECK (AUD_ACCION IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','VER')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUD_DATOS_ANT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUD_DATOS_NVO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_AUD_TABLA" ON "RIESGO_LAVADO"."RL_AUDITORIA" ("AUD_TABLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_AUD_USR" ON "RIESGO_LAVADO"."RL_AUDITORIA" ("AUD_USR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_AUDITORIA IS 'Bitácora general de auditoría para control interno.';

CREATE TABLE "RIESGO_LAVADO"."RL_CALIF_COINCIDENCIAS" 
   (	"CAL_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"CAL_REPORTE_COINCIDENCIA_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"CAL_TIPO_CALIFICACION_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"CAL_USUARIO_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CAL_FECHA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CAL_OBSERVACION" VARCHAR2(1000), 
	 CONSTRAINT "PK_RL_CALIFICACIONES" PRIMARY KEY ("CAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_RL_CAL_REPORTE" UNIQUE ("CAL_REPORTE_COINCIDENCIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_CAL_USUARIO" ON "RIESGO_LAVADO"."RL_CALIF_COINCIDENCIAS" ("CAL_USUARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_CALIF_COINCIDENCIAS IS 'Calificaciones de coincidencias de patronos (Positivo / Falso Positivo).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_CALIF_COINCIDENCIAS.CAL_ID IS 'Clave primaria.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_CALIF_COINCIDENCIAS.CAL_REPORTE_COINCIDENCIA_ID IS 'ID del registro en DNP_IHSS.REPORTE_COINCIDENCIAS.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_CALIF_COINCIDENCIAS.CAL_TIPO_CALIFICACION_ID IS '1 = Positivo, 2 = Falso Positivo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_CALIF_COINCIDENCIAS.CAL_USUARIO_ID IS 'Usuario que realiz¿¿ la calificaci¿¿n.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_CALIF_COINCIDENCIAS.CAL_FECHA IS 'Fecha y hora de la calificaci¿¿n.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_CALIF_COINCIDENCIAS.CAL_OBSERVACION IS 'Observaciones opcionales.';

CREATE TABLE "RIESGO_LAVADO"."RL_CONFIG_SISTEMA" 
   (	"SFS_ID" NUMBER(1,0) DEFAULT 1, 
	"SFS_NOMBRE_INSTITUCION" VARCHAR2(255) NOT NULL ENABLE, 
	"SFS_NOMBRE_SISTEMA" VARCHAR2(100) NOT NULL ENABLE, 
	"SFS_LOGO_URL" VARCHAR2(500), 
	"SFS_ICONO_URL" VARCHAR2(500), 
	"SFS_COLOR_PRIMARIO" VARCHAR2(20) DEFAULT '#1e3a8a', 
	"SFS_COLOR_SECUNDARIO" VARCHAR2(20) DEFAULT '#1d4ed8', 
	"SFS_TIMEOUT_SESION" NUMBER DEFAULT 30, 
	"SFS_ULTIMA_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"SFS_ACUERDO_LEGAL" CLOB, 
	"SFS_MAX_INTENTOS" NUMBER DEFAULT 5, 
	"SFS_VALIDEZ_CLAVE_TEMP" NUMBER DEFAULT 15 NOT NULL ENABLE, 
	 CONSTRAINT "CHK_RL_ONE_ROW" CHECK (SFS_ID = 1) ENABLE, 
	 PRIMARY KEY ("SFS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SFS_ACUERDO_LEGAL") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

COMMENT ON TABLE RIESGO_LAVADO.RL_CONFIG_SISTEMA IS 'Configuración de imagen corporativa e inactividad.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_CONFIG_SISTEMA.SFS_VALIDEZ_CLAVE_TEMP IS 'Tiempo de validez de la clave provisional en minutos.';

CREATE TABLE "RIESGO_LAVADO"."RL_DETALLE_EVIDENCIA" 
   (	"EVI_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EVI_DETALLE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EVI_NOMBRE_ARCHIVO" VARCHAR2(255) NOT NULL ENABLE, 
	"EVI_TIPO_MIME" VARCHAR2(100) NOT NULL ENABLE, 
	"EVI_RUTA_ARCHIVO" VARCHAR2(500) NOT NULL ENABLE, 
	"EVI_FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"EVI_USR_CREACION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EVI_ESTADO_REGISTRO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"EVI_USR_INACTIVO_ID" NUMBER(10,0), 
	"EVI_FECHA_INACTIVO" DATE, 
	 CONSTRAINT "PK_RL_DETALLE_EVIDENCIA" PRIMARY KEY ("EVI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RIESGO_LAVADO"."RL_DETALLE_EVIDENCIA" ADD CONSTRAINT "FK_EVI_DETALLE_LISTA" FOREIGN KEY ("EVI_DETALLE_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_DETALLE_LISTA" ("DLL_DETALLE_LISTA_ID") ON DELETE CASCADE ENABLE;

CREATE INDEX "RIESGO_LAVADO"."IDX_EVI_DETALLE" ON "RIESGO_LAVADO"."RL_DETALLE_EVIDENCIA" ("EVI_DETALLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_EVI_DETALLE_ESTADO" ON "RIESGO_LAVADO"."RL_DETALLE_EVIDENCIA" ("EVI_DETALLE_ID", "EVI_ESTADO_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_DETALLE_EVIDENCIA IS 'Almacén de metadatos y rutas físicas de archivos cargados como evidencia de seguimiento.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_ID IS 'Clave primaria.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_DETALLE_ID IS 'Clave foránea a la nota de seguimiento en RL_DETALLE_LISTA.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_NOMBRE_ARCHIVO IS 'Nombre original del archivo (ej. documento.pdf).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_TIPO_MIME IS 'Tipo de contenido MIME del archivo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_RUTA_ARCHIVO IS 'Nombre/ruta física del archivo almacenado en el disco del servidor.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_FECHA_CREACION IS 'Fecha de carga.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_USR_CREACION_ID IS 'ID del usuario que subió la evidencia.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_ESTADO_REGISTRO IS 'Estado del registro: 1=Activo, 0=Inactivo por eliminacion logica.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_USR_INACTIVO_ID IS 'ID del usuario que realizo la eliminacion logica.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_EVIDENCIA.EVI_FECHA_INACTIVO IS 'Fecha en que se realizo la eliminacion logica.';

CREATE TABLE "RIESGO_LAVADO"."RL_DETALLE_LISTA" 
   (	"DLL_DETALLE_LISTA_ID" NUMBER(15,0), 
	"DLL_LSP_POSITIVO_ID" NUMBER(15,0), 
	"DLL_MOTIVO_INGRESO" VARCHAR2(1500 CHAR), 
	"DLL_USR_CREACION_ID" NUMBER(10,0), 
	"DLL_FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"DLL_USR_MODIFICACION_ID" NUMBER(10,0), 
	"DLL_FECHA_MODIFICACION" DATE, 
	"DLL_ESTADO_REGISTRO" NUMBER(1,0) DEFAULT 1, 
	"DLL_USR_INACTIVO_ID" NUMBER(10,0), 
	"DLL_FECHA_INACTIVO" DATE, 
	 CONSTRAINT "RL_DETALLE_LISTA_PK" PRIMARY KEY ("DLL_DETALLE_LISTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_DLL_LSP" ON "RIESGO_LAVADO"."RL_DETALLE_LISTA" ("DLL_LSP_POSITIVO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_DLL_USR_INACTIVO" ON "RIESGO_LAVADO"."RL_DETALLE_LISTA" ("DLL_USR_INACTIVO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_DLL_USR_CREACION" ON "RIESGO_LAVADO"."RL_DETALLE_LISTA" ("DLL_USR_CREACION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_DLL_USR_MODIF" ON "RIESGO_LAVADO"."RL_DETALLE_LISTA" ("DLL_USR_MODIFICACION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_DLL_ESTADO" ON "RIESGO_LAVADO"."RL_DETALLE_LISTA" ("DLL_ESTADO_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_DETALLE_LISTA IS 'Detalle de ingreso, monitoreo y control de estado para registros de la lista positiva.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_DETALLE_LISTA_ID IS 'Identificador unico correlativo del detalle de lista positiva.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_LSP_POSITIVO_ID IS 'ID del registro principal en RL_LISTA_POSITIVOS.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_MOTIVO_INGRESO IS 'Motivo por el cual el registro fue ingresado o actualizado en la lista positiva.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_USR_CREACION_ID IS 'ID del usuario que creo el detalle.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_FECHA_CREACION IS 'Fecha de creacion del detalle.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_USR_MODIFICACION_ID IS 'ID del usuario que realizo la ultima modificacion del detalle.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_FECHA_MODIFICACION IS 'Fecha de la ultima modificacion del detalle.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_ESTADO_REGISTRO IS 'Estado del detalle: 1=Activo, 0=Inactivo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_USR_INACTIVO_ID IS 'ID del usuario que inactivo el detalle.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DETALLE_LISTA.DLL_FECHA_INACTIVO IS 'Fecha en que el detalle fue inactivado.';

CREATE TABLE "RIESGO_LAVADO"."RL_DOMINIO" 
   (	"DOM_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"DOM_NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"DOM_DESCRIPCION" VARCHAR2(255), 
	"DOM_ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "CK_RL_DOM_ACTIVO" CHECK (DOM_ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_DOMINIO" PRIMARY KEY ("DOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_RL_DOM_NOMBRE" UNIQUE ("DOM_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_DOMINIO IS 'Catálogo de dominios institucionales de red.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DOMINIO.DOM_ID IS 'Identificador único correlativo del dominio.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DOMINIO.DOM_NOMBRE IS 'Nombre o DNS del dominio.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DOMINIO.DOM_DESCRIPCION IS 'Descripción del dominio.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_DOMINIO.DOM_ACTIVO IS 'Estado: 1=Activo, 0=Inactivo.';

CREATE TABLE "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" 
   (	"LSP_POSITIVO_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"LSP_TIPO_DOCUMENTO_ID" NUMBER NOT NULL ENABLE, 
	"LSP_TIPO_POSITIVO_ID" NUMBER NOT NULL ENABLE, 
	"LSP_NO_DOCUMENTO" VARCHAR2(50), 
	"LSP_NOMBRE_COMPLETO" VARCHAR2(255) NOT NULL ENABLE, 
	"LSP_MOTIVO_INGRESO" VARCHAR2(500), 
	"LSP_FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LSP_USR_CREACION_ID" NUMBER(10,0), 
	"LSP_USR_MODIFICACION_ID" NUMBER(10,0), 
	"LSP_FECHA_MODIFICACION" DATE, 
	"LSP_ESTADO_REGISTRO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"LSP_USR_INACTIVO_ID" NUMBER(10,0), 
	"LSP_FECHA_INACTIVO" DATE, 
	"LSP_TIPO_LISTA_CAUTELA_ID" NUMBER, 
	"LSP_ORIGEN_REGISTRO" VARCHAR2(50 CHAR), 
	 CONSTRAINT "CK_RL_LSP_ESTADO" CHECK ("LSP_ESTADO_REGISTRO" IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_LISTA_POSITIVOS" PRIMARY KEY ("LSP_POSITIVO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_RL_LSP_DOCUMENTO" UNIQUE ("LSP_TIPO_DOCUMENTO_ID", "LSP_NO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CK_RL_LSP_ORIGEN_REG" CHECK (LSP_ORIGEN_REGISTRO IS NULL OR LSP_ORIGEN_REGISTRO IN ('DNP_LISTAS', 'MANUAL_CUMPLIMIENTO', 'NOTICIA_PRENSA', 'OTRO')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ADD CONSTRAINT "FK_RL_LSP_USR_CREACION" FOREIGN KEY ("LSP_USR_CREACION_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_USUARIOS" ("USR_ID") ENABLE;
 
  ALTER TABLE "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ADD CONSTRAINT "FK_RL_LSP_USR_INACTIVO" FOREIGN KEY ("LSP_USR_INACTIVO_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_USUARIOS" ("USR_ID") ENABLE;
 
  ALTER TABLE "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ADD CONSTRAINT "FK_RL_LSP_USR_MODIF" FOREIGN KEY ("LSP_USR_MODIFICACION_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_USUARIOS" ("USR_ID") ENABLE;
 
  ALTER TABLE "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ADD CONSTRAINT "RL_LISTA_POSITIVOS_R01" FOREIGN KEY ("LSP_TIPO_POSITIVO_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_TIPOS_POSITIVO" ("RL_TIPO_POSITIVO_ID") ENABLE;
 
  ALTER TABLE "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ADD CONSTRAINT "RL_LISTA_POSITIVOS_R02" FOREIGN KEY ("LSP_TIPO_DOCUMENTO_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_TIPOS_DOCUMENTO" ("RL_TIPO_DOCUMENTO_ID") ENABLE;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_LSP_ORIGEN" ON "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ("LSP_ORIGEN_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_LSP_USR_CREACION" ON "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ("LSP_USR_CREACION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_LSP_ESTADO" ON "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ("LSP_ESTADO_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_LSP_USR_MODIF" ON "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ("LSP_USR_MODIFICACION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_LSP_NOMBRE_COMPLETO" ON "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ("LSP_NOMBRE_COMPLETO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_LSP_USR_INACTIVO" ON "RIESGO_LAVADO"."RL_LISTA_POSITIVOS" ("LSP_USR_INACTIVO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_LISTA_POSITIVOS IS 'Encabezado de personas naturales o juridicas incluidas en la lista positiva del modulo de monitoreo de listas.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_POSITIVO_ID IS 'Identificador unico correlativo del registro en lista positiva.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_TIPO_DOCUMENTO_ID IS 'Tipo de documento del registro. Opciones disponibles: DNI, RTN, N° Patronal.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_NO_DOCUMENTO IS 'Numero de documento asociado a la persona natural o juridica registrada.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_NOMBRE_COMPLETO IS 'Nombre completo o razon social de la persona natural o juridica incluida en la lista positiva.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_MOTIVO_INGRESO IS 'Motivo por el cual el registro fue ingresado en la lista positiva.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_FECHA_CREACION IS 'Fecha de creacion del registro principal.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_USR_CREACION_ID IS 'ID del usuario que creo el registro.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_USR_MODIFICACION_ID IS 'ID del usuario que realizo la ultima modificacion del registro.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_FECHA_MODIFICACION IS 'Fecha de la ultima modificacion del registro.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_ESTADO_REGISTRO IS 'Estado del registro principal: 1=Activo, 0=Inactivo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_USR_INACTIVO_ID IS 'ID del usuario que inactivo el registro.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_FECHA_INACTIVO IS 'Fecha en que el registro fue inactivado.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_LISTA_POSITIVOS.LSP_ORIGEN_REGISTRO IS 'Origen operativo del registro: DNP_LISTAS, MANUAL_CUMPLIMIENTO, NOTICIA_PRENSA u OTRO.';

CREATE TABLE "RIESGO_LAVADO"."RL_LOGIN_SLIDES" 
   (	"SGL_ID" NUMBER(2,0) NOT NULL ENABLE, 
	"SGL_IMAGEN_URL" VARCHAR2(500) NOT NULL ENABLE, 
	"SGL_TITULO" VARCHAR2(100), 
	"SGL_DESCRIPCION" VARCHAR2(500), 
	"SGL_ORDEN" NUMBER(2,0) DEFAULT 0, 
	"SGL_ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"SGL_FECHA_MODIF" DATE DEFAULT SYSDATE, 
	"SGL_IMAGEN_ICONO" VARCHAR2(100), 
	 CONSTRAINT "CK_RL_SGL_ACTIVO" CHECK (SGL_ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_LOGIN_SLIDES" PRIMARY KEY ("SGL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_LOGIN_SLIDES IS ' slides informativos para carrusel en pantalla de login.';

CREATE TABLE "RIESGO_LAVADO"."RL_MODULOS" 
   (	"MOD_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"MOD_NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"MOD_DESCRIPCION" VARCHAR2(255), 
	"MOD_RUTA" VARCHAR2(200) NOT NULL ENABLE, 
	"MOD_ICONO" VARCHAR2(100) NOT NULL ENABLE, 
	"MOD_SECCION" VARCHAR2(100) NOT NULL ENABLE, 
	"MOD_ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "CK_RL_MOD_ACTIVO" CHECK (MOD_ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_MODULOS" PRIMARY KEY ("MOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_RL_MOD_RUTA" UNIQUE ("MOD_RUTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_MODULOS IS 'Catálogo de módulos y accesos del sistema.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_MODULOS.MOD_ID IS 'Clave primaria del módulo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_MODULOS.MOD_NOMBRE IS 'Nombre descriptivo del módulo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_MODULOS.MOD_RUTA IS 'Ruta de navegación en el frontend (ej. /usuarios).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_MODULOS.MOD_ICONO IS 'Nombre del icono asociado (ej. users).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_MODULOS.MOD_SECCION IS 'Sección del menú lateral (ej. Administración).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_MODULOS.MOD_ACTIVO IS 'Estado: 1=Activo, 0=Inactivo.';

CREATE TABLE "RIESGO_LAVADO"."RL_PASSWORD_RESET_TOKENS" 
   (	"PRT_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"PRT_USR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PRT_TOKEN" VARCHAR2(255) NOT NULL ENABLE, 
	"PRT_EXPIRA" DATE NOT NULL ENABLE, 
	"PRT_CREADO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"PRT_USADO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "CK_RL_PRT_USADO" CHECK (PRT_USADO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_RESET_TOKENS" PRIMARY KEY ("PRT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "RIESGO_LAVADO"."RL_PASSWORD_RESET_TOKENS" ADD CONSTRAINT "FK_RL_PRT_USR" FOREIGN KEY ("PRT_USR_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_USUARIOS" ("USR_ID") ENABLE;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_PRT_TOKEN" ON "RIESGO_LAVADO"."RL_PASSWORD_RESET_TOKENS" ("PRT_TOKEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_PASSWORD_RESET_TOKENS IS 'Tokens para restablecimiento de contraseñas olvidadas.';

CREATE TABLE "RIESGO_LAVADO"."RL_REFRESH_TOKENS" 
   (	"RFT_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"RFT_USR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RFT_TOKEN" VARCHAR2(500) NOT NULL ENABLE, 
	"RFT_EXPIRA" DATE NOT NULL ENABLE, 
	"RFT_REVOCADO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"RFT_FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"RFT_IP_ORIGEN" VARCHAR2(45), 
	 CONSTRAINT "CK_RL_RFT_REVOCADO" CHECK (RFT_REVOCADO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_REFRESH_TOKENS" PRIMARY KEY ("RFT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RIESGO_LAVADO"."RL_REFRESH_TOKENS" ADD CONSTRAINT "FK_RL_RFT_USR" FOREIGN KEY ("RFT_USR_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_USUARIOS" ("USR_ID") ENABLE;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_RFT_TOKEN" ON "RIESGO_LAVADO"."RL_REFRESH_TOKENS" ("RFT_TOKEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_RFT_USR" ON "RIESGO_LAVADO"."RL_REFRESH_TOKENS" ("RFT_USR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_REFRESH_TOKENS IS 'Almacén de Refresh Tokens para renovación de JWT.';

CREATE TABLE "RIESGO_LAVADO"."RL_ROLES" 
   (	"ROL_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"ROL_NOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
	"ROL_DESCRIPCION" VARCHAR2(200), 
	"ROL_ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"ROL_FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "CK_RL_ROL_ACTIVO" CHECK (ROL_ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_ROLES" PRIMARY KEY ("ROL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_RL_ROL_NOMBRE" UNIQUE ("ROL_NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE RIESGO_LAVADO.RL_ROLES IS 'Roles del sistema para control de accesos.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_ROLES.ROL_ID IS 'Identificador del rol.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_ROLES.ROL_NOMBRE IS 'Nombre del rol (ej. ADMINISTRADOR).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_ROLES.ROL_DESCRIPCION IS 'Descripción del rol.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_ROLES.ROL_ACTIVO IS 'Estado: 1=Activo, 0=Inactivo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_ROLES.ROL_FECHA_CREACION IS 'Fecha de creación.';

CREATE TABLE "RIESGO_LAVADO"."RL_TIPOS_DOCUMENTO" 
   (	"RL_TIPO_DOCUMENTO_ID" NUMBER, 
	"RL_TIPO_DOCUMENTO_DESCRIPCION" VARCHAR2(75), 
	 CONSTRAINT "RL_TIPOS_DOCUMENTO_PK" PRIMARY KEY ("RL_TIPO_DOCUMENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "RIESGO_LAVADO"."RL_TIPOS_POSITIVO" 
   (	"RL_TIPO_POSITIVO_ID" NUMBER, 
	"RL_TIPO_POSITIVO_DESCRIPCION" VARCHAR2(75 CHAR), 
	 CONSTRAINT "RL_TIPOS_POSITIVO_PK" PRIMARY KEY ("RL_TIPO_POSITIVO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "RIESGO_LAVADO"."RL_USUARIOS" 
   (	"USR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USR_NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"USR_APELLIDO" VARCHAR2(100) NOT NULL ENABLE, 
	"USR_EMAIL" VARCHAR2(150) NOT NULL ENABLE, 
	"USR_PASSWORD_HASH" VARCHAR2(256) NOT NULL ENABLE, 
	"USR_PASSWORD_SALT" VARCHAR2(256) NOT NULL ENABLE, 
	"USR_ROL_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"USR_EMPLEADO_ID" VARCHAR2(20), 
	"USR_ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"USR_FECHA_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USR_FECHA_MODIFICACION" DATE, 
	"USR_CREADO_POR" NUMBER(10,0), 
	"ES_USUARIO_DOMINIO" NUMBER(1,0) DEFAULT 0, 
	"USR_DOM_ID" NUMBER(5,0), 
	"USUARIO_DOMINIO" VARCHAR2(500), 
	"USR_DNI" VARCHAR2(25 CHAR), 
	"USR_INTENTOS_FALLIDOS" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"USR_FECHA_BLOQUEO" DATE, 
	"USR_DEBE_CAMBIAR_PASS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USR_FECHA_CLAVE_TEMP" DATE, 
	 CONSTRAINT "CK_RL_USR_ACTIVO" CHECK (USR_ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_RL_USUARIOS" PRIMARY KEY ("USR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UQ_RL_USR_EMAIL" UNIQUE ("USR_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CK_RL_USR_DEBE_CAMBIAR" CHECK (USR_DEBE_CAMBIAR_PASS IN (0,1)) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RIESGO_LAVADO"."RL_USUARIOS" ADD CONSTRAINT "FK_RL_USR_DOM" FOREIGN KEY ("USR_DOM_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_DOMINIO" ("DOM_ID") ENABLE;
 
  ALTER TABLE "RIESGO_LAVADO"."RL_USUARIOS" ADD CONSTRAINT "FK_RL_USR_ROL" FOREIGN KEY ("USR_ROL_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_ROLES" ("ROL_ID") ENABLE;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_USR_ROL" ON "RIESGO_LAVADO"."RL_USUARIOS" ("USR_ROL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "RIESGO_LAVADO"."IDX_RL_USR_DOM" ON "RIESGO_LAVADO"."RL_USUARIOS" ("USR_DOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT SELECT ON "RIESGO_LAVADO"."RL_USUARIOS" TO "DNP_IHSS" WITH GRANT OPTION;

COMMENT ON TABLE RIESGO_LAVADO.RL_USUARIOS IS 'Información de cuentas de usuario.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_ID IS 'Clave primaria.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_NOMBRE IS 'Nombres del usuario.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_APELLIDO IS 'Apellidos del usuario.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_EMAIL IS 'Email corporativo único.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_PASSWORD_HASH IS 'Hash de contraseña.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_PASSWORD_SALT IS 'Salt de la contraseña (o BCRYPT).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_ROL_ID IS 'ID del rol asignado.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_EMPLEADO_ID IS 'Identificador del empleado.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_ACTIVO IS 'Estado: 1=Habilitado, 0=Bloqueado/Inactivo.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_FECHA_CREACION IS 'Fecha de creación de la cuenta.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_FECHA_MODIFICACION IS 'Fecha del último cambio.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_CREADO_POR IS 'ID del usuario que creó este registro.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.ES_USUARIO_DOMINIO IS 'Indica si inicia sesión con AD (1) o local (0).';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_DOM_ID IS 'ID del dominio AD al que pertenece.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USUARIO_DOMINIO IS 'Nombre de usuario del dominio AD.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_DNI IS 'Número de identidad.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_DEBE_CAMBIAR_PASS IS 'Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión: 1=Sí, 0=No.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIOS.USR_FECHA_CLAVE_TEMP IS 'Fecha y hora en que se generó la última clave provisional.';

CREATE TABLE "RIESGO_LAVADO"."RL_USUARIO_MODULOS" 
   (	"USM_USR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USM_MOD_ID" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_RL_USUARIO_MODULOS" PRIMARY KEY ("USM_USR_ID", "USM_MOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RIESGO_LAVADO"."RL_USUARIO_MODULOS" ADD CONSTRAINT "FK_USM_MOD_ID" FOREIGN KEY ("USM_MOD_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_MODULOS" ("MOD_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "RIESGO_LAVADO"."RL_USUARIO_MODULOS" ADD CONSTRAINT "FK_USM_USR_ID" FOREIGN KEY ("USM_USR_ID")
	  REFERENCES "RIESGO_LAVADO"."RL_USUARIOS" ("USR_ID") ON DELETE CASCADE ENABLE;

COMMENT ON TABLE RIESGO_LAVADO.RL_USUARIO_MODULOS IS 'Tabla intermedia para control de accesos de usuario a módulos.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIO_MODULOS.USM_USR_ID IS 'ID del usuario en RL_USUARIOS.';
COMMENT ON COLUMN RIESGO_LAVADO.RL_USUARIO_MODULOS.USM_MOD_ID IS 'ID del módulo en RL_MODULOS.';

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_AREA_DOMINIO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_AUDITORIA INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_CALIFICACIONES INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_DETALLE_EVIDENCIA INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_DETALLE_LISTA INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_DOMINIO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_LISTA_POSITIVOS INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_MODULOS INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_REFRESH_TOKENS INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_RESET_TOKENS INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_ROLES INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE RIESGO_LAVADO.SEQ_RL_USUARIOS INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

