-- FASE 6 - Certificación integral del módulo Matrices de Riesgos
-- Solo lectura. No contiene DDL, DML, COMMIT ni ROLLBACK de datos.
-- Ejecutar conectado a RIESGO_LAVADO en el ambiente autorizado.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 200
SET LINESIZE 240
SET LONG 100000
SET FEEDBACK ON
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === READ_ONLY_PHASE6_SESSION ===
SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') SESSION_USER,
       SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV', 'DB_NAME') DB_NAME,
       SYS_CONTEXT('USERENV', 'SERVICE_NAME') SERVICE_NAME
  FROM DUAL;

PROMPT === ACTIVE_OBJECT_INVENTORY ===
SELECT COUNT(*) ACTIVE_TABLES
  FROM USER_TABLES
 WHERE TABLE_NAME IN (
    'RL_MR_FAMILIAS_FORMULARIO','RL_MR_VERSIONES_FORMULARIO','RL_MR_CATALOGOS',
    'RL_MR_ELEMENTOS_CATALOGO','RL_MR_REGLAS_CALCULO','RL_MR_RIESGOS',
    'RL_MR_EVALUACIONES_RIESGO','RL_MR_PROYECCIONES_EVALUACION','RL_MR_FLUJOS_EVALUACION',
    'RL_MR_CONTROLES_RIESGO','RL_MR_EVALUACIONES_CONTROL','RL_MR_PLANES',
    'RL_MR_ACTIVIDADES','RL_MR_EVIDENCIAS','RL_MR_EVIDENCIAS_VINCULOS',
    'RL_MR_SENALES_ALERTA','RL_MR_AUTOMONITOREO',
    'RL_MR_FORMULAS','RL_MR_FORMULA_USOS','RL_MR_FORMULA_VERSIONES',
    'RL_MR_FUNCION_ARGUMENTOS','RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES',
    'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES'
 );

SELECT COUNT(*) RETIRED_IMPORT_TABLES_PRESENT
  FROM USER_TABLES
 WHERE TABLE_NAME IN ('RL_MR_LOTES_IMPORTACION','RL_MR_DETALLES_IMPORTACION',
                      'RL_MR_AUDITORIA','RL_MR_TRAZAS_CALCULO');

SELECT COUNT(*) INVALID_OBJECTS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME LIKE 'RL_MR%'
   AND STATUS <> 'VALID';

PROMPT === FAMILY_AND_VERSION ===
SELECT f.FAM_ID,
       f.FAM_CODIGO,
       f.FAM_PREDETERMINADA,
       v.VER_ID,
       v.VER_CODIGO,
       v.VER_VERSION,
       v.VER_ESTADO,
       v.VER_VIGENTE,
       DBMS_LOB.GETLENGTH(v.VER_JSON) JSON_BYTES,
       v.VER_HASH
  FROM RL_MR_FAMILIAS_FORMULARIO f
  JOIN RL_MR_VERSIONES_FORMULARIO v ON v.VER_FAMILIA_ID = f.FAM_ID
 WHERE f.FAM_CODIGO = 'MATRIZ_RIESGOS_LAFT'
 ORDER BY v.VER_VERSION;

PROMPT === SOURCE_RISK_INTEGRITY ===
SELECT COUNT(*) SOURCE_RISKS,
       COUNT(DISTINCT RIE_CODIGO) DISTINCT_SOURCE_CODES,
       COUNT(*) - COUNT(DISTINCT RIE_CODIGO) DUPLICATE_SOURCE_RISKS
  FROM RL_MR_RIESGOS
 WHERE RIE_CODIGO IS NOT NULL;

SELECT COUNT(*) ORPHAN_EVALUATIONS
  FROM RL_MR_EVALUACIONES_RIESGO e
 WHERE NOT EXISTS (SELECT 1 FROM RL_MR_RIESGOS r WHERE r.RIE_ID = e.EVA_RIESGO_ID);

SELECT COUNT(*) ORPHAN_PROJECTIONS
  FROM RL_MR_PROYECCIONES_EVALUACION p
 WHERE NOT EXISTS (SELECT 1 FROM RL_MR_EVALUACIONES_RIESGO e WHERE e.EVA_ID = p.PROY_EVALUACION_ID);

SELECT COUNT(*) INVALID_VERSION_BINDINGS
  FROM RL_MR_EVALUACIONES_RIESGO e
 WHERE NOT EXISTS (SELECT 1 FROM RL_MR_VERSIONES_FORMULARIO v WHERE v.VER_ID = e.EVA_VERSION_ID);

SELECT COUNT(*) SOURCE_BINDING_VIOLATIONS
  FROM RL_MR_EVALUACIONES_RIESGO e
  JOIN RL_MR_RIESGOS r ON r.RIE_ID = e.EVA_RIESGO_ID
 WHERE e.EVA_VERSION_ID <> 61;

SELECT COUNT(*) EVAL_PROJ_MISMATCH
  FROM RL_MR_EVALUACIONES_RIESGO e
 WHERE NOT EXISTS (
    SELECT 1 FROM RL_MR_PROYECCIONES_EVALUACION p
     WHERE p.PROY_EVALUACION_ID = e.EVA_ID
 );

PROMPT === JSON_SHAPE_AND_TEST_DATA ===
SELECT COUNT(*) INVALID_JSON_SHAPE
  FROM RL_MR_EVALUACIONES_RIESGO
 WHERE DBMS_LOB.GETLENGTH(EVA_DATOS_JSON) = 0
    OR DBMS_LOB.GETLENGTH(EVA_CALCULOS_JSON) = 0
    OR DBMS_LOB.SUBSTR(EVA_DATOS_JSON, 1, 1) <> '{'
    OR DBMS_LOB.SUBSTR(EVA_CALCULOS_JSON, 1, 1) <> '{';

SELECT RIE_CODIGO,
       DBMS_LOB.SUBSTR(e.EVA_DATOS_JSON, 4000, 1) DATOS_JSON,
       DBMS_LOB.SUBSTR(e.EVA_CALCULOS_JSON, 4000, 1) CALCULOS_JSON
  FROM RL_MR_RIESGOS r
  JOIN RL_MR_EVALUACIONES_RIESGO e ON e.EVA_RIESGO_ID = r.RIE_ID
 WHERE r.RIE_CODIGO IN ('ROTR-ALMACENBIENE-23','RCUMP-COMPRAS-37')
 ORDER BY r.RIE_CODIGO;

PROMPT === CATALOGS_AND_CONSTRAINTS ===
SELECT c.CAT_CODIGO,
       c.CAT_ACTIVO,
       COUNT(e.ELE_ID) ELEMENTS
  FROM RL_MR_CATALOGOS c
  LEFT JOIN RL_MR_ELEMENTOS_CATALOGO e ON e.ELE_CATALOGO_ID = c.CAT_ID
 WHERE c.CAT_CODIGO IN ('MR_FRECUENCIA_1_5','MR_IMPACTO_1_5',
                        'MR_NIVEL_RIESGO','MR_RESPUESTA_RIESGO')
 GROUP BY c.CAT_CODIGO, c.CAT_ACTIVO
 ORDER BY c.CAT_CODIGO;

SELECT COUNT(*) DISABLED_CONSTRAINTS
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME LIKE 'RL_MR%'
   AND STATUS <> 'ENABLED';

PROMPT === EXPECTED_PHASE6_READ_ONLY_RESULT ===
SELECT 'READ_ONLY=TRUE; NO_DDL=TRUE; NO_DML=TRUE' RESULTADO FROM DUAL;
EXIT
