-- Fase 10 - validacion DBA reproducible y de solo lectura.
-- Ejecutar con un usuario que pueda consultar el esquema objetivo.
-- Este archivo no contiene DDL, DML, COMMIT ni operaciones destructivas.

SET PAGESIZE 200
SET LINESIZE 220
SET VERIFY OFF
SET FEEDBACK ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

PROMPT === FASE 10: OBJETOS REQUERIDOS ===
SELECT object_type, object_name, status
  FROM user_objects
 WHERE object_name IN (
       'RL_MR_PLANES_ACCION', 'RL_MR_EVIDENCIAS', 'RL_MR_HISTORIAL',
       'SEQ_RL_MR_PLANES_ACCION', 'SEQ_RL_MR_EVIDENCIAS', 'SEQ_RL_MR_HISTORIAL')
 ORDER BY object_type, object_name;

PROMPT === FASE 10: CONSTRAINTS ===
SELECT table_name, constraint_name, constraint_type, status
  FROM user_constraints
 WHERE table_name IN ('RL_MR_PLANES_ACCION', 'RL_MR_EVIDENCIAS', 'RL_MR_HISTORIAL')
 ORDER BY table_name, constraint_type, constraint_name;

PROMPT === FASE 10: INDICES ===
SELECT table_name, index_name, uniqueness, status
  FROM user_indexes
 WHERE table_name IN ('RL_MR_PLANES_ACCION', 'RL_MR_EVIDENCIAS', 'RL_MR_HISTORIAL')
 ORDER BY table_name, index_name;

PROMPT === FASE 10: VOLUMEN Y ESTADOS DE PLANES ===
SELECT MRPA_ESTADO AS estado, COUNT(*) AS total
  FROM RL_MR_PLANES_ACCION
 GROUP BY MRPA_ESTADO
 ORDER BY MRPA_ESTADO;

PROMPT === FASE 10: VOLUMEN Y ESTADOS DE EVIDENCIAS ===
SELECT MREV_ESTADO_REGISTRO AS activo, COUNT(*) AS total,
       SUM(CASE WHEN MREV_HASH_SHA256 IS NOT NULL THEN 1 ELSE 0 END) AS con_hash_sha256
  FROM RL_MR_EVIDENCIAS
 GROUP BY MREV_ESTADO_REGISTRO
 ORDER BY MREV_ESTADO_REGISTRO;

PROMPT === FASE 10: INTEGRIDAD FUNCIONAL ===
SELECT 'PLAN_SIN_MATRIZ' AS control, COUNT(*) AS hallazgos
  FROM RL_MR_PLANES_ACCION p
 WHERE NOT EXISTS (SELECT 1 FROM RL_MR_MATRICES m WHERE m.MRMAT_ID = p.MRPA_MATRIZ_ID)
UNION ALL
SELECT 'EVIDENCIA_SIN_MATRIZ', COUNT(*)
  FROM RL_MR_EVIDENCIAS e
 WHERE NOT EXISTS (SELECT 1 FROM RL_MR_MATRICES m WHERE m.MRMAT_ID = e.MREV_MATRIZ_ID)
UNION ALL
SELECT 'EVIDENCIA_PLAN_INCONSISTENTE', COUNT(*)
  FROM RL_MR_EVIDENCIAS e
 WHERE e.MREV_PLAN_ID IS NOT NULL
   AND NOT EXISTS (
       SELECT 1 FROM RL_MR_PLANES_ACCION p
        WHERE p.MRPA_ID = e.MREV_PLAN_ID
          AND p.MRPA_MATRIZ_ID = e.MREV_MATRIZ_ID)
UNION ALL
SELECT 'EVIDENCIA_ACTIVA_SIN_HASH', COUNT(*)
  FROM RL_MR_EVIDENCIAS e
 WHERE e.MREV_ESTADO_REGISTRO = 1
   AND e.MREV_HASH_SHA256 IS NULL;

PROMPT === FASE 10: TRAZABILIDAD FUNCIONAL AGREGADA ===
SELECT MRH_TABLA AS tabla, MRH_ACCION AS accion, COUNT(*) AS total,
       MIN(MRH_FECHA) AS primera_fecha, MAX(MRH_FECHA) AS ultima_fecha
  FROM RL_MR_HISTORIAL
 WHERE MRH_TABLA IN ('RL_MR_PLANES_ACCION', 'RL_MR_EVIDENCIAS')
 GROUP BY MRH_TABLA, MRH_ACCION
 ORDER BY MRH_TABLA, MRH_ACCION;

PROMPT === FIN VALIDACION FASE 10 (SOLO LECTURA) ===
EXIT SUCCESS
