-- ============================================================
-- SISTEMA DE GESTIÓN DE RIESGOS LA/FT - IHSS
-- Módulo: Matrices de Riesgos
-- Script: 01_create_rl_mr_estructura_dinamica.sql
-- Objetivo: Crear la nueva estructura física híbrida para el Módulo Dinámico.
-- Clasificación: SCRIPT EN FASE DE DISEÑO (BLOQUEADO HASTA FASE 5 DE INSTALACIÓN).
-- ============================================================

-- BLOQUE DE SEGURIDAD EXPLICITO - IMPEDIR EJECUCIÓN ACCIDENTAL
DECLARE
  v_fase_aprobada VARCHAR2(10) := 'NO'; -- CAMBIAR A 'SI' CUANDO SE AUTORICE LA FASE 5 DE INSTALACIÓN
BEGIN
  IF v_fase_aprobada <> 'SI' THEN
    RAISE_APPLICATION_ERROR(-20100, 'EJECUCIÓN BLOQUEADA: Este script está en fase de diseño. El DBA debe cambiar v_fase_aprobada a ''SI'' en la Fase 5.');
  END IF;
END;
/

-- DECLARACIÓN DE SECUENCIAS
CREATE SEQUENCE SEQ_RL_MR_FAMILIAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_VERSIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_RIESGOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_EVALUACIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_REVISIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_PROYECCIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_FLUJOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_CONTROLES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_EVAL_CONTROLES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_PLANES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_ACTIVIDADES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_EVIDENCIAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_SENALES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_AUTOMONITOREO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_CATALOGOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_ELEMENTOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_REGLAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_TRAZAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_LOTES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_DETALLES_IMP START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE;

-- 1. TABLA: FAMILIAS DE FORMULARIO
CREATE TABLE RL_MR_FAMILIAS_FORMULARIO (
    FAM_ID            NUMBER(15)      NOT NULL,
    FAM_CODIGO        VARCHAR2(50)    NOT NULL,
    FAM_NOMBRE        VARCHAR2(150)   NOT NULL,
    FAM_DESCRIPCION   VARCHAR2(500),
    FAM_ACTIVO        NUMBER(1)       DEFAULT 1 NOT NULL,
    FAM_FECHA_CREACION DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_MR_FAMILIAS PRIMARY KEY (FAM_ID),
    CONSTRAINT UQ_RL_MR_FAM_COD UNIQUE (FAM_CODIGO),
    CONSTRAINT CK_RL_MR_FAM_ACT CHECK (FAM_ACTIVO IN (0,1))
);

-- 2. TABLA: VERSIONES DE FORMULARIO (JSON de Configuración)
CREATE TABLE RL_MR_VERSIONES_FORMULARIO (
    VER_ID            NUMBER(15)      NOT NULL,
    VER_FAMILIA_ID    NUMBER(15)      NOT NULL,
    VER_CODIGO        VARCHAR2(30)    NOT NULL,
    VER_VERSION       NUMBER(5)       NOT NULL,
    VER_JSON          CLOB            NOT NULL,
    VER_HASH          VARCHAR2(64)    NOT NULL,
    VER_ESTADO        VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL,
    VER_VIGENTE       NUMBER(1)       DEFAULT 0 NOT NULL,
    VER_FECHA_INICIO  DATE,
    VER_FECHA_FIN     DATE,
    VER_FECHA_CREACION DATE            DEFAULT SYSDATE NOT NULL,
    VER_USR_CREACION  NUMBER(10)      NOT NULL,
    CONSTRAINT PK_RL_MR_VERSIONES PRIMARY KEY (VER_ID),
    CONSTRAINT FK_RL_MR_VER_FAM FOREIGN KEY (VER_FAMILIA_ID) REFERENCES RL_MR_FAMILIAS_FORMULARIO(FAM_ID),
    CONSTRAINT UQ_RL_MR_VER_FAM_VER UNIQUE (VER_FAMILIA_ID, VER_VERSION),
    CONSTRAINT CK_RL_MR_VER_EST CHECK (VER_ESTADO IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED_ACTIVE', 'RETIRED', 'ARCHIVED')),
    CONSTRAINT CK_RL_MR_VER_VIG CHECK (VER_VIGENTE IN (0,1)),
    CONSTRAINT CK_RL_MR_VER_JSON CHECK (VER_JSON IS JSON)
);

-- 3. TABLA: CAMPOS CANÓNICOS DEL FORMULARIO
CREATE TABLE RL_MR_CAMPOS_FORMULARIO (
    CAM_ID            NUMBER(15)      NOT NULL,
    CAM_CLAVE_CANONICA VARCHAR2(100)   NOT NULL,
    CAM_NOMBRE_MOSTRAR VARCHAR2(150)   NOT NULL,
    CAM_DESCRIPCION   VARCHAR2(500),
    CAM_TIPO_DATO     VARCHAR2(50)    NOT NULL,
    CAM_FECHA_CREACION DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_MR_CAMPOS PRIMARY KEY (CAM_ID),
    CONSTRAINT UQ_RL_MR_CAM_CANONICA UNIQUE (CAM_CLAVE_CANONICA)
);

-- 4. TABLA: HISTORIAL DE APROBACIONES DE FORMULARIO
CREATE TABLE RL_MR_APROBACIONES_FORMULARIO (
    APR_ID            NUMBER(15)      NOT NULL,
    APR_VERSION_ID    NUMBER(15)      NOT NULL,
    APR_ESTADO_NVO    VARCHAR2(20)    NOT NULL,
    APR_COMENTARIO    VARCHAR2(1000),
    APR_USR_ID        NUMBER(10)      NOT NULL,
    APR_FECHA         DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_MR_APROBACIONES PRIMARY KEY (APR_ID),
    CONSTRAINT FK_RL_MR_APR_VER FOREIGN KEY (APR_VERSION_ID) REFERENCES RL_MR_VERSIONES_FORMULARIO(VER_ID)
);

-- 5. TABLA: CONFIGURACIÓN DE PERMISOS POR CAMPO/ROL
CREATE TABLE RL_MR_PERMISOS_FORMULARIO (
    PER_ID            NUMBER(15)      NOT NULL,
    PER_VERSION_ID    NUMBER(15)      NOT NULL,
    PER_ROL_ID        NUMBER(3)       NOT NULL,
    PER_SECCION_ID    VARCHAR2(100)   NOT NULL,
    PER_PERMISO       VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK_RL_MR_PERMISOS PRIMARY KEY (PER_ID),
    CONSTRAINT FK_RL_MR_PER_VER FOREIGN KEY (PER_VERSION_ID) REFERENCES RL_MR_VERSIONES_FORMULARIO(VER_ID),
    CONSTRAINT CK_RL_MR_PER_TIPO CHECK (PER_PERMISO IN ('LECTURA', 'EDICION', 'OCULTO'))
);

-- 6. TABLA: CABECERA PERMANENTE DEL RIESGO
CREATE TABLE RL_MR_RIESGOS (
    RIE_ID            NUMBER(15)      NOT NULL,
    RIE_CODIGO        VARCHAR2(30)    NOT NULL,
    RIE_FECHA_CREACION DATE            DEFAULT SYSDATE NOT NULL,
    RIE_ACTIVO        NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_RIESGOS PRIMARY KEY (RIE_ID),
    CONSTRAINT UQ_RL_MR_RIE_COD UNIQUE (RIE_CODIGO),
    CONSTRAINT CK_RL_MR_RIE_ACT CHECK (RIE_ACTIVO IN (0,1))
);

-- 7. TABLA: RELACIONES TRANSVERSALES N:N DE RIESGOS
CREATE TABLE RL_MR_RELACIONES_RIESGO (
    REL_RIE_PADRE_ID  NUMBER(15)      NOT NULL,
    REL_RIE_HIJO_ID   NUMBER(15)      NOT NULL,
    CONSTRAINT PK_RL_MR_RELACIONES PRIMARY KEY (REL_RIE_PADRE_ID, REL_RIE_HIJO_ID),
    CONSTRAINT FK_RL_MR_REL_PADRE FOREIGN KEY (REL_RIE_PADRE_ID) REFERENCES RL_MR_RIESGOS(RIE_ID),
    CONSTRAINT FK_RL_MR_REL_HIJO FOREIGN KEY (REL_RIE_HIJO_ID) REFERENCES RL_MR_RIESGOS(RIE_ID)
);

-- 8. TABLA: EVALUACIONES DINÁMICAS DEL RIESGO
CREATE TABLE RL_MR_EVALUACIONES_RIESGO (
    EVA_ID            NUMBER(15)      NOT NULL,
    EVA_RIESGO_ID     NUMBER(15)      NOT NULL,
    EVA_VERSION_ID    NUMBER(15)      NOT NULL,
    EVA_DATA_JSON     CLOB            NOT NULL,
    EVA_DATA_CALC_JSON CLOB           NOT NULL,
    EVA_FECHA_REGISTRO DATE            DEFAULT SYSDATE NOT NULL,
    EVA_USR_REGISTRO  NUMBER(10)      NOT NULL,
    EVA_VERSION_ROW   NUMBER(10)      DEFAULT 1 NOT NULL,
    EVA_ACTIVO        NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_EVALUACIONES PRIMARY KEY (EVA_ID),
    CONSTRAINT FK_RL_MR_EVA_RIE FOREIGN KEY (EVA_RIESGO_ID) REFERENCES RL_MR_RIESGOS(RIE_ID),
    CONSTRAINT FK_RL_MR_EVA_VER FOREIGN KEY (EVA_VERSION_ID) REFERENCES RL_MR_VERSIONES_FORMULARIO(VER_ID),
    CONSTRAINT CK_RL_MR_EVA_ACT CHECK (EVA_ACTIVO IN (0,1)),
    CONSTRAINT CK_RL_MR_EVA_JSON CHECK (EVA_DATA_JSON IS JSON),
    CONSTRAINT CK_RL_MR_EVA_CALC CHECK (EVA_DATA_CALC_JSON IS JSON)
);

-- 9. TABLA: REVISIONES E INSTANTÁNEAS HISTÓRICAS
CREATE TABLE RL_MR_REVISIONES_EVALUACION (
    REV_ID            NUMBER(15)      NOT NULL,
    REV_EVALUACION_ID NUMBER(15)      NOT NULL,
    REV_DATOS_JSON    CLOB            NOT NULL,
    REV_FECHA         DATE            DEFAULT SYSDATE NOT NULL,
    REV_USR_ID        NUMBER(10)      NOT NULL,
    CONSTRAINT PK_RL_MR_REVISIONES PRIMARY KEY (REV_ID),
    CONSTRAINT FK_RL_MR_REV_EVA FOREIGN KEY (REV_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT CK_RL_MR_REV_JSON CHECK (REV_DATOS_JSON IS JSON)
);

-- 10. TABLA: PROYECCIONES RELACIONALES PLANAS (Consulta rápida)
CREATE TABLE RL_MR_PROYECCIONES_EVALUACION (
    PROY_ID            NUMBER(15)      NOT NULL,
    PROY_EVALUACION_ID NUMBER(15)      NOT NULL,
    PROY_CODIGO_RIESGO VARCHAR2(30)    NOT NULL,
    PROY_AREA_PRINCIPAL VARCHAR2(100)   NOT NULL,
    PROY_VRI           NUMBER(3)       NOT NULL,
    PROY_VRR           NUMBER(3)       NOT NULL,
    PROY_NIVEL_INHERENTE VARCHAR2(20)  NOT NULL,
    PROY_NIVEL_RESIDUAL VARCHAR2(20)   NOT NULL,
    PROY_RESPUESTA_RIESGO VARCHAR2(50) NOT NULL,
    PROY_ESTADO_EVALUACION VARCHAR2(30) DEFAULT 'BORRADOR' NOT NULL,
    PROY_DUEÑO_RIESGO  VARCHAR2(150)   NOT NULL,
    PROY_FECHA_EVAL    DATE            NOT NULL,
    CONSTRAINT PK_RL_MR_PROYECCIONES PRIMARY KEY (PROY_ID),
    CONSTRAINT FK_RL_MR_PROY_EVA FOREIGN KEY (PROY_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT CK_RL_MR_PROY_VRI CHECK (PROY_VRI BETWEEN 1 AND 9),
    CONSTRAINT CK_RL_MR_PROY_VRR CHECK (PROY_VRR BETWEEN 1 AND 9)
);

-- 11. TABLA: FLUJOS Y ESTADOS DE LA EVALUACIÓN
CREATE TABLE RL_MR_FLUJOS_EVALUACION (
    FLU_ID            NUMBER(15)      NOT NULL,
    FLU_EVALUACION_ID NUMBER(15)      NOT NULL,
    FLU_ESTADO        VARCHAR2(30)    NOT NULL,
    FLU_MOTIVO        VARCHAR2(1000),
    FLU_USR_ID        NUMBER(10)      NOT NULL,
    FLU_FECHA         DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_MR_FLUJOS PRIMARY KEY (FLU_ID),
    CONSTRAINT FK_RL_MR_FLU_EVA FOREIGN KEY (FLU_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT CK_RL_MR_FLU_EST CHECK (FLU_ESTADO IN ('BORRADOR', 'EN_REVISION', 'OBSERVADA', 'APROBADA', 'RECHAZADA', 'CERRADA'))
);

-- 12. TABLA: CONTROLES ASOCIADOS A LA EVALUACIÓN
CREATE TABLE RL_MR_CONTROLES_RIESGO (
    CON_ID            NUMBER(15)      NOT NULL,
    CON_EVALUACION_ID NUMBER(15)      NOT NULL,
    CON_TIPO          VARCHAR2(30)    NOT NULL,
    CON_DESCRIPCION   VARCHAR2(500)   NOT NULL,
    CON_AUTOMATIZACION VARCHAR2(30)   NOT NULL,
    CON_ESTADO        VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK_RL_MR_CONTROLES PRIMARY KEY (CON_ID),
    CONSTRAINT FK_RL_MR_CON_EVA FOREIGN KEY (CON_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT CK_RL_MR_CON_TIPO CHECK (CON_TIPO IN ('PREVENTIVO', 'DETECTIVO', 'CORRECTIVO')),
    CONSTRAINT CK_RL_MR_CON_AUTO CHECK (CON_AUTOMATIZACION IN ('MANUAL', 'SEMIAUTOMATICO', 'AUTOMATICO'))
);

-- 13. TABLA: EVALUACIONES DE EFECTIVIDAD DEL CONTROL
CREATE TABLE RL_MR_EVALUACIONES_CONTROL (
    ECO_ID            NUMBER(15)      NOT NULL,
    ECO_CONTROL_ID    NUMBER(15)      NOT NULL,
    ECO_EFECTIVIDAD   NUMBER(5,2)     NOT NULL,
    ECO_COMENTARIO    VARCHAR2(500),
    CONSTRAINT PK_RL_MR_EVAL_CONTROLES PRIMARY KEY (ECO_ID),
    CONSTRAINT FK_RL_MR_ECO_CON FOREIGN KEY (ECO_CONTROL_ID) REFERENCES RL_MR_CONTROLES_RIESGO(CON_ID),
    CONSTRAINT CK_RL_MR_ECO_EF CHECK (ECO_EFECTIVIDAD BETWEEN 0 AND 100)
);

-- 14. TABLA: PLANES DE MITIGACIÓN
CREATE TABLE RL_MR_PLANES (
    PLA_ID            NUMBER(15)      NOT NULL,
    PLA_EVALUACION_ID NUMBER(15)      NOT NULL,
    PLA_DESCRIPCION   VARCHAR2(500)   NOT NULL,
    PLA_AVANCE        NUMBER(5,2)     DEFAULT 0 NOT NULL,
    PLA_PRESUPUESTO   NUMBER(15,2)    DEFAULT 0 NOT NULL,
    PLA_FECHA_INICIO  DATE            NOT NULL,
    PLA_FECHA_FIN     DATE            NOT NULL,
    PLA_ESTADO        VARCHAR2(30)    NOT NULL,
    CONSTRAINT PK_RL_MR_PLANES PRIMARY KEY (PLA_ID),
    CONSTRAINT FK_RL_MR_PLA_EVA FOREIGN KEY (PLA_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT CK_RL_MR_PLA_AV CHECK (PLA_AVANCE BETWEEN 0 AND 100),
    CONSTRAINT CK_RL_MR_PLA_PR CHECK (PLA_PRESUPUESTO >= 0)
);

-- 15. TABLA: ACTIVIDADES DE PLAN
CREATE TABLE RL_MR_ACTIVIDADES (
    ACT_ID            NUMBER(15)      NOT NULL,
    ACT_PLAN_ID       NUMBER(15)      NOT NULL,
    ACT_DESCRIPCION   VARCHAR2(500)   NOT NULL,
    ACT_RESPONSABLE   VARCHAR2(150)   NOT NULL,
    ACT_AVANCE        NUMBER(5,2)     DEFAULT 0 NOT NULL,
    ACT_FECHA_INICIO  DATE            NOT NULL,
    ACT_FECHA_FIN     DATE            NOT NULL,
    ACT_ESTADO        VARCHAR2(30)    NOT NULL,
    CONSTRAINT PK_RL_MR_ACTIVIDADES PRIMARY KEY (ACT_ID),
    CONSTRAINT FK_RL_MR_ACT_PLAN FOREIGN KEY (ACT_PLAN_ID) REFERENCES RL_MR_PLANES(PLA_ID),
    CONSTRAINT CK_RL_MR_ACT_AV CHECK (ACT_AVANCE BETWEEN 0 AND 100)
);

-- 16. TABLA: CENTRAL DE ARCHIVOS DE EVIDENCIA
CREATE TABLE RL_MR_EVIDENCIAS (
    EVI_ID            NUMBER(15)      NOT NULL,
    EVI_NOMBRE_ARCHIVO VARCHAR2(255)   NOT NULL,
    EVI_EXTENSIN      VARCHAR2(10)    NOT NULL,
    EVI_TAMANO        NUMBER(15)      NOT NULL,
    EVI_HASH          VARCHAR2(64)    NOT NULL,
    EVI_RUTA          VARCHAR2(500)   NOT NULL,
    EVI_USR_CREACION  NUMBER(10)      NOT NULL,
    EVI_FECHA_CREACION DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_MR_EVIDENCIAS PRIMARY KEY (EVI_ID),
    CONSTRAINT CK_RL_MR_EVI_TAM CHECK (EVI_TAMANO > 0)
);

-- Tablas de cruce para mantener integridad referencial física sin polimorfismo genérico:
CREATE TABLE RL_MR_EVI_EVALUACION (
    EVE_EVALUACION_ID NUMBER(15)      NOT NULL,
    EVE_EVIDENCIA_ID  NUMBER(15)      NOT NULL,
    CONSTRAINT PK_RL_MR_EVI_EVAL PRIMARY KEY (EVE_EVALUACION_ID, EVE_EVIDENCIA_ID),
    CONSTRAINT FK_RL_MR_EVE_EVA FOREIGN KEY (EVE_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT FK_RL_MR_EVE_EVI FOREIGN KEY (EVE_EVIDENCIA_ID) REFERENCES RL_MR_EVIDENCIAS(EVI_ID)
);

CREATE TABLE RL_MR_EVI_CONTROL (
    EVC_CONTROL_ID    NUMBER(15)      NOT NULL,
    EVC_EVIDENCIA_ID  NUMBER(15)      NOT NULL,
    CONSTRAINT PK_RL_MR_EVI_CTRL PRIMARY KEY (EVC_CONTROL_ID, EVC_EVIDENCIA_ID),
    CONSTRAINT FK_RL_MR_EVC_CON FOREIGN KEY (EVC_CONTROL_ID) REFERENCES RL_MR_CONTROLES_RIESGO(CON_ID),
    CONSTRAINT FK_RL_MR_EVC_EVI FOREIGN KEY (EVC_EVIDENCIA_ID) REFERENCES RL_MR_EVIDENCIAS(EVI_ID)
);

CREATE TABLE RL_MR_EVI_ACTIVIDAD (
    EVA_ACTIVIDAD_ID  NUMBER(15)      NOT NULL,
    EVA_EVIDENCIA_ID  NUMBER(15)      NOT NULL,
    CONSTRAINT PK_RL_MR_EVI_ACT PRIMARY KEY (EVA_ACTIVIDAD_ID, EVA_EVIDENCIA_ID),
    CONSTRAINT FK_RL_MR_EVA_ACT_ID FOREIGN KEY (EVA_ACTIVIDAD_ID) REFERENCES RL_MR_ACTIVIDADES(ACT_ID),
    CONSTRAINT FK_RL_MR_EVA_EVI_ID FOREIGN KEY (EVA_EVIDENCIA_ID) REFERENCES RL_MR_EVIDENCIAS(EVI_ID)
);

-- 17. TABLA: SEÑALES DE ALERTA
CREATE TABLE RL_MR_SENALES_ALERTA (
    ALE_ID            NUMBER(15)      NOT NULL,
    ALE_EVALUACION_ID NUMBER(15)      NOT NULL,
    ALE_CODIGO        VARCHAR2(50)    NOT NULL,
    ALE_INDICADOR     VARCHAR2(150)   NOT NULL,
    ALE_ESTADO        VARCHAR2(30)    DEFAULT 'INACTIVO' NOT NULL,
    ALE_FECHA_DISPARO DATE,
    CONSTRAINT PK_RL_MR_SENALES PRIMARY KEY (ALE_ID),
    CONSTRAINT FK_RL_MR_ALE_EVA FOREIGN KEY (ALE_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT CK_RL_MR_ALE_EST CHECK (ALE_ESTADO IN ('ACTIVO', 'INACTIVO'))
);

-- 18. TABLA: AUTOMONITOREO PERIÓDICO
CREATE TABLE RL_MR_AUTOMONITOREO (
    MON_ID            NUMBER(15)      NOT NULL,
    MON_EVALUACION_ID NUMBER(15)      NOT NULL,
    MON_ESTADO_RIESGO VARCHAR2(30)    NOT NULL,
    MON_ESTADO_CONTR  VARCHAR2(30)    NOT NULL,
    MON_RESULTADO     VARCHAR2(1000)  NOT NULL,
    MON_USR_ID        NUMBER(10)      NOT NULL,
    MON_FECHA         DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_MR_AUTOMONITOREO PRIMARY KEY (MON_ID),
    CONSTRAINT FK_RL_MR_MON_EVA FOREIGN KEY (MON_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID)
);

-- 19. TABLA: CATÁLOGOS PARAMÉTRICOS DINÁMICOS
CREATE TABLE RL_MR_CATALOGOS (
    CAT_ID            NUMBER(15)      NOT NULL,
    CAT_CODIGO        VARCHAR2(50)    NOT NULL,
    CAT_NOMBRE        VARCHAR2(150)   NOT NULL,
    CAT_ACTIVO        NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_CATALOGOS PRIMARY KEY (CAT_ID),
    CONSTRAINT UQ_RL_MR_CAT_COD UNIQUE (CAT_CODIGO)
);

CREATE TABLE RL_MR_ELEMENTOS_CATALOGO (
    ELE_ID            NUMBER(15)      NOT NULL,
    ELE_CATALOGO_ID   NUMBER(15)      NOT NULL,
    ELE_CODIGO        VARCHAR2(50)    NOT NULL,
    ELE_VALOR         VARCHAR2(255)   NOT NULL,
    ELE_ORDEN         NUMBER(5)       DEFAULT 0 NOT NULL,
    ELE_ACTIVO        NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_ELEMENTOS PRIMARY KEY (ELE_ID),
    CONSTRAINT FK_RL_MR_ELE_CAT FOREIGN KEY (ELE_CATALOGO_ID) REFERENCES RL_MR_CATALOGOS(CAT_ID),
    CONSTRAINT UQ_RL_MR_ELE_COD UNIQUE (ELE_CATALOGO_ID, ELE_CODIGO)
);

-- 20. TABLA: METADATOS DE REGLAS DE CÁLCULO
CREATE TABLE RL_MR_REGLAS_CALCULO (
    REG_ID            NUMBER(15)      NOT NULL,
    REG_CODIGO        VARCHAR2(50)    NOT NULL,
    REG_VERSION       VARCHAR2(20)    NOT NULL,
    REG_NOMBRE        VARCHAR2(150)   NOT NULL,
    REG_ALGORITMO_ID  VARCHAR2(100)   NOT NULL, -- Vincula a la clase C# del backend
    REG_ACTIVA        NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_REGLAS PRIMARY KEY (REG_ID),
    CONSTRAINT UQ_RL_MR_REG_COD UNIQUE (REG_CODIGO, REG_VERSION)
);

-- 21. TABLA: TRAZAS Y BITÁCORAS DE CÓMPUTO EN BACKEND
CREATE TABLE RL_MR_TRAZAS_CALCULO (
    TRA_ID            NUMBER(15)      NOT NULL,
    TRA_EVALUACION_ID NUMBER(15)      NOT NULL,
    TRA_REGLA_ID      NUMBER(15)      NOT NULL,
    TRA_ENTRADAS_JSON CLOB            NOT NULL,
    TRA_RESULTADOS_JSON CLOB          NOT NULL,
    TRA_FECHA         DATE            DEFAULT SYSDATE NOT NULL,
    TRA_USR_ID        NUMBER(10)      NOT NULL,
    CONSTRAINT PK_RL_MR_TRAZAS PRIMARY KEY (TRA_ID),
    CONSTRAINT FK_RL_MR_TRA_EVA FOREIGN KEY (TRA_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
    CONSTRAINT FK_RL_MR_TRA_REG FOREIGN KEY (TRA_REGLA_ID) REFERENCES RL_MR_REGLAS_CALCULO(REG_ID),
    CONSTRAINT CK_RL_MR_TRA_ENT CHECK (TRA_ENTRADAS_JSON IS JSON),
    CONSTRAINT CK_RL_MR_TRA_RES CHECK (TRA_RESULTADOS_JSON IS JSON)
);

-- 22. TABLA: LOTES DE IMPORTACIÓN Y CONCILIACIÓN
CREATE TABLE RL_MR_LOTES_IMPORTACION (
    LOT_ID            NUMBER(15)      NOT NULL,
    LOT_HASH_EXCEL    VARCHAR2(64)    NOT NULL,
    LOT_ESTADO        VARCHAR2(30)    NOT NULL,
    LOT_FECHA         DATE            DEFAULT SYSDATE NOT NULL,
    LOT_USR_ID        NUMBER(10)      NOT NULL,
    CONSTRAINT PK_RL_MR_LOTES PRIMARY KEY (LOT_ID)
);

CREATE TABLE RL_MR_DETALLES_IMPORTACION (
    DET_ID            NUMBER(15)      NOT NULL,
    DET_LOTE_ID       NUMBER(15)      NOT NULL,
    DET_INDICE_FILA   NUMBER(10)      NOT NULL,
    DET_CODIGO_RIESGO VARCHAR2(30),
    DET_ESTADO        VARCHAR2(20)    NOT NULL,
    DET_ERROR_LOG     CLOB,
    CONSTRAINT PK_RL_MR_DETALLES_IMP PRIMARY KEY (DET_ID),
    CONSTRAINT FK_RL_MR_DET_LOTE FOREIGN KEY (DET_LOTE_ID) REFERENCES RL_MR_LOTES_IMPORTACION(LOT_ID)
);

-- 23. TABLA: LOG DE AUDITORÍA DE CAMBIO DE VALORES DINÁMICOS
CREATE TABLE RL_MR_AUDITORIA (
    AUD_ID            NUMBER(20)      NOT NULL,
    AUD_EVALUACION_ID NUMBER(15)      NOT NULL,
    AUD_CAMPO_CLAVE   VARCHAR2(100)   NOT NULL,
    AUD_VALOR_ANT     CLOB,
    AUD_VALOR_NVO     CLOB,
    AUD_IP            VARCHAR2(45),
    AUD_USR_ID        NUMBER(10)      NOT NULL,
    AUD_FECHA         DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_MR_AUDITORIA PRIMARY KEY (AUD_ID),
    CONSTRAINT FK_RL_MR_AUD_EVA FOREIGN KEY (AUD_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID)
);
