-- ============================================================
-- SISTEMA DE GESTIÓN DE RIESGOS LA/FT - IHSS
-- Módulo: Matrices de Riesgos
-- Script: 02_create_rl_mr_restricciones_indices.sql
-- Objetivo: Crear índices de rendimiento e integridad referencial
--           secundaria para las 34 tablas del modelo definitivo.
-- Clasificación: SCRIPT EN FASE DE DISEÑO (BLOQUEADO HASTA FASE 5 DE INSTALACIÓN).
-- Nota DDL Oracle: Las sentencias CREATE INDEX y ALTER TABLE realizan
--   commit implícito. WHENEVER SQLERROR detiene la ejecución pero no
--   revierte los objetos DDL ya creados antes del fallo.
-- ============================================================

-- DIRECTIVA OBLIGATORIA PARA SQL*PLUS: ABORTAR EJECUCIÓN ANTE ERROR
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- PARÁMETRO DE ENTRADA OBLIGATORIO PARA SQL*PLUS: &1 (Palabra clave 'EJECUTAR')
DEFINE autorizacion = '&1';

-- BLOQUE DE SEGURIDAD EXPLICITO - IMPEDIR EJECUCIÓN ACCIDENTAL
DECLARE
  v_auth           VARCHAR2(50) := q'[&autorizacion]';
  v_esquema_actual VARCHAR2(100);
BEGIN
  SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') INTO v_esquema_actual FROM DUAL;
  IF UPPER(v_esquema_actual) <> 'RIESGO_LAVADO' THEN
    RAISE_APPLICATION_ERROR(-20098, 'EJECUCIÓN BLOQUEADA: Este script solo puede ejecutarse en el esquema RIESGO_LAVADO. Esquema detectado: ' || v_esquema_actual);
  END IF;

  IF UPPER(v_auth) <> 'EJECUTAR' THEN
    RAISE_APPLICATION_ERROR(-20100, 'EJECUCIÓN BLOQUEADA: Script en fase de diseño. El DBA debe pasar "EJECUTAR" como primer argumento de SQL*Plus en la Fase 5.');
  END IF;
END;
/

-- ============================================================
-- 1. ÍNDICES DE RENDIMIENTO (B-TREE)
-- ============================================================

-- 1.1 Proyecciones planas - Consultas del mapa de calor y dashboard
CREATE INDEX IDX_RL_MR_PROY_NIV_RES ON RL_MR_PROYECCIONES_EVALUACION(PROY_NIVEL_RESIDUAL);
CREATE INDEX IDX_RL_MR_PROY_EST_EVA ON RL_MR_PROYECCIONES_EVALUACION(PROY_ESTADO_EVALUACION);
CREATE INDEX IDX_RL_MR_PROY_COD ON RL_MR_PROYECCIONES_EVALUACION(PROY_CODIGO_RIESGO);
CREATE INDEX IDX_RL_MR_PROY_DUE ON RL_MR_PROYECCIONES_EVALUACION(PROY_DUENO_RIESGO);
CREATE INDEX IDX_RL_MR_PROY_AREA ON RL_MR_PROYECCIONES_EVALUACION(PROY_AREA_PRINCIPAL);
CREATE INDEX IDX_RL_MR_PROY_FECHA ON RL_MR_PROYECCIONES_EVALUACION(PROY_FECHA_EVAL);

-- 1.2 Evaluaciones de riesgo - Búsqueda transaccional
CREATE INDEX IDX_RL_MR_EVA_RIESGO ON RL_MR_EVALUACIONES_RIESGO(EVA_RIESGO_ID);
CREATE INDEX IDX_RL_MR_EVA_VERSION ON RL_MR_EVALUACIONES_RIESGO(EVA_VERSION_ID);
CREATE INDEX IDX_RL_MR_EVA_FECHA ON RL_MR_EVALUACIONES_RIESGO(EVA_FECHA_REGISTRO);

-- 1.3 Flujos y transiciones de estado
CREATE INDEX IDX_RL_MR_FLU_EVAL ON RL_MR_FLUJOS_EVALUACION(FLU_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_FLU_ESTADO ON RL_MR_FLUJOS_EVALUACION(FLU_ESTADO);

-- 1.4 Controles asociados
CREATE INDEX IDX_RL_MR_CON_EVAL ON RL_MR_CONTROLES_RIESGO(CON_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_CON_TIPO ON RL_MR_CONTROLES_RIESGO(CON_TIPO);

-- 1.5 Evaluaciones de efectividad de control
CREATE INDEX IDX_RL_MR_ECO_CTRL ON RL_MR_EVALUACIONES_CONTROL(ECO_CONTROL_ID);

-- 1.6 Planes de mitigación y actividades
CREATE INDEX IDX_RL_MR_PLA_EVAL ON RL_MR_PLANES(PLA_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_PLA_ESTADO ON RL_MR_PLANES(PLA_ESTADO);
CREATE INDEX IDX_RL_MR_ACT_PLAN ON RL_MR_ACTIVIDADES(ACT_PLAN_ID);
CREATE INDEX IDX_RL_MR_ACT_ESTADO ON RL_MR_ACTIVIDADES(ACT_ESTADO);

-- 1.7 Señales de alerta
CREATE INDEX IDX_RL_MR_ALE_EVAL ON RL_MR_SENALES_ALERTA(ALE_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_ALE_ESTADO ON RL_MR_SENALES_ALERTA(ALE_ESTADO);

-- 1.8 Automonitoreo
CREATE INDEX IDX_RL_MR_MON_EVAL ON RL_MR_AUTOMONITOREO(MON_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_MON_FECHA ON RL_MR_AUTOMONITOREO(MON_FECHA);

-- 1.9 Revisiones históricas
CREATE INDEX IDX_RL_MR_REV_EVAL ON RL_MR_REVISIONES_EVALUACION(REV_EVALUACION_ID);

-- 1.10 Trazas de cálculo
CREATE INDEX IDX_RL_MR_TRA_EVAL ON RL_MR_TRAZAS_CALCULO(TRA_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_TRA_REGLA ON RL_MR_TRAZAS_CALCULO(TRA_REGLA_ID);

-- 1.11 Importación y conciliación
CREATE INDEX IDX_RL_MR_DET_LOTE ON RL_MR_DETALLES_IMPORTACION(DET_LOTE_ID);
CREATE INDEX IDX_RL_MR_DET_ESTADO ON RL_MR_DETALLES_IMPORTACION(DET_ESTADO);

-- 1.12 Auditoría
CREATE INDEX IDX_RL_MR_AUD_EVAL ON RL_MR_AUDITORIA(AUD_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_AUD_CAMPO ON RL_MR_AUDITORIA(AUD_CAMPO_CLAVE);
CREATE INDEX IDX_RL_MR_AUD_FECHA ON RL_MR_AUDITORIA(AUD_FECHA);

-- 1.13 Catálogos y elementos
CREATE INDEX IDX_RL_MR_ELE_CAT ON RL_MR_ELEMENTOS_CATALOGO(ELE_CATALOGO_ID);

-- 1.14 Permisos granulares
CREATE INDEX IDX_RL_MR_PER_VER ON RL_MR_PERMISOS_FORMULARIO(PER_VERSION_ID);
CREATE INDEX IDX_RL_MR_PER_ROL ON RL_MR_PERMISOS_FORMULARIO(PER_ROL_ID);
CREATE INDEX IDX_RL_MR_PER_AMB ON RL_MR_PERMISOS_FORMULARIO(PER_AMBITO);

-- 1.15 Aprobaciones de formulario
CREATE INDEX IDX_RL_MR_APR_VER ON RL_MR_APROBACIONES_FORMULARIO(APR_VERSION_ID);

-- 1.16 Tablas asociativas de evidencias (9 tablas)
CREATE INDEX IDX_RL_MR_EVR_RIE ON RL_MR_EVI_RIESGO(EVR_RIESGO_ID);
CREATE INDEX IDX_RL_MR_EVR_EVI ON RL_MR_EVI_RIESGO(EVR_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVE_EVAL ON RL_MR_EVI_EVALUACION(EVE_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_EVE_EVI ON RL_MR_EVI_EVALUACION(EVE_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVC_CTRL ON RL_MR_EVI_CONTROL(EVC_CONTROL_ID);
CREATE INDEX IDX_RL_MR_EVC_EVI ON RL_MR_EVI_CONTROL(EVC_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVP_PLAN ON RL_MR_EVI_PLAN(EVP_PLAN_ID);
CREATE INDEX IDX_RL_MR_EVP_EVI ON RL_MR_EVI_PLAN(EVP_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVA_ACT ON RL_MR_EVI_ACTIVIDAD(EVA_ACTIVIDAD_ID);
CREATE INDEX IDX_RL_MR_EVA_ACT_EVI ON RL_MR_EVI_ACTIVIDAD(EVA_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVA_ALE ON RL_MR_EVI_ALERTA(EVA_ALERTA_ID);
CREATE INDEX IDX_RL_MR_EVA_ALE_EVI ON RL_MR_EVI_ALERTA(EVA_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVM_MON ON RL_MR_EVI_AUTOMONITOREO(EVM_MONITOREO_ID);
CREATE INDEX IDX_RL_MR_EVM_EVI ON RL_MR_EVI_AUTOMONITOREO(EVM_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVV_REV ON RL_MR_EVI_REVISION(EVV_REVISION_ID);
CREATE INDEX IDX_RL_MR_EVV_EVI ON RL_MR_EVI_REVISION(EVV_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_EVAP_APR ON RL_MR_EVI_APROBACION(EVAP_APROBACION_ID);
CREATE INDEX IDX_RL_MR_EVAP_EVI ON RL_MR_EVI_APROBACION(EVAP_EVIDENCIA_ID);

-- ============================================================
-- 2. RESTRICCIONES SECUNDARIAS DE INTEGRIDAD REFERENCIAL
--    (Claves foráneas hacia RL_USUARIOS del módulo principal)
-- ============================================================

ALTER TABLE RL_MR_VERSIONES_FORMULARIO ADD CONSTRAINT FK_RL_MR_VER_USR FOREIGN KEY (VER_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_APROBACIONES_FORMULARIO ADD CONSTRAINT FK_RL_MR_APR_USR FOREIGN KEY (APR_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_EVALUACIONES_RIESGO ADD CONSTRAINT FK_RL_MR_EVA_USR FOREIGN KEY (EVA_USR_REGISTRO) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_REVISIONES_EVALUACION ADD CONSTRAINT FK_RL_MR_REV_USR FOREIGN KEY (REV_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_FLUJOS_EVALUACION ADD CONSTRAINT FK_RL_MR_FLU_USR FOREIGN KEY (FLU_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_EVIDENCIAS ADD CONSTRAINT FK_RL_MR_EVI_USR FOREIGN KEY (EVI_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_AUTOMONITOREO ADD CONSTRAINT FK_RL_MR_MON_USR FOREIGN KEY (MON_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_TRAZAS_CALCULO ADD CONSTRAINT FK_RL_MR_TRA_USR FOREIGN KEY (TRA_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_LOTES_IMPORTACION ADD CONSTRAINT FK_RL_MR_LOT_USR FOREIGN KEY (LOT_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_AUDITORIA ADD CONSTRAINT FK_RL_MR_AUD_USR FOREIGN KEY (AUD_USR_ID) REFERENCES RL_USUARIOS(USR_ID);

BEGIN
  DBMS_OUTPUT.PUT_LINE('Índices de rendimiento y restricciones de integridad secundaria creadas correctamente para las 34 tablas.');
END;
/
