-- ============================================================
-- SISTEMA DE GESTIÓN DE RIESGOS LA/FT - IHSS
-- Módulo: Matrices de Riesgos
-- Script: 02_create_rl_mr_restricciones_indices.sql
-- Objetivo: Crear índices adicionales y restricciones secundarias para el módulo dinámico.
-- Clasificación: SCRIPT EN FASE DE DISEÑO (BLOQUEADO HASTA FASE 5 DE INSTALACIÓN).
-- ============================================================

-- DIRECTIVA OBLIGATORIA PARA SQL*PLUS: ABORTAR TRANSACCIÓN Y EJECUCIÓN ANTE ERROR
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- BLOQUE DE SEGURIDAD EXPLICITO - IMPEDIR EJECUCIÓN ACCIDENTAL
DECLARE
  v_fase_aprobada VARCHAR2(10) := 'NO'; -- CAMBIAR A 'SI' CUANDO SE AUTORICE LA FASE 5 DE INSTALACIÓN
BEGIN
  IF v_fase_aprobada <> 'SI' THEN
    RAISE_APPLICATION_ERROR(-20100, 'EJECUCIÓN BLOQUEADA: Este script está en fase de diseño. El DBA debe cambiar v_fase_aprobada a ''SI'' en la Fase 5.');
  END IF;
END;
/

-- 1. ÍNDICES DE RENDIMIENTO (B-TREE)
-- Optimización para consultas rápidas sobre la proyección plana y mapa de calor
CREATE INDEX IDX_RL_MR_PROY_NIV_RES ON RL_MR_PROYECCIONES_EVALUACION(PROY_NIVEL_RESIDUAL);
CREATE INDEX IDX_RL_MR_PROY_EST_EVA ON RL_MR_PROYECCIONES_EVALUACION(PROY_ESTADO_EVALUACION);
CREATE INDEX IDX_RL_MR_PROY_COD ON RL_MR_PROYECCIONES_EVALUACION(PROY_CODIGO_RIESGO);
CREATE INDEX IDX_RL_MR_PROY_DUE ON RL_MR_PROYECCIONES_EVALUACION(PROY_DUENO_RIESGO);

-- Optimización de búsquedas transaccionales de evaluaciones
CREATE INDEX IDX_RL_MR_EVA_RIESGO ON RL_MR_EVALUACIONES_RIESGO(EVA_RIESGO_ID);
CREATE INDEX IDX_RL_MR_EVA_VERSION ON RL_MR_EVALUACIONES_RIESGO(EVA_VERSION_ID);

-- Optimización de auditorías y flujos
CREATE INDEX IDX_RL_MR_FLU_EVAL ON RL_MR_FLUJOS_EVALUACION(FLU_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_AUD_EVAL ON RL_MR_AUDITORIA(AUD_EVALUACION_ID);

-- Optimización para evidencias relacionales
CREATE INDEX IDX_RL_MR_EVE_EVAL ON RL_MR_EVI_EVALUACION(EVE_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_EVC_CTRL ON RL_MR_EVI_CONTROL(EVC_CONTROL_ID);
CREATE INDEX IDX_RL_MR_EVA_ACT ON RL_MR_EVI_ACTIVIDAD(EVA_ACTIVIDAD_ID);

-- 2. RESTRICCIONES ADICIONALES (INTEGRIDAD REFERENCIAL GLOBAL)
-- Claves foráneas transversales de seguridad (auditorías y flujos)
ALTER TABLE RL_MR_VERSIONES_FORMULARIO ADD CONSTRAINT FK_RL_MR_VER_USR FOREIGN KEY (VER_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_APROBACIONES_FORMULARIO ADD CONSTRAINT FK_RL_MR_APR_USR FOREIGN KEY (APR_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_EVALUACIONES_RIESGO ADD CONSTRAINT FK_RL_MR_EVA_USR FOREIGN KEY (EVA_USR_REGISTRO) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_REVISIONES_EVALUACION ADD CONSTRAINT FK_RL_MR_REV_USR FOREIGN KEY (REV_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_FLUJOS_EVALUACION ADD CONSTRAINT FK_RL_MR_FLU_USR FOREIGN KEY (FLU_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_EVIDENCIAS ADD CONSTRAINT FK_RL_MR_EVI_USR FOREIGN KEY (EVI_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_AUTOMONITOREO ADD CONSTRAINT FK_RL_MR_MON_USR FOREIGN KEY (MON_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_TRAZAS_CALCULO ADD CONSTRAINT FK_RL_MR_TRA_USR FOREIGN KEY (TRA_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_LOTES_IMPORTACION ADD CONSTRAINT FK_RL_MR_LOT_USR FOREIGN KEY (LOT_USR_ID) REFERENCES RL_USUARIOS(USR_ID);
ALTER TABLE RL_MR_AUDITORIA ADD CONSTRAINT FK_RL_MR_AUD_USR FOREIGN KEY (AUD_USR_ID) REFERENCES RL_USUARIOS(USR_ID);

DBMS_OUTPUT.PUT_LINE('Índices y restricciones de integridad secundaria creadas correctamente.');
/
