-- ============================================================
-- SISTEMA DE GESTIÓN DE RIESGO DE LAVADO DE ACTIVOS
-- Script: 01_create_tables.sql
-- Objetivo: Estructuración de tablas (Compatible con Oracle 11g)
-- ============================================================

-- BLOQUE PL/SQL PARA ELIMINACIÓN SEGURA DE OBJETOS EXISTENTES (DROP IF EXISTS)
DECLARE
  PROCEDURE drop_table(p_table_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_table_name || ' CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
        RAISE;
      END IF;
  END;

  PROCEDURE drop_sequence(p_seq_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || p_seq_name;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
        RAISE;
      END IF;
  END;
BEGIN
  -- Eliminar tablas en orden inverso a sus dependencias
  drop_table('RL_LOGIN_SLIDES');
  drop_table('RL_CONFIG_SISTEMA');
  drop_table('RL_AUDITORIA');
  drop_table('RL_PASSWORD_RESET_TOKENS');
  drop_table('RL_REFRESH_TOKENS');
  drop_table('RL_USUARIOS');
  drop_table('RL_ROLES');
  drop_table('RL_DOMINIO');

  -- Eliminar secuencias
  drop_sequence('SEQ_RL_DOMINIO');
  drop_sequence('SEQ_RL_ROLES');
  drop_sequence('SEQ_RL_USUARIOS');
  drop_sequence('SEQ_RL_REFRESH_TOKENS');
  drop_sequence('SEQ_RL_RESET_TOKENS');
  drop_sequence('SEQ_RL_AUDITORIA');
END;
/

-- 1. TABLA: DOMINIOS DE RED
CREATE TABLE RL_DOMINIO (
    DOM_ID          NUMBER(5)       NOT NULL,
    DOM_NOMBRE      VARCHAR2(100)   NOT NULL,
    DOM_DESCRIPCION VARCHAR2(255),
    DOM_ACTIVO      NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_DOMINIO PRIMARY KEY (DOM_ID),
    CONSTRAINT UQ_RL_DOM_NOMBRE UNIQUE (DOM_NOMBRE),
    CONSTRAINT CK_RL_DOM_ACTIVO CHECK (DOM_ACTIVO IN (0,1))
);
COMMENT ON TABLE RL_DOMINIO IS 'Catálogo de dominios institucionales de red.';
COMMENT ON COLUMN RL_DOMINIO.DOM_ID IS 'Identificador único correlativo del dominio.';
COMMENT ON COLUMN RL_DOMINIO.DOM_NOMBRE IS 'Nombre o DNS del dominio.';
COMMENT ON COLUMN RL_DOMINIO.DOM_DESCRIPCION IS 'Descripción del dominio.';
COMMENT ON COLUMN RL_DOMINIO.DOM_ACTIVO IS 'Estado: 1=Activo, 0=Inactivo.';

CREATE SEQUENCE SEQ_RL_DOMINIO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. TABLA: ROLES DE USUARIO
CREATE TABLE RL_ROLES (
    ROL_ID             NUMBER(3)       NOT NULL,
    ROL_NOMBRE         VARCHAR2(50)    NOT NULL,
    ROL_DESCRIPCION    VARCHAR2(200),
    ROL_ACTIVO         NUMBER(1)       DEFAULT 1 NOT NULL,
    ROL_FECHA_CREACION DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RL_ROLES PRIMARY KEY (ROL_ID),
    CONSTRAINT UQ_RL_ROL_NOMBRE UNIQUE (ROL_NOMBRE),
    CONSTRAINT CK_RL_ROL_ACTIVO CHECK (ROL_ACTIVO IN (0,1))
);
COMMENT ON TABLE RL_ROLES IS 'Roles del sistema para control de accesos.';
COMMENT ON COLUMN RL_ROLES.ROL_ID IS 'Identificador del rol.';
COMMENT ON COLUMN RL_ROLES.ROL_NOMBRE IS 'Nombre del rol (ej. ADMINISTRADOR).';
COMMENT ON COLUMN RL_ROLES.ROL_DESCRIPCION IS 'Descripción del rol.';
COMMENT ON COLUMN RL_ROLES.ROL_ACTIVO IS 'Estado: 1=Activo, 0=Inactivo.';
COMMENT ON COLUMN RL_ROLES.ROL_FECHA_CREACION IS 'Fecha de creación.';

CREATE SEQUENCE SEQ_RL_ROLES START WITH 1 INCREMENT BY 1 NOCACHE;

-- 3. TABLA: USUARIOS CENTRALIZADA
CREATE TABLE RL_USUARIOS (
    USR_ID                  NUMBER(10)      NOT NULL,
    USR_NOMBRE              VARCHAR2(100)   NOT NULL,
    USR_APELLIDO            VARCHAR2(100)   NOT NULL,
    USR_EMAIL               VARCHAR2(150)   NOT NULL,
    USR_PASSWORD_HASH       VARCHAR2(256)   NOT NULL,
    USR_PASSWORD_SALT       VARCHAR2(256)   NOT NULL,
    USR_ROL_ID              NUMBER(3)       NOT NULL,
    USR_EMPLEADO_ID         VARCHAR2(20),
    USR_ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    USR_FECHA_CREACION      DATE            DEFAULT SYSDATE NOT NULL,
    USR_FECHA_MODIFICACION  DATE,
    USR_CREADO_POR          NUMBER(10),
    ES_USUARIO_DOMINIO      NUMBER(1)       DEFAULT 0,
    USR_DOM_ID              NUMBER(5),
    USUARIO_DOMINIO         VARCHAR2(500),
    USR_DNI                 VARCHAR2(25 CHAR),
    CONSTRAINT PK_RL_USUARIOS PRIMARY KEY (USR_ID),
    CONSTRAINT UQ_RL_USR_EMAIL UNIQUE (USR_EMAIL),
    CONSTRAINT FK_RL_USR_ROL FOREIGN KEY (USR_ROL_ID) REFERENCES RL_ROLES(ROL_ID),
    CONSTRAINT FK_RL_USR_DOM FOREIGN KEY (USR_DOM_ID) REFERENCES RL_DOMINIO(DOM_ID),
    CONSTRAINT CK_RL_USR_ACTIVO CHECK (USR_ACTIVO IN (0,1))
);
COMMENT ON TABLE RL_USUARIOS IS 'Información de cuentas de usuario.';
COMMENT ON COLUMN RL_USUARIOS.USR_ID IS 'Clave primaria.';
COMMENT ON COLUMN RL_USUARIOS.USR_NOMBRE IS 'Nombres del usuario.';
COMMENT ON COLUMN RL_USUARIOS.USR_APELLIDO IS 'Apellidos del usuario.';
COMMENT ON COLUMN RL_USUARIOS.USR_EMAIL IS 'Email corporativo único.';
COMMENT ON COLUMN RL_USUARIOS.USR_PASSWORD_HASH IS 'Hash de contraseña.';
COMMENT ON COLUMN RL_USUARIOS.USR_PASSWORD_SALT IS 'Salt de la contraseña (o BCRYPT).';
COMMENT ON COLUMN RL_USUARIOS.USR_ROL_ID IS 'ID del rol asignado.';
COMMENT ON COLUMN RL_USUARIOS.USR_EMPLEADO_ID IS 'Identificador del empleado.';
COMMENT ON COLUMN RL_USUARIOS.USR_ACTIVO IS 'Estado: 1=Habilitado, 0=Bloqueado/Inactivo.';
COMMENT ON COLUMN RL_USUARIOS.USR_FECHA_CREACION IS 'Fecha de creación de la cuenta.';
COMMENT ON COLUMN RL_USUARIOS.USR_FECHA_MODIFICACION IS 'Fecha del último cambio.';
COMMENT ON COLUMN RL_USUARIOS.USR_CREADO_POR IS 'ID del usuario que creó este registro.';
COMMENT ON COLUMN RL_USUARIOS.ES_USUARIO_DOMINIO IS 'Indica si inicia sesión con AD (1) o local (0).';
COMMENT ON COLUMN RL_USUARIOS.USR_DOM_ID IS 'ID del dominio AD al que pertenece.';
COMMENT ON COLUMN RL_USUARIOS.USUARIO_DOMINIO IS 'Nombre de usuario del dominio AD.';
COMMENT ON COLUMN RL_USUARIOS.USR_DNI IS 'Número de identidad.';

CREATE SEQUENCE SEQ_RL_USUARIOS START WITH 2 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_RL_USR_EMAIL ON RL_USUARIOS(USR_EMAIL);
CREATE INDEX IDX_RL_USR_ROL ON RL_USUARIOS(USR_ROL_ID);
CREATE INDEX IDX_RL_USR_DOM ON RL_USUARIOS(USR_DOM_ID);

-- 4. TABLA: REFRESH TOKENS (Sesiones JWT Extendidas)
CREATE TABLE RL_REFRESH_TOKENS (
    RFT_ID              NUMBER(15)      NOT NULL,
    RFT_USR_ID          NUMBER(10)      NOT NULL,
    RFT_TOKEN           VARCHAR2(500)   NOT NULL,
    RFT_EXPIRA          DATE            NOT NULL,
    RFT_REVOCADO        NUMBER(1)       DEFAULT 0 NOT NULL,
    RFT_FECHA_CREACION  DATE            DEFAULT SYSDATE NOT NULL,
    RFT_IP_ORIGEN       VARCHAR2(45),
    CONSTRAINT PK_RL_REFRESH_TOKENS PRIMARY KEY (RFT_ID),
    CONSTRAINT FK_RL_RFT_USR FOREIGN KEY (RFT_USR_ID) REFERENCES RL_USUARIOS(USR_ID),
    CONSTRAINT CK_RL_RFT_REVOCADO CHECK (RFT_REVOCADO IN (0,1))
);
COMMENT ON TABLE RL_REFRESH_TOKENS IS 'Almacén de Refresh Tokens para renovación de JWT.';

CREATE SEQUENCE SEQ_RL_REFRESH_TOKENS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_RL_RFT_TOKEN ON RL_REFRESH_TOKENS(RFT_TOKEN);
CREATE INDEX IDX_RL_RFT_USR ON RL_REFRESH_TOKENS(RFT_USR_ID);

-- 5. TABLA: PASSWORD RESET TOKENS (Tokens de recuperación de contraseña)
CREATE TABLE RL_PASSWORD_RESET_TOKENS (
    PRT_ID          NUMBER(15)      NOT NULL,
    PRT_USR_ID      NUMBER(10)      NOT NULL,
    PRT_TOKEN       VARCHAR2(255)   NOT NULL,
    PRT_EXPIRA      DATE            NOT NULL,
    PRT_CREADO      DATE            DEFAULT SYSDATE NOT NULL,
    PRT_USADO       NUMBER(1)       DEFAULT 0 NOT NULL,
    CONSTRAINT PK_RL_RESET_TOKENS PRIMARY KEY (PRT_ID),
    CONSTRAINT FK_RL_PRT_USR FOREIGN KEY (PRT_USR_ID) REFERENCES RL_USUARIOS(USR_ID),
    CONSTRAINT CK_RL_PRT_USADO CHECK (PRT_USADO IN (0,1))
);
COMMENT ON TABLE RL_PASSWORD_RESET_TOKENS IS 'Tokens para restablecimiento de contraseñas olvidadas.';

CREATE SEQUENCE SEQ_RL_RESET_TOKENS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_RL_PRT_TOKEN ON RL_PASSWORD_RESET_TOKENS(PRT_TOKEN);

-- 6. TABLA: AUDITORÍA GENERAL DE ACCIONES
CREATE TABLE RL_AUDITORIA (
    AUD_ID          NUMBER(20)      NOT NULL,
    AUD_TABLA       VARCHAR2(50)    NOT NULL,
    AUD_REGISTRO_ID VARCHAR2(50)    NOT NULL,
    AUD_ACCION      VARCHAR2(10)    NOT NULL,
    AUD_DATOS_ANT   CLOB,
    AUD_DATOS_NVO   CLOB,
    AUD_USR_ID      NUMBER(10),
    AUD_USR_EMAIL   VARCHAR2(150),
    AUD_IP          VARCHAR2(45),
    AUD_FECHA       DATE            DEFAULT SYSDATE NOT NULL,
    AUD_MODULO      VARCHAR2(50),
    CONSTRAINT PK_RL_AUDITORIA PRIMARY KEY (AUD_ID),
    CONSTRAINT CK_RL_AUD_ACCION CHECK (AUD_ACCION IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT'))
);
COMMENT ON TABLE RL_AUDITORIA IS 'Bitácora general de auditoría para control interno.';

CREATE SEQUENCE SEQ_RL_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_RL_AUD_TABLA ON RL_AUDITORIA(AUD_TABLA);
CREATE INDEX IDX_RL_AUD_USR ON RL_AUDITORIA(AUD_USR_ID);

-- 7. TABLA: CONFIGURACIÓN VISUAL GENERAL DEL SISTEMA
CREATE TABLE RL_CONFIG_SISTEMA (
    SFS_ID                 NUMBER(1) DEFAULT 1 PRIMARY KEY,
    SFS_NOMBRE_INSTITUCION VARCHAR2(255) NOT NULL,
    SFS_NOMBRE_SISTEMA     VARCHAR2(100) NOT NULL,
    SFS_LOGO_URL           VARCHAR2(500),
    SFS_ICONO_URL          VARCHAR2(500),
    SFS_COLOR_PRIMARIO     VARCHAR2(20) DEFAULT '#1e3a8a',
    SFS_COLOR_SECUNDARIO   VARCHAR2(20) DEFAULT '#1d4ed8',
    SFS_TIMEOUT_SESION     NUMBER DEFAULT 30,
    SFS_ULTIMA_ACTUALIZACION DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_RL_ONE_ROW CHECK (SFS_ID = 1)
);
COMMENT ON TABLE RL_CONFIG_SISTEMA IS 'Configuración de imagen corporativa e inactividad.';

-- 8. TABLA: SLIDES DE CARRUSEL DE INICIO DE SESIÓN
CREATE TABLE RL_LOGIN_SLIDES (
    SGL_ID          NUMBER(2)       NOT NULL,
    SGL_IMAGEN_URL  VARCHAR2(500)   NOT NULL,
    SGL_TITULO      VARCHAR2(100),
    SGL_DESCRIPCION VARCHAR2(500),
    SGL_ORDEN       NUMBER(2)       DEFAULT 0,
    SGL_ACTIVO      NUMBER(1)       DEFAULT 1 NOT NULL,
    SGL_FECHA_MODIF DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_RL_LOGIN_SLIDES PRIMARY KEY (SGL_ID),
    CONSTRAINT CK_RL_SGL_ACTIVO CHECK (SGL_ACTIVO IN (0,1))
);
COMMENT ON TABLE RL_LOGIN_SLIDES IS ' slides informativos para carrusel en pantalla de login.';
