-- ============================================================
-- SISTEMA DE GESTIÓN DE RIESGO DE LAVADO DE ACTIVOS
-- Script: 09_create_detalle_evidencia.sql
-- Objetivo: Crear tabla de metadatos de evidencia física para seguimientos
-- ============================================================

DECLARE
  PROCEDURE drop_table(p_table_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_table_name || ' CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;

  PROCEDURE drop_sequence(p_seq_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || p_seq_name;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
BEGIN
  drop_table('RL_DETALLE_EVIDENCIA');
  drop_sequence('SEQ_RL_DETALLE_EVIDENCIA');
END;
/

-- 1. TABLA: RL_DETALLE_EVIDENCIA
CREATE TABLE RL_DETALLE_EVIDENCIA (
    EVI_ID              NUMBER(20)      NOT NULL,
    EVI_DETALLE_ID      NUMBER(20)      NOT NULL,
    EVI_NOMBRE_ARCHIVO  VARCHAR2(255)   NOT NULL,
    EVI_TIPO_MIME       VARCHAR2(100)   NOT NULL,
    EVI_RUTA_ARCHIVO    VARCHAR2(500)   NOT NULL,
    EVI_FECHA_CREACION  DATE            DEFAULT SYSDATE NOT NULL,
    EVI_USR_CREACION_ID NUMBER(10)      NOT NULL,
    EVI_ESTADO_REGISTRO NUMBER(1)       DEFAULT 1 NOT NULL,
    EVI_USR_INACTIVO_ID NUMBER(10),
    EVI_FECHA_INACTIVO  DATE,
    CONSTRAINT PK_RL_DETALLE_EVIDENCIA PRIMARY KEY (EVI_ID),
    CONSTRAINT FK_EVI_DETALLE_LISTA FOREIGN KEY (EVI_DETALLE_ID) REFERENCES RL_DETALLE_LISTA(DLL_DETALLE_LISTA_ID) ON DELETE CASCADE
);

COMMENT ON TABLE RL_DETALLE_EVIDENCIA IS 'Almacén de metadatos y rutas físicas de archivos cargados como evidencia de seguimiento.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_ID IS 'Clave primaria.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_DETALLE_ID IS 'Clave foránea a la nota de seguimiento en RL_DETALLE_LISTA.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_NOMBRE_ARCHIVO IS 'Nombre original del archivo (ej. documento.pdf).';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_TIPO_MIME IS 'Tipo de contenido MIME del archivo.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_RUTA_ARCHIVO IS 'Nombre/ruta física del archivo almacenado en el disco del servidor.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_FECHA_CREACION IS 'Fecha de carga.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_USR_CREACION_ID IS 'ID del usuario que subió la evidencia.';

COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_ESTADO_REGISTRO IS 'Estado del registro: 1=Activo, 0=Inactivo por eliminacion logica.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_USR_INACTIVO_ID IS 'ID del usuario que realizo la eliminacion logica.';
COMMENT ON COLUMN RL_DETALLE_EVIDENCIA.EVI_FECHA_INACTIVO IS 'Fecha en que se realizo la eliminacion logica.';

-- 2. SECUENCIA
CREATE SEQUENCE SEQ_RL_DETALLE_EVIDENCIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_EVI_DETALLE ON RL_DETALLE_EVIDENCIA(EVI_DETALLE_ID);
CREATE INDEX IDX_EVI_DETALLE_ESTADO ON RL_DETALLE_EVIDENCIA(EVI_DETALLE_ID, EVI_ESTADO_REGISTRO);

COMMIT;
