-- Auditoria manual y estrictamente de solo lectura de database links Oracle.
--
-- EJECUCION OBLIGATORIA:
--   1. Conectarse como DNP_IHSS y ejecutar este archivo.
--   2. Conectarse como RIESGO_LAVADO y ejecutar este archivo.
--
-- USER_DB_LINKS y USER_DEPENDENCIES dependen del usuario autenticado. No use
-- ALTER SESSION SET CURRENT_SCHEMA como sustituto de una conexion por esquema.
-- Este utilitario no pertenece a los maestros de instalacion o actualizacion.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SET ECHO OFF
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 500
SET TRIMSPOOL ON

PROMPT === AUDITORIA_DBLINKS_SESION ===
SELECT
    SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME,
    SYS_CONTEXT('USERENV', 'SESSION_USER') AS SESSION_USER,
    SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA
FROM DUAL;

PROMPT === DDLINKS_PRIVADOS_DEL_ESQUEMA ===
SELECT
    DB_LINK,
    USERNAME,
    HOST,
    CREATED
FROM USER_DB_LINKS
ORDER BY DB_LINK;

PROMPT === DDLINKS_PUBLICOS_O_ACCESIBLES ===
SELECT
    OWNER,
    DB_LINK,
    USERNAME,
    HOST,
    CREATED
FROM ALL_DB_LINKS
WHERE OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
   OR OWNER = 'PUBLIC'
ORDER BY OWNER, DB_LINK;

PROMPT === SINONIMOS_LOCALES_O_PUBLICOS_QUE_USAN_DBLINK ===
SELECT
    OWNER,
    SYNONYM_NAME,
    TABLE_OWNER,
    TABLE_NAME,
    DB_LINK
FROM ALL_SYNONYMS
WHERE DB_LINK IS NOT NULL
  AND (OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') OR OWNER = 'PUBLIC')
ORDER BY OWNER, SYNONYM_NAME;

PROMPT === OBJETOS_DEL_ESQUEMA_CON_DEPENDENCIA_REMOTA ===
SELECT
    NAME,
    TYPE,
    REFERENCED_OWNER,
    REFERENCED_NAME,
    REFERENCED_TYPE,
    REFERENCED_LINK_NAME
FROM USER_DEPENDENCIES
WHERE REFERENCED_LINK_NAME IS NOT NULL
ORDER BY NAME, TYPE, REFERENCED_LINK_NAME;

EXIT SUCCESS
