-- ============================================================
-- UTILITARIO: plantilla de respaldo previo a actualizaciones
-- Uso: copiar, ajustar sufijo y ejecutar manualmente bajo aprobacion DBA.
-- Este archivo NO forma parte de los scripts maestros.
-- ============================================================

-- Reemplace el sufijo por fecha/hora de ejecucion, por ejemplo: 20260630_1530
DEFINE BKP_SUFFIX = 'YYYYMMDD_HH24MI'

PROMPT Creando respaldos previos con sufijo &BKP_SUFFIX

CREATE TABLE BKP_RL_MODULOS_&BKP_SUFFIX AS SELECT * FROM RL_MODULOS;
CREATE TABLE BKP_RL_USUARIO_MODULOS_&BKP_SUFFIX AS SELECT * FROM RL_USUARIO_MODULOS;
CREATE TABLE BKP_RL_USUARIOS_&BKP_SUFFIX AS SELECT * FROM RL_USUARIOS;
CREATE TABLE BKP_RL_CONFIG_SISTEMA_&BKP_SUFFIX AS SELECT * FROM RL_CONFIG_SISTEMA;
CREATE TABLE BKP_RL_LOGIN_SLIDES_&BKP_SUFFIX AS SELECT * FROM RL_LOGIN_SLIDES;

-- Ejecutar solo si existen en el ambiente destino.
-- CREATE TABLE BKP_RL_DETALLE_EVIDENCIA_&BKP_SUFFIX AS SELECT * FROM RL_DETALLE_EVIDENCIA;
-- CREATE TABLE BKP_RL_LISTA_POSITIVOS_&BKP_SUFFIX AS SELECT * FROM RL_LISTA_POSITIVOS;
-- CREATE TABLE BKP_RL_CALIF_COINCIDENCIAS_&BKP_SUFFIX AS SELECT * FROM RL_CALIF_COINCIDENCIAS;

PROMPT Respaldos creados. Validar conteos:
SELECT 'RL_MODULOS' TABLA, COUNT(*) TOTAL FROM BKP_RL_MODULOS_&BKP_SUFFIX
UNION ALL SELECT 'RL_USUARIO_MODULOS', COUNT(*) FROM BKP_RL_USUARIO_MODULOS_&BKP_SUFFIX
UNION ALL SELECT 'RL_USUARIOS', COUNT(*) FROM BKP_RL_USUARIOS_&BKP_SUFFIX
UNION ALL SELECT 'RL_CONFIG_SISTEMA', COUNT(*) FROM BKP_RL_CONFIG_SISTEMA_&BKP_SUFFIX
UNION ALL SELECT 'RL_LOGIN_SLIDES', COUNT(*) FROM BKP_RL_LOGIN_SLIDES_&BKP_SUFFIX;
