-- ============================================================
-- FASE 11 - BLOQUE 4
-- Mitigación, controles, planes, actividades y evidencias
-- Validación de solo lectura
-- ============================================================
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === CONTEOS BLOQUE 4 ===
SELECT 'RL_MR_CONTROLES_RIESGO' AS OBJETO, COUNT(*) AS TOTAL FROM RL_MR_CONTROLES_RIESGO
UNION ALL SELECT 'RL_MR_EVALUACIONES_CONTROL' AS OBJETO, COUNT(*) AS TOTAL FROM RL_MR_EVALUACIONES_CONTROL
UNION ALL SELECT 'RL_MR_PLANES' AS OBJETO, COUNT(*) AS TOTAL FROM RL_MR_PLANES
UNION ALL SELECT 'RL_MR_ACTIVIDADES' AS OBJETO, COUNT(*) AS TOTAL FROM RL_MR_ACTIVIDADES
UNION ALL SELECT 'RL_MR_EVIDENCIAS' AS OBJETO, COUNT(*) AS TOTAL FROM RL_MR_EVIDENCIAS
UNION ALL SELECT 'RL_MR_EVIDENCIAS_VINCULOS' AS OBJETO, COUNT(*) AS TOTAL FROM RL_MR_EVIDENCIAS_VINCULOS
 ORDER BY OBJETO ASC;

DECLARE
    v_count NUMBER;
    PROCEDURE exigir(p_cond BOOLEAN, p_code NUMBER, p_message VARCHAR2) IS
    BEGIN
        IF NOT p_cond THEN RAISE_APPLICATION_ERROR(p_code, p_message); END IF;
    END;
BEGIN
    exigir(UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA')) = 'RIESGO_LAVADO', -20501,
           'CURRENT_SCHEMA debe ser RIESGO_LAVADO.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_CONTROLES_RIESGO c
     WHERE NOT EXISTS (SELECT 1 FROM RL_MR_EVALUACIONES_RIESGO e WHERE e.EVA_ID = c.CON_EVALUACION_ID);
    exigir(v_count = 0, -20502, 'Existen controles huérfanos.');

    SELECT COUNT(*) INTO v_count FROM RL_MR_CONTROLES_RIESGO
     WHERE CON_TIPO NOT IN ('PREVENTIVO','DETECTIVO','CORRECTIVO')
        OR CON_AUTOMATIZACION NOT IN ('MANUAL','SEMIAUTOMATICO','AUTOMATICO');
    exigir(v_count = 0, -20503, 'Existen controles fuera de los dominios oficiales.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_EVALUACIONES_CONTROL ec
     WHERE NOT EXISTS (SELECT 1 FROM RL_MR_CONTROLES_RIESGO c WHERE c.CON_ID = ec.ECO_CONTROL_ID)
        OR ec.ECO_EFECTIVIDAD < 0 OR ec.ECO_EFECTIVIDAD > 100;
    exigir(v_count = 0, -20504, 'Existen evaluaciones de control inválidas o huérfanas.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_PLANES p
     WHERE NOT EXISTS (SELECT 1 FROM RL_MR_EVALUACIONES_RIESGO e WHERE e.EVA_ID = p.PLA_EVALUACION_ID)
        OR p.PLA_AVANCE < 0 OR p.PLA_AVANCE > 100
        OR p.PLA_PRESUPUESTO < 0
        OR p.PLA_FECHA_FIN < p.PLA_FECHA_INICIO;
    exigir(v_count = 0, -20505, 'Existen planes inválidos o huérfanos.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_ACTIVIDADES a
     WHERE NOT EXISTS (SELECT 1 FROM RL_MR_PLANES p WHERE p.PLA_ID = a.ACT_PLAN_ID)
        OR a.ACT_AVANCE < 0 OR a.ACT_AVANCE > 100
        OR a.ACT_FECHA_FIN < a.ACT_FECHA_INICIO;
    exigir(v_count = 0, -20506, 'Existen actividades inválidas o huérfanas.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_EVIDENCIAS e
     WHERE e.EVI_TAMANO <= 0
        OR e.EVI_HASH IS NULL
        OR LENGTH(e.EVI_HASH) <> 64
        OR NOT EXISTS (SELECT 1 FROM RL_USUARIOS u WHERE u.USR_ID = e.EVI_USR_CREACION);
    exigir(v_count = 0, -20507, 'Existen evidencias con metadatos o usuario inválidos.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_EVIDENCIAS_VINCULOS v
     WHERE v.EVV_TIPO_ENTIDAD NOT IN ('RIESGO','EVALUACION','CONTROL','PLAN','ACTIVIDAD','ALERTA','AUTOMONITOREO')
        OR NOT EXISTS (SELECT 1 FROM RL_MR_EVIDENCIAS e WHERE e.EVI_ID = v.EVV_EVIDENCIA_ID)
        OR NOT EXISTS (SELECT 1 FROM RL_USUARIOS u WHERE u.USR_ID = v.EVV_USR_CREACION);
    exigir(v_count = 0, -20508, 'Existen vínculos de evidencia inválidos.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_EVIDENCIAS_VINCULOS v
     WHERE (v.EVV_TIPO_ENTIDAD = 'RIESGO' AND NOT EXISTS (SELECT 1 FROM RL_MR_RIESGOS r WHERE r.RIE_ID = v.EVV_ENTIDAD_ID))
        OR (v.EVV_TIPO_ENTIDAD = 'EVALUACION' AND NOT EXISTS (SELECT 1 FROM RL_MR_EVALUACIONES_RIESGO e WHERE e.EVA_ID = v.EVV_ENTIDAD_ID))
        OR (v.EVV_TIPO_ENTIDAD = 'CONTROL' AND NOT EXISTS (SELECT 1 FROM RL_MR_CONTROLES_RIESGO c WHERE c.CON_ID = v.EVV_ENTIDAD_ID))
        OR (v.EVV_TIPO_ENTIDAD = 'PLAN' AND NOT EXISTS (SELECT 1 FROM RL_MR_PLANES p WHERE p.PLA_ID = v.EVV_ENTIDAD_ID))
        OR (v.EVV_TIPO_ENTIDAD = 'ACTIVIDAD' AND NOT EXISTS (SELECT 1 FROM RL_MR_ACTIVIDADES a WHERE a.ACT_ID = v.EVV_ENTIDAD_ID))
        OR (v.EVV_TIPO_ENTIDAD = 'ALERTA' AND NOT EXISTS (SELECT 1 FROM RL_MR_SENALES_ALERTA s WHERE s.ALE_ID = v.EVV_ENTIDAD_ID))
        OR (v.EVV_TIPO_ENTIDAD = 'AUTOMONITOREO' AND NOT EXISTS (SELECT 1 FROM RL_MR_AUTOMONITOREO m WHERE m.MON_ID = v.EVV_ENTIDAD_ID));
    exigir(v_count = 0, -20509, 'Existen vínculos apuntando a entidades inexistentes.');

    SELECT COUNT(*) INTO v_count FROM (
        SELECT EVV_EVIDENCIA_ID, EVV_TIPO_ENTIDAD, EVV_ENTIDAD_ID
          FROM RL_MR_EVIDENCIAS_VINCULOS
         GROUP BY EVV_EVIDENCIA_ID, EVV_TIPO_ENTIDAD, EVV_ENTIDAD_ID
        HAVING COUNT(*) > 1
    );
    exigir(v_count = 0, -20510, 'Existen vínculos de evidencia duplicados.');

    DBMS_OUTPUT.PUT_LINE('VALIDACION FASE 11 BLOQUE 4: CORRECTA');
END;
/
