-- ============================================================
-- FASE 11 - BLOQUE 5
-- Alertas, automonitoreo y reportería - validación de solo lectura
-- ============================================================
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === CONTEOS BLOQUE 5 ===
SELECT 'RL_MR_SENALES_ALERTA' OBJETO, COUNT(*) TOTAL FROM RL_MR_SENALES_ALERTA
UNION ALL SELECT 'RL_MR_AUTOMONITOREO', COUNT(*) FROM RL_MR_AUTOMONITOREO
UNION ALL SELECT 'RL_MR_PROYECCIONES_EVALUACION', COUNT(*) FROM RL_MR_PROYECCIONES_EVALUACION;

PROMPT === ALERTAS POR ESTADO ===
SELECT ALE_ESTADO, COUNT(*) TOTAL FROM RL_MR_SENALES_ALERTA GROUP BY ALE_ESTADO ORDER BY ALE_ESTADO;

PROMPT === AUTOMONITOREO RECIENTE ===
SELECT MON_ID, MON_EVALUACION_ID, MON_ESTADO_RIESGO, MON_ESTADO_CONTR, MON_USR_ID, MON_FECHA
  FROM RL_MR_AUTOMONITOREO
 ORDER BY MON_FECHA DESC, MON_ID DESC;

DECLARE
    v_count NUMBER;
    PROCEDURE exigir(p_cond BOOLEAN, p_code NUMBER, p_message VARCHAR2) IS
    BEGIN
        IF NOT p_cond THEN RAISE_APPLICATION_ERROR(p_code, p_message); END IF;
    END;
BEGIN
    exigir(UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA')) = 'RIESGO_LAVADO', -21601,
           'CURRENT_SCHEMA debe ser RIESGO_LAVADO.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_SENALES_ALERTA a
     WHERE a.ALE_ESTADO NOT IN ('ACTIVO','INACTIVO')
        OR NOT EXISTS (SELECT 1 FROM RL_MR_EVALUACIONES_RIESGO e WHERE e.EVA_ID = a.ALE_EVALUACION_ID);
    exigir(v_count = 0, -21602, 'Existen alertas inválidas o huérfanas.');

    SELECT COUNT(*) INTO v_count FROM (
        SELECT ALE_EVALUACION_ID, ALE_CODIGO
          FROM RL_MR_SENALES_ALERTA
         GROUP BY ALE_EVALUACION_ID, ALE_CODIGO
        HAVING COUNT(*) > 1
    );
    exigir(v_count = 0, -21603, 'Existen códigos de alerta duplicados dentro de una evaluación.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_SENALES_ALERTA
     WHERE ALE_ESTADO = 'ACTIVO' AND ALE_FECHA_DISPARO IS NULL;
    exigir(v_count = 0, -21604, 'Existen alertas activas sin fecha de disparo.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_AUTOMONITOREO m
     WHERE NOT EXISTS (SELECT 1 FROM RL_MR_EVALUACIONES_RIESGO e WHERE e.EVA_ID = m.MON_EVALUACION_ID)
        OR NOT EXISTS (SELECT 1 FROM RL_USUARIOS u WHERE u.USR_ID = m.MON_USR_ID)
        OR TRIM(m.MON_ESTADO_RIESGO) IS NULL
        OR TRIM(m.MON_ESTADO_CONTR) IS NULL
        OR TRIM(m.MON_RESULTADO) IS NULL;
    exigir(v_count = 0, -21605, 'Existen registros de automonitoreo inválidos.');

    SELECT COUNT(*) INTO v_count
      FROM RL_MR_PROYECCIONES_EVALUACION p
     WHERE TRIM(p.PROY_CODIGO_RIESGO) IS NULL
        OR TRIM(p.PROY_AREA_PRINCIPAL) IS NULL
        OR TRIM(p.PROY_DUENO_RIESGO) IS NULL
        OR TRIM(p.PROY_NIVEL_INHERENTE) IS NULL
        OR TRIM(p.PROY_NIVEL_RESIDUAL) IS NULL
        OR TRIM(p.PROY_RESPUESTA_RIESGO) IS NULL
        OR TRIM(p.PROY_ESTADO_EVALUACION) IS NULL;
    exigir(v_count = 0, -21606, 'Existen proyecciones incompletas para reportería.');

    SELECT COUNT(*) INTO v_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME IN ('RL_MR_SENALES_ALERTA','RL_MR_AUTOMONITOREO','RL_MR_PROYECCIONES_EVALUACION')
       AND STATUS <> 'VALID';
    exigir(v_count = 0, -21607, 'Existen objetos de Bloque 5 inválidos.');

    DBMS_OUTPUT.PUT_LINE('VALIDACION FASE 11 BLOQUE 5: CORRECTA');
END;
/
