<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RL.API</RootNamespace>
    <AssemblyName>RL.API</AssemblyName>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <!-- Oracle -->
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.4.0" />

    <!-- JWT -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />

    <!-- Password Hashing -->
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />

    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />

    <!-- Serialización -->
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.9" />

    <!-- Logs -->
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />

    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.9" />
  </ItemGroup>

</Project>
