-- DB-01 - Diagnostico agregado de RL_AUDITORIA (Oracle 11g)
-- SOLO LECTURA. No muestra CLOB, correo, IP ni datos funcionales de detalle.
-- Verificar que CURRENT_SCHEMA sea RIESGO_LAVADO antes de interpretar resultados.

SET PAGESIZE 500
SET LINESIZE 220
SET FEEDBACK ON
SET VERIFY OFF

PROMPT === DB-01 / IDENTIDAD DE ESQUEMA ===
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA FROM DUAL;

PROMPT === DB-01 / VOLUMEN TOTAL Y RANGO TEMPORAL ===
SELECT COUNT(*) AS TOTAL_REGISTROS,
       MIN(AUD_FECHA) AS FECHA_MAS_ANTIGUA,
       MAX(AUD_FECHA) AS FECHA_MAS_RECIENTE
  FROM RL_AUDITORIA;

PROMPT === DB-01 / CRECIMIENTO MENSUAL ===
SELECT TRUNC(AUD_FECHA, 'MM') AS MES,
       COUNT(*) AS TOTAL_REGISTROS
  FROM RL_AUDITORIA
 GROUP BY TRUNC(AUD_FECHA, 'MM')
 ORDER BY MES;

PROMPT === DB-01 / DISTRIBUCION POR ACCION ===
SELECT AUD_ACCION,
       COUNT(*) AS TOTAL_REGISTROS
  FROM RL_AUDITORIA
 GROUP BY AUD_ACCION
 ORDER BY TOTAL_REGISTROS DESC, AUD_ACCION;

PROMPT === DB-01 / DISTRIBUCION POR MODULO ===
SELECT NVL(AUD_MODULO, '(SIN_MODULO)') AS MODULO,
       COUNT(*) AS TOTAL_REGISTROS
  FROM RL_AUDITORIA
 GROUP BY NVL(AUD_MODULO, '(SIN_MODULO)')
 ORDER BY TOTAL_REGISTROS DESC, MODULO;

PROMPT === DB-01 / TOP 20 TABLAS AUDITADAS POR VOLUMEN ===
SELECT AUD_TABLA, TOTAL_REGISTROS
  FROM (
        SELECT AUD_TABLA,
               COUNT(*) AS TOTAL_REGISTROS
          FROM RL_AUDITORIA
         GROUP BY AUD_TABLA
         ORDER BY COUNT(*) DESC, AUD_TABLA
       )
 WHERE ROWNUM <= 20;

PROMPT === DB-01 / HUELLA LOGICA APROXIMADA DE CLOB ===
SELECT SUM(NVL(DBMS_LOB.GETLENGTH(AUD_DATOS_ANT), 0)) AS CARACTERES_DATOS_ANT,
       SUM(NVL(DBMS_LOB.GETLENGTH(AUD_DATOS_NVO), 0)) AS CARACTERES_DATOS_NVO
  FROM RL_AUDITORIA;

PROMPT === DB-01 / FIN DE DIAGNOSTICO SOLO LECTURA ===
