[CmdletBinding()]
param(
    [string]$ConfigPath = "backend/RL.API/appsettings.json",
    [string]$SqlPlusPath = "C:\app\nahomi.martinez\product\11.2.0\client_1\sqlplus.exe"
)

# This tool intentionally submits SELECT statements only. It never invokes
# EXPLAIN PLAN because that can persist rows in PLAN_TABLE.
$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $ConfigPath)) {
    throw "Oracle configuration was not found at the supplied ConfigPath."
}
if (-not (Test-Path -LiteralPath $SqlPlusPath)) {
    throw "SQL*Plus was not found at the supplied SqlPlusPath."
}

$config = Get-Content -Raw -LiteralPath $ConfigPath | ConvertFrom-Json
$connectionText = [string]$config.ConnectionStrings.OracleDB
$login = [regex]::Match($connectionText, 'User Id=([^;]+)').Groups[1].Value
$secret = [regex]::Match($connectionText, 'Password=([^;]+)').Groups[1].Value
$source = ($connectionText -replace '^.*?Data Source=', '') -replace ';User Id=.*$', ''

if ([string]::IsNullOrWhiteSpace($login) -or [string]::IsNullOrWhiteSpace($secret) -or [string]::IsNullOrWhiteSpace($source)) {
    throw "The ignored local Oracle configuration is missing a required connection component."
}

$sql = @"
set echo off
set feedback on
set heading on
set pagesize 500
set linesize 320
set long 250000
set longchunksize 250000
set trimspool on
set verify off
connect $login/$secret@$source

prompt === CONNECTION_IDENTITY ===
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME
FROM DUAL;

prompt === EFFECTIVE_SYSTEM_PRIVILEGES ===
SELECT PRIVILEGE
FROM SESSION_PRIVS
WHERE PRIVILEGE IN ('CREATE INDEX', 'CREATE ANY INDEX', 'ANALYZE ANY', 'ANALYZE ANY DICTIONARY')
ORDER BY PRIVILEGE;

prompt === DBMS_STATS_EXECUTE_GRANTS_VISIBLE ===
SELECT *
FROM USER_TAB_PRIVS_RECD
WHERE TABLE_NAME = 'DBMS_STATS'
  AND PRIVILEGE = 'EXECUTE';

prompt === REPORTE_COINCIDENCIAS_INDEXES ===
SELECT i.OWNER, i.INDEX_NAME, i.TABLE_NAME, i.UNIQUENESS, i.STATUS, i.INDEX_TYPE,
       c.COLUMN_POSITION, c.COLUMN_NAME, c.DESCEND
FROM ALL_INDEXES i
LEFT JOIN ALL_IND_COLUMNS c
  ON c.INDEX_OWNER = i.OWNER AND c.INDEX_NAME = i.INDEX_NAME AND c.TABLE_OWNER = i.TABLE_OWNER
WHERE i.TABLE_OWNER = 'DNP_IHSS' AND i.TABLE_NAME = 'REPORTE_COINCIDENCIAS'
ORDER BY i.INDEX_NAME, c.COLUMN_POSITION;

prompt === REPORTE_COINCIDENCIAS_INDEX_EXPRESSIONS ===
SELECT INDEX_OWNER, INDEX_NAME, TABLE_NAME, COLUMN_POSITION, COLUMN_EXPRESSION
FROM ALL_IND_EXPRESSIONS
WHERE TABLE_OWNER = 'DNP_IHSS' AND TABLE_NAME = 'REPORTE_COINCIDENCIAS'
ORDER BY INDEX_NAME, COLUMN_POSITION;

prompt === REPORTE_COINCIDENCIAS_CONSTRAINTS ===
SELECT c.OWNER, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS, cc.POSITION, cc.COLUMN_NAME
FROM ALL_CONSTRAINTS c
LEFT JOIN ALL_CONS_COLUMNS cc
  ON cc.OWNER = c.OWNER AND cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.TABLE_NAME = c.TABLE_NAME
WHERE c.OWNER = 'DNP_IHSS' AND c.TABLE_NAME = 'REPORTE_COINCIDENCIAS'
  AND c.CONSTRAINT_TYPE IN ('P', 'U')
ORDER BY c.CONSTRAINT_NAME, cc.POSITION;

prompt === RL_LISTA_POSITIVOS_INDEXES ===
SELECT i.OWNER, i.INDEX_NAME, i.TABLE_NAME, i.UNIQUENESS, i.STATUS, i.INDEX_TYPE,
       c.COLUMN_POSITION, c.COLUMN_NAME, c.DESCEND
FROM ALL_INDEXES i
LEFT JOIN ALL_IND_COLUMNS c
  ON c.INDEX_OWNER = i.OWNER AND c.INDEX_NAME = i.INDEX_NAME AND c.TABLE_OWNER = i.TABLE_OWNER
WHERE i.TABLE_OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND i.TABLE_NAME = 'RL_LISTA_POSITIVOS'
ORDER BY i.INDEX_NAME, c.COLUMN_POSITION;

prompt === RL_LISTA_POSITIVOS_CONSTRAINTS ===
SELECT c.OWNER, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS, cc.POSITION, cc.COLUMN_NAME
FROM ALL_CONSTRAINTS c
LEFT JOIN ALL_CONS_COLUMNS cc
  ON cc.OWNER = c.OWNER AND cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.TABLE_NAME = c.TABLE_NAME
WHERE c.OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND c.TABLE_NAME = 'RL_LISTA_POSITIVOS'
  AND c.CONSTRAINT_TYPE IN ('P', 'U')
ORDER BY c.CONSTRAINT_NAME, cc.POSITION;

prompt === NATURAL_AND_JURIDICA_BASE_INDEXES ===
SELECT i.OWNER, i.INDEX_NAME, i.TABLE_NAME, i.UNIQUENESS, i.STATUS, i.INDEX_TYPE,
       c.COLUMN_POSITION, c.COLUMN_NAME, c.DESCEND
FROM ALL_INDEXES i
LEFT JOIN ALL_IND_COLUMNS c
  ON c.INDEX_OWNER = i.OWNER AND c.INDEX_NAME = i.INDEX_NAME AND c.TABLE_OWNER = i.TABLE_OWNER
WHERE i.OWNER = 'DNP_IHSS'
  AND i.TABLE_NAME IN ('SOCIOS', 'REPRESENTANTES', 'DATOS_EMPRESA', 'PATRONOS', 'TIPO_LISTAS_CAUTELA')
ORDER BY i.TABLE_NAME, i.INDEX_NAME, c.COLUMN_POSITION;

prompt === NATURAL_AND_JURIDICA_BASE_CONSTRAINTS ===
SELECT c.OWNER, c.TABLE_NAME, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS, cc.POSITION, cc.COLUMN_NAME
FROM ALL_CONSTRAINTS c
LEFT JOIN ALL_CONS_COLUMNS cc
  ON cc.OWNER = c.OWNER AND cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME AND cc.TABLE_NAME = c.TABLE_NAME
WHERE c.OWNER = 'DNP_IHSS'
  AND c.TABLE_NAME IN ('SOCIOS', 'REPRESENTANTES', 'DATOS_EMPRESA', 'PATRONOS', 'TIPO_LISTAS_CAUTELA')
  AND c.CONSTRAINT_TYPE IN ('P', 'U')
ORDER BY c.TABLE_NAME, c.CONSTRAINT_NAME, cc.POSITION;

prompt === PATRONOS_INDEXES_VISIBLE ===
SELECT i.OWNER, i.INDEX_NAME, i.TABLE_NAME, i.UNIQUENESS, i.STATUS, i.INDEX_TYPE,
       c.COLUMN_POSITION, c.COLUMN_NAME, c.DESCEND
FROM ALL_INDEXES i
LEFT JOIN ALL_IND_COLUMNS c
  ON c.INDEX_OWNER = i.OWNER AND c.INDEX_NAME = i.INDEX_NAME AND c.TABLE_OWNER = i.TABLE_OWNER
WHERE i.OWNER = 'MMATAMOROS' AND i.TABLE_NAME = 'PATRONOS'
ORDER BY i.INDEX_NAME, c.COLUMN_POSITION;

prompt === VIEW_DEFINITIONS ===
SELECT VIEW_NAME, TEXT
FROM ALL_VIEWS
WHERE OWNER = 'DNP_IHSS'
  AND VIEW_NAME IN ('V_SOCIOS_REPRESENTANTES', 'V_SOCIOS', 'V_REPRESENTANTES', 'V_DATOS_EMPRESA', 'V_EMPLEADOS_IHSS_PLANILLAS')
ORDER BY VIEW_NAME;

prompt === BASE_OBJECT_SYNONYMS ===
SELECT OWNER, SYNONYM_NAME, TABLE_OWNER, TABLE_NAME, DB_LINK
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME IN ('PATRONOS', 'V_SOCIOS', 'V_REPRESENTANTES')
  AND OWNER IN ('DNP_IHSS', 'PUBLIC')
ORDER BY OWNER, SYNONYM_NAME;

prompt === TABLE_STATISTICS ===
SELECT OWNER, TABLE_NAME, NUM_ROWS, BLOCKS, SAMPLE_SIZE, LAST_ANALYZED
FROM ALL_TABLES
WHERE (OWNER = 'DNP_IHSS' AND TABLE_NAME IN ('REPORTE_COINCIDENCIAS', 'SOCIOS', 'REPRESENTANTES', 'DATOS_EMPRESA', 'PATRONOS'))
   OR (OWNER = 'MMATAMOROS' AND TABLE_NAME IN ('PATRONOS', 'PLANILLAS'))
   OR (OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME = 'RL_LISTA_POSITIVOS')
ORDER BY OWNER, TABLE_NAME;

prompt === CRITICAL_COLUMN_STATISTICS ===
SELECT OWNER, TABLE_NAME, COLUMN_NAME, NUM_DISTINCT, DENSITY, HISTOGRAM, SAMPLE_SIZE, LAST_ANALYZED
FROM ALL_TAB_COL_STATISTICS
WHERE (OWNER = 'DNP_IHSS' AND TABLE_NAME = 'REPORTE_COINCIDENCIAS'
       AND COLUMN_NAME IN ('TIPO_CALIFICACION_ID', 'DNI', 'NUMERO_PATRONO', 'LISTA_CONCIDENCIA', 'FECHA_CALIFICO'))
   OR (OWNER = 'DNP_IHSS' AND TABLE_NAME IN ('SOCIOS', 'REPRESENTANTES') AND COLUMN_NAME = 'NUMERO_IDENTIFICACION')
   OR (OWNER = 'DNP_IHSS' AND TABLE_NAME = 'DATOS_EMPRESA' AND COLUMN_NAME IN ('NUMERO_PATRONAL', 'TIPO_EMPRESA_ID'))
   OR (OWNER = 'MMATAMOROS' AND TABLE_NAME = 'PATRONOS' AND COLUMN_NAME IN ('NUMEPATRO', 'RTN'))
   OR (OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME = 'RL_LISTA_POSITIVOS'
       AND COLUMN_NAME IN ('LSP_NO_DOCUMENTO', 'LSP_ESTADO_REGISTRO', 'LSP_TIPO_POSITIVO_ID', 'LSP_FECHA_CREACION'))
ORDER BY OWNER, TABLE_NAME, COLUMN_NAME;

prompt === PRIVILEGED_DICTIONARY_LIMITATIONS ===
SELECT 'ALL_SEGMENTS and V$SQL are intentionally not queried by this read-only audit after the connected user returned ORA-00942 for both catalog views. A DBA session is required for segment estimates and DISPLAY_CURSOR.' AS LIMITATION
FROM DUAL;

prompt === PREEXISTING_OPTIMIZER_PLANS_READ_ONLY ===
SELECT STATEMENT_ID, TIMESTAMP, PLAN_ID, OPERATION, OPTIONS, OBJECT_OWNER, OBJECT_NAME, COST, CARDINALITY
FROM PLAN_TABLE
WHERE STATEMENT_ID IN ('MON_NATURAL', 'MON_JURIDICA', 'MON_EMPLEADO')
ORDER BY STATEMENT_ID, ID;

prompt === PLAN_NATURALES_PREEXISTING_READ_ONLY ===
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'MON_NATURAL', 'TYPICAL +PREDICATE'));

prompt === PLAN_JURIDICAS_PREEXISTING_READ_ONLY ===
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'MON_JURIDICA', 'TYPICAL +PREDICATE'));

prompt === PLAN_EMPLEADOS_PREEXISTING_READ_ONLY ===
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'MON_EMPLEADO', 'TYPICAL +PREDICATE'));

exit
"@

$temporarySql = [IO.Path]::GetTempFileName()
try {
    [IO.File]::WriteAllText($temporarySql, $sql, [Text.Encoding]::ASCII)
    & $SqlPlusPath -L /nolog "@$temporarySql" 2>&1
    if ($LASTEXITCODE -ne 0) { throw "SQLPLUS_EXIT_CODE=$LASTEXITCODE" }
}
finally {
    Remove-Item -LiteralPath $temporarySql -Force -ErrorAction SilentlyContinue
}
