[CmdletBinding()]
param(
    [string]$ConfigPath = "backend/RL.API/appsettings.json",
    [string]$SqlPlusPath = "C:\app\nahomi.martinez\product\11.2.0\client_1\sqlplus.exe"
)

$ErrorActionPreference = "Stop"
$config = Get-Content -Raw -LiteralPath $ConfigPath | ConvertFrom-Json
$connectionText = $config.ConnectionStrings.OracleDB
$login = [regex]::Match($connectionText, 'User Id=([^;]+)').Groups[1].Value
$secret = [regex]::Match($connectionText, 'Password=([^;]+)').Groups[1].Value
$source = ($connectionText -replace '^.*?Data Source=', '') -replace ';User Id=.*$', ''

$sql = @"
set echo off
set heading on
set pagesize 500
set linesize 240
set trimspool on
set feedback on
set long 200000
connect $login/$secret@$source

prompt === TABLE_STATS ===
select OWNER,TABLE_NAME,NUM_ROWS,LAST_ANALYZED,BLOCKS from ALL_TABLES where TABLE_NAME in ('PATRONOS','V_SOCIOS','V_REPRESENTANTES') order by OWNER,TABLE_NAME;
select OWNER,TABLE_NAME,NUM_ROWS,LAST_ANALYZED,BLOCKS from ALL_TABLES where OWNER='MMATAMOROS' and TABLE_NAME in ('PATRONOS','PLANILLAS') order by TABLE_NAME;
select OWNER,TABLE_NAME,NUM_ROWS,LAST_ANALYZED,BLOCKS
from ALL_TABLES
where (OWNER='DNP_IHSS' and TABLE_NAME in ('REPORTE_COINCIDENCIAS','SOCIOS','REPRESENTANTES','PATRONOS','EMPLEADOS_IHSS_PLANILLAS','DATOS_EMPRESA','TIPO_LISTAS_CAUTELA'))
   or (OWNER=USER and TABLE_NAME='RL_LISTA_POSITIVOS')
order by OWNER,TABLE_NAME;

prompt === INDEXES ===
select OWNER,INDEX_NAME,TABLE_NAME,UNIQUENESS,STATUS from ALL_INDEXES where OWNER='MMATAMOROS' and TABLE_NAME in ('PATRONOS','PLANILLAS') order by TABLE_NAME,INDEX_NAME;
select OWNER,INDEX_NAME,TABLE_NAME,UNIQUENESS,STATUS
from ALL_INDEXES
where (OWNER='DNP_IHSS' and TABLE_NAME in ('REPORTE_COINCIDENCIAS','SOCIOS','REPRESENTANTES','PATRONOS','EMPLEADOS_IHSS_PLANILLAS','DATOS_EMPRESA','TIPO_LISTAS_CAUTELA'))
   or (OWNER=USER and TABLE_NAME='RL_LISTA_POSITIVOS')
order by OWNER,TABLE_NAME,INDEX_NAME;

prompt === INDEX_COLUMNS ===
select INDEX_OWNER,INDEX_NAME,TABLE_NAME,COLUMN_POSITION,COLUMN_NAME from ALL_IND_COLUMNS where TABLE_OWNER='MMATAMOROS' and TABLE_NAME in ('PATRONOS','PLANILLAS') order by TABLE_NAME,INDEX_NAME,COLUMN_POSITION;
select INDEX_OWNER,INDEX_NAME,TABLE_NAME,COLUMN_POSITION,COLUMN_NAME
from ALL_IND_COLUMNS
where (TABLE_OWNER='DNP_IHSS' and TABLE_NAME in ('REPORTE_COINCIDENCIAS','SOCIOS','REPRESENTANTES','PATRONOS','EMPLEADOS_IHSS_PLANILLAS','DATOS_EMPRESA','TIPO_LISTAS_CAUTELA'))
   or (TABLE_OWNER=USER and TABLE_NAME='RL_LISTA_POSITIVOS')
order by TABLE_OWNER,TABLE_NAME,INDEX_NAME,COLUMN_POSITION;

prompt === INDEX_EXPRESSIONS ===
select INDEX_OWNER,INDEX_NAME,TABLE_NAME,COLUMN_POSITION,COLUMN_EXPRESSION
from ALL_IND_EXPRESSIONS
where (INDEX_OWNER='MMATAMOROS' and TABLE_NAME in ('PATRONOS','PLANILLAS'))
   or (INDEX_OWNER='DNP_IHSS' and TABLE_NAME in ('DATOS_EMPRESA','SOCIOS','REPRESENTANTES','REPORTE_COINCIDENCIAS'))
order by INDEX_OWNER,TABLE_NAME,INDEX_NAME,COLUMN_POSITION;

prompt === COLUMN_STATS ===
select OWNER,TABLE_NAME,COLUMN_NAME,NUM_DISTINCT,DENSITY,LAST_ANALYZED from ALL_TAB_COL_STATISTICS where OWNER='MMATAMOROS' and TABLE_NAME in ('PATRONOS','PLANILLAS') and COLUMN_NAME in ('NUMEPATRO','RTN','IDENTIDAD','PERIODO') order by TABLE_NAME,COLUMN_NAME;
select OWNER,TABLE_NAME,COLUMN_NAME,NUM_DISTINCT,DENSITY,LAST_ANALYZED
from ALL_TAB_COL_STATISTICS
where ((OWNER='DNP_IHSS' and TABLE_NAME in ('REPORTE_COINCIDENCIAS','SOCIOS','REPRESENTANTES','PATRONOS','EMPLEADOS_IHSS_PLANILLAS','DATOS_EMPRESA','TIPO_LISTAS_CAUTELA'))
    or (OWNER=USER and TABLE_NAME='RL_LISTA_POSITIVOS'))
  and COLUMN_NAME in ('DNI','NUMERO_PATRONO','TIPO_CALIFICACION_ID','FECHA_CALIFICO','LISTA_CONCIDENCIA','NUMERO_IDENTIFICACION','IDENTIDAD','NUMEPATRO','RTN','NOMBRE','LSP_NO_DOCUMENTO','LSP_ESTADO_REGISTRO','LSP_TIPO_POSITIVO_ID')
order by OWNER,TABLE_NAME,COLUMN_NAME;

prompt === CONSTRAINTS ===
select OWNER,TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE,STATUS
from ALL_CONSTRAINTS
where (OWNER='DNP_IHSS' and TABLE_NAME in ('REPORTE_COINCIDENCIAS','SOCIOS','REPRESENTANTES','PATRONOS','EMPLEADOS_IHSS_PLANILLAS','DATOS_EMPRESA','TIPO_LISTAS_CAUTELA'))
   or (OWNER=USER and TABLE_NAME='RL_LISTA_POSITIVOS')
order by OWNER,TABLE_NAME,CONSTRAINT_NAME;

prompt === VIEW_VISIBILITY ===
select OWNER,VIEW_NAME from ALL_VIEWS
where OWNER='DNP_IHSS'
  and VIEW_NAME in ('V_SOCIOS_REPRESENTANTES','V_DATOS_EMPRESA','V_EMPLEADOS_IHSS_PLANILLAS');

prompt === VIEW_DEFINITIONS ===
select VIEW_NAME,TEXT from ALL_VIEWS
where OWNER='DNP_IHSS'
  and VIEW_NAME in ('V_SOCIOS_REPRESENTANTES','V_DATOS_EMPRESA','V_EMPLEADOS_IHSS_PLANILLAS');

prompt === PLAN_NATURALES ===
explain plan set statement_id='MON_NATURAL' for
select * from (
  select q.*, ROWNUM as NUMERO_FILA
  from (
    with REPORTE_AGG as (
      select DNI, LISTA_CONCIDENCIA, count(*) TOTAL_REPETIDOS,
             max(FECHA_ENCONTRO) FECHA_ENCONTRO, max(FECHA_CALIFICO) FECHA_CALIFICO
      from DNP_IHSS.REPORTE_COINCIDENCIAS
      where TIPO_CALIFICACION_ID=1 and FECHA_CALIFICO is not null
      group by DNI, LISTA_CONCIDENCIA
    ), REPORTE_IDS as (
      select distinct DNI from REPORTE_AGG
    ), PERSONA_FUENTE as (
      select D.NUMERO_IDENTIFICACION, trim(D.NOMBRES_PERSONA) NOMBRES_PERSONA
      from DNP_IHSS.V_SOCIOS_REPRESENTANTES D
      inner join REPORTE_IDS I on I.DNI=D.NUMERO_IDENTIFICACION
    ), PERSONA_FUENTE_DISTINCTA as (
      select NUMERO_IDENTIFICACION,NOMBRES_PERSONA
      from PERSONA_FUENTE
      group by NUMERO_IDENTIFICACION,NOMBRES_PERSONA
    ), PERSONAS as (
      select NUMERO_IDENTIFICACION,
             trim(regexp_replace(NOMBRES_PERSONA,'[[:space:]]+',' ')) NOMBRE
      from PERSONA_FUENTE_DISTINCTA
      group by NUMERO_IDENTIFICACION,
               trim(regexp_replace(NOMBRES_PERSONA,'[[:space:]]+',' '))
    )
    select R.DNI, D.NOMBRE, R.LISTA_CONCIDENCIA, R.TOTAL_REPETIDOS,
           R.FECHA_ENCONTRO, R.FECHA_CALIFICO
    from REPORTE_AGG R
    inner join PERSONAS D on D.NUMERO_IDENTIFICACION=R.DNI
    order by R.TOTAL_REPETIDOS desc, D.NOMBRE asc, R.DNI asc
  ) q
  where ROWNUM <= 10
)
where NUMERO_FILA > 0;
select plan_table_output from table(DBMS_XPLAN.DISPLAY('PLAN_TABLE','MON_NATURAL','TYPICAL'));

prompt === PLAN_JURIDICAS ===
explain plan set statement_id='MON_JURIDICA' for
select * from (
  select q.*, ROWNUM as NUMERO_FILA
  from (
    select D.RTN,D.NOMBRE,D.NUMEPATRO,R.LISTA_CONCIDENCIA,R.FECHA_ENCONTRO,R.FECHA_CALIFICO
    from DNP_IHSS.V_DATOS_EMPRESA D
    inner join DNP_IHSS.REPORTE_COINCIDENCIAS R on D.NUMEPATRO=R.NUMERO_PATRONO
    where D.TIPO_EMPRESA_ID=1 and R.TIPO_CALIFICACION_ID=1
    order by D.NOMBRE asc,D.NUMEPATRO asc
  ) q
  where ROWNUM <= 10
)
where NUMERO_FILA > 0;
select plan_table_output from table(DBMS_XPLAN.DISPLAY('PLAN_TABLE','MON_JURIDICA','TYPICAL'));

prompt === PLAN_EMPLEADOS ===
explain plan set statement_id='MON_EMPLEADO' for
select * from (
  select q.*, ROWNUM as NUMERO_FILA
  from (
    select D.IDENTIDAD,trim(regexp_replace(D.NOMBRE_EMPLEADO,'[[:space:]]+',' ')) NOMBRE,
           R.LISTA_CONCIDENCIA,count(*) TOTAL_REPETIDOS,
           max(R.FECHA_ENCONTRO) FECHA_ENCONTRO,max(R.FECHA_CALIFICO) FECHA_CALIFICO
    from DNP_IHSS.V_EMPLEADOS_IHSS_PLANILLAS D
    join DNP_IHSS.REPORTE_COINCIDENCIAS R on D.IDENTIDAD=R.DNI and R.TIPO_CALIFICACION_ID=1
    where D.PERIODO=TRUNC(ADD_MONTHS(SYSDATE,-1),'MM')
    group by D.IDENTIDAD,trim(regexp_replace(D.NOMBRE_EMPLEADO,'[[:space:]]+',' ')),R.LISTA_CONCIDENCIA
    order by TOTAL_REPETIDOS desc,NOMBRE asc,D.IDENTIDAD asc
  ) q
  where ROWNUM <= 10
)
where NUMERO_FILA > 0;
select plan_table_output from table(DBMS_XPLAN.DISPLAY('PLAN_TABLE','MON_EMPLEADO','TYPICAL'));

exit
"@

$temporarySql = [IO.Path]::GetTempFileName()
try {
    [IO.File]::WriteAllText($temporarySql, $sql, [Text.Encoding]::ASCII)
    & $SqlPlusPath -L /nolog @$temporarySql 2>&1
    if ($LASTEXITCODE -ne 0) { throw "SQLPLUS_EXIT_CODE=$LASTEXITCODE" }
}
finally {
    Remove-Item -LiteralPath $temporarySql -Force -ErrorAction SilentlyContinue
}
