-- ============================================================
-- MODULO MATRICES DE RIESGOS - TRANSICION AL MODELO REDUCIDO
-- Script: 06_reconstruir_modelo_17_tablas.sql
-- Uso: SOLO manual, con respaldo validado y autorizacion expresa.
-- No esta incluido en 00_APLICAR_MODULO_MATRICES_RIESGOS.sql.
-- ATENCION: elimina objetos RL_MR_* de prueba y los reconstruye.
-- ============================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DEFINE autorizacion = '&1'

DECLARE
  v_auth VARCHAR2(50) := q'[&autorizacion]';
  v_schema VARCHAR2(128);
  v_usuarios NUMBER;
BEGIN
  SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') INTO v_schema FROM DUAL;
  IF UPPER(v_schema) <> 'RIESGO_LAVADO' THEN
    RAISE_APPLICATION_ERROR(-20201, 'EJECUCION BLOQUEADA: esquema distinto de RIESGO_LAVADO.');
  END IF;
  IF UPPER(v_auth) <> 'EJECUTAR' THEN
    RAISE_APPLICATION_ERROR(-20202, 'EJECUCION BLOQUEADA: invoque el script con el parametro EJECUTAR.');
  END IF;
  SELECT COUNT(*) INTO v_usuarios FROM USER_TABLES WHERE TABLE_NAME = 'RL_USUARIOS';
  IF v_usuarios <> 1 THEN
    RAISE_APPLICATION_ERROR(-20203, 'EJECUCION BLOQUEADA: no existe RL_USUARIOS.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('Prevalidacion aprobada. El retiro es irreversible sin respaldo.');
END;
/

DECLARE
  PROCEDURE drop_table_if_exists(p_name VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_name || ' CASCADE CONSTRAINTS PURGE';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE <> -942 THEN RAISE; END IF;
  END;
  PROCEDURE drop_sequence_if_exists(p_name VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || p_name;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE <> -2289 THEN RAISE; END IF;
  END;
BEGIN
  -- Se eliminan primero las dependencias y luego las entidades raiz.
  FOR t IN (
    SELECT column_value nombre FROM TABLE(sys.odcivarchar2list(
      'RL_MR_EVIDENCIAS_VINCULOS','RL_MR_EVI_APROBACION','RL_MR_EVI_REVISION','RL_MR_EVI_AUTOMONITOREO',
      'RL_MR_EVI_ALERTA','RL_MR_EVI_ACTIVIDAD','RL_MR_EVI_PLAN','RL_MR_EVI_CONTROL',
      'RL_MR_EVI_EVALUACION','RL_MR_EVI_RIESGO','RL_MR_DETALLES_IMPORTACION',
      'RL_MR_LOTES_IMPORTACION','RL_MR_TRAZAS_CALCULO','RL_MR_AUDITORIA',
      'RL_MR_PERMISOS_FORMULARIO','RL_MR_APROBACIONES_FORMULARIO','RL_MR_CAMPOS_FORMULARIO',
      'RL_MR_RELACIONES_RIESGO','RL_MR_REVISIONES_EVALUACION','RL_MR_PROYECCIONES_EVALUACION',
      'RL_MR_EVALUACIONES_CONTROL','RL_MR_CONTROLES_RIESGO','RL_MR_ACTIVIDADES','RL_MR_PLANES',
      'RL_MR_SENALES_ALERTA','RL_MR_AUTOMONITOREO','RL_MR_EVIDENCIAS',
      'RL_MR_FLUJOS_EVALUACION','RL_MR_EVALUACIONES_RIESGO','RL_MR_REGLAS_CALCULO',
      'RL_MR_ELEMENTOS_CATALOGO','RL_MR_CATALOGOS','RL_MR_RIESGOS',
      'RL_MR_VERSIONES_FORMULARIO','RL_MR_FAMILIAS_FORMULARIO'))
  ) LOOP
    drop_table_if_exists(t.nombre);
  END LOOP;
  FOR s IN (SELECT sequence_name nombre FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'SEQ_RL_MR_%') LOOP
    drop_sequence_if_exists(s.nombre);
  END LOOP;
END;
/

-- Secuencias del modelo reducido.
CREATE SEQUENCE SEQ_RL_MR_FAMILIAS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_VERSIONES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_CATALOGOS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_ELEMENTOS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_REGLAS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_RIESGOS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_EVALUACIONES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_PROYECCIONES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_FLUJOS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_CONTROLES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_EVAL_CONTROLES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_PLANES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_ACTIVIDADES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_EVIDENCIAS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_EVI_VINCULOS START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_SENALES START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_RL_MR_AUTOMONITOREO START WITH 1 NOCACHE;

CREATE TABLE RL_MR_FAMILIAS_FORMULARIO (
  FAM_ID NUMBER(15) NOT NULL, FAM_CODIGO VARCHAR2(50) NOT NULL,
  FAM_NOMBRE VARCHAR2(150) NOT NULL, FAM_DESCRIPCION VARCHAR2(500),
  FAM_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL, FAM_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RL_MR_FAMILIAS PRIMARY KEY (FAM_ID),
  CONSTRAINT UQ_RL_MR_FAM_COD UNIQUE (FAM_CODIGO),
  CONSTRAINT CK_RL_MR_FAM_ACT CHECK (FAM_ACTIVO IN (0,1)));

CREATE TABLE RL_MR_VERSIONES_FORMULARIO (
  VER_ID NUMBER(15) NOT NULL, VER_FAMILIA_ID NUMBER(15) NOT NULL,
  VER_CODIGO VARCHAR2(30) NOT NULL, VER_VERSION NUMBER(5) NOT NULL,
  VER_JSON CLOB NOT NULL, VER_HASH VARCHAR2(64) NOT NULL,
  VER_ESTADO VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL, VER_VIGENTE NUMBER(1) DEFAULT 0 NOT NULL,
  VER_FECHA_INICIO DATE, VER_FECHA_FIN DATE, VER_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  VER_USR_CREACION NUMBER(10) NOT NULL,
  CONSTRAINT PK_RL_MR_VERSIONES PRIMARY KEY (VER_ID),
  CONSTRAINT FK_RL_MR_VER_FAM FOREIGN KEY (VER_FAMILIA_ID) REFERENCES RL_MR_FAMILIAS_FORMULARIO(FAM_ID),
  CONSTRAINT FK_RL_MR_VER_USR FOREIGN KEY (VER_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT UQ_RL_MR_VER_FAM_VER UNIQUE (VER_FAMILIA_ID, VER_VERSION),
  CONSTRAINT CK_RL_MR_VER_EST CHECK (VER_ESTADO IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')),
  CONSTRAINT CK_RL_MR_VER_VIG CHECK (VER_VIGENTE IN (0,1)));

CREATE TABLE RL_MR_CATALOGOS (
  CAT_ID NUMBER(15) NOT NULL, CAT_CODIGO VARCHAR2(50) NOT NULL, CAT_NOMBRE VARCHAR2(150) NOT NULL,
  CAT_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RL_MR_CATALOGOS PRIMARY KEY (CAT_ID),
  CONSTRAINT UQ_RL_MR_CAT_COD UNIQUE (CAT_CODIGO), CONSTRAINT CK_RL_MR_CAT_ACT CHECK (CAT_ACTIVO IN (0,1)));
CREATE TABLE RL_MR_ELEMENTOS_CATALOGO (
  ELE_ID NUMBER(15) NOT NULL, ELE_CATALOGO_ID NUMBER(15) NOT NULL, ELE_CODIGO VARCHAR2(50) NOT NULL,
  ELE_VALOR VARCHAR2(255) NOT NULL, ELE_ORDEN NUMBER(5) DEFAULT 0 NOT NULL, ELE_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RL_MR_ELEMENTOS PRIMARY KEY (ELE_ID),
  CONSTRAINT FK_RL_MR_ELE_CAT FOREIGN KEY (ELE_CATALOGO_ID) REFERENCES RL_MR_CATALOGOS(CAT_ID),
  CONSTRAINT UQ_RL_MR_ELE_COD UNIQUE (ELE_CATALOGO_ID,ELE_CODIGO), CONSTRAINT CK_RL_MR_ELE_ACT CHECK (ELE_ACTIVO IN (0,1)));
CREATE TABLE RL_MR_REGLAS_CALCULO (
  REG_ID NUMBER(15) NOT NULL, REG_CODIGO VARCHAR2(50) NOT NULL, REG_VERSION VARCHAR2(20) NOT NULL,
  REG_NOMBRE VARCHAR2(150) NOT NULL, REG_ALGORITMO_ID VARCHAR2(100) NOT NULL, REG_ACTIVA NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RL_MR_REGLAS PRIMARY KEY (REG_ID), CONSTRAINT UQ_RL_MR_REG_COD UNIQUE (REG_CODIGO,REG_VERSION),
  CONSTRAINT CK_RL_MR_REG_ACT CHECK (REG_ACTIVA IN (0,1)));

CREATE TABLE RL_MR_RIESGOS (
  RIE_ID NUMBER(15) NOT NULL, RIE_CODIGO VARCHAR2(30) NOT NULL, RIE_NOMBRE VARCHAR2(250) NOT NULL,
  RIE_DESCRIPCION VARCHAR2(2000), RIE_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  RIE_USR_CREACION NUMBER(10) NOT NULL, RIE_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RL_MR_RIESGOS PRIMARY KEY (RIE_ID), CONSTRAINT UQ_RL_MR_RIE_COD UNIQUE (RIE_CODIGO),
  CONSTRAINT FK_RL_MR_RIE_USR FOREIGN KEY (RIE_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT CK_RL_MR_RIE_ACT CHECK (RIE_ACTIVO IN (0,1)));
CREATE TABLE RL_MR_EVALUACIONES_RIESGO (
  EVA_ID NUMBER(15) NOT NULL, EVA_RIESGO_ID NUMBER(15) NOT NULL, EVA_VERSION_ID NUMBER(15) NOT NULL,
  EVA_DATOS_JSON CLOB NOT NULL, EVA_CALCULOS_JSON CLOB NOT NULL, EVA_FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
  EVA_USR_REGISTRO NUMBER(10) NOT NULL, EVA_VERSION_ROW NUMBER(10) DEFAULT 1 NOT NULL, EVA_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RL_MR_EVALUACIONES PRIMARY KEY (EVA_ID),
  CONSTRAINT FK_RL_MR_EVA_RIE FOREIGN KEY (EVA_RIESGO_ID) REFERENCES RL_MR_RIESGOS(RIE_ID),
  CONSTRAINT FK_RL_MR_EVA_VER FOREIGN KEY (EVA_VERSION_ID) REFERENCES RL_MR_VERSIONES_FORMULARIO(VER_ID),
  CONSTRAINT FK_RL_MR_EVA_USR FOREIGN KEY (EVA_USR_REGISTRO) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT CK_RL_MR_EVA_ACT CHECK (EVA_ACTIVO IN (0,1)));
CREATE TABLE RL_MR_PROYECCIONES_EVALUACION (
  PROY_ID NUMBER(15) NOT NULL, PROY_EVALUACION_ID NUMBER(15) NOT NULL, PROY_CODIGO_RIESGO VARCHAR2(30) NOT NULL,
  PROY_AREA_PRINCIPAL VARCHAR2(100) NOT NULL, PROY_VRI NUMBER(8,2) NOT NULL, PROY_VRR NUMBER(8,2) NOT NULL,
  PROY_NIVEL_INHERENTE VARCHAR2(20) NOT NULL, PROY_NIVEL_RESIDUAL VARCHAR2(20) NOT NULL,
  PROY_RESPUESTA_RIESGO VARCHAR2(50) NOT NULL, PROY_ESTADO_EVALUACION VARCHAR2(30) NOT NULL,
  PROY_DUENO_RIESGO VARCHAR2(150) NOT NULL, PROY_FECHA_EVAL DATE NOT NULL,
  CONSTRAINT PK_RL_MR_PROYECCIONES PRIMARY KEY (PROY_ID),
  CONSTRAINT FK_RL_MR_PROY_EVA FOREIGN KEY (PROY_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
  CONSTRAINT UQ_RL_MR_PROY_EVA UNIQUE (PROY_EVALUACION_ID));
CREATE TABLE RL_MR_FLUJOS_EVALUACION (
  FLU_ID NUMBER(15) NOT NULL, FLU_EVALUACION_ID NUMBER(15) NOT NULL, FLU_ESTADO VARCHAR2(30) NOT NULL,
  FLU_MOTIVO VARCHAR2(1000), FLU_USR_ID NUMBER(10) NOT NULL, FLU_FECHA DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RL_MR_FLUJOS PRIMARY KEY (FLU_ID),
  CONSTRAINT FK_RL_MR_FLU_EVA FOREIGN KEY (FLU_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
  CONSTRAINT FK_RL_MR_FLU_USR FOREIGN KEY (FLU_USR_ID) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT CK_RL_MR_FLU_EST CHECK (FLU_ESTADO IN ('BORRADOR','EN_REVISION','OBSERVADA','APROBADA','RECHAZADA','CERRADA')));

CREATE TABLE RL_MR_CONTROLES_RIESGO (
  CON_ID NUMBER(15) NOT NULL, CON_EVALUACION_ID NUMBER(15) NOT NULL, CON_TIPO VARCHAR2(30) NOT NULL,
  CON_DESCRIPCION VARCHAR2(500) NOT NULL, CON_AUTOMATIZACION VARCHAR2(30) NOT NULL, CON_ESTADO VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_RL_MR_CONTROLES PRIMARY KEY (CON_ID),
  CONSTRAINT FK_RL_MR_CON_EVA FOREIGN KEY (CON_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
  CONSTRAINT CK_RL_MR_CON_TIPO CHECK (CON_TIPO IN ('PREVENTIVO','DETECTIVO','CORRECTIVO')),
  CONSTRAINT CK_RL_MR_CON_AUTO CHECK (CON_AUTOMATIZACION IN ('MANUAL','SEMIAUTOMATICO','AUTOMATICO')));
CREATE TABLE RL_MR_EVALUACIONES_CONTROL (
  ECO_ID NUMBER(15) NOT NULL, ECO_CONTROL_ID NUMBER(15) NOT NULL, ECO_EFECTIVIDAD NUMBER(5,2) NOT NULL,
  ECO_COMENTARIO VARCHAR2(500), CONSTRAINT PK_RL_MR_EVAL_CONTROLES PRIMARY KEY (ECO_ID),
  CONSTRAINT FK_RL_MR_ECO_CON FOREIGN KEY (ECO_CONTROL_ID) REFERENCES RL_MR_CONTROLES_RIESGO(CON_ID),
  CONSTRAINT CK_RL_MR_ECO_EF CHECK (ECO_EFECTIVIDAD BETWEEN 0 AND 100));
CREATE TABLE RL_MR_PLANES (
  PLA_ID NUMBER(15) NOT NULL, PLA_EVALUACION_ID NUMBER(15) NOT NULL, PLA_DESCRIPCION VARCHAR2(500) NOT NULL,
  PLA_AVANCE NUMBER(5,2) DEFAULT 0 NOT NULL, PLA_PRESUPUESTO NUMBER(15,2) DEFAULT 0 NOT NULL,
  PLA_FECHA_INICIO DATE NOT NULL, PLA_FECHA_FIN DATE NOT NULL, PLA_ESTADO VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_RL_MR_PLANES PRIMARY KEY (PLA_ID),
  CONSTRAINT FK_RL_MR_PLA_EVA FOREIGN KEY (PLA_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
  CONSTRAINT CK_RL_MR_PLA_AV CHECK (PLA_AVANCE BETWEEN 0 AND 100), CONSTRAINT CK_RL_MR_PLA_PR CHECK (PLA_PRESUPUESTO >= 0));
CREATE TABLE RL_MR_ACTIVIDADES (
  ACT_ID NUMBER(15) NOT NULL, ACT_PLAN_ID NUMBER(15) NOT NULL, ACT_DESCRIPCION VARCHAR2(500) NOT NULL,
  ACT_RESPONSABLE VARCHAR2(150) NOT NULL, ACT_AVANCE NUMBER(5,2) DEFAULT 0 NOT NULL,
  ACT_FECHA_INICIO DATE NOT NULL, ACT_FECHA_FIN DATE NOT NULL, ACT_ESTADO VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_RL_MR_ACTIVIDADES PRIMARY KEY (ACT_ID),
  CONSTRAINT FK_RL_MR_ACT_PLAN FOREIGN KEY (ACT_PLAN_ID) REFERENCES RL_MR_PLANES(PLA_ID),
  CONSTRAINT CK_RL_MR_ACT_AV CHECK (ACT_AVANCE BETWEEN 0 AND 100));

CREATE TABLE RL_MR_EVIDENCIAS (
  EVI_ID NUMBER(15) NOT NULL, EVI_NOMBRE_ARCHIVO VARCHAR2(255) NOT NULL, EVI_EXTENSION VARCHAR2(10) NOT NULL,
  EVI_TAMANO NUMBER(15) NOT NULL, EVI_HASH VARCHAR2(64) NOT NULL, EVI_RUTA VARCHAR2(500) NOT NULL,
  EVI_USR_CREACION NUMBER(10) NOT NULL, EVI_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RL_MR_EVIDENCIAS PRIMARY KEY (EVI_ID),
  CONSTRAINT FK_RL_MR_EVI_USR FOREIGN KEY (EVI_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT CK_RL_MR_EVI_TAM CHECK (EVI_TAMANO > 0));
CREATE TABLE RL_MR_EVIDENCIAS_VINCULOS (
  EVV_ID NUMBER(15) NOT NULL, EVV_EVIDENCIA_ID NUMBER(15) NOT NULL, EVV_TIPO_ENTIDAD VARCHAR2(30) NOT NULL,
  EVV_ENTIDAD_ID NUMBER(15) NOT NULL, EVV_USR_CREACION NUMBER(10) NOT NULL, EVV_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RL_MR_EVI_VINCULOS PRIMARY KEY (EVV_ID),
  CONSTRAINT FK_RL_MR_EVV_EVI FOREIGN KEY (EVV_EVIDENCIA_ID) REFERENCES RL_MR_EVIDENCIAS(EVI_ID),
  CONSTRAINT FK_RL_MR_EVV_USR FOREIGN KEY (EVV_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT UQ_RL_MR_EVV_UNICO UNIQUE (EVV_EVIDENCIA_ID,EVV_TIPO_ENTIDAD,EVV_ENTIDAD_ID),
  CONSTRAINT CK_RL_MR_EVV_TIPO CHECK (EVV_TIPO_ENTIDAD IN ('RIESGO','EVALUACION','CONTROL','PLAN','ACTIVIDAD','ALERTA','AUTOMONITOREO')));
CREATE TABLE RL_MR_SENALES_ALERTA (
  ALE_ID NUMBER(15) NOT NULL, ALE_EVALUACION_ID NUMBER(15) NOT NULL, ALE_CODIGO VARCHAR2(50) NOT NULL,
  ALE_INDICADOR VARCHAR2(150) NOT NULL, ALE_ESTADO VARCHAR2(30) DEFAULT 'INACTIVO' NOT NULL, ALE_FECHA_DISPARO DATE,
  CONSTRAINT PK_RL_MR_SENALES PRIMARY KEY (ALE_ID),
  CONSTRAINT FK_RL_MR_ALE_EVA FOREIGN KEY (ALE_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
  CONSTRAINT CK_RL_MR_ALE_EST CHECK (ALE_ESTADO IN ('ACTIVO','INACTIVO')));
CREATE TABLE RL_MR_AUTOMONITOREO (
  MON_ID NUMBER(15) NOT NULL, MON_EVALUACION_ID NUMBER(15) NOT NULL, MON_ESTADO_RIESGO VARCHAR2(30) NOT NULL,
  MON_ESTADO_CONTR VARCHAR2(30) NOT NULL, MON_RESULTADO VARCHAR2(1000) NOT NULL, MON_USR_ID NUMBER(10) NOT NULL,
  MON_FECHA DATE DEFAULT SYSDATE NOT NULL, CONSTRAINT PK_RL_MR_AUTOMONITOREO PRIMARY KEY (MON_ID),
  CONSTRAINT FK_RL_MR_MON_EVA FOREIGN KEY (MON_EVALUACION_ID) REFERENCES RL_MR_EVALUACIONES_RIESGO(EVA_ID),
  CONSTRAINT FK_RL_MR_MON_USR FOREIGN KEY (MON_USR_ID) REFERENCES RL_USUARIOS(USR_ID));

CREATE INDEX IDX_RL_MR_VER_VIG ON RL_MR_VERSIONES_FORMULARIO(VER_FAMILIA_ID,VER_VIGENTE,VER_ESTADO);
CREATE INDEX IDX_RL_MR_ELE_CAT ON RL_MR_ELEMENTOS_CATALOGO(ELE_CATALOGO_ID);
CREATE INDEX IDX_RL_MR_EVA_RIE ON RL_MR_EVALUACIONES_RIESGO(EVA_RIESGO_ID);
CREATE INDEX IDX_RL_MR_EVA_VER ON RL_MR_EVALUACIONES_RIESGO(EVA_VERSION_ID);
CREATE INDEX IDX_RL_MR_FLU_EVA_FEC ON RL_MR_FLUJOS_EVALUACION(FLU_EVALUACION_ID,FLU_FECHA);
CREATE INDEX IDX_RL_MR_PROY_BUSQ ON RL_MR_PROYECCIONES_EVALUACION(PROY_ESTADO_EVALUACION,PROY_NIVEL_RESIDUAL,PROY_FECHA_EVAL);
CREATE INDEX IDX_RL_MR_PROY_AREA ON RL_MR_PROYECCIONES_EVALUACION(PROY_AREA_PRINCIPAL);
CREATE INDEX IDX_RL_MR_PROY_DUENO ON RL_MR_PROYECCIONES_EVALUACION(PROY_DUENO_RIESGO);
CREATE INDEX IDX_RL_MR_CON_EVA ON RL_MR_CONTROLES_RIESGO(CON_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_ECO_CON ON RL_MR_EVALUACIONES_CONTROL(ECO_CONTROL_ID);
CREATE INDEX IDX_RL_MR_PLA_EVA ON RL_MR_PLANES(PLA_EVALUACION_ID);
CREATE INDEX IDX_RL_MR_ACT_PLAN ON RL_MR_ACTIVIDADES(ACT_PLAN_ID);
CREATE INDEX IDX_RL_MR_EVV_ENTIDAD ON RL_MR_EVIDENCIAS_VINCULOS(EVV_TIPO_ENTIDAD,EVV_ENTIDAD_ID);
CREATE INDEX IDX_RL_MR_EVV_EVIDENCIA ON RL_MR_EVIDENCIAS_VINCULOS(EVV_EVIDENCIA_ID);
CREATE INDEX IDX_RL_MR_ALE_EVAL ON RL_MR_SENALES_ALERTA(ALE_EVALUACION_ID,ALE_ESTADO);
CREATE INDEX IDX_RL_MR_MON_EVAL_FEC ON RL_MR_AUTOMONITOREO(MON_EVALUACION_ID,MON_FECHA);

PROMPT MODELO REDUCIDO DE 17 TABLAS CREADO. EJECUTE VALIDACIONES ANTES DE DESPLEGAR LA APLICACION.
