-- Fase 1 - hardening estructural Oracle, SOLO DDL.
-- Oracle DDL confirma implícitamente; se ejecuta separado del saneamiento DML.
-- Precondición: ejecutar 07_preflight y revisar su evidencia.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  v_count NUMBER;
  v_ddl CLOB;
  v_condition VARCHAR2(32767);
  PROCEDURE check_rows(p_sql VARCHAR2, p_label VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql INTO v_count;
    IF v_count <> 0 THEN RAISE_APPLICATION_ERROR(-20910, p_label || ' tiene datos incompatibles.'); END IF;
  END;
  PROCEDURE ensure_check(p_name VARCHAR2, p_expected VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME=UPPER(p_name);
    IF v_count=0 THEN
      EXECUTE IMMEDIATE p_ddl;
      DBMS_OUTPUT.PUT_LINE('ADDED_CONSTRAINT=' || p_name);
    ELSE
      SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME=UPPER(p_name) AND CONSTRAINT_TYPE='C' AND STATUS='ENABLED';
      IF v_count<>1 THEN RAISE_APPLICATION_ERROR(-20911,'Objeto existente no es CHECK habilitado: ' || p_name); END IF;
      v_ddl := DBMS_METADATA.GET_DDL('CONSTRAINT', UPPER(p_name), USER);
      v_condition := REPLACE(REGEXP_REPLACE(UPPER(DBMS_LOB.SUBSTR(v_ddl,32767,1)), '[[:space:]]', ''), '"', '');
      IF INSTR(v_condition, UPPER(REPLACE(REPLACE(p_expected,' ',''),CHR(10),'')))=0 THEN
        RAISE_APPLICATION_ERROR(-20912,'Definicion inesperada para constraint: ' || p_name);
      END IF;
      DBMS_OUTPUT.PUT_LINE('VERIFIED_CONSTRAINT=' || p_name);
    END IF;
  END;
BEGIN
  check_rows('SELECT COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_VIGENTE=1 AND VER_ESTADO<>''PUBLISHED''','VIGENTE_NOT_PUBLISHED');
  check_rows('SELECT COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO WHERE EVA_VERSION_ROW IS NULL OR EVA_VERSION_ROW<1','BAD_VERSION_ROW');
  check_rows('SELECT COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_FECHA_INICIO IS NOT NULL AND VER_FECHA_FIN IS NOT NULL AND VER_FECHA_FIN<VER_FECHA_INICIO','BAD_INTERVAL');
  check_rows('SELECT COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_HASH IS NULL OR LENGTH(VER_HASH)<>64 OR NOT REGEXP_LIKE(UPPER(VER_HASH),''^[0-9A-F]{64}$'')','HASH_FORMAT_INVALID');
  check_rows('SELECT COUNT(*) FROM (SELECT VER_FAMILIA_ID FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_VIGENTE=1 GROUP BY VER_FAMILIA_ID HAVING COUNT(*)>1)','MULTIPLE_VIGENTE');
  ensure_check('CK_RL_MR_VER_VIG_PUB','VER_VIGENTE=0ORVER_ESTADO=''PUBLISHED''','ALTER TABLE RL_MR_VERSIONES_FORMULARIO ADD CONSTRAINT CK_RL_MR_VER_VIG_PUB CHECK (VER_VIGENTE=0 OR VER_ESTADO=''PUBLISHED'') ENABLE');
  ensure_check('CK_RL_MR_VER_FECHAS','VER_FECHA_FINISNULLORVER_FECHA_INICIOISNULLORVER_FECHA_FIN>=VER_FECHA_INICIO','ALTER TABLE RL_MR_VERSIONES_FORMULARIO ADD CONSTRAINT CK_RL_MR_VER_FECHAS CHECK (VER_FECHA_FIN IS NULL OR VER_FECHA_INICIO IS NULL OR VER_FECHA_FIN>=VER_FECHA_INICIO) ENABLE');
  ensure_check('CK_RL_MR_EVA_VERSION_ROW','EVA_VERSION_ROW>=1','ALTER TABLE RL_MR_EVALUACIONES_RIESGO ADD CONSTRAINT CK_RL_MR_EVA_VERSION_ROW CHECK (EVA_VERSION_ROW>=1) ENABLE');
  ensure_check('CK_RL_MR_VER_HASH_FMT','VER_HASHISNOTNULLANDLENGTH(VER_HASH)=64ANDREGEXP_LIKE(UPPER(VER_HASH),''^[0-9A-F]{64}$'')','ALTER TABLE RL_MR_VERSIONES_FORMULARIO ADD CONSTRAINT CK_RL_MR_VER_HASH_FMT CHECK (VER_HASH IS NOT NULL AND LENGTH(VER_HASH)=64 AND REGEXP_LIKE(UPPER(VER_HASH),''^[0-9A-F]{64}$'')) ENABLE');
  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME='UX_RL_MR_VER_FAM_VIG';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_RL_MR_VER_FAM_VIG ON RL_MR_VERSIONES_FORMULARIO (CASE WHEN VER_VIGENTE=1 THEN VER_FAMILIA_ID END)';
    DBMS_OUTPUT.PUT_LINE('ADDED_INDEX=UX_RL_MR_VER_FAM_VIG');
  ELSE
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME='UX_RL_MR_VER_FAM_VIG' AND UNIQUENESS='UNIQUE' AND STATUS='VALID';
    IF v_count<>1 THEN RAISE_APPLICATION_ERROR(-20913,'Indice existente no es UNIQUE/VALID.'); END IF;
    v_ddl := DBMS_METADATA.GET_DDL('INDEX', 'UX_RL_MR_VER_FAM_VIG', USER);
    v_condition := REPLACE(REGEXP_REPLACE(UPPER(DBMS_LOB.SUBSTR(v_ddl,32767,1)), '[[:space:]]', ''), '"', '');
    IF INSTR(v_condition, 'CASEVER_VIGENTEWHEN1THENVER_FAMILIA_IDEND')=0 THEN RAISE_APPLICATION_ERROR(-20914,'Expresion inesperada para indice.'); END IF;
    DBMS_OUTPUT.PUT_LINE('VERIFIED_INDEX=UX_RL_MR_VER_FAM_VIG');
  END IF;
END;
/
EXIT
