-- Fase 1 - postflight READ-ONLY de integridad y enforcement Oracle.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE UNLIMITED
SET HEADING OFF FEEDBACK OFF PAGESIZE 0 VERIFY OFF ECHO OFF

PROMPT POSTFLIGHT_FASE1_START
SELECT 'MULTIPLE_VIGENTE=' || COUNT(*) FROM (
  SELECT VER_FAMILIA_ID FROM RL_MR_VERSIONES_FORMULARIO
   WHERE VER_VIGENTE = 1 GROUP BY VER_FAMILIA_ID HAVING COUNT(*) > 1);
SELECT 'VIGENTE_NOT_PUBLISHED=' || COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO
 WHERE VER_VIGENTE = 1 AND VER_ESTADO <> 'PUBLISHED';
SELECT 'BAD_INTERVAL=' || COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO
 WHERE VER_FECHA_INICIO IS NOT NULL AND VER_FECHA_FIN IS NOT NULL
   AND VER_FECHA_FIN < VER_FECHA_INICIO;
SELECT 'CURRENT_WITH_END_DATE=' || COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO
 WHERE VER_VIGENTE = 1 AND VER_FECHA_FIN IS NOT NULL;
SELECT 'TEMPORAL_OVERLAPS=' || COUNT(*)
  FROM RL_MR_VERSIONES_FORMULARIO a JOIN RL_MR_VERSIONES_FORMULARIO b
    ON b.VER_FAMILIA_ID = a.VER_FAMILIA_ID AND b.VER_ID > a.VER_ID
   AND a.VER_ESTADO = 'PUBLISHED' AND b.VER_ESTADO = 'PUBLISHED'
   AND a.VER_FECHA_INICIO IS NOT NULL AND b.VER_FECHA_INICIO IS NOT NULL
   AND a.VER_FECHA_INICIO < NVL(b.VER_FECHA_FIN, TO_DATE('9999-12-31','YYYY-MM-DD'))
   AND b.VER_FECHA_INICIO < NVL(a.VER_FECHA_FIN, TO_DATE('9999-12-31','YYYY-MM-DD'));
SELECT 'HASH_FORMAT_INVALID=' || COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO
 WHERE VER_HASH IS NULL OR LENGTH(VER_HASH) <> 64
    OR NOT REGEXP_LIKE(UPPER(VER_HASH), '^[0-9A-F]{64}$');
SELECT 'ORPHAN_VERSION=' || COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO e
 LEFT JOIN RL_MR_VERSIONES_FORMULARIO v ON v.VER_ID = e.EVA_VERSION_ID
 WHERE v.VER_ID IS NULL;
SELECT 'BAD_VERSION_ROW=' || COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO
 WHERE EVA_VERSION_ROW IS NULL OR EVA_VERSION_ROW < 1;
SELECT 'INVALID_OBJECTS=' || COUNT(*) FROM USER_OBJECTS WHERE STATUS <> 'VALID';
SELECT 'DISABLED_CONSTRAINTS=' || COUNT(*) FROM USER_CONSTRAINTS WHERE STATUS <> 'ENABLED';
PROMPT POSTFLIGHT_FASE1_END
EXIT
