-- Fase 1 - saneamiento temporal H4 de las tres transiciones auditadas.
-- DML separado del DDL; no modifica JSON, hash ni EVA_VERSION_ID.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  v_pairs NUMBER; v_rows NUMBER := 0;
  v_eval_total_before NUMBER; v_eval_total_after NUMBER;
  v_eval_refs_before NUMBER; v_eval_refs_after NUMBER;
  v_overlap NUMBER; v_missing_start NUMBER; v_bad_interval NUMBER;
  v_current_end NUMBER; v_order_inconsistency NUMBER;
  v_multiple_current NUMBER; v_current_not_published NUMBER; v_bad_version_row NUMBER;
  v_len_1_before NUMBER; v_len_1_after NUMBER; v_len_17_before NUMBER; v_len_17_after NUMBER;
  v_len_25_before NUMBER; v_len_25_after NUMBER; v_len_33_before NUMBER; v_len_33_after NUMBER;
  v_hash_1_before VARCHAR2(64); v_hash_1_after VARCHAR2(64);
  v_hash_17_before VARCHAR2(64); v_hash_17_after VARCHAR2(64);
  v_hash_25_before VARCHAR2(64); v_hash_25_after VARCHAR2(64);
  v_hash_33_before VARCHAR2(64); v_hash_33_after VARCHAR2(64);
BEGIN
  SELECT COUNT(*) INTO v_pairs
    FROM RL_MR_VERSIONES_FORMULARIO a JOIN RL_MR_VERSIONES_FORMULARIO b
      ON b.VER_FAMILIA_ID=a.VER_FAMILIA_ID
     AND ((a.VER_ID=1 AND a.VER_FAMILIA_ID=2 AND a.VER_VERSION=1 AND a.VER_FECHA_INICIO=TO_DATE('2026-08-07 09:27:22','YYYY-MM-DD HH24:MI:SS') AND a.VER_FECHA_FIN=TO_DATE('2026-08-13 09:38:44','YYYY-MM-DD HH24:MI:SS') AND b.VER_ID=17 AND b.VER_VERSION=5 AND b.VER_FECHA_INICIO=TO_DATE('2026-08-12 11:12:44','YYYY-MM-DD HH24:MI:SS'))
       OR (a.VER_ID=17 AND a.VER_FAMILIA_ID=2 AND a.VER_VERSION=5 AND a.VER_FECHA_INICIO=TO_DATE('2026-08-12 11:12:44','YYYY-MM-DD HH24:MI:SS') AND a.VER_FECHA_FIN=TO_DATE('2026-08-20 09:47:55','YYYY-MM-DD HH24:MI:SS') AND b.VER_ID=25 AND b.VER_VERSION=7 AND b.VER_FECHA_INICIO=TO_DATE('2026-08-19 15:12:19','YYYY-MM-DD HH24:MI:SS'))
       OR (a.VER_ID=25 AND a.VER_FAMILIA_ID=2 AND a.VER_VERSION=7 AND a.VER_FECHA_INICIO=TO_DATE('2026-08-19 15:12:19','YYYY-MM-DD HH24:MI:SS') AND a.VER_FECHA_FIN=TO_DATE('2026-08-20 15:01:09','YYYY-MM-DD HH24:MI:SS') AND b.VER_ID=33 AND b.VER_VERSION=10 AND b.VER_FECHA_INICIO=TO_DATE('2026-08-20 14:28:03','YYYY-MM-DD HH24:MI:SS')))
   WHERE a.VER_ESTADO='PUBLISHED' AND b.VER_ESTADO='PUBLISHED'
     AND a.VER_FECHA_INICIO < b.VER_FECHA_FIN AND b.VER_FECHA_INICIO < a.VER_FECHA_FIN;
  IF v_pairs<>3 THEN RAISE_APPLICATION_ERROR(-20920,'Precondición H4 no coincide exactamente con los tres pares auditados.'); END IF;

  SELECT COUNT(*) INTO v_eval_total_before FROM RL_MR_EVALUACIONES_RIESGO;
  SELECT COUNT(*) INTO v_eval_refs_before FROM RL_MR_EVALUACIONES_RIESGO WHERE EVA_VERSION_ID IN (1,17,25,33);
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_1_before,v_hash_1_before FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=1;
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_17_before,v_hash_17_before FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=17;
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_25_before,v_hash_25_before FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=25;
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_33_before,v_hash_33_before FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=33;

  UPDATE RL_MR_VERSIONES_FORMULARIO SET VER_FECHA_FIN=TO_DATE('2026-08-12 11:12:44','YYYY-MM-DD HH24:MI:SS') WHERE VER_ID=1 AND VER_FAMILIA_ID=2 AND VER_VERSION=1 AND VER_ESTADO='PUBLISHED' AND VER_FECHA_INICIO=TO_DATE('2026-08-07 09:27:22','YYYY-MM-DD HH24:MI:SS') AND VER_FECHA_FIN=TO_DATE('2026-08-13 09:38:44','YYYY-MM-DD HH24:MI:SS'); v_rows:=v_rows+SQL%ROWCOUNT;
  UPDATE RL_MR_VERSIONES_FORMULARIO SET VER_FECHA_FIN=TO_DATE('2026-08-19 15:12:19','YYYY-MM-DD HH24:MI:SS') WHERE VER_ID=17 AND VER_FAMILIA_ID=2 AND VER_VERSION=5 AND VER_ESTADO='PUBLISHED' AND VER_FECHA_INICIO=TO_DATE('2026-08-12 11:12:44','YYYY-MM-DD HH24:MI:SS') AND VER_FECHA_FIN=TO_DATE('2026-08-20 09:47:55','YYYY-MM-DD HH24:MI:SS'); v_rows:=v_rows+SQL%ROWCOUNT;
  UPDATE RL_MR_VERSIONES_FORMULARIO SET VER_FECHA_FIN=TO_DATE('2026-08-20 14:28:03','YYYY-MM-DD HH24:MI:SS') WHERE VER_ID=25 AND VER_FAMILIA_ID=2 AND VER_VERSION=7 AND VER_ESTADO='PUBLISHED' AND VER_FECHA_INICIO=TO_DATE('2026-08-19 15:12:19','YYYY-MM-DD HH24:MI:SS') AND VER_FECHA_FIN=TO_DATE('2026-08-20 15:01:09','YYYY-MM-DD HH24:MI:SS'); v_rows:=v_rows+SQL%ROWCOUNT;
  IF v_rows<>3 THEN ROLLBACK; RAISE_APPLICATION_ERROR(-20921,'No se actualizaron exactamente tres filas.'); END IF;

  SELECT COUNT(*) INTO v_overlap FROM RL_MR_VERSIONES_FORMULARIO a JOIN RL_MR_VERSIONES_FORMULARIO b ON b.VER_FAMILIA_ID=a.VER_FAMILIA_ID WHERE a.VER_ESTADO='PUBLISHED' AND b.VER_ESTADO='PUBLISHED' AND a.VER_ID<b.VER_ID AND a.VER_FECHA_INICIO IS NOT NULL AND b.VER_FECHA_INICIO IS NOT NULL AND a.VER_FECHA_INICIO<NVL(b.VER_FECHA_FIN,TO_DATE('9999-12-31','YYYY-MM-DD')) AND b.VER_FECHA_INICIO<NVL(a.VER_FECHA_FIN,TO_DATE('9999-12-31','YYYY-MM-DD'));
  SELECT COUNT(*) INTO v_missing_start FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ESTADO='PUBLISHED' AND VER_FECHA_INICIO IS NULL;
  SELECT COUNT(*) INTO v_bad_interval FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_FECHA_INICIO IS NOT NULL AND VER_FECHA_FIN IS NOT NULL AND VER_FECHA_FIN<VER_FECHA_INICIO;
  SELECT COUNT(*) INTO v_current_end FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_VIGENTE=1 AND VER_FECHA_FIN IS NOT NULL;
  SELECT COUNT(*) INTO v_order_inconsistency FROM RL_MR_VERSIONES_FORMULARIO a JOIN RL_MR_VERSIONES_FORMULARIO b ON b.VER_FAMILIA_ID=a.VER_FAMILIA_ID AND b.VER_VERSION>a.VER_VERSION AND b.VER_FECHA_INICIO<a.VER_FECHA_INICIO;
  SELECT COUNT(*) INTO v_multiple_current FROM (SELECT VER_FAMILIA_ID FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_VIGENTE=1 GROUP BY VER_FAMILIA_ID HAVING COUNT(*)>1);
  SELECT COUNT(*) INTO v_current_not_published FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_VIGENTE=1 AND VER_ESTADO<>'PUBLISHED';
  SELECT COUNT(*) INTO v_bad_version_row FROM RL_MR_EVALUACIONES_RIESGO WHERE EVA_VERSION_ROW IS NULL OR EVA_VERSION_ROW<1;
  SELECT COUNT(*) INTO v_eval_total_after FROM RL_MR_EVALUACIONES_RIESGO;
  SELECT COUNT(*) INTO v_eval_refs_after FROM RL_MR_EVALUACIONES_RIESGO WHERE EVA_VERSION_ID IN (1,17,25,33);
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_1_after,v_hash_1_after FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=1;
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_17_after,v_hash_17_after FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=17;
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_25_after,v_hash_25_after FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=25;
  SELECT DBMS_LOB.GETLENGTH(VER_JSON),VER_HASH INTO v_len_33_after,v_hash_33_after FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID=33;
  IF v_overlap<>0 OR v_missing_start<>0 OR v_bad_interval<>0 OR v_current_end<>0 OR v_order_inconsistency<>0 OR v_multiple_current<>0 OR v_current_not_published<>0 OR v_bad_version_row<>0 OR v_eval_total_after<>v_eval_total_before OR v_eval_refs_after<>v_eval_refs_before OR v_len_1_after<>v_len_1_before OR v_len_17_after<>v_len_17_before OR v_len_25_after<>v_len_25_before OR v_len_33_after<>v_len_33_before OR v_hash_1_after<>v_hash_1_before OR v_hash_17_after<>v_hash_17_before OR v_hash_25_after<>v_hash_25_before OR v_hash_33_after<>v_hash_33_before THEN ROLLBACK; RAISE_APPLICATION_ERROR(-20922,'Postcheck H4 fallo; rollback ejecutado.'); END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('TEMPORAL_ROWS_CORRECTED=3');
END;
/
EXIT
