-- Fase 1 - evidencia READ-ONLY de sucesión temporal H4.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET HEADING OFF FEEDBACK OFF PAGESIZE 0 VERIFY OFF ECHO OFF
PROMPT H4_SUCCESSOR_PROOF_START
SELECT a.VER_FAMILIA_ID||'|'||a.VER_ID||'|v'||a.VER_VERSION||'|'||TO_CHAR(a.VER_FECHA_FIN,'YYYY-MM-DD HH24:MI:SS')||'|SUCCESSOR|'||b.VER_ID||'|v'||b.VER_VERSION||'|'||TO_CHAR(b.VER_FECHA_INICIO,'YYYY-MM-DD HH24:MI:SS') FROM RL_MR_VERSIONES_FORMULARIO a JOIN RL_MR_VERSIONES_FORMULARIO b ON b.VER_FAMILIA_ID=a.VER_FAMILIA_ID AND ((a.VER_ID=1 AND b.VER_ID=17) OR (a.VER_ID=17 AND b.VER_ID=25) OR (a.VER_ID=25 AND b.VER_ID=33)) WHERE a.VER_ESTADO='PUBLISHED' AND b.VER_ESTADO='PUBLISHED';
SELECT 'EVALUATIONS_IN_AFFECTED_VERSIONS='||COUNT(*) FROM RL_MR_EVALUACIONES_RIESGO WHERE EVA_VERSION_ID IN (1,17,25,33);
SELECT 'JSON_HASH_ROWS_UNTOUCHED='||COUNT(*) FROM RL_MR_VERSIONES_FORMULARIO WHERE VER_ID IN (1,17,25,33) AND VER_JSON IS NOT NULL AND VER_HASH IS NOT NULL;
PROMPT H4_SUCCESSOR_PROOF_END
EXIT
