-- FASE 3.1.2 - PRECHECK READ-ONLY. No contiene DDL ni DML.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF
SET VERIFY OFF
SET TERMOUT ON
SET HEADING ON
SET FEEDBACK ON
SET SERVEROUTPUT ON

PROMPT PRECHECK_CONFIGURACION_CALCULO_312
SELECT VERSION AS ORACLE_VERSION
  FROM PRODUCT_COMPONENT_VERSION
 WHERE PRODUCT LIKE 'Oracle Database%'
   AND ROWNUM = 1;

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE (OBJECT_NAME LIKE 'RL\_MR\_%' ESCAPE '\'
        OR OBJECT_NAME = 'RL_AUDITORIA')
   AND OBJECT_TYPE IN ('TABLE', 'SEQUENCE', 'TRIGGER', 'VIEW', 'PACKAGE', 'PROCEDURE', 'FUNCTION')
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT OBJETOS_312_EXISTENTES
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN (
   'RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
   'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
   'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES',
   'SEQ_RL_MR_FORMULAS','SEQ_RL_MR_FORMULA_VERSIONES','SEQ_RL_MR_FORMULA_USOS',
   'SEQ_RL_MR_FUNCIONES','SEQ_RL_MR_FUNCION_VERSIONES','SEQ_RL_MR_FUNCION_ARGUMENTOS',
   'SEQ_RL_MR_PARAMETROS','SEQ_RL_MR_PARAMETRO_VERSIONES'
 )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT COLUMNAS_312_EXISTENTES
SELECT TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN (
   'RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
   'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
   'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES'
 )
 ORDER BY TABLE_NAME, COLUMN_ID;

PROMPT FUENTES_REUTILIZADAS
SELECT t.TABLE_NAME, COUNT(*) AS COLUMN_COUNT
  FROM USER_TABLES t
  JOIN USER_TAB_COLUMNS c ON c.TABLE_NAME = t.TABLE_NAME
 WHERE t.TABLE_NAME IN (
   'RL_MR_REGLAS_CALCULO','RL_MR_CATALOGOS','RL_MR_ELEMENTOS_CATALOGO',
   'RL_MR_VERSIONES_FORMULARIO','RL_MR_FAMILIAS_FORMULARIO',
   'RL_MR_EVALUACIONES_RIESGO','RL_AUDITORIA'
 )
 GROUP BY t.TABLE_NAME
 ORDER BY TABLE_NAME;

PROMPT CONSTRAINTS_E_INDICES_REUTILIZADOS
SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE, STATUS
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME IN (
   'RL_MR_REGLAS_CALCULO','RL_MR_CATALOGOS','RL_MR_ELEMENTOS_CATALOGO',
   'RL_MR_VERSIONES_FORMULARIO','RL_MR_FAMILIAS_FORMULARIO',
   'RL_MR_EVALUACIONES_RIESGO','RL_AUDITORIA'
 )
 ORDER BY TABLE_NAME, CONSTRAINT_NAME;

PROMPT HISTORICO_BASE_SIN_CLOB
SELECT COUNT(*) AS VERSIONES_FORMULARIO,
       COUNT(VER_HASH) AS VERSIONES_CON_HASH,
       COUNT(DISTINCT VER_HASH) AS HASHES_DISTINTOS
  FROM RL_MR_VERSIONES_FORMULARIO;
SELECT COUNT(*) AS EVALUACIONES,
       COUNT(EVA_VERSION_ID) AS EVALUACIONES_CON_VERSION,
       COUNT(EVA_CALCULOS_JSON) AS EVALUACIONES_CON_RESULTADO
  FROM RL_MR_EVALUACIONES_RIESGO;
SELECT VER_ID, VER_HASH, VER_ESTADO, VER_VIGENTE
  FROM RL_MR_VERSIONES_FORMULARIO
 WHERE VER_ID IN (24, 53, 27, 28)
 ORDER BY VER_ID;
SELECT 'RL_MR_REGLAS_CALCULO' AS OBJETO, COUNT(*) AS FILAS FROM RL_MR_REGLAS_CALCULO
UNION ALL SELECT 'RL_MR_CATALOGOS', COUNT(*) FROM RL_MR_CATALOGOS
UNION ALL SELECT 'RL_MR_ELEMENTOS_CATALOGO', COUNT(*) FROM RL_MR_ELEMENTOS_CATALOGO
UNION ALL SELECT 'RL_AUDITORIA', COUNT(*) FROM RL_AUDITORIA;

PROMPT INVALIDOS_RELEVANTES
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE STATUS <> 'VALID'
   AND (OBJECT_NAME LIKE 'RL\_MR\_%' ESCAPE '\' OR OBJECT_NAME = 'RL_AUDITORIA');

DECLARE
  v_existing NUMBER;
  v_columns NUMBER;
  v_invalid NUMBER;
  PROCEDURE require_base(p_name VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_existing FROM USER_TABLES WHERE TABLE_NAME = p_name;
    IF v_existing <> 1 THEN
      RAISE_APPLICATION_ERROR(-20901, 'Tabla base requerida ausente: ' || p_name);
    END IF;
  END;
  PROCEDURE check_existing_shape(p_name VARCHAR2, p_min_columns NUMBER) IS
  BEGIN
    SELECT COUNT(*) INTO v_existing FROM USER_TABLES WHERE TABLE_NAME = p_name;
    IF v_existing = 1 THEN
      SELECT COUNT(*) INTO v_columns FROM USER_TAB_COLUMNS WHERE TABLE_NAME = p_name;
      IF v_columns < p_min_columns THEN
        RAISE_APPLICATION_ERROR(-20902, 'Objeto 3.1.2 existente con firma incompatible: ' || p_name);
      END IF;
    END IF;
  END;
BEGIN
  require_base('RL_MR_VERSIONES_FORMULARIO');
  require_base('RL_MR_FAMILIAS_FORMULARIO');
  require_base('RL_MR_EVALUACIONES_RIESGO');
  require_base('RL_MR_REGLAS_CALCULO');
  require_base('RL_MR_CATALOGOS');
  require_base('RL_MR_ELEMENTOS_CATALOGO');
  require_base('RL_AUDITORIA');
  check_existing_shape('RL_MR_FORMULAS', 9);
  check_existing_shape('RL_MR_FORMULA_VERSIONES', 10);
  check_existing_shape('RL_MR_FORMULA_USOS', 6);
  check_existing_shape('RL_MR_FUNCIONES', 9);
  check_existing_shape('RL_MR_FUNCION_VERSIONES', 13);
  check_existing_shape('RL_MR_FUNCION_ARGUMENTOS', 9);
  check_existing_shape('RL_MR_PARAMETROS_CALCULO', 9);
  check_existing_shape('RL_MR_PARAMETRO_VERSIONES', 14);
  SELECT COUNT(*) INTO v_invalid
    FROM USER_OBJECTS
   WHERE STATUS <> 'VALID'
     AND (OBJECT_NAME LIKE 'RL\_MR\_%' ESCAPE '\' OR OBJECT_NAME = 'RL_AUDITORIA');
  IF v_invalid <> 0 THEN
    RAISE_APPLICATION_ERROR(-20903, 'Existen objetos relevantes INVALID.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('ORACLE_PRECHECK=PASS');
END;
/
EXIT SUCCESS
