-- FASE 3.1.2 - DDL Oracle 11g. Ejecutar solo después de autorización explícita.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF
SET VERIFY OFF
SET TERMOUT ON
SET SERVEROUTPUT ON

DECLARE
  v_exists NUMBER;
  PROCEDURE create_table_if_absent(p_name VARCHAR2, p_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = p_name;
    IF v_exists = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    ELSE
      DBMS_OUTPUT.PUT_LINE('ALREADY_APPLIED_TABLE=' || p_name);
    END IF;
  END;
  PROCEDURE create_sequence_if_absent(p_name VARCHAR2, p_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = p_name;
    IF v_exists = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    ELSE
      DBMS_OUTPUT.PUT_LINE('ALREADY_APPLIED_SEQUENCE=' || p_name);
    END IF;
  END;
  PROCEDURE create_index_if_absent(p_name VARCHAR2, p_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
    IF v_exists = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    ELSE
      DBMS_OUTPUT.PUT_LINE('ALREADY_APPLIED_INDEX=' || p_name);
    END IF;
  END;
BEGIN
  create_table_if_absent('RL_MR_FORMULAS', q'[CREATE TABLE RL_MR_FORMULAS (
    FOR_ID NUMBER(15) NOT NULL,
    FOR_CODIGO VARCHAR2(80 CHAR) NOT NULL,
    FOR_NOMBRE VARCHAR2(150 CHAR) NOT NULL,
    FOR_DESCRIPCION VARCHAR2(1000 CHAR),
    FOR_ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    FOR_METADATA_JSON CLOB,
    FOR_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FOR_USR_CREACION NUMBER(10) NOT NULL,
    FOR_VERSION_ROW NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_FORMULAS PRIMARY KEY (FOR_ID),
    CONSTRAINT UQ_RL_MR_FOR_COD UNIQUE (FOR_CODIGO),
    CONSTRAINT CK_RL_MR_FOR_EST CHECK (FOR_ESTADO IN ('ACTIVE','INACTIVE','RETIRED')),
    CONSTRAINT CK_RL_MR_FOR_ROW CHECK (FOR_VERSION_ROW >= 1),
    CONSTRAINT FK_RL_MR_FOR_USR FOREIGN KEY (FOR_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID)
  )]');
  create_table_if_absent('RL_MR_FORMULA_VERSIONES', q'[CREATE TABLE RL_MR_FORMULA_VERSIONES (
    FOV_ID NUMBER(15) NOT NULL,
    FOV_FORMULA_ID NUMBER(15) NOT NULL,
    FOV_VERSION NUMBER(5) NOT NULL,
    FOV_EXPRESION CLOB NOT NULL,
    FOV_TIPO_RESULTADO VARCHAR2(20 CHAR) NOT NULL,
    FOV_ESTADO VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    FOV_HASH VARCHAR2(64 CHAR) NOT NULL,
    FOV_FECHA_INICIO DATE,
    FOV_FECHA_FIN DATE,
    FOV_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FOV_USR_CREACION NUMBER(10) NOT NULL,
    FOV_VERSION_ROW NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_FOV PRIMARY KEY (FOV_ID),
    CONSTRAINT FK_RL_MR_FOV_FOR FOREIGN KEY (FOV_FORMULA_ID) REFERENCES RL_MR_FORMULAS(FOR_ID),
    CONSTRAINT FK_RL_MR_FOV_USR FOREIGN KEY (FOV_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
    CONSTRAINT UQ_RL_MR_FOV_VER UNIQUE (FOV_FORMULA_ID,FOV_VERSION),
    CONSTRAINT CK_RL_MR_FOV_VER CHECK (FOV_VERSION >= 1),
    CONSTRAINT CK_RL_MR_FOV_EST CHECK (FOV_ESTADO IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')),
    CONSTRAINT CK_RL_MR_FOV_HASH CHECK (REGEXP_LIKE(FOV_HASH,'^[0-9A-Fa-f]{64}$')),
    CONSTRAINT CK_RL_MR_FOV_ROW CHECK (FOV_VERSION_ROW >= 1)
  )]');
  create_table_if_absent('RL_MR_FORMULA_USOS', q'[CREATE TABLE RL_MR_FORMULA_USOS (
    FUS_ID NUMBER(15) NOT NULL,
    FUS_VERSION_FORMULARIO_ID NUMBER(15) NOT NULL,
    FUS_CAMPO_CLAVE VARCHAR2(150 CHAR) NOT NULL,
    FUS_FORMULA_VERSION_ID NUMBER(15) NOT NULL,
    FUS_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FUS_USR_CREACION NUMBER(10) NOT NULL,
    CONSTRAINT PK_RL_MR_FUS PRIMARY KEY (FUS_ID),
    CONSTRAINT FK_RL_MR_FUS_VERF FOREIGN KEY (FUS_VERSION_FORMULARIO_ID) REFERENCES RL_MR_VERSIONES_FORMULARIO(VER_ID),
    CONSTRAINT FK_RL_MR_FUS_FOV FOREIGN KEY (FUS_FORMULA_VERSION_ID) REFERENCES RL_MR_FORMULA_VERSIONES(FOV_ID),
    CONSTRAINT FK_RL_MR_FUS_USR FOREIGN KEY (FUS_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
    CONSTRAINT UQ_RL_MR_FUS_FIELD UNIQUE (FUS_VERSION_FORMULARIO_ID,FUS_CAMPO_CLAVE)
  )]');
  create_table_if_absent('RL_MR_FUNCIONES', q'[CREATE TABLE RL_MR_FUNCIONES (
    FUN_ID NUMBER(15) NOT NULL,
    FUN_CODIGO VARCHAR2(80 CHAR) NOT NULL,
    FUN_NOMBRE VARCHAR2(150 CHAR) NOT NULL,
    FUN_DESCRIPCION VARCHAR2(1000 CHAR),
    FUN_CATEGORIA VARCHAR2(50 CHAR) DEFAULT 'CALCULO' NOT NULL,
    FUN_ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    FUN_METADATA_JSON CLOB,
    FUN_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FUN_USR_CREACION NUMBER(10) NOT NULL,
    FUN_VERSION_ROW NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_FUN PRIMARY KEY (FUN_ID),
    CONSTRAINT UQ_RL_MR_FUN_COD UNIQUE (FUN_CODIGO),
    CONSTRAINT CK_RL_MR_FUN_EST CHECK (FUN_ESTADO IN ('ACTIVE','INACTIVE','RETIRED')),
    CONSTRAINT CK_RL_MR_FUN_ROW CHECK (FUN_VERSION_ROW >= 1),
    CONSTRAINT FK_RL_MR_FUN_USR FOREIGN KEY (FUN_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID)
  )]');
  create_table_if_absent('RL_MR_FUNCION_VERSIONES', q'[CREATE TABLE RL_MR_FUNCION_VERSIONES (
    FUV_ID NUMBER(15) NOT NULL,
    FUV_FUNCION_ID NUMBER(15) NOT NULL,
    FUV_VERSION NUMBER(5) NOT NULL,
    FUV_TIPO VARCHAR2(12 CHAR) NOT NULL,
    FUV_TIPO_RESULTADO VARCHAR2(20 CHAR) NOT NULL,
    FUV_SIGNATURE_JSON CLOB,
    FUV_DEFINICION_DSL CLOB,
    FUV_HANDLER_KEY VARCHAR2(80 CHAR),
    FUV_MIN_ARITY NUMBER(3) DEFAULT 0 NOT NULL,
    FUV_MAX_ARITY NUMBER(3),
    FUV_ESTADO VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    FUV_HASH VARCHAR2(64 CHAR) NOT NULL,
    FUV_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FUV_USR_CREACION NUMBER(10) NOT NULL,
    FUV_VERSION_ROW NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_FUV PRIMARY KEY (FUV_ID),
    CONSTRAINT FK_RL_MR_FUV_FUN FOREIGN KEY (FUV_FUNCION_ID) REFERENCES RL_MR_FUNCIONES(FUN_ID),
    CONSTRAINT FK_RL_MR_FUV_USR FOREIGN KEY (FUV_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
    CONSTRAINT UQ_RL_MR_FUV_VER UNIQUE (FUV_FUNCION_ID,FUV_VERSION),
    CONSTRAINT CK_RL_MR_FUV_VER CHECK (FUV_VERSION >= 1),
    CONSTRAINT CK_RL_MR_FUV_TIPO CHECK (FUV_TIPO IN ('NATIVE','COMPOSITE')),
    CONSTRAINT CK_RL_MR_FUV_NC CHECK ((FUV_TIPO='NATIVE' AND FUV_HANDLER_KEY IS NOT NULL AND FUV_DEFINICION_DSL IS NULL) OR (FUV_TIPO='COMPOSITE' AND FUV_HANDLER_KEY IS NULL AND FUV_DEFINICION_DSL IS NOT NULL)),
    CONSTRAINT CK_RL_MR_FUV_ARITY CHECK (FUV_MIN_ARITY >= 0 AND (FUV_MAX_ARITY IS NULL OR FUV_MAX_ARITY >= FUV_MIN_ARITY)),
    CONSTRAINT CK_RL_MR_FUV_EST CHECK (FUV_ESTADO IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')),
    CONSTRAINT CK_RL_MR_FUV_HASH CHECK (REGEXP_LIKE(FUV_HASH,'^[0-9A-Fa-f]{64}$')),
    CONSTRAINT CK_RL_MR_FUV_ROW CHECK (FUV_VERSION_ROW >= 1)
  )]');
  create_table_if_absent('RL_MR_FUNCION_ARGUMENTOS', q'[CREATE TABLE RL_MR_FUNCION_ARGUMENTOS (
    FUA_ID NUMBER(15) NOT NULL,
    FUA_FUNCION_VERSION_ID NUMBER(15) NOT NULL,
    FUA_POSICION NUMBER(3) NOT NULL,
    FUA_CODIGO VARCHAR2(80 CHAR) NOT NULL,
    FUA_NOMBRE VARCHAR2(150 CHAR) NOT NULL,
    FUA_TIPO VARCHAR2(20 CHAR) NOT NULL,
    FUA_REQUERIDO NUMBER(1) DEFAULT 1 NOT NULL,
    FUA_VARIADIC NUMBER(1) DEFAULT 0 NOT NULL,
    FUA_DEFAULT_JSON CLOB,
    FUA_DESCRIPCION VARCHAR2(500 CHAR),
    CONSTRAINT PK_RL_MR_FUA PRIMARY KEY (FUA_ID),
    CONSTRAINT FK_RL_MR_FUA_FUV FOREIGN KEY (FUA_FUNCION_VERSION_ID) REFERENCES RL_MR_FUNCION_VERSIONES(FUV_ID),
    CONSTRAINT UQ_RL_MR_FUA_POS UNIQUE (FUA_FUNCION_VERSION_ID,FUA_POSICION),
    CONSTRAINT UQ_RL_MR_FUA_COD UNIQUE (FUA_FUNCION_VERSION_ID,FUA_CODIGO),
    CONSTRAINT CK_RL_MR_FUA_POS CHECK (FUA_POSICION >= 1),
    CONSTRAINT CK_RL_MR_FUA_TYPE CHECK (FUA_TIPO IN ('INTEGER','DECIMAL','BOOLEAN','TEXT','DATE')),
    CONSTRAINT CK_RL_MR_FUA_REQ CHECK (FUA_REQUERIDO IN (0,1)),
    CONSTRAINT CK_RL_MR_FUA_VAR CHECK (FUA_VARIADIC IN (0,1))
  )]');
  create_table_if_absent('RL_MR_PARAMETROS_CALCULO', q'[CREATE TABLE RL_MR_PARAMETROS_CALCULO (
    PAC_ID NUMBER(15) NOT NULL,
    PAC_CODIGO VARCHAR2(80 CHAR) NOT NULL,
    PAC_NOMBRE VARCHAR2(150 CHAR) NOT NULL,
    PAC_DESCRIPCION VARCHAR2(1000 CHAR),
    PAC_TIPO VARCHAR2(20 CHAR) NOT NULL,
    PAC_ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    PAC_METADATA_JSON CLOB,
    PAC_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    PAC_USR_CREACION NUMBER(10) NOT NULL,
    PAC_VERSION_ROW NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_PAC PRIMARY KEY (PAC_ID),
    CONSTRAINT UQ_RL_MR_PAC_COD UNIQUE (PAC_CODIGO),
    CONSTRAINT CK_RL_MR_PAC_TYPE CHECK (PAC_TIPO IN ('INTEGER','DECIMAL','BOOLEAN','TEXT','DATE')),
    CONSTRAINT CK_RL_MR_PAC_EST CHECK (PAC_ESTADO IN ('ACTIVE','INACTIVE','RETIRED')),
    CONSTRAINT CK_RL_MR_PAC_ROW CHECK (PAC_VERSION_ROW >= 1),
    CONSTRAINT FK_RL_MR_PAC_USR FOREIGN KEY (PAC_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID)
  )]');
  create_table_if_absent('RL_MR_PARAMETRO_VERSIONES', q'[CREATE TABLE RL_MR_PARAMETRO_VERSIONES (
    PAV_ID NUMBER(15) NOT NULL,
    PAV_PARAMETRO_ID NUMBER(15) NOT NULL,
    PAV_VERSION NUMBER(5) NOT NULL,
    PAV_TIPO VARCHAR2(20 CHAR) NOT NULL,
    PAV_VALOR_ENTERO NUMBER(15),
    PAV_VALOR_DECIMAL NUMBER(28,10),
    PAV_VALOR_BOOLEANO NUMBER(1),
    PAV_VALOR_TEXTO VARCHAR2(2000 CHAR),
    PAV_VALOR_FECHA DATE,
    PAV_ESTADO VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    PAV_HASH VARCHAR2(64 CHAR) NOT NULL,
    PAV_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    PAV_USR_CREACION NUMBER(10) NOT NULL,
    PAV_VERSION_ROW NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RL_MR_PAV PRIMARY KEY (PAV_ID),
    CONSTRAINT FK_RL_MR_PAV_PAC FOREIGN KEY (PAV_PARAMETRO_ID) REFERENCES RL_MR_PARAMETROS_CALCULO(PAC_ID),
    CONSTRAINT FK_RL_MR_PAV_USR FOREIGN KEY (PAV_USR_CREACION) REFERENCES RL_USUARIOS(USR_ID),
    CONSTRAINT UQ_RL_MR_PAV_VER UNIQUE (PAV_PARAMETRO_ID,PAV_VERSION),
    CONSTRAINT CK_RL_MR_PAV_VER CHECK (PAV_VERSION >= 1),
    CONSTRAINT CK_RL_MR_PAV_TYPE CHECK (PAV_TIPO IN ('INTEGER','DECIMAL','BOOLEAN','TEXT','DATE')),
    CONSTRAINT CK_RL_MR_PAV_VALUE CHECK (((PAV_TIPO='INTEGER' AND PAV_VALOR_ENTERO IS NOT NULL AND PAV_VALOR_DECIMAL IS NULL AND PAV_VALOR_BOOLEANO IS NULL AND PAV_VALOR_TEXTO IS NULL AND PAV_VALOR_FECHA IS NULL) OR (PAV_TIPO='DECIMAL' AND PAV_VALOR_ENTERO IS NULL AND PAV_VALOR_DECIMAL IS NOT NULL AND PAV_VALOR_BOOLEANO IS NULL AND PAV_VALOR_TEXTO IS NULL AND PAV_VALOR_FECHA IS NULL) OR (PAV_TIPO='BOOLEAN' AND PAV_VALOR_ENTERO IS NULL AND PAV_VALOR_DECIMAL IS NULL AND PAV_VALOR_BOOLEANO IN (0,1) AND PAV_VALOR_TEXTO IS NULL AND PAV_VALOR_FECHA IS NULL) OR (PAV_TIPO='TEXT' AND PAV_VALOR_ENTERO IS NULL AND PAV_VALOR_DECIMAL IS NULL AND PAV_VALOR_BOOLEANO IS NULL AND PAV_VALOR_TEXTO IS NOT NULL AND PAV_VALOR_FECHA IS NULL) OR (PAV_TIPO='DATE' AND PAV_VALOR_ENTERO IS NULL AND PAV_VALOR_DECIMAL IS NULL AND PAV_VALOR_BOOLEANO IS NULL AND PAV_VALOR_TEXTO IS NULL AND PAV_VALOR_FECHA IS NOT NULL))),
    CONSTRAINT CK_RL_MR_PAV_EST CHECK (PAV_ESTADO IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')),
    CONSTRAINT CK_RL_MR_PAV_HASH CHECK (REGEXP_LIKE(PAV_HASH,'^[0-9A-Fa-f]{64}$')),
    CONSTRAINT CK_RL_MR_PAV_ROW CHECK (PAV_VERSION_ROW >= 1)
  )]');

  create_sequence_if_absent('SEQ_RL_MR_FORMULAS', 'CREATE SEQUENCE SEQ_RL_MR_FORMULAS START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_sequence_if_absent('SEQ_RL_MR_FORMULA_VERSIONES', 'CREATE SEQUENCE SEQ_RL_MR_FORMULA_VERSIONES START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_sequence_if_absent('SEQ_RL_MR_FORMULA_USOS', 'CREATE SEQUENCE SEQ_RL_MR_FORMULA_USOS START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_sequence_if_absent('SEQ_RL_MR_FUNCIONES', 'CREATE SEQUENCE SEQ_RL_MR_FUNCIONES START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_sequence_if_absent('SEQ_RL_MR_FUNCION_VERSIONES', 'CREATE SEQUENCE SEQ_RL_MR_FUNCION_VERSIONES START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_sequence_if_absent('SEQ_RL_MR_FUNCION_ARGUMENTOS', 'CREATE SEQUENCE SEQ_RL_MR_FUNCION_ARGUMENTOS START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_sequence_if_absent('SEQ_RL_MR_PARAMETROS', 'CREATE SEQUENCE SEQ_RL_MR_PARAMETROS START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_sequence_if_absent('SEQ_RL_MR_PARAMETRO_VERSIONES', 'CREATE SEQUENCE SEQ_RL_MR_PARAMETRO_VERSIONES START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20');
  create_index_if_absent('IDX_RL_MR_FOV_FOR', 'CREATE INDEX IDX_RL_MR_FOV_FOR ON RL_MR_FORMULA_VERSIONES(FOV_FORMULA_ID)');
  create_index_if_absent('IDX_RL_MR_FUS_VERF', 'CREATE INDEX IDX_RL_MR_FUS_VERF ON RL_MR_FORMULA_USOS(FUS_VERSION_FORMULARIO_ID)');
  create_index_if_absent('IDX_RL_MR_FUS_FOV', 'CREATE INDEX IDX_RL_MR_FUS_FOV ON RL_MR_FORMULA_USOS(FUS_FORMULA_VERSION_ID)');
  create_index_if_absent('IDX_RL_MR_FUV_FUN', 'CREATE INDEX IDX_RL_MR_FUV_FUN ON RL_MR_FUNCION_VERSIONES(FUV_FUNCION_ID)');
  create_index_if_absent('IDX_RL_MR_FUA_FUV', 'CREATE INDEX IDX_RL_MR_FUA_FUV ON RL_MR_FUNCION_ARGUMENTOS(FUA_FUNCION_VERSION_ID)');
  create_index_if_absent('IDX_RL_MR_PAV_PAC', 'CREATE INDEX IDX_RL_MR_PAV_PAC ON RL_MR_PARAMETRO_VERSIONES(PAV_PARAMETRO_ID)');
END;
/

PROMPT DDL_CONFIGURACION_CALCULO_312_APPLIED
EXIT SUCCESS
