-- FASE 3.1.2 - POSTCHECK READ-ONLY. No contiene DDL ni DML.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF
SET VERIFY OFF
SET TERMOUT ON
SET SERVEROUTPUT ON

PROMPT POSTCHECK_CONFIGURACION_CALCULO_312
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN (
   'RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
   'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
   'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES',
   'SEQ_RL_MR_FORMULAS','SEQ_RL_MR_FORMULA_VERSIONES','SEQ_RL_MR_FORMULA_USOS',
   'SEQ_RL_MR_FUNCIONES','SEQ_RL_MR_FUNCION_VERSIONES','SEQ_RL_MR_FUNCION_ARGUMENTOS',
   'SEQ_RL_MR_PARAMETROS','SEQ_RL_MR_PARAMETRO_VERSIONES'
 )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT METRICAS_NUEVAS
SELECT 'RL_MR_FORMULAS' AS OBJETO, COUNT(*) AS FILAS FROM RL_MR_FORMULAS
UNION ALL SELECT 'RL_MR_FORMULA_VERSIONES', COUNT(*) FROM RL_MR_FORMULA_VERSIONES
UNION ALL SELECT 'RL_MR_FORMULA_USOS', COUNT(*) FROM RL_MR_FORMULA_USOS
UNION ALL SELECT 'RL_MR_FUNCIONES', COUNT(*) FROM RL_MR_FUNCIONES
UNION ALL SELECT 'RL_MR_FUNCION_VERSIONES', COUNT(*) FROM RL_MR_FUNCION_VERSIONES
UNION ALL SELECT 'RL_MR_FUNCION_ARGUMENTOS', COUNT(*) FROM RL_MR_FUNCION_ARGUMENTOS
UNION ALL SELECT 'RL_MR_PARAMETROS_CALCULO', COUNT(*) FROM RL_MR_PARAMETROS_CALCULO
UNION ALL SELECT 'RL_MR_PARAMETRO_VERSIONES', COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES;

SELECT 'SEED_NATIVE_COUNT' AS METRICA, COUNT(*) AS VALOR
  FROM RL_MR_FUNCIONES f JOIN RL_MR_FUNCION_VERSIONES v ON v.FUV_FUNCION_ID=f.FUN_ID
 WHERE f.FUN_CODIGO IN ('IF','IFERROR','ROUND','ROUNDDOWN','MAX','MOD','OR')
   AND v.FUV_VERSION=1 AND v.FUV_TIPO='NATIVE';

PROMPT INTEGRIDAD_REFERENCIAL
SELECT 'ORPHAN_FORMULA_VERSIONS' AS METRICA, COUNT(*) AS VALOR FROM RL_MR_FORMULA_VERSIONES v LEFT JOIN RL_MR_FORMULAS f ON f.FOR_ID=v.FOV_FORMULA_ID WHERE f.FOR_ID IS NULL
UNION ALL SELECT 'ORPHAN_FORMULA_USAGES', COUNT(*) FROM RL_MR_FORMULA_USOS u LEFT JOIN RL_MR_FORMULA_VERSIONES v ON v.FOV_ID=u.FUS_FORMULA_VERSION_ID LEFT JOIN RL_MR_VERSIONES_FORMULARIO fv ON fv.VER_ID=u.FUS_VERSION_FORMULARIO_ID WHERE v.FOV_ID IS NULL OR fv.VER_ID IS NULL
UNION ALL SELECT 'ORPHAN_FUNCTION_VERSIONS', COUNT(*) FROM RL_MR_FUNCION_VERSIONES v LEFT JOIN RL_MR_FUNCIONES f ON f.FUN_ID=v.FUV_FUNCION_ID WHERE f.FUN_ID IS NULL
UNION ALL SELECT 'ORPHAN_FUNCTION_ARGUMENTS', COUNT(*) FROM RL_MR_FUNCION_ARGUMENTOS a LEFT JOIN RL_MR_FUNCION_VERSIONES v ON v.FUV_ID=a.FUA_FUNCION_VERSION_ID WHERE v.FUV_ID IS NULL
UNION ALL SELECT 'ORPHAN_PARAMETER_VERSIONS', COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES v LEFT JOIN RL_MR_PARAMETROS_CALCULO p ON p.PAC_ID=v.PAV_PARAMETRO_ID WHERE p.PAC_ID IS NULL;

PROMPT DUPLICADOS_Y_CONTRATOS
SELECT 'DUPLICATE_FORMULA_CODES' AS METRICA, NVL(SUM(CASE WHEN C > 1 THEN 1 ELSE 0 END),0) AS VALOR FROM (SELECT FOR_CODIGO,COUNT(*) C FROM RL_MR_FORMULAS GROUP BY FOR_CODIGO)
UNION ALL SELECT 'DUPLICATE_FUNCTION_CODES', NVL(SUM(CASE WHEN C > 1 THEN 1 ELSE 0 END),0) FROM (SELECT FUN_CODIGO,COUNT(*) C FROM RL_MR_FUNCIONES GROUP BY FUN_CODIGO)
UNION ALL SELECT 'DUPLICATE_PARAMETER_CODES', NVL(SUM(CASE WHEN C > 1 THEN 1 ELSE 0 END),0) FROM (SELECT PAC_CODIGO,COUNT(*) C FROM RL_MR_PARAMETROS_CALCULO GROUP BY PAC_CODIGO)
UNION ALL SELECT 'DUPLICATE_FORMULA_VERSIONS', NVL(SUM(CASE WHEN C > 1 THEN 1 ELSE 0 END),0) FROM (SELECT FOV_FORMULA_ID,FOV_VERSION,COUNT(*) C FROM RL_MR_FORMULA_VERSIONES GROUP BY FOV_FORMULA_ID,FOV_VERSION)
UNION ALL SELECT 'DUPLICATE_FUNCTION_VERSIONS', NVL(SUM(CASE WHEN C > 1 THEN 1 ELSE 0 END),0) FROM (SELECT FUV_FUNCION_ID,FUV_VERSION,COUNT(*) C FROM RL_MR_FUNCION_VERSIONES GROUP BY FUV_FUNCION_ID,FUV_VERSION)
UNION ALL SELECT 'DUPLICATE_PARAMETER_VERSIONS', NVL(SUM(CASE WHEN C > 1 THEN 1 ELSE 0 END),0) FROM (SELECT PAV_PARAMETRO_ID,PAV_VERSION,COUNT(*) C FROM RL_MR_PARAMETRO_VERSIONES GROUP BY PAV_PARAMETRO_ID,PAV_VERSION)
UNION ALL SELECT 'INVALID_NATIVE_COMPOSITE_CONTRACTS', COUNT(*) FROM RL_MR_FUNCION_VERSIONES WHERE (FUV_TIPO='NATIVE' AND (FUV_HANDLER_KEY IS NULL OR FUV_DEFINICION_DSL IS NOT NULL)) OR (FUV_TIPO='COMPOSITE' AND (FUV_HANDLER_KEY IS NOT NULL OR FUV_DEFINICION_DSL IS NULL))
UNION ALL SELECT 'INVALID_HASH_FORMATS', COUNT(*) FROM RL_MR_FORMULA_VERSIONES WHERE NOT REGEXP_LIKE(FOV_HASH,'^[0-9A-Fa-f]{64}$')
UNION ALL SELECT 'INVALID_HASH_FORMATS', COUNT(*) FROM RL_MR_FUNCION_VERSIONES WHERE NOT REGEXP_LIKE(FUV_HASH,'^[0-9A-Fa-f]{64}$')
UNION ALL SELECT 'INVALID_HASH_FORMATS', COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES WHERE NOT REGEXP_LIKE(PAV_HASH,'^[0-9A-Fa-f]{64}$');

PROMPT ESTADOS_Y_VERSIONES
SELECT 'INVALID_STATUS_VALUES' AS METRICA,
       (SELECT COUNT(*) FROM RL_MR_FORMULAS WHERE FOR_ESTADO NOT IN ('ACTIVE','INACTIVE','RETIRED')) +
       (SELECT COUNT(*) FROM RL_MR_FUNCIONES WHERE FUN_ESTADO NOT IN ('ACTIVE','INACTIVE','RETIRED')) +
       (SELECT COUNT(*) FROM RL_MR_PARAMETROS_CALCULO WHERE PAC_ESTADO NOT IN ('ACTIVE','INACTIVE','RETIRED')) +
       (SELECT COUNT(*) FROM RL_MR_FORMULA_VERSIONES WHERE FOV_ESTADO NOT IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')) +
       (SELECT COUNT(*) FROM RL_MR_FUNCION_VERSIONES WHERE FUV_ESTADO NOT IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')) +
       (SELECT COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES WHERE PAV_ESTADO NOT IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')) AS VALOR
  FROM DUAL;
SELECT 'INVALID_VERSION_VALUES' AS METRICA,
       (SELECT COUNT(*) FROM RL_MR_FORMULA_VERSIONES WHERE FOV_VERSION < 1 OR FOV_VERSION IS NULL) +
       (SELECT COUNT(*) FROM RL_MR_FUNCION_VERSIONES WHERE FUV_VERSION < 1 OR FUV_VERSION IS NULL) +
       (SELECT COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES WHERE PAV_VERSION < 1 OR PAV_VERSION IS NULL) AS VALOR
  FROM DUAL;
SELECT 'DISABLED_CONSTRAINTS' AS METRICA, COUNT(*) AS VALOR
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS','RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS','RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES')
   AND STATUS <> 'ENABLED';

PROMPT HISTORICO_POSTCHECK_SIN_CLOB
SELECT COUNT(*) AS VERSIONES_FORMULARIO,
       COUNT(VER_HASH) AS VERSIONES_CON_HASH,
       COUNT(DISTINCT VER_HASH) AS HASHES_DISTINTOS
  FROM RL_MR_VERSIONES_FORMULARIO;
SELECT COUNT(*) AS EVALUACIONES,
       COUNT(EVA_VERSION_ID) AS EVALUACIONES_CON_VERSION,
       COUNT(EVA_CALCULOS_JSON) AS EVALUACIONES_CON_RESULTADO
  FROM RL_MR_EVALUACIONES_RIESGO;
SELECT VER_ID, VER_HASH, VER_ESTADO, VER_VIGENTE
  FROM RL_MR_VERSIONES_FORMULARIO
 WHERE VER_ID IN (24, 53, 27, 28)
 ORDER BY VER_ID;
PROMPT Los cuatro valores anteriores se comparan con la salida del precheck; no se leen ni reescriben CLOB.

DECLARE
  v_tables NUMBER;
  v_sequences NUMBER;
  v_invalid NUMBER;
  v_disabled NUMBER;
  v_orphans NUMBER;
  v_duplicates NUMBER;
  v_contracts NUMBER;
  v_hashes NUMBER;
  v_status NUMBER;
  v_versions NUMBER;
  v_evaluations NUMBER;
  v_seed NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_tables FROM USER_TABLES WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS','RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS','RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES');
  SELECT COUNT(*) INTO v_sequences FROM USER_SEQUENCES WHERE SEQUENCE_NAME IN ('SEQ_RL_MR_FORMULAS','SEQ_RL_MR_FORMULA_VERSIONES','SEQ_RL_MR_FORMULA_USOS','SEQ_RL_MR_FUNCIONES','SEQ_RL_MR_FUNCION_VERSIONES','SEQ_RL_MR_FUNCION_ARGUMENTOS','SEQ_RL_MR_PARAMETROS','SEQ_RL_MR_PARAMETRO_VERSIONES');
  SELECT COUNT(*) INTO v_invalid FROM USER_OBJECTS WHERE STATUS <> 'VALID' AND OBJECT_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS','RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS','RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES');
  SELECT COUNT(*) INTO v_disabled FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS','RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS','RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES') AND STATUS <> 'ENABLED';
  SELECT (SELECT COUNT(*) FROM RL_MR_FORMULA_VERSIONES v LEFT JOIN RL_MR_FORMULAS f ON f.FOR_ID=v.FOV_FORMULA_ID WHERE f.FOR_ID IS NULL) +
         (SELECT COUNT(*) FROM RL_MR_FORMULA_USOS u LEFT JOIN RL_MR_FORMULA_VERSIONES v ON v.FOV_ID=u.FUS_FORMULA_VERSION_ID LEFT JOIN RL_MR_VERSIONES_FORMULARIO fv ON fv.VER_ID=u.FUS_VERSION_FORMULARIO_ID WHERE v.FOV_ID IS NULL OR fv.VER_ID IS NULL) +
         (SELECT COUNT(*) FROM RL_MR_FUNCION_VERSIONES v LEFT JOIN RL_MR_FUNCIONES f ON f.FUN_ID=v.FUV_FUNCION_ID WHERE f.FUN_ID IS NULL) +
         (SELECT COUNT(*) FROM RL_MR_FUNCION_ARGUMENTOS a LEFT JOIN RL_MR_FUNCION_VERSIONES v ON v.FUV_ID=a.FUA_FUNCION_VERSION_ID WHERE v.FUV_ID IS NULL) +
         (SELECT COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES v LEFT JOIN RL_MR_PARAMETROS_CALCULO p ON p.PAC_ID=v.PAV_PARAMETRO_ID WHERE p.PAC_ID IS NULL)
    INTO v_orphans FROM DUAL;
  SELECT COUNT(*) INTO v_duplicates FROM (SELECT FOR_CODIGO FROM RL_MR_FORMULAS GROUP BY FOR_CODIGO HAVING COUNT(*)>1 UNION ALL SELECT FUN_CODIGO FROM RL_MR_FUNCIONES GROUP BY FUN_CODIGO HAVING COUNT(*)>1 UNION ALL SELECT PAC_CODIGO FROM RL_MR_PARAMETROS_CALCULO GROUP BY PAC_CODIGO HAVING COUNT(*)>1);
  SELECT COUNT(*) INTO v_contracts FROM RL_MR_FUNCION_VERSIONES WHERE (FUV_TIPO='NATIVE' AND (FUV_HANDLER_KEY IS NULL OR FUV_DEFINICION_DSL IS NOT NULL)) OR (FUV_TIPO='COMPOSITE' AND (FUV_HANDLER_KEY IS NOT NULL OR FUV_DEFINICION_DSL IS NULL));
  SELECT (SELECT COUNT(*) FROM RL_MR_FORMULA_VERSIONES WHERE NOT REGEXP_LIKE(FOV_HASH,'^[0-9A-Fa-f]{64}$')) +
         (SELECT COUNT(*) FROM RL_MR_FUNCION_VERSIONES WHERE NOT REGEXP_LIKE(FUV_HASH,'^[0-9A-Fa-f]{64}$')) +
         (SELECT COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES WHERE NOT REGEXP_LIKE(PAV_HASH,'^[0-9A-Fa-f]{64}$'))
    INTO v_hashes FROM DUAL;
  SELECT (SELECT COUNT(*) FROM RL_MR_FORMULAS WHERE FOR_ESTADO NOT IN ('ACTIVE','INACTIVE','RETIRED')) +
         (SELECT COUNT(*) FROM RL_MR_FUNCIONES WHERE FUN_ESTADO NOT IN ('ACTIVE','INACTIVE','RETIRED')) +
         (SELECT COUNT(*) FROM RL_MR_PARAMETROS_CALCULO WHERE PAC_ESTADO NOT IN ('ACTIVE','INACTIVE','RETIRED')) +
         (SELECT COUNT(*) FROM RL_MR_FORMULA_VERSIONES WHERE FOV_ESTADO NOT IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')) +
         (SELECT COUNT(*) FROM RL_MR_FUNCION_VERSIONES WHERE FUV_ESTADO NOT IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED')) +
         (SELECT COUNT(*) FROM RL_MR_PARAMETRO_VERSIONES WHERE PAV_ESTADO NOT IN ('DRAFT','IN_REVIEW','APPROVED','PUBLISHED','RETIRED','ARCHIVED'))
    INTO v_status FROM DUAL;
  SELECT COUNT(*) INTO v_versions FROM RL_MR_VERSIONES_FORMULARIO;
  SELECT COUNT(*) INTO v_evaluations FROM RL_MR_EVALUACIONES_RIESGO;
  SELECT COUNT(*) INTO v_seed FROM (SELECT f.FUN_CODIGO FROM RL_MR_FUNCIONES f JOIN RL_MR_FUNCION_VERSIONES v ON v.FUV_FUNCION_ID=f.FUN_ID WHERE f.FUN_CODIGO IN ('IF','IFERROR','ROUND','ROUNDDOWN','MAX','MOD','OR') AND v.FUV_VERSION=1 AND v.FUV_TIPO='NATIVE' GROUP BY f.FUN_CODIGO);
  IF v_tables <> 8 OR v_sequences <> 8 OR v_invalid <> 0 OR v_disabled <> 0 OR v_orphans <> 0 OR v_duplicates <> 0 OR v_contracts <> 0 OR v_hashes <> 0 OR v_status <> 0 OR v_versions <> 24 OR v_evaluations <> 14 OR v_seed <> 7 THEN
    RAISE_APPLICATION_ERROR(-20921, 'ORACLE_POSTCHECK=FAIL');
  END IF;
  DBMS_OUTPUT.PUT_LINE('NEW_TABLES_EXPECTED=PASS');
  DBMS_OUTPUT.PUT_LINE('NEW_SEQUENCES_EXPECTED=PASS');
  DBMS_OUTPUT.PUT_LINE('INVALID_OBJECTS=0');
  DBMS_OUTPUT.PUT_LINE('DISABLED_CONSTRAINTS=0');
  DBMS_OUTPUT.PUT_LINE('ORPHANS=0');
  DBMS_OUTPUT.PUT_LINE('DUPLICATES=0');
  DBMS_OUTPUT.PUT_LINE('INVALID_NATIVE_COMPOSITE_CONTRACTS=0');
  DBMS_OUTPUT.PUT_LINE('INVALID_HASH_FORMATS=0');
  DBMS_OUTPUT.PUT_LINE('INVALID_STATUS_VALUES=0');
  DBMS_OUTPUT.PUT_LINE('INVALID_VERSION_VALUES=0');
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_INTEGRITY=PASS');
  DBMS_OUTPUT.PUT_LINE('ORACLE_POSTCHECK=PASS');
END;
/
EXIT SUCCESS
