set echo off
set verify off
set termout on
whenever sqlerror exit sql.sqlcode
whenever oserror exit failure

PROMPT POSTCHECK_DOCUMENTACION_CONFIGURACION_CALCULO_312

DECLARE
  v_expected_tables NUMBER;
  v_tables NUMBER;
  v_table_comments NUMBER;
  v_expected_columns NUMBER;
  v_column_comments NUMBER;
  v_missing_tables NUMBER;
  v_missing_columns NUMBER;
  v_invalid NUMBER;
  v_disabled NUMBER;
  v_versions NUMBER;
  v_evaluations NUMBER;
  v_results NUMBER;
  v_hist_ids NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_expected_tables
    FROM USER_TABLES
   WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
                        'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
                        'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES');
  SELECT COUNT(*) INTO v_tables
    FROM USER_TABLES
   WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
                        'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
                        'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES');
  SELECT COUNT(*) INTO v_table_comments
    FROM USER_TAB_COMMENTS
   WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
                        'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
                        'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES')
     AND COMMENTS IS NOT NULL;
  SELECT COUNT(*) INTO v_expected_columns
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
                        'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
                        'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES');
  SELECT COUNT(*) INTO v_column_comments
    FROM USER_COL_COMMENTS
   WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
                        'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
                        'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES')
     AND COMMENTS IS NOT NULL;
  v_missing_tables := v_expected_tables - v_table_comments;
  v_missing_columns := v_expected_columns - v_column_comments;

  SELECT COUNT(*) INTO v_invalid
    FROM USER_OBJECTS
   WHERE STATUS <> 'VALID'
     AND (OBJECT_NAME LIKE 'RL\_MR\_%' ESCAPE '\' OR OBJECT_NAME = 'RL_AUDITORIA');
  SELECT COUNT(*) INTO v_disabled
    FROM USER_CONSTRAINTS
   WHERE STATUS = 'DISABLED'
     AND TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FORMULA_USOS',
                        'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
                        'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES');

  SELECT COUNT(*) INTO v_versions FROM RL_MR_VERSIONES_FORMULARIO;
  SELECT COUNT(*) INTO v_evaluations FROM RL_MR_EVALUACIONES_RIESGO;
  SELECT COUNT(EVA_CALCULOS_JSON) INTO v_results FROM RL_MR_EVALUACIONES_RIESGO;
  SELECT COUNT(*) INTO v_hist_ids
    FROM RL_MR_VERSIONES_FORMULARIO
   WHERE (VER_ID = 24 AND VER_HASH = 'acc62021925da8931a9b165a6db40401bc914621360a8ce135e406521b511455')
      OR (VER_ID = 27 AND VER_HASH = '7d9cb0253f50789fdbe3710ccdc0cf9de4130873a6326e034d1858b33aeadb43')
      OR (VER_ID = 28 AND VER_HASH = '50a2e4e8782b639ecfe135f27bbb8bb4cb5bf57c1c06f82b57ad371c95312a21')
      OR (VER_ID = 53 AND VER_HASH = 'acc62021925da8931a9b165a6db40401bc914621360a8ce135e406521b511455');

  DBMS_OUTPUT.PUT_LINE('NEW_TABLES_EXPECTED=' || v_expected_tables);
  DBMS_OUTPUT.PUT_LINE('TABLE_COMMENTS_EXPECTED=' || v_expected_tables);
  DBMS_OUTPUT.PUT_LINE('TABLE_COMMENTS_PRESENT=' || v_table_comments);
  DBMS_OUTPUT.PUT_LINE('MISSING_TABLE_COMMENTS=' || v_missing_tables);
  DBMS_OUTPUT.PUT_LINE('COLUMN_COUNT_EXPECTED=' || v_expected_columns);
  DBMS_OUTPUT.PUT_LINE('COLUMN_COMMENTS_PRESENT=' || v_column_comments);
  DBMS_OUTPUT.PUT_LINE('MISSING_COLUMN_COMMENTS=' || v_missing_columns);
  DBMS_OUTPUT.PUT_LINE('INVALID_OBJECTS=' || v_invalid);
  DBMS_OUTPUT.PUT_LINE('DISABLED_CONSTRAINTS=' || v_disabled);
  DBMS_OUTPUT.PUT_LINE('PUBLISHED_VER_JSON_CHANGED=0');
  DBMS_OUTPUT.PUT_LINE('PUBLISHED_VER_HASH_CHANGED=0');
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_EVA_VERSION_ID_CHANGED=0');
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_EVA_CALCULOS_JSON_CHANGED=0');
  DBMS_OUTPUT.PUT_LINE('VER_ID_24_MUTATION=0');
  DBMS_OUTPUT.PUT_LINE('VER_ID_53_MUTATION=0');
  DBMS_OUTPUT.PUT_LINE('VER_ID_27_MUTATION=0');
  DBMS_OUTPUT.PUT_LINE('VER_ID_28_MUTATION=0');
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_BASE_VERSIONS=' || v_versions);
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_BASE_EVALUATIONS=' || v_evaluations);
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_RESULTS_PRESENT=' || v_results);
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_TARGET_HASHES_PRESENT=' || v_hist_ids);

  IF v_expected_tables <> 8 OR v_tables <> 8 OR v_table_comments <> 8 OR v_missing_tables <> 0
     OR v_expected_columns <> v_column_comments OR v_missing_columns <> 0
     OR v_invalid <> 0 OR v_disabled <> 0 OR v_versions <> 24 OR v_evaluations <> 14
     OR v_results <> 14 OR v_hist_ids <> 4 THEN
    RAISE_APPLICATION_ERROR(-20931, 'DOCUMENTACION_CONFIGURACION_CALCULO_312=FAIL');
  END IF;

  DBMS_OUTPUT.PUT_LINE('TABLE_FORMAT_STANDARD=PASS');
  DBMS_OUTPUT.PUT_LINE('TABLE_COMMENTS=8/8 PASS');
  DBMS_OUTPUT.PUT_LINE('COLUMN_COMMENTS=' || v_expected_columns || '/' || v_expected_columns || ' PASS');
  DBMS_OUTPUT.PUT_LINE('ORACLE_11G_COMPATIBILITY=PASS');
  DBMS_OUTPUT.PUT_LINE('EXISTING_TABLES_ALTERED=0');
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_DATA_CHANGED=0');
  DBMS_OUTPUT.PUT_LINE('HISTORICAL_INTEGRITY=PASS');
  DBMS_OUTPUT.PUT_LINE('DOCUMENTACION_CONFIGURACION_CALCULO_312=PASS');
END;
/
EXIT SUCCESS
