-- FASE 3.1.5 - precheck read-only de la carga institucional.
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF
SET VERIFY OFF
SET TERMOUT ON
SET LONG 4000
SET SERVEROUTPUT ON

SELECT 'EXPECTED_FORMULAS' AS METRICA, 34 AS VALOR FROM DUAL
UNION ALL SELECT 'EXPECTED_NATIVE_FUNCTIONS', 10 FROM DUAL
UNION ALL SELECT 'EXPECTED_WEIGHT_PARAMETERS', 3 FROM DUAL;

SELECT 'REQUIRED_TABLES' AS METRICA, COUNT(*) AS VALOR
FROM USER_TABLES
WHERE TABLE_NAME IN (
  'RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FUNCIONES',
  'RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
  'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES',
  'RL_MR_CATALOGOS','RL_MR_ELEMENTOS_CATALOGO'
);

SELECT 'REQUIRED_SEQUENCES' AS METRICA, COUNT(*) AS VALOR
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
  'SEQ_RL_MR_FORMULAS','SEQ_RL_MR_FORMULA_VERSIONES','SEQ_RL_MR_FUNCIONES',
  'SEQ_RL_MR_FUNCION_VERSIONES','SEQ_RL_MR_FUNCION_ARGUMENTOS',
  'SEQ_RL_MR_PARAMETROS','SEQ_RL_MR_PARAMETRO_VERSIONES'
);

SELECT CONSTRAINT_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'RL_MR_FUNCION_ARGUMENTOS'
  AND CONSTRAINT_NAME = 'CK_RL_MR_FUA_TYPE';

SELECT 'TECHNICAL_USER_COUNT' AS METRICA, COUNT(*) AS VALOR FROM RL_USUARIOS;

SELECT 'EXISTING_INSTITUTIONAL_FORMULAS' AS METRICA, COUNT(*) AS VALOR
FROM RL_MR_FORMULAS
WHERE REGEXP_LIKE(FOR_CODIGO, '^F(0[1-9]|[12][0-9]|3[0-4])_');

SELECT 'EXISTING_WEIGHT_PARAMETERS' AS METRICA, COUNT(*) AS VALOR
FROM RL_MR_PARAMETROS_CALCULO
WHERE PAC_CODIGO IN ('PESO_PREVENTIVO','PESO_DETECTIVO','PESO_CORRECTIVO');

SELECT 'EXISTING_NATIVE_FUNCTIONS' AS METRICA, COUNT(*) AS VALOR
FROM RL_MR_FUNCIONES
WHERE FUN_CODIGO IN ('IF','IFERROR','ROUND','ROUNDDOWN','MAX','MIN','MOD','OR','AND','LOOKUP');

SELECT 'INVALID_OBJECTS' AS METRICA, COUNT(*) AS VALOR
FROM USER_OBJECTS
WHERE STATUS <> 'VALID'
  AND OBJECT_NAME IN (
    'RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FUNCIONES',
    'RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
    'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES'
  );

SELECT 'DISABLED_CONSTRAINTS' AS METRICA, COUNT(*) AS VALOR
FROM USER_CONSTRAINTS
WHERE STATUS <> 'ENABLED'
  AND TABLE_NAME IN (
    'RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FUNCIONES',
    'RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
    'RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES'
  );

DECLARE
  v_tables NUMBER;
  v_sequences NUMBER;
  v_users NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_tables FROM USER_TABLES
   WHERE TABLE_NAME IN ('RL_MR_FORMULAS','RL_MR_FORMULA_VERSIONES','RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_FUNCION_ARGUMENTOS','RL_MR_PARAMETROS_CALCULO','RL_MR_PARAMETRO_VERSIONES','RL_MR_CATALOGOS','RL_MR_ELEMENTOS_CATALOGO');
  SELECT COUNT(*) INTO v_sequences FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME IN ('SEQ_RL_MR_FORMULAS','SEQ_RL_MR_FORMULA_VERSIONES','SEQ_RL_MR_FUNCIONES','SEQ_RL_MR_FUNCION_VERSIONES','SEQ_RL_MR_FUNCION_ARGUMENTOS','SEQ_RL_MR_PARAMETROS','SEQ_RL_MR_PARAMETRO_VERSIONES');
  SELECT COUNT(*) INTO v_users FROM RL_USUARIOS;
  IF v_tables <> 9 THEN RAISE_APPLICATION_ERROR(-20951, 'Faltan tablas requeridas para la carga institucional.'); END IF;
  IF v_sequences <> 7 THEN RAISE_APPLICATION_ERROR(-20952, 'Faltan secuencias requeridas para la carga institucional.'); END IF;
  IF v_users = 0 THEN RAISE_APPLICATION_ERROR(-20953, 'No existe usuario técnico para la carga institucional.'); END IF;
END;
/

PROMPT PRECHECK_FORMULA_INSTITUCIONAL_315_PASS
EXIT SUCCESS
