-- FASE 3.1.5 - habilita el tipo contractual VALUE requerido por LOOKUP.
-- No crea tablas ni modifica datos; solo armoniza la restricción de argumentos
-- con el contrato seguro del runtime ya implementado.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF
SET VERIFY OFF
SET TERMOUT ON
SET SERVEROUTPUT ON

DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'RL_MR_FUNCION_ARGUMENTOS'
    AND CONSTRAINT_NAME = 'CK_RL_MR_FUA_TYPE';

  IF v_exists = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RL_MR_FUNCION_ARGUMENTOS DROP CONSTRAINT CK_RL_MR_FUA_TYPE';
  END IF;

  EXECUTE IMMEDIATE q'[ALTER TABLE RL_MR_FUNCION_ARGUMENTOS ADD CONSTRAINT CK_RL_MR_FUA_TYPE CHECK (FUA_TIPO IN ('VALUE','INTEGER','DECIMAL','BOOLEAN','TEXT','DATE'))]';
  DBMS_OUTPUT.PUT_LINE('FUA_VALUE_CONTRACT=ENABLED');
END;
/

PROMPT DDL_ARGUMENTO_VALUE_315_APPLIED
EXIT SUCCESS
