-- FP.1 - Core estructural de familia de formulario predeterminada.
-- Ejecucion manual autorizada: no se incluye en maestros automaticos.
-- El cambio es aditivo y no asigna ninguna familia como predeterminada.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF
SET VERIFY OFF
SET TERMOUT ON
SET SERVEROUTPUT ON

DECLARE
  v_exists NUMBER;
  v_data_type USER_TAB_COLUMNS.DATA_TYPE%TYPE;
  v_precision USER_TAB_COLUMNS.DATA_PRECISION%TYPE;
  v_nullable USER_TAB_COLUMNS.NULLABLE%TYPE;
  v_default VARCHAR2(4000);
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'RL_MR_FAMILIAS_FORMULARIO'
     AND COLUMN_NAME = 'FAM_PREDETERMINADA';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RL_MR_FAMILIAS_FORMULARIO ADD (FAM_PREDETERMINADA NUMBER(1) DEFAULT 0 NOT NULL)';
  ELSE
    SELECT DATA_TYPE, DATA_PRECISION, NULLABLE, DATA_DEFAULT
      INTO v_data_type, v_precision, v_nullable, v_default
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'RL_MR_FAMILIAS_FORMULARIO'
       AND COLUMN_NAME = 'FAM_PREDETERMINADA';

    IF v_data_type <> 'NUMBER'
       OR v_precision <> 1
       OR v_nullable <> 'N'
       OR TRIM(v_default) <> '0' THEN
      RAISE_APPLICATION_ERROR(-20081, 'FAM_PREDETERMINADA existe con contrato incompatible.');
    END IF;
  END IF;

  SELECT COUNT(*)
    INTO v_exists
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'RL_MR_FAMILIAS_FORMULARIO'
     AND CONSTRAINT_NAME = 'CK_RL_MR_FAM_PREDET';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE RL_MR_FAMILIAS_FORMULARIO ADD CONSTRAINT CK_RL_MR_FAM_PREDET CHECK (FAM_PREDETERMINADA IN (0,1))]';
  END IF;

  SELECT COUNT(*)
    INTO v_exists
    FROM USER_INDEXES
   WHERE TABLE_NAME = 'RL_MR_FAMILIAS_FORMULARIO'
     AND INDEX_NAME = 'UQ_RL_MR_FAMILIA_DEFAULT';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX UQ_RL_MR_FAMILIA_DEFAULT ON RL_MR_FAMILIAS_FORMULARIO (CASE WHEN FAM_PREDETERMINADA = 1 THEN 1 ELSE NULL END)]';
  END IF;

  SELECT COUNT(*)
    INTO v_exists
    FROM RL_MR_FAMILIAS_FORMULARIO
   WHERE FAM_PREDETERMINADA = 1;

  IF v_exists > 1 THEN
    RAISE_APPLICATION_ERROR(-20082, 'La base contiene mas de una familia predeterminada.');
  END IF;

  DBMS_OUTPUT.PUT_LINE('FP1_DEFAULT_FAMILY_COLUMN=READY');
  DBMS_OUTPUT.PUT_LINE('FP1_DEFAULT_FAMILY_COUNT=' || v_exists);
END;
/

PROMPT FP1_DEFAULT_FAMILY_DDL_PREPARED
EXIT SUCCESS
