-- Oracle 11g / READ ONLY. No contiene DML.
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 240
SET PAGESIZE 200
PROMPT RISK_NAME_PRECHECK_BEGIN

SELECT COUNT(*) AS TOTAL_DB FROM RL_MR_RIESGOS;
SELECT 59 AS TOTAL_SOURCE_EXPECTED FROM DUAL;
SELECT RIE_CODIGO, COUNT(*) AS DUPLICATE_COUNT
  FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1 ORDER BY RIE_CODIGO;

SELECT 'U+FFFD=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_NOMBRE, UNISTR('\FFFD')) > 0;
SELECT 'U+00BF_EMBEDDED=' || COUNT(*) FROM RL_MR_RIESGOS
 WHERE REGEXP_LIKE(RIE_NOMBRE, '[[:alpha:]]' || UNISTR('\00BF') || '[[:alpha:]]');
SELECT 'U+00C3=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_NOMBRE, UNISTR('\00C3')) > 0;
SELECT 'U+00C2=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_NOMBRE, UNISTR('\00C2')) > 0;
SELECT 'SEQUENCE_I_QUESTION_N=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_NOMBRE, 'i' || UNISTR('\00BF') || 'n') > 0;
SELECT 'SEQUENCE_REPLACEMENT=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_NOMBRE, UNISTR('\00EF\00BF\00BD')) > 0;

SELECT RIE_ID, RIE_CODIGO, RIE_NOMBRE, LENGTH(RIE_NOMBRE) AS LENGTH_CHARS,
       LENGTHB(RIE_NOMBRE) AS LENGTH_BYTES, DUMP(RIE_NOMBRE, 1016) AS HEX_DUMP
  FROM RL_MR_RIESGOS
 WHERE RIE_CODIGO IN ('RCUMP-COMPRAS-24','RCUMP-COMPRAS-37','RCUMP-COMPRASCONTR-44')
 ORDER BY RIE_CODIGO;

SELECT 'RCUMP-COMPRAS-24_CURRENT=' || NVL(RIE_NOMBRE, '<NULL>')
  FROM RL_MR_RIESGOS WHERE RIE_CODIGO = 'RCUMP-COMPRAS-24';
SELECT 'RISK_NAME_PRECHECK_DB_ROWS=' || COUNT(*) FROM RL_MR_RIESGOS;
SELECT 'RISK_NAME_PRECHECK_DUPLICATES=' || COUNT(*) FROM
 (SELECT RIE_CODIGO FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1);
SELECT 'RISK_NAME_PRECHECK_STATUS=' || CASE WHEN
 (SELECT COUNT(*) FROM RL_MR_RIESGOS)=59 AND
 (SELECT COUNT(*) FROM (SELECT RIE_CODIGO FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1))=0
 THEN 'PASS' ELSE 'FAIL' END FROM DUAL;
PROMPT RISK_NAME_PRECHECK_END
