-- Oracle 11g / MANUAL. Ejecutar solo después de 31 y antes de 33.
-- No sobrescribe el respaldo controlado RL_MR_RIES_NOM_BKP_20260924.
SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  v_exists NUMBER;
  v_rows NUMBER;
  v_created BOOLEAN := FALSE;
BEGIN
  SELECT COUNT(*) INTO v_rows FROM RL_MR_RIESGOS;
  IF v_rows <> 59 THEN
    RAISE_APPLICATION_ERROR(-20930, 'Backup abortado: RL_MR_RIESGOS tiene ' || v_rows || ' filas; se esperaban 59.');
  END IF;
  SELECT COUNT(*) INTO v_rows FROM
   (SELECT RIE_CODIGO FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1);
  IF v_rows <> 0 THEN
    RAISE_APPLICATION_ERROR(-20934, 'Backup abortado: existen ' || v_rows || ' códigos duplicados.');
  END IF;
  SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'RL_MR_RIES_NOM_BKP_20260924';
  IF v_exists > 0 THEN
    RAISE_APPLICATION_ERROR(-20931, 'El backup RL_MR_RIES_NOM_BKP_20260924 ya existe; no se sobrescribirá.');
  END IF;
  EXECUTE IMMEDIATE 'CREATE TABLE RL_MR_RIES_NOM_BKP_20260924 AS
    SELECT RIE_ID, RIE_CODIGO, RIE_NOMBRE, RIE_DESCRIPCION,
           SYSDATE AS BKP_FECHA, USER AS BKP_USUARIO
      FROM RL_MR_RIESGOS';
  v_created := TRUE;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM RL_MR_RIES_NOM_BKP_20260924' INTO v_rows;
  IF v_rows <> 59 THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20932, 'Backup abortado: se esperaban 59 filas y se capturaron ' || v_rows || '.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('RISK_NAME_BACKUP_ROWS=' || v_rows);
  DBMS_OUTPUT.PUT_LINE('RISK_NAME_BACKUP_TABLE=RL_MR_RIES_NOM_BKP_20260924');
  DBMS_OUTPUT.PUT_LINE('RISK_NAME_BACKUP_STATUS=PASS');
EXCEPTION WHEN OTHERS THEN
  IF v_created THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE RL_MR_RIES_NOM_BKP_20260924 PURGE';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END IF;
  ROLLBACK;
  RAISE;
END;
/
