-- Oracle 11g / READ ONLY. No contiene DML.
-- Detecta corrupción visible en RIE_DESCRIPCION; no define una fuente canónica semántica.
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 260
SET PAGESIZE 200
PROMPT RISK_DESCRIPTION_PRECHECK_BEGIN

SELECT COUNT(*) AS TOTAL_DB FROM RL_MR_RIESGOS;
SELECT RIE_CODIGO, COUNT(*) AS DUPLICATE_COUNT
  FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1 ORDER BY RIE_CODIGO;
SELECT 'U+FFFD=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_DESCRIPCION, UNISTR('\FFFD')) > 0;
SELECT 'U+00BF_EMBEDDED=' || COUNT(*) FROM RL_MR_RIESGOS
 WHERE REGEXP_LIKE(RIE_DESCRIPCION, '[[:alpha:]]' || UNISTR('\00BF') || '[[:alpha:]]');
SELECT 'U+00C3=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_DESCRIPCION, UNISTR('\00C3')) > 0;
SELECT 'U+00C2=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_DESCRIPCION, UNISTR('\00C2')) > 0;
SELECT 'SEQUENCE_I_QUESTION_N=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_DESCRIPCION, 'i' || UNISTR('\00BF') || 'n') > 0;
SELECT 'SEQUENCE_REPLACEMENT=' || COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_DESCRIPCION, UNISTR('\00EF\00BF\00BD')) > 0;

SELECT RIE_ID, RIE_CODIGO, SUBSTR(RIE_DESCRIPCION, 1, 240) AS DESCRIPTION_SAMPLE,
       LENGTH(RIE_DESCRIPCION) AS LENGTH_CHARS,
       LENGTHB(RIE_DESCRIPCION) AS LENGTH_BYTES,
       DUMP(RIE_DESCRIPCION, 1016) AS HEX_DUMP
  FROM RL_MR_RIESGOS
 WHERE RIE_CODIGO IN ('RCUMP-COMPRAS-24','RCUMP-COMPRAS-25','RCUMP-COMPRAS-27')
 ORDER BY RIE_CODIGO;

SELECT 'RISK_DESCRIPTION_PRECHECK_DB_ROWS=' || COUNT(*) FROM RL_MR_RIESGOS;
SELECT 'RISK_DESCRIPTION_PRECHECK_DUPLICATES=' || COUNT(*) FROM
 (SELECT RIE_CODIGO FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1);
SELECT 'RISK_DESCRIPTION_PRECHECK_NULL_ROWS=' || COUNT(*) FROM RL_MR_RIESGOS WHERE RIE_DESCRIPCION IS NULL;
SELECT 'RISK_DESCRIPTION_PRECHECK_SUSPICIOUS_ROWS=' || COUNT(*) FROM RL_MR_RIESGOS
 WHERE INSTR(RIE_DESCRIPCION, UNISTR('\FFFD')) > 0
    OR INSTR(RIE_DESCRIPCION, UNISTR('\00C3')) > 0
    OR INSTR(RIE_DESCRIPCION, UNISTR('\00C2')) > 0
    OR INSTR(RIE_DESCRIPCION, UNISTR('\00EF\00BF\00BD')) > 0
    OR REGEXP_LIKE(RIE_DESCRIPCION, '[[:alpha:]]' || UNISTR('\00BF') || '[[:alpha:]]');
SELECT 'RISK_DESCRIPTION_PRECHECK_STATUS=' || CASE WHEN
 (SELECT COUNT(*) FROM RL_MR_RIESGOS)=59 AND
 (SELECT COUNT(*) FROM (SELECT RIE_CODIGO FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1))=0
 THEN 'PASS' ELSE 'FAIL' END FROM DUAL;
PROMPT RISK_DESCRIPTION_PRECHECK_END
