-- Oracle 11g / READ ONLY. Ejecutar después de 38.
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 260
SET PAGESIZE 200
PROMPT RISK_DESCRIPTION_POSTCHECK_BEGIN
SELECT 'RISK_DESCRIPTION_POSTCHECK_DB_ROWS=' || COUNT(*) FROM RL_MR_RIESGOS;
SELECT 'RISK_DESCRIPTION_POSTCHECK_DUPLICATES=' || COUNT(*) FROM
 (SELECT RIE_CODIGO FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1);
SELECT 'RISK_DESCRIPTION_POSTCHECK_RESIDUAL_SUSPICIOUS=' || COUNT(*) FROM RL_MR_RIESGOS
 WHERE INSTR(RIE_DESCRIPCION, UNISTR('\FFFD')) > 0
    OR INSTR(RIE_DESCRIPCION, UNISTR('\00C3')) > 0
    OR INSTR(RIE_DESCRIPCION, UNISTR('\00C2')) > 0
    OR INSTR(RIE_DESCRIPCION, UNISTR('\00EF\00BF\00BD')) > 0
    OR REGEXP_LIKE(RIE_DESCRIPCION, '[[:alpha:]]' || UNISTR('\00BF') || '[[:alpha:]]');
SELECT RIE_CODIGO, SUBSTR(RIE_DESCRIPCION, 1, 240) AS DESCRIPTION_SAMPLE,
       LENGTH(RIE_DESCRIPCION) AS LENGTH_CHARS, LENGTHB(RIE_DESCRIPCION) AS LENGTH_BYTES,
       DUMP(RIE_DESCRIPCION, 1016) AS HEX_DUMP
  FROM RL_MR_RIESGOS WHERE RIE_CODIGO = 'RCUMP-COMPRAS-24';
SELECT 'RISK_DESCRIPTION_POSTCHECK_RCUMP_24_HAS_ACCENT=' || CASE WHEN EXISTS
 (SELECT 1 FROM RL_MR_RIESGOS WHERE RIE_CODIGO = 'RCUMP-COMPRAS-24' AND INSTR(RIE_DESCRIPCION, UNISTR('\00F3')) > 0)
 THEN 'YES' ELSE 'NO' END FROM DUAL;
SELECT 'RISK_DESCRIPTION_POSTCHECK_STATUS=' || CASE WHEN
 (SELECT COUNT(*) FROM RL_MR_RIESGOS)=59 AND
 (SELECT COUNT(*) FROM (SELECT RIE_CODIGO FROM RL_MR_RIESGOS GROUP BY RIE_CODIGO HAVING COUNT(*) > 1))=0 AND
 (SELECT COUNT(*) FROM RL_MR_RIESGOS WHERE INSTR(RIE_DESCRIPCION, UNISTR('\FFFD')) > 0 OR INSTR(RIE_DESCRIPCION, UNISTR('\00C3')) > 0 OR INSTR(RIE_DESCRIPCION, UNISTR('\00C2')) > 0 OR INSTR(RIE_DESCRIPCION, UNISTR('\00EF\00BF\00BD')) > 0 OR REGEXP_LIKE(RIE_DESCRIPCION, '[[:alpha:]]' || UNISTR('\00BF') || '[[:alpha:]]'))=0
 THEN 'PASS' ELSE 'FAIL' END FROM DUAL;
PROMPT RISK_DESCRIPTION_POSTCHECK_END
