-- Oracle 11g / MANUAL. Restauración desde RL_MR_RIESGOS_DESC_BKP_20260923.
SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  v_backup NUMBER;
  v_db_rows NUMBER;
  v_expected NUMBER;
  v_restored NUMBER := 0;
  v_diffs NUMBER;
  v_backup_duplicates NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_backup FROM USER_TABLES WHERE TABLE_NAME = 'RL_MR_RIESGOS_DESC_BKP_20260923';
  IF v_backup = 0 THEN RAISE_APPLICATION_ERROR(-20940, 'No existe RL_MR_RIESGOS_DESC_BKP_20260923.'); END IF;
  SELECT COUNT(*) INTO v_expected FROM RL_MR_RIESGOS_DESC_BKP_20260923;
  IF v_expected <> 59 THEN RAISE_APPLICATION_ERROR(-20941, 'Backup inválido: filas=' || v_expected || ', esperado=59.'); END IF;
  SELECT COUNT(*) INTO v_db_rows FROM RL_MR_RIESGOS;
  IF v_db_rows <> 59 THEN RAISE_APPLICATION_ERROR(-20945, 'Restauración bloqueada: filas destino=' || v_db_rows || ', esperado=59.'); END IF;
  SELECT COUNT(*) INTO v_backup_duplicates FROM
   (SELECT RIE_ID, RIE_CODIGO FROM RL_MR_RIESGOS_DESC_BKP_20260923 GROUP BY RIE_ID, RIE_CODIGO HAVING COUNT(*) > 1);
  IF v_backup_duplicates <> 0 THEN RAISE_APPLICATION_ERROR(-20946, 'Backup inválido: claves duplicadas=' || v_backup_duplicates || '.'); END IF;
  SAVEPOINT risk_description_restore;
  UPDATE RL_MR_RIESGOS r SET RIE_DESCRIPCION =
    (SELECT b.RIE_DESCRIPCION FROM RL_MR_RIESGOS_DESC_BKP_20260923 b
      WHERE b.RIE_ID = r.RIE_ID AND b.RIE_CODIGO = r.RIE_CODIGO)
   WHERE EXISTS (SELECT 1 FROM RL_MR_RIESGOS_DESC_BKP_20260923 b
      WHERE b.RIE_ID = r.RIE_ID AND b.RIE_CODIGO = r.RIE_CODIGO);
  v_restored := SQL%ROWCOUNT;
  SELECT COUNT(*) INTO v_diffs FROM RL_MR_RIESGOS r JOIN RL_MR_RIESGOS_DESC_BKP_20260923 b
    ON b.RIE_ID = r.RIE_ID AND b.RIE_CODIGO = r.RIE_CODIGO
   WHERE r.RIE_DESCRIPCION <> b.RIE_DESCRIPCION
      OR (r.RIE_DESCRIPCION IS NULL AND b.RIE_DESCRIPCION IS NOT NULL)
      OR (r.RIE_DESCRIPCION IS NOT NULL AND b.RIE_DESCRIPCION IS NULL);
  DBMS_OUTPUT.PUT_LINE('EXPECTED_DESCRIPTION_RESTORE=' || v_expected);
  DBMS_OUTPUT.PUT_LINE('ACTUAL_DESCRIPTION_RESTORE=' || v_restored);
  DBMS_OUTPUT.PUT_LINE('DESCRIPTION_RESTORE_DIFFS=' || v_diffs);
  IF v_restored <> v_expected OR v_diffs <> 0 THEN
    ROLLBACK TO risk_description_restore;
    RAISE_APPLICATION_ERROR(-20942, 'Restauración abortada por cantidad o diferencias.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('RISK_DESCRIPTION_ROLLBACK_STATUS=PASS');
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
