-- Oracle 11g / MANUAL. Ejecutar sólo después de revisar 41.
-- Crea un respaldo de las celdas sospechosas; no modifica RL_MR_* existentes.
SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  l_exists NUMBER;
  l_rows NUMBER := 0;
  l_sql VARCHAR2(32767);
  l_expr VARCHAR2(4000);
  l_pred VARCHAR2(12000);
  l_created BOOLEAN := FALSE;
  l_required NUMBER;
  l_tables SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST(
    'RL_MR_FAMILIAS_FORMULARIO','RL_MR_VERSIONES_FORMULARIO','RL_MR_CATALOGOS',
    'RL_MR_ELEMENTOS_CATALOGO','RL_MR_REGLAS_CALCULO','RL_MR_RIESGOS',
    'RL_MR_EVALUACIONES_RIESGO','RL_MR_PROYECCIONES_EVALUACION','RL_MR_FLUJOS_EVALUACION',
    'RL_MR_CONTROLES_RIESGO','RL_MR_EVALUACIONES_CONTROL','RL_MR_PLANES',
    'RL_MR_ACTIVIDADES','RL_MR_EVIDENCIAS','RL_MR_EVIDENCIAS_VINCULOS',
    'RL_MR_SENALES_ALERTA','RL_MR_AUTOMONITOREO','RL_MR_FORMULAS',
    'RL_MR_FORMULA_USOS','RL_MR_FORMULA_VERSIONES','RL_MR_FUNCION_ARGUMENTOS',
    'RL_MR_FUNCIONES','RL_MR_FUNCION_VERSIONES','RL_MR_PARAMETROS_CALCULO',
    'RL_MR_PARAMETRO_VERSIONES');
  @@_predicado_unicode_sospechoso.sql
BEGIN
  SELECT COUNT(*) INTO l_required FROM user_tables
   WHERE table_name IN (SELECT COLUMN_VALUE FROM TABLE(l_tables));
  IF l_required <> l_tables.COUNT THEN
    RAISE_APPLICATION_ERROR(-20742, 'No están disponibles las 25 tablas RL_MR requeridas; no se crea backup.');
  END IF;
  SELECT COUNT(*) INTO l_exists FROM user_tables WHERE table_name = 'RL_MR_UNI_BKP_20260924';
  IF l_exists <> 0 THEN
    RAISE_APPLICATION_ERROR(-20741, 'RL_MR_UNI_BKP_20260924 ya existe; no se sobrescribe.');
  END IF;
  EXECUTE IMMEDIATE 'CREATE TABLE RL_MR_UNI_BKP_20260924 (' ||
    'UBK_TABLE_NAME VARCHAR2(30) NOT NULL, UBK_COLUMN_NAME VARCHAR2(30) NOT NULL,' ||
    'UBK_ROWID_TEXT VARCHAR2(30) NOT NULL, UBK_OLD_VALUE CLOB,' ||
    'UBK_BACKUP_DATE DATE NOT NULL, CONSTRAINT PK_RL_MR_UNI_BKP_20260924 ' ||
    'PRIMARY KEY (UBK_TABLE_NAME, UBK_COLUMN_NAME, UBK_ROWID_TEXT))';
  l_created := TRUE;
  FOR t IN 1..l_tables.COUNT LOOP
    FOR c IN (SELECT column_name, data_type FROM user_tab_columns
               WHERE table_name = l_tables(t)
                 AND data_type IN ('VARCHAR2','CHAR','NVARCHAR2','NCHAR','CLOB')
               ORDER BY column_id) LOOP
      l_pred := suspicious_predicate(c.column_name);
      l_sql := 'INSERT INTO RL_MR_UNI_BKP_20260924 ' ||
        '(UBK_TABLE_NAME,UBK_COLUMN_NAME,UBK_ROWID_TEXT,UBK_OLD_VALUE,UBK_BACKUP_DATE) ' ||
        'SELECT :1,:2,ROWIDTOCHAR(ROWID),TO_CLOB(' || DBMS_ASSERT.SIMPLE_SQL_NAME(c.column_name) ||
        '),SYSDATE FROM ' || DBMS_ASSERT.SQL_OBJECT_NAME(l_tables(t)) || ' WHERE ' || l_pred;
      EXECUTE IMMEDIATE l_sql USING l_tables(t), c.column_name;
      l_rows := l_rows + SQL%ROWCOUNT;
    END LOOP;
  END LOOP;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM RL_MR_UNI_BKP_20260924' INTO l_rows;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('MATRICES_UNICODE_BACKUP_ROWS=' || l_rows);
  DBMS_OUTPUT.PUT_LINE('MATRICES_UNICODE_BACKUP_STATUS=PASS');
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  IF l_created THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE RL_MR_UNI_BKP_20260924 PURGE';
      COMMIT;
      DBMS_OUTPUT.PUT_LINE('MATRICES_UNICODE_BACKUP_CLEANUP=DROPPED');
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('MATRICES_UNICODE_BACKUP_CLEANUP=FAIL '||SQLERRM);
    END;
  END IF;
  DBMS_OUTPUT.PUT_LINE('MATRICES_UNICODE_BACKUP_STATUS=FAIL ' || SQLERRM);
  RAISE;
END;
/
