-- Bloque 4: precheck read-only para las propiedades plan-level 44, 45 y 48.
-- No ejecuta DDL/DML. Compatible con Oracle 11g.
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_count NUMBER;
  v_type USER_TAB_COLUMNS.DATA_TYPE%TYPE;
  v_precision USER_TAB_COLUMNS.DATA_PRECISION%TYPE;
  v_scale USER_TAB_COLUMNS.DATA_SCALE%TYPE;
  v_nullable USER_TAB_COLUMNS.NULLABLE%TYPE;
  v_length USER_TAB_COLUMNS.CHAR_LENGTH%TYPE;
  v_char_used USER_TAB_COLUMNS.CHAR_USED%TYPE;
BEGIN
  IF UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')) <> 'RIESGO_LAVADO' THEN
    RAISE_APPLICATION_ERROR(-20646, 'Precheck bloqueado: CURRENT_SCHEMA debe ser RIESGO_LAVADO.');
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'RL_MR_PLANES';
  IF v_count <> 1 THEN RAISE_APPLICATION_ERROR(-20646, 'No existe RL_MR_PLANES en el esquema actual.'); END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'RL_MR_PLANES' AND COLUMN_NAME IN
     ('PLA_ID','PLA_EVALUACION_ID','PLA_DESCRIPCION','PLA_AVANCE','PLA_PRESUPUESTO',
      'PLA_FECHA_INICIO','PLA_FECHA_FIN','PLA_ESTADO');
  IF v_count <> 8 THEN RAISE_APPLICATION_ERROR(-20646, 'RL_MR_PLANES no coincide con las ocho columnas base esperadas.'); END IF;

  SELECT DATA_TYPE, DATA_PRECISION, DATA_SCALE, NULLABLE INTO v_type, v_precision, v_scale, v_nullable
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RL_MR_PLANES' AND COLUMN_NAME = 'PLA_PRESUPUESTO';
  IF v_type <> 'NUMBER' OR v_precision <> 15 OR v_scale <> 2 OR v_nullable <> 'N' THEN
    RAISE_APPLICATION_ERROR(-20646, 'PLA_PRESUPUESTO no coincide con NUMBER(15,2) NOT NULL.');
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'RL_MR_PLANES'
     AND CONSTRAINT_NAME IN ('PK_RL_MR_PLANES','FK_RL_MR_PLA_EVA','CK_RL_MR_PLA_AV','CK_RL_MR_PLA_PR');
  IF v_count <> 4 THEN RAISE_APPLICATION_ERROR(-20646, 'Faltan constraints base de RL_MR_PLANES.'); END IF;

  FOR c IN (SELECT CONSTRAINT_NAME, STATUS FROM USER_CONSTRAINTS
             WHERE TABLE_NAME = 'RL_MR_PLANES'
               AND CONSTRAINT_NAME IN ('PK_RL_MR_PLANES','FK_RL_MR_PLA_EVA','CK_RL_MR_PLA_AV','CK_RL_MR_PLA_PR')) LOOP
    IF c.STATUS <> 'ENABLED' THEN RAISE_APPLICATION_ERROR(-20646, 'Constraint deshabilitada: ' || c.CONSTRAINT_NAME); END IF;
  END LOOP;

  FOR c IN (SELECT COLUMN_NAME, DATA_TYPE, CHAR_LENGTH, CHAR_USED, NULLABLE
              FROM USER_TAB_COLUMNS
             WHERE TABLE_NAME = 'RL_MR_PLANES'
               AND COLUMN_NAME IN ('PLA_MONITOREO_SEGUIMIENTO','PLA_RESPONSABLES','PLA_RECURSOS')) LOOP
    IF c.DATA_TYPE <> 'VARCHAR2' OR c.CHAR_LENGTH <> 1000 OR c.CHAR_USED <> 'C' OR c.NULLABLE <> 'Y' THEN
      RAISE_APPLICATION_ERROR(-20646, c.COLUMN_NAME || ' existe con tipo, tamaño o nullability incompatible.');
    END IF;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('BLOCK4_PRECHECK=PASS');
  DBMS_OUTPUT.PUT_LINE('BLOCK4_BASE_COLUMNS=8');
  DBMS_OUTPUT.PUT_LINE('BLOCK4_NEW_COLUMNS_COMPATIBLE_OR_ABSENT=PASS');
  DBMS_OUTPUT.PUT_LINE('BLOCK4_PRECHECK_READ_ONLY=YES');
END;
/
