-- Bloque 4: postcheck read-only de columnas y contrato conservado.
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_count NUMBER;
  v_type USER_TAB_COLUMNS.DATA_TYPE%TYPE;
  v_precision USER_TAB_COLUMNS.DATA_PRECISION%TYPE;
  v_scale USER_TAB_COLUMNS.DATA_SCALE%TYPE;
  v_nullable USER_TAB_COLUMNS.NULLABLE%TYPE;
BEGIN
  IF UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')) <> 'RIESGO_LAVADO' THEN
    RAISE_APPLICATION_ERROR(-20648, 'Postcheck bloqueado: CURRENT_SCHEMA debe ser RIESGO_LAVADO.');
  END IF;
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'RL_MR_PLANES'
     AND COLUMN_NAME IN ('PLA_MONITOREO_SEGUIMIENTO','PLA_RESPONSABLES','PLA_RECURSOS')
     AND DATA_TYPE = 'VARCHAR2' AND CHAR_LENGTH = 1000 AND CHAR_USED = 'C' AND NULLABLE = 'Y';
  IF v_count <> 3 THEN RAISE_APPLICATION_ERROR(-20648, 'Las tres columnas nuevas no cumplen el contrato nullable VARCHAR2(1000 CHAR).'); END IF;

  SELECT DATA_TYPE, DATA_PRECISION, DATA_SCALE, NULLABLE INTO v_type, v_precision, v_scale, v_nullable
    FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RL_MR_PLANES' AND COLUMN_NAME = 'PLA_PRESUPUESTO';
  IF v_type <> 'NUMBER' OR v_precision <> 15 OR v_scale <> 2 OR v_nullable <> 'N' THEN
    RAISE_APPLICATION_ERROR(-20648, 'PLA_PRESUPUESTO cambió respecto a NUMBER(15,2) NOT NULL.');
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_COL_COMMENTS
   WHERE TABLE_NAME = 'RL_MR_PLANES'
     AND COLUMN_NAME IN ('PLA_MONITOREO_SEGUIMIENTO','PLA_RESPONSABLES','PLA_RECURSOS')
     AND COMMENTS IS NOT NULL;
  IF v_count <> 3 THEN RAISE_APPLICATION_ERROR(-20648, 'Faltan comentarios institucionales de columnas nuevas.'); END IF;

  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'RL_MR_PLANES'
     AND CONSTRAINT_NAME IN ('PK_RL_MR_PLANES','FK_RL_MR_PLA_EVA','CK_RL_MR_PLA_AV','CK_RL_MR_PLA_PR')
     AND STATUS = 'ENABLED';
  IF v_count <> 4 THEN RAISE_APPLICATION_ERROR(-20648, 'Constraints existentes de RL_MR_PLANES no están todas habilitadas.'); END IF;
  DBMS_OUTPUT.PUT_LINE('BLOCK4_POSTCHECK=PASS');
  DBMS_OUTPUT.PUT_LINE('BLOCK4_POSTCHECK_READ_ONLY=YES');
END;
/
