-- Precheck read-only for Block 6 schema extension. Run only in the intended schema.
SET SERVEROUTPUT ON
DECLARE
  v_count NUMBER;
  v_missing NUMBER;
  v_existing NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME IN
    ('RL_MR_CONTROLES_RIESGO','RL_MR_AUTOMONITOREO','RL_USUARIOS');
  IF v_count <> 3 THEN RAISE_APPLICATION_ERROR(-20600, 'SCHEMA_CONFLICT: required tables are missing'); END IF;
  SELECT COUNT(*) INTO v_missing FROM USER_TAB_COLUMNS WHERE TABLE_NAME='RL_MR_CONTROLES_RIESGO'
    AND COLUMN_NAME IN ('CON_ID','CON_EVALUACION_ID','CON_TIPO','CON_ESTADO');
  IF v_missing <> 4 THEN RAISE_APPLICATION_ERROR(-20601, 'SCHEMA_CONFLICT: unexpected controls schema'); END IF;
  SELECT COUNT(*) INTO v_missing FROM USER_TAB_COLUMNS WHERE TABLE_NAME='RL_MR_AUTOMONITOREO'
    AND COLUMN_NAME IN ('MON_ID','MON_EVALUACION_ID','MON_ESTADO_RIESGO');
  IF v_missing <> 3 THEN RAISE_APPLICATION_ERROR(-20602, 'SCHEMA_CONFLICT: unexpected monitoring schema'); END IF;
  SELECT COUNT(*) INTO v_existing FROM USER_TAB_COLUMNS WHERE
    (TABLE_NAME='RL_MR_CONTROLES_RIESGO' AND COLUMN_NAME IN ('CON_ESTADO_MONITOREO','CON_EFECTIVIDAD_MONITOREO')) OR
    (TABLE_NAME='RL_MR_AUTOMONITOREO' AND COLUMN_NAME IN ('MON_OBSERVACIONES_AREA','MON_OBSERVACIONES_UGR'));
  IF v_existing NOT IN (0,4) THEN RAISE_APPLICATION_ERROR(-20603, 'SCHEMA_CONFLICT: partial Block 6 schema already exists'); END IF;
  IF v_existing=4 THEN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE
      (TABLE_NAME='RL_MR_CONTROLES_RIESGO' AND COLUMN_NAME='CON_ESTADO_MONITOREO' AND DATA_TYPE='VARCHAR2' AND CHAR_LENGTH=30 AND CHAR_USED='C' AND NULLABLE='Y') OR
      (TABLE_NAME='RL_MR_CONTROLES_RIESGO' AND COLUMN_NAME='CON_EFECTIVIDAD_MONITOREO' AND DATA_TYPE='NUMBER' AND DATA_PRECISION=5 AND DATA_SCALE=2 AND NULLABLE='Y') OR
      (TABLE_NAME='RL_MR_AUTOMONITOREO' AND COLUMN_NAME IN ('MON_OBSERVACIONES_AREA','MON_OBSERVACIONES_UGR') AND DATA_TYPE='VARCHAR2' AND CHAR_LENGTH=2000 AND CHAR_USED='C' AND NULLABLE='Y');
    IF v_count <> 4 THEN RAISE_APPLICATION_ERROR(-20605, 'SCHEMA_CONFLICT: existing Block 6 columns have incompatible definitions'); END IF;
  END IF;
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='RL_USUARIO_CAPACIDADES';
  IF v_count NOT IN (0,1) THEN RAISE_APPLICATION_ERROR(-20604, 'SCHEMA_CONFLICT: capability table state is unexpected'); END IF;
  IF v_count=1 THEN
    SELECT COUNT(*) INTO v_missing FROM USER_TAB_COLUMNS WHERE TABLE_NAME='RL_USUARIO_CAPACIDADES'
      AND COLUMN_NAME IN ('UCP_USR_ID','UCP_CAPACIDAD','UCP_ACTIVO','UCP_ASIGNADO_POR','UCP_FECHA_ASIGNACION');
    IF v_missing <> 5 THEN RAISE_APPLICATION_ERROR(-20606, 'SCHEMA_CONFLICT: existing capability table is incompatible'); END IF;
  END IF;
  DBMS_OUTPUT.PUT_LINE('BLOCK6_COLUMNS_ALREADY_PRESENT=' || CASE WHEN v_existing=4 THEN 'YES' ELSE 'NO' END);
  DBMS_OUTPUT.PUT_LINE('BLOCK6_PRECHECK=PASS');
END;
/
