-- Additive Block 6 columns and deny-by-default direct-user capabilities.
-- Do not grant capabilities to production users in this migration.
ALTER TABLE RL_MR_CONTROLES_RIESGO ADD (
  CON_ESTADO_MONITOREO VARCHAR2(30 CHAR),
  CON_EFECTIVIDAD_MONITOREO NUMBER(5,2),
  CONSTRAINT CK_RL_MR_CON_MON_EF CHECK (CON_EFECTIVIDAD_MONITOREO BETWEEN 0 AND 100)
);
COMMENT ON COLUMN RL_MR_CONTROLES_RIESGO.CON_ESTADO_MONITOREO IS 'Estado posterior del control en el seguimiento de la evaluación; independiente de CON_ESTADO.';
COMMENT ON COLUMN RL_MR_CONTROLES_RIESGO.CON_EFECTIVIDAD_MONITOREO IS 'Efectividad posterior del control (0 a 100); independiente de ECO_EFECTIVIDAD.';

ALTER TABLE RL_MR_AUTOMONITOREO ADD (
  MON_OBSERVACIONES_AREA VARCHAR2(2000 CHAR),
  MON_OBSERVACIONES_UGR VARCHAR2(2000 CHAR)
);
COMMENT ON COLUMN RL_MR_AUTOMONITOREO.MON_OBSERVACIONES_AREA IS 'Observaciones del área registradas durante el automonitoreo.';
COMMENT ON COLUMN RL_MR_AUTOMONITOREO.MON_OBSERVACIONES_UGR IS 'Observaciones UGR registradas durante el automonitoreo.';

CREATE TABLE RL_USUARIO_CAPACIDADES (
  UCP_USR_ID NUMBER(10) NOT NULL,
  UCP_CAPACIDAD VARCHAR2(80 CHAR) NOT NULL,
  UCP_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
  UCP_ASIGNADO_POR NUMBER(10),
  UCP_FECHA_ASIGNACION DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RL_USUARIO_CAP PRIMARY KEY (UCP_USR_ID, UCP_CAPACIDAD),
  CONSTRAINT FK_RL_UCP_USR FOREIGN KEY (UCP_USR_ID) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT FK_RL_UCP_ASIG FOREIGN KEY (UCP_ASIGNADO_POR) REFERENCES RL_USUARIOS(USR_ID),
  CONSTRAINT CK_RL_UCP_CAP CHECK (UCP_CAPACIDAD IN ('MATRICES_RIESGO_OBSERVACIONES_AREA_EDITAR','MATRICES_RIESGO_OBSERVACIONES_UGR_EDITAR')),
  CONSTRAINT CK_RL_UCP_ACTIVO CHECK (UCP_ACTIVO IN (0,1))
);
COMMENT ON TABLE RL_USUARIO_CAPACIDADES IS 'Capacidades explícitas por usuario; sus asignaciones no se infieren desde roles.';
CREATE INDEX IDX_RL_UCP_CAP ON RL_USUARIO_CAPACIDADES(UCP_CAPACIDAD, UCP_ACTIVO);
