-- Additive Block 6 columns and deny-by-default direct-user capabilities.
-- Do not grant capabilities to production users in this migration.
ALTER TABLE RL_MR_CONTROLES_RIESGO ADD (
  CON_ESTADO_MONITOREO VARCHAR2(30 CHAR),
  CON_EFECTIVIDAD_MONITOREO NUMBER(5,2),
  CONSTRAINT CK_RL_MR_CON_MON_EF CHECK (CON_EFECTIVIDAD_MONITOREO BETWEEN 0 AND 100)
);
COMMENT ON COLUMN RL_MR_CONTROLES_RIESGO.CON_ESTADO_MONITOREO IS 'Estado posterior del control en el seguimiento de la evaluación; independiente de CON_ESTADO.';
COMMENT ON COLUMN RL_MR_CONTROLES_RIESGO.CON_EFECTIVIDAD_MONITOREO IS 'Efectividad posterior del control (0 a 100); independiente de ECO_EFECTIVIDAD.';

ALTER TABLE RL_MR_AUTOMONITOREO ADD (
  MON_OBSERVACIONES_AREA VARCHAR2(2000 CHAR),
  MON_OBSERVACIONES_UGR VARCHAR2(2000 CHAR)
);
COMMENT ON COLUMN RL_MR_AUTOMONITOREO.MON_OBSERVACIONES_AREA IS 'Observaciones del área registradas durante el automonitoreo.';
COMMENT ON COLUMN RL_MR_AUTOMONITOREO.MON_OBSERVACIONES_UGR IS 'Observaciones UGR registradas durante el automonitoreo.';

DECLARE
  v_table_count NUMBER;
  v_column_count NUMBER;
  v_constraint_count NUMBER;
  v_index_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_table_count
    FROM USER_TABLES
   WHERE TABLE_NAME = 'RL_USUARIO_CAPACIDADES';

  IF v_table_count = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE RL_USUARIO_CAPACIDADES (
      UCP_USR_ID NUMBER(10) NOT NULL,
      UCP_CAPACIDAD VARCHAR2(80 CHAR) NOT NULL,
      UCP_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
      UCP_ASIGNADO_POR NUMBER(10),
      UCP_FECHA_ASIGNACION DATE DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_RL_USUARIO_CAP PRIMARY KEY (UCP_USR_ID, UCP_CAPACIDAD),
      CONSTRAINT FK_RL_UCP_USR FOREIGN KEY (UCP_USR_ID) REFERENCES RL_USUARIOS(USR_ID),
      CONSTRAINT FK_RL_UCP_ASIG FOREIGN KEY (UCP_ASIGNADO_POR) REFERENCES RL_USUARIOS(USR_ID),
      CONSTRAINT CK_RL_UCP_CAP CHECK (UCP_CAPACIDAD IN ('MATRICES_RIESGO_OBSERVACIONES_AREA_EDITAR','MATRICES_RIESGO_OBSERVACIONES_UGR_EDITAR')),
      CONSTRAINT CK_RL_UCP_ACTIVO CHECK (UCP_ACTIVO IN (0,1))
    )~';
  ELSE
    SELECT COUNT(*) INTO v_column_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'RL_USUARIO_CAPACIDADES'
       AND ((COLUMN_NAME = 'UCP_USR_ID' AND DATA_TYPE = 'NUMBER' AND DATA_PRECISION = 10 AND DATA_SCALE = 0 AND NULLABLE = 'N')
         OR (COLUMN_NAME = 'UCP_CAPACIDAD' AND DATA_TYPE = 'VARCHAR2' AND CHAR_LENGTH = 80 AND CHAR_USED = 'C' AND NULLABLE = 'N')
         OR (COLUMN_NAME = 'UCP_ACTIVO' AND DATA_TYPE = 'NUMBER' AND DATA_PRECISION = 1 AND DATA_SCALE = 0 AND NULLABLE = 'N')
         OR (COLUMN_NAME = 'UCP_ASIGNADO_POR' AND DATA_TYPE = 'NUMBER' AND DATA_PRECISION = 10 AND DATA_SCALE = 0 AND NULLABLE = 'Y')
         OR (COLUMN_NAME = 'UCP_FECHA_ASIGNACION' AND DATA_TYPE = 'DATE' AND NULLABLE = 'N'));
    IF v_column_count <> 5 THEN
      RAISE_APPLICATION_ERROR(-20615, 'SCHEMA_CONFLICT: RL_USUARIO_CAPACIDADES existe con columnas incompatibles.');
    END IF;

    SELECT COUNT(*) INTO v_constraint_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'RL_USUARIO_CAPACIDADES'
       AND CONSTRAINT_NAME IN ('PK_RL_USUARIO_CAP','FK_RL_UCP_USR','FK_RL_UCP_ASIG','CK_RL_UCP_CAP','CK_RL_UCP_ACTIVO')
       AND STATUS = 'ENABLED';
    IF v_constraint_count <> 5 THEN
      RAISE_APPLICATION_ERROR(-20616, 'SCHEMA_CONFLICT: RL_USUARIO_CAPACIDADES existe sin constraints compatibles habilitadas.');
    END IF;
  END IF;

  SELECT COUNT(*) INTO v_index_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_RL_UCP_CAP'
     AND TABLE_NAME = 'RL_USUARIO_CAPACIDADES'
     AND UNIQUENESS = 'NONUNIQUE';
  IF v_index_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_RL_UCP_CAP ON RL_USUARIO_CAPACIDADES(UCP_CAPACIDAD, UCP_ACTIVO)';
  ELSE
    SELECT COUNT(*) INTO v_index_count
      FROM USER_IND_COLUMNS
     WHERE INDEX_NAME = 'IDX_RL_UCP_CAP'
       AND TABLE_NAME = 'RL_USUARIO_CAPACIDADES'
       AND ((COLUMN_POSITION = 1 AND COLUMN_NAME = 'UCP_CAPACIDAD')
         OR (COLUMN_POSITION = 2 AND COLUMN_NAME = 'UCP_ACTIVO'));
    IF v_index_count <> 2 THEN
      RAISE_APPLICATION_ERROR(-20617, 'SCHEMA_CONFLICT: IDX_RL_UCP_CAP existe con columnas incompatibles.');
    END IF;
  END IF;
END;
/
COMMENT ON TABLE RL_USUARIO_CAPACIDADES IS 'Capacidades explícitas por usuario; sus asignaciones no se infieren desde roles.';
