-- Postcheck read-only for Block 6.
SET SERVEROUTPUT ON
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE
    (TABLE_NAME='RL_MR_CONTROLES_RIESGO' AND COLUMN_NAME IN ('CON_ESTADO_MONITOREO','CON_EFECTIVIDAD_MONITOREO') AND NULLABLE='Y') OR
    (TABLE_NAME='RL_MR_AUTOMONITOREO' AND COLUMN_NAME IN ('MON_OBSERVACIONES_AREA','MON_OBSERVACIONES_UGR') AND NULLABLE='Y');
  IF v_count <> 4 THEN RAISE_APPLICATION_ERROR(-20610, 'BLOCK6_POSTCHECK_FAIL: nullable columns missing'); END IF;
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE
    ((TABLE_NAME='RL_MR_CONTROLES_RIESGO' AND COLUMN_NAME='CON_ESTADO_MONITOREO' AND DATA_TYPE='VARCHAR2' AND CHAR_LENGTH=30 AND CHAR_USED='C' AND NULLABLE='Y') OR
     (TABLE_NAME='RL_MR_CONTROLES_RIESGO' AND COLUMN_NAME='CON_EFECTIVIDAD_MONITOREO' AND DATA_TYPE='NUMBER' AND DATA_PRECISION=5 AND DATA_SCALE=2 AND NULLABLE='Y') OR
     (TABLE_NAME='RL_MR_AUTOMONITOREO' AND COLUMN_NAME IN ('MON_OBSERVACIONES_AREA','MON_OBSERVACIONES_UGR') AND DATA_TYPE='VARCHAR2' AND CHAR_LENGTH=2000 AND CHAR_USED='C' AND NULLABLE='Y'));
  IF v_count <> 4 THEN RAISE_APPLICATION_ERROR(-20614, 'BLOCK6_POSTCHECK_FAIL: new column type/length/scale mismatch'); END IF;
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME='CK_RL_MR_CON_MON_EF' AND STATUS='ENABLED';
  IF v_count <> 1 THEN RAISE_APPLICATION_ERROR(-20611, 'BLOCK6_POSTCHECK_FAIL: effectiveness constraint missing'); END IF;
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME='RL_USUARIO_CAPACIDADES';
  IF v_count <> 1 THEN RAISE_APPLICATION_ERROR(-20612, 'BLOCK6_POSTCHECK_FAIL: capability table missing'); END IF;
  SELECT COUNT(*) INTO v_count FROM RL_USUARIO_CAPACIDADES;
  IF v_count <> 0 THEN RAISE_APPLICATION_ERROR(-20613, 'BLOCK6_POSTCHECK_FAIL: unexpected production grants'); END IF;
  DBMS_OUTPUT.PUT_LINE('BLOCK6_POSTCHECK=PASS');
END;
/
