-- Manual recovery only. Removes only Block 6 additions. No data backfill exists.
DROP INDEX IDX_RL_UCP_CAP;
DROP TABLE RL_USUARIO_CAPACIDADES CASCADE CONSTRAINTS;
ALTER TABLE RL_MR_AUTOMONITOREO DROP COLUMN MON_OBSERVACIONES_AREA;
ALTER TABLE RL_MR_AUTOMONITOREO DROP COLUMN MON_OBSERVACIONES_UGR;
ALTER TABLE RL_MR_CONTROLES_RIESGO DROP CONSTRAINT CK_RL_MR_CON_MON_EF;
ALTER TABLE RL_MR_CONTROLES_RIESGO DROP COLUMN CON_ESTADO_MONITOREO;
ALTER TABLE RL_MR_CONTROLES_RIESGO DROP COLUMN CON_EFECTIVIDAD_MONITOREO;
