-- Manual recovery only. Removes only Block 6 additions. No data backfill exists.
-- RL_USUARIO_CAPACIDADES is also part of the general fresh-install schema.
-- Preserve this shared table and its index during rollback.
ALTER TABLE RL_MR_AUTOMONITOREO DROP COLUMN MON_OBSERVACIONES_AREA;
ALTER TABLE RL_MR_AUTOMONITOREO DROP COLUMN MON_OBSERVACIONES_UGR;
ALTER TABLE RL_MR_CONTROLES_RIESGO DROP CONSTRAINT CK_RL_MR_CON_MON_EF;
ALTER TABLE RL_MR_CONTROLES_RIESGO DROP COLUMN CON_ESTADO_MONITOREO;
ALTER TABLE RL_MR_CONTROLES_RIESGO DROP COLUMN CON_EFECTIVIDAD_MONITOREO;
