-- ============================================================
-- Sistema de Gestión de Riesgos LA/FT - IHSS
-- Fase 3. Modelo de datos y arquitectura Oracle
-- Script: 01_F3_create_rl_mr_estructura.sql
-- Objetivo: Crear estructura inicial RL_MR_* para Matrices de Riesgos.
-- Clasificación: Aprobable para revisión DBA. No ejecutar en producción sin aprobación.
-- Responsable documental: Javier Mejía
-- Reglas: idempotente cuando el objeto no existe, sin DROP, sin TRUNCATE, sin DELETE.
-- ============================================================

SET DEFINE OFF;

DECLARE
  PROCEDURE create_sequence_if_missing(p_sequence_name IN VARCHAR2, p_sql IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = UPPER(p_sequence_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    END IF;
  END;

  PROCEDURE create_table_if_missing(p_table_name IN VARCHAR2, p_sql IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = UPPER(p_table_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    END IF;
  END;

  PROCEDURE create_index_if_missing(p_index_name IN VARCHAR2, p_sql IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = UPPER(p_index_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    END IF;
  END;
BEGIN
  create_sequence_if_missing('SEQ_RL_MR_MODELOS', 'CREATE SEQUENCE SEQ_RL_MR_MODELOS START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_FACTORES', 'CREATE SEQUENCE SEQ_RL_MR_FACTORES START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_VARIABLES', 'CREATE SEQUENCE SEQ_RL_MR_VARIABLES START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_ESCALAS', 'CREATE SEQUENCE SEQ_RL_MR_ESCALAS START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_CRITERIOS', 'CREATE SEQUENCE SEQ_RL_MR_CRITERIOS START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_MATRICES', 'CREATE SEQUENCE SEQ_RL_MR_MATRICES START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_DETALLE', 'CREATE SEQUENCE SEQ_RL_MR_DETALLE START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_CONTROLES', 'CREATE SEQUENCE SEQ_RL_MR_CONTROLES START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_RESULTADOS', 'CREATE SEQUENCE SEQ_RL_MR_RESULTADOS START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_PLANES_ACCION', 'CREATE SEQUENCE SEQ_RL_MR_PLANES_ACCION START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_EVIDENCIAS', 'CREATE SEQUENCE SEQ_RL_MR_EVIDENCIAS START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_HISTORIAL', 'CREATE SEQUENCE SEQ_RL_MR_HISTORIAL START WITH 1 INCREMENT BY 1 NOCACHE');
  create_sequence_if_missing('SEQ_RL_MR_INTEGRACION_DNP', 'CREATE SEQUENCE SEQ_RL_MR_INTEGRACION_DNP START WITH 1 INCREMENT BY 1 NOCACHE');

  create_table_if_missing('RL_MR_MODELOS',
    'CREATE TABLE RL_MR_MODELOS (
      MRM_ID                 NUMBER(15) NOT NULL,
      MRM_NOMBRE             VARCHAR2(150) NOT NULL,
      MRM_VERSION            VARCHAR2(30) NOT NULL,
      MRM_DESCRIPCION        VARCHAR2(1000),
      MRM_ESTADO             VARCHAR2(20) DEFAULT ''BORRADOR'' NOT NULL,
      MRM_FECHA_VIGENCIA     DATE,
      MRM_FECHA_CIERRE       DATE,
      MRM_APROBADO_POR       NUMBER(10),
      MRM_FECHA_APROBACION   DATE,
      MRM_MOTIVO_ESTADO      VARCHAR2(1000),
      MRM_USR_CREACION_ID    NUMBER(10),
      MRM_FECHA_CREACION     DATE DEFAULT SYSDATE NOT NULL,
      MRM_USR_MODIF_ID       NUMBER(10),
      MRM_FECHA_MODIF        DATE,
      MRM_ESTADO_REGISTRO    NUMBER(1) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_RL_MR_MODELOS PRIMARY KEY (MRM_ID),
      CONSTRAINT UQ_RL_MR_MODELO_VER UNIQUE (MRM_NOMBRE, MRM_VERSION),
      CONSTRAINT CK_RL_MR_MOD_ESTADO CHECK (MRM_ESTADO IN (''BORRADOR'',''EN_REVISION'',''APROBADO'',''CERRADO'',''INACTIVO'')),
      CONSTRAINT CK_RL_MR_MOD_REG CHECK (MRM_ESTADO_REGISTRO IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_FACTORES',
    'CREATE TABLE RL_MR_FACTORES (
      MRF_ID                 NUMBER(15) NOT NULL,
      MRF_MODELO_ID          NUMBER(15) NOT NULL,
      MRF_CODIGO             VARCHAR2(40) NOT NULL,
      MRF_NOMBRE             VARCHAR2(120) NOT NULL,
      MRF_DESCRIPCION        VARCHAR2(1000),
      MRF_PESO_INSTITUCIONAL NUMBER(7,4) NOT NULL,
      MRF_ORDEN              NUMBER(5) DEFAULT 1 NOT NULL,
      MRF_ESTADO_REGISTRO    NUMBER(1) DEFAULT 1 NOT NULL,
      MRF_MOTIVO_INACTIVO    VARCHAR2(1000),
      MRF_USR_CREACION_ID    NUMBER(10),
      MRF_FECHA_CREACION     DATE DEFAULT SYSDATE NOT NULL,
      MRF_USR_MODIF_ID       NUMBER(10),
      MRF_FECHA_MODIF        DATE,
      CONSTRAINT PK_RL_MR_FACTORES PRIMARY KEY (MRF_ID),
      CONSTRAINT FK_RL_MR_FAC_MODELO FOREIGN KEY (MRF_MODELO_ID) REFERENCES RL_MR_MODELOS(MRM_ID),
      CONSTRAINT UQ_RL_MR_FAC_COD UNIQUE (MRF_MODELO_ID, MRF_CODIGO),
      CONSTRAINT CK_RL_MR_FAC_PESO CHECK (MRF_PESO_INSTITUCIONAL >= 0 AND MRF_PESO_INSTITUCIONAL <= 100),
      CONSTRAINT CK_RL_MR_FAC_REG CHECK (MRF_ESTADO_REGISTRO IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_VARIABLES',
    'CREATE TABLE RL_MR_VARIABLES (
      MRV_ID                 NUMBER(15) NOT NULL,
      MRV_FACTOR_ID          NUMBER(15) NOT NULL,
      MRV_CODIGO             VARCHAR2(40) NOT NULL,
      MRV_NOMBRE             VARCHAR2(150) NOT NULL,
      MRV_DESCRIPCION        VARCHAR2(1000),
      MRV_PESO_INTERNO       NUMBER(7,4) NOT NULL,
      MRV_TIPO_DATO          VARCHAR2(30) DEFAULT ''NUMERICO'' NOT NULL,
      MRV_FUENTE_DATO        VARCHAR2(50) DEFAULT ''CAPTURA'' NOT NULL,
      MRV_OBLIGATORIA        NUMBER(1) DEFAULT 1 NOT NULL,
      MRV_ORDEN              NUMBER(5) DEFAULT 1 NOT NULL,
      MRV_ESTADO_REGISTRO    NUMBER(1) DEFAULT 1 NOT NULL,
      MRV_MOTIVO_INACTIVO    VARCHAR2(1000),
      MRV_USR_CREACION_ID    NUMBER(10),
      MRV_FECHA_CREACION     DATE DEFAULT SYSDATE NOT NULL,
      MRV_USR_MODIF_ID       NUMBER(10),
      MRV_FECHA_MODIF        DATE,
      CONSTRAINT PK_RL_MR_VARIABLES PRIMARY KEY (MRV_ID),
      CONSTRAINT FK_RL_MR_VAR_FACTOR FOREIGN KEY (MRV_FACTOR_ID) REFERENCES RL_MR_FACTORES(MRF_ID),
      CONSTRAINT UQ_RL_MR_VAR_COD UNIQUE (MRV_FACTOR_ID, MRV_CODIGO),
      CONSTRAINT CK_RL_MR_VAR_PESO CHECK (MRV_PESO_INTERNO >= 0 AND MRV_PESO_INTERNO <= 100),
      CONSTRAINT CK_RL_MR_VAR_OBL CHECK (MRV_OBLIGATORIA IN (0,1)),
      CONSTRAINT CK_RL_MR_VAR_REG CHECK (MRV_ESTADO_REGISTRO IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_ESCALAS',
    'CREATE TABLE RL_MR_ESCALAS (
      MRE_ID                 NUMBER(15) NOT NULL,
      MRE_MODELO_ID          NUMBER(15) NOT NULL,
      MRE_TIPO               VARCHAR2(30) NOT NULL,
      MRE_VALOR_MIN          NUMBER(10,4) NOT NULL,
      MRE_VALOR_MAX          NUMBER(10,4) NOT NULL,
      MRE_NIVEL              VARCHAR2(40) NOT NULL,
      MRE_COLOR_HEX          VARCHAR2(10),
      MRE_DESCRIPCION        VARCHAR2(1000),
      MRE_ORDEN              NUMBER(5) DEFAULT 1 NOT NULL,
      MRE_ESTADO_REGISTRO    NUMBER(1) DEFAULT 1 NOT NULL,
      MRE_MOTIVO_INACTIVO    VARCHAR2(1000),
      CONSTRAINT PK_RL_MR_ESCALAS PRIMARY KEY (MRE_ID),
      CONSTRAINT FK_RL_MR_ESC_MODELO FOREIGN KEY (MRE_MODELO_ID) REFERENCES RL_MR_MODELOS(MRM_ID),
      CONSTRAINT UQ_RL_MR_ESC_RANGO UNIQUE (MRE_MODELO_ID, MRE_TIPO, MRE_VALOR_MIN, MRE_VALOR_MAX, MRE_NIVEL),
      CONSTRAINT CK_RL_MR_ESC_TIPO CHECK (MRE_TIPO IN (''VARIABLE'',''INHERENTE'',''RESIDUAL'',''CONTROL'')),
      CONSTRAINT CK_RL_MR_ESC_RANGO CHECK (MRE_VALOR_MIN <= MRE_VALOR_MAX),
      CONSTRAINT CK_RL_MR_ESC_REG CHECK (MRE_ESTADO_REGISTRO IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_CRITERIOS',
    'CREATE TABLE RL_MR_CRITERIOS (
      MRC_ID                 NUMBER(15) NOT NULL,
      MRC_VARIABLE_ID        NUMBER(15) NOT NULL,
      MRC_ESCALA_ID          NUMBER(15),
      MRC_VALOR_DESDE        NUMBER(10,4),
      MRC_VALOR_HASTA        NUMBER(10,4),
      MRC_PUNTAJE            NUMBER(10,4) NOT NULL,
      MRC_DESCRIPCION        VARCHAR2(1500) NOT NULL,
      MRC_ESTADO_REGISTRO    NUMBER(1) DEFAULT 1 NOT NULL,
      MRC_MOTIVO_INACTIVO    VARCHAR2(1000),
      CONSTRAINT PK_RL_MR_CRITERIOS PRIMARY KEY (MRC_ID),
      CONSTRAINT FK_RL_MR_CRI_VAR FOREIGN KEY (MRC_VARIABLE_ID) REFERENCES RL_MR_VARIABLES(MRV_ID),
      CONSTRAINT FK_RL_MR_CRI_ESC FOREIGN KEY (MRC_ESCALA_ID) REFERENCES RL_MR_ESCALAS(MRE_ID),
      CONSTRAINT CK_RL_MR_CRI_PUNTAJE CHECK (MRC_PUNTAJE >= 0),
      CONSTRAINT CK_RL_MR_CRI_REG CHECK (MRC_ESTADO_REGISTRO IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_MATRICES',
    'CREATE TABLE RL_MR_MATRICES (
      MRMAT_ID               NUMBER(15) NOT NULL,
      MRMAT_MODELO_ID        NUMBER(15) NOT NULL,
      MRMAT_SUJETO_TIPO      VARCHAR2(40) NOT NULL,
      MRMAT_SUJETO_ID_EXT    VARCHAR2(80),
      MRMAT_DOCUMENTO        VARCHAR2(80),
      MRMAT_NOMBRE_SUJETO    VARCHAR2(250) NOT NULL,
      MRMAT_ORIGEN_DATOS     VARCHAR2(50) DEFAULT ''CAPTURA'' NOT NULL,
      MRMAT_ESTADO           VARCHAR2(30) DEFAULT ''BORRADOR'' NOT NULL,
      MRMAT_FECHA_EVALUACION DATE DEFAULT SYSDATE NOT NULL,
      MRMAT_FECHA_CIERRE     DATE,
      MRMAT_CERRADO_POR      NUMBER(10),
      MRMAT_MOTIVO_ESTADO    VARCHAR2(1000),
      MRMAT_SNAPSHOT_METODO  CLOB,
      MRMAT_USR_CREACION_ID  NUMBER(10),
      MRMAT_FECHA_CREACION   DATE DEFAULT SYSDATE NOT NULL,
      MRMAT_USR_MODIF_ID     NUMBER(10),
      MRMAT_FECHA_MODIF      DATE,
      MRMAT_ESTADO_REGISTRO  NUMBER(1) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_RL_MR_MATRICES PRIMARY KEY (MRMAT_ID),
      CONSTRAINT FK_RL_MR_MAT_MODELO FOREIGN KEY (MRMAT_MODELO_ID) REFERENCES RL_MR_MODELOS(MRM_ID),
      CONSTRAINT CK_RL_MR_MAT_SUJETO CHECK (MRMAT_SUJETO_TIPO IN (''PROVEEDOR'',''CLIENTE_PATRONO'',''EMPLEADO'',''AREA'',''PROCESO'',''CASO_POSITIVO'',''INSTITUCIONAL'')),
      CONSTRAINT CK_RL_MR_MAT_ESTADO CHECK (MRMAT_ESTADO IN (''BORRADOR'',''EN_EVALUACION'',''CALCULADA'',''EN_REVISION'',''OBSERVADA'',''APROBADA'',''CERRADA'',''INACTIVA'')),
      CONSTRAINT CK_RL_MR_MAT_REG CHECK (MRMAT_ESTADO_REGISTRO IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_DETALLE',
    'CREATE TABLE RL_MR_DETALLE (
      MRD_ID                 NUMBER(15) NOT NULL,
      MRD_MATRIZ_ID          NUMBER(15) NOT NULL,
      MRD_VARIABLE_ID        NUMBER(15) NOT NULL,
      MRD_VALOR_CAPTURADO    VARCHAR2(500),
      MRD_PUNTAJE            NUMBER(10,4) NOT NULL,
      MRD_PESO_SNAPSHOT      NUMBER(7,4) NOT NULL,
      MRD_PUNTAJE_PONDERADO  NUMBER(10,4) NOT NULL,
      MRD_JUSTIFICACION      VARCHAR2(1500),
      MRD_FUENTE_DATO        VARCHAR2(80),
      MRD_SNAPSHOT_VARIABLE  CLOB,
      MRD_USR_CREACION_ID    NUMBER(10),
      MRD_FECHA_CREACION     DATE DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_RL_MR_DETALLE PRIMARY KEY (MRD_ID),
      CONSTRAINT FK_RL_MR_DET_MATRIZ FOREIGN KEY (MRD_MATRIZ_ID) REFERENCES RL_MR_MATRICES(MRMAT_ID),
      CONSTRAINT FK_RL_MR_DET_VARIABLE FOREIGN KEY (MRD_VARIABLE_ID) REFERENCES RL_MR_VARIABLES(MRV_ID),
      CONSTRAINT UQ_RL_MR_DET_VAR UNIQUE (MRD_MATRIZ_ID, MRD_VARIABLE_ID)
    )'
  );

  create_table_if_missing('RL_MR_CONTROLES',
    'CREATE TABLE RL_MR_CONTROLES (
      MRCTRL_ID              NUMBER(15) NOT NULL,
      MRCTRL_MATRIZ_ID       NUMBER(15) NOT NULL,
      MRCTRL_FACTOR_ID       NUMBER(15),
      MRCTRL_NOMBRE          VARCHAR2(200) NOT NULL,
      MRCTRL_DESCRIPCION     VARCHAR2(1500),
      MRCTRL_PERIODICIDAD    VARCHAR2(40),
      MRCTRL_OPORTUNIDAD     VARCHAR2(40),
      MRCTRL_AUTOMATIZACION  VARCHAR2(40),
      MRCTRL_PROCEDIMIENTOS  VARCHAR2(40),
      MRCTRL_CALIDAD         VARCHAR2(40),
      MRCTRL_EFECTIVIDAD_PCT NUMBER(7,4) DEFAULT 0 NOT NULL,
      MRCTRL_RESPONSABLE     VARCHAR2(150),
      MRCTRL_ESTADO          VARCHAR2(30) DEFAULT ''ACTIVO'' NOT NULL,
      MRCTRL_MOTIVO_INACTIVO VARCHAR2(1000),
      MRCTRL_EVIDENCIA_OBL   NUMBER(1) DEFAULT 0 NOT NULL,
      MRCTRL_USR_CREACION_ID NUMBER(10),
      MRCTRL_FECHA_CREACION  DATE DEFAULT SYSDATE NOT NULL,
      MRCTRL_USR_MODIF_ID    NUMBER(10),
      MRCTRL_FECHA_MODIF     DATE,
      CONSTRAINT PK_RL_MR_CONTROLES PRIMARY KEY (MRCTRL_ID),
      CONSTRAINT FK_RL_MR_CTRL_MATRIZ FOREIGN KEY (MRCTRL_MATRIZ_ID) REFERENCES RL_MR_MATRICES(MRMAT_ID),
      CONSTRAINT FK_RL_MR_CTRL_FACTOR FOREIGN KEY (MRCTRL_FACTOR_ID) REFERENCES RL_MR_FACTORES(MRF_ID),
      CONSTRAINT CK_RL_MR_CTRL_EFEC CHECK (MRCTRL_EFECTIVIDAD_PCT >= 0 AND MRCTRL_EFECTIVIDAD_PCT <= 100),
      CONSTRAINT CK_RL_MR_CTRL_EVID CHECK (MRCTRL_EVIDENCIA_OBL IN (0,1)),
      CONSTRAINT CK_RL_MR_CTRL_EST CHECK (MRCTRL_ESTADO IN (''ACTIVO'',''OBSERVADO'',''INACTIVO''))
    )'
  );

  create_table_if_missing('RL_MR_RESULTADOS',
    'CREATE TABLE RL_MR_RESULTADOS (
      MRR_ID                 NUMBER(15) NOT NULL,
      MRR_MATRIZ_ID          NUMBER(15) NOT NULL,
      MRR_FACTOR_ID          NUMBER(15),
      MRR_TIPO_RESULTADO     VARCHAR2(30) NOT NULL,
      MRR_VERSION_CALCULO    VARCHAR2(30) DEFAULT ''1.0'' NOT NULL,
      MRR_ES_VIGENTE         NUMBER(1) DEFAULT 1 NOT NULL,
      MRR_PUNTAJE_INHERENTE  NUMBER(10,4) NOT NULL,
      MRR_NIVEL_INHERENTE    VARCHAR2(40) NOT NULL,
      MRR_MITIGACION_PCT     NUMBER(7,4) DEFAULT 0 NOT NULL,
      MRR_PUNTAJE_RESIDUAL   NUMBER(10,4) NOT NULL,
      MRR_NIVEL_RESIDUAL     VARCHAR2(40) NOT NULL,
      MRR_REQUIERE_PLAN      NUMBER(1) DEFAULT 0 NOT NULL,
      MRR_MOTIVO_RECALCULO   VARCHAR2(1000),
      MRR_RESULTADO_ANTERIOR_ID NUMBER(15),
      MRR_SNAPSHOT_CALCULO   CLOB,
      MRR_FECHA_CALCULO      DATE DEFAULT SYSDATE NOT NULL,
      MRR_USR_CALCULO_ID     NUMBER(10),
      CONSTRAINT PK_RL_MR_RESULTADOS PRIMARY KEY (MRR_ID),
      CONSTRAINT FK_RL_MR_RES_MATRIZ FOREIGN KEY (MRR_MATRIZ_ID) REFERENCES RL_MR_MATRICES(MRMAT_ID),
      CONSTRAINT FK_RL_MR_RES_FACTOR FOREIGN KEY (MRR_FACTOR_ID) REFERENCES RL_MR_FACTORES(MRF_ID),
      CONSTRAINT FK_RL_MR_RES_ANTERIOR FOREIGN KEY (MRR_RESULTADO_ANTERIOR_ID) REFERENCES RL_MR_RESULTADOS(MRR_ID),
      CONSTRAINT CK_RL_MR_RES_TIPO CHECK (MRR_TIPO_RESULTADO IN (''FACTOR'',''INSTITUCIONAL'')),
      CONSTRAINT CK_RL_MR_RES_VIG CHECK (MRR_ES_VIGENTE IN (0,1)),
      CONSTRAINT CK_RL_MR_RES_PLAN CHECK (MRR_REQUIERE_PLAN IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_PLANES_ACCION',
    'CREATE TABLE RL_MR_PLANES_ACCION (
      MRPA_ID                NUMBER(15) NOT NULL,
      MRPA_MATRIZ_ID         NUMBER(15) NOT NULL,
      MRPA_RESULTADO_ID      NUMBER(15),
      MRPA_ACTIVIDAD         VARCHAR2(2000) NOT NULL,
      MRPA_RESPONSABLE       VARCHAR2(150) NOT NULL,
      MRPA_PERIODICIDAD      VARCHAR2(80),
      MRPA_FECHA_INICIO      DATE,
      MRPA_FECHA_FIN         DATE,
      MRPA_MEDIO_PRUEBA      VARCHAR2(1000),
      MRPA_OBSERVACIONES     VARCHAR2(1500),
      MRPA_ESTADO            VARCHAR2(30) DEFAULT ''PENDIENTE'' NOT NULL,
      MRPA_MOTIVO_CIERRE     VARCHAR2(1000),
      MRPA_USR_CREACION_ID   NUMBER(10),
      MRPA_FECHA_CREACION    DATE DEFAULT SYSDATE NOT NULL,
      MRPA_USR_CIERRE_ID     NUMBER(10),
      MRPA_FECHA_CIERRE      DATE,
      CONSTRAINT PK_RL_MR_PLANES_ACCION PRIMARY KEY (MRPA_ID),
      CONSTRAINT FK_RL_MR_PLAN_MATRIZ FOREIGN KEY (MRPA_MATRIZ_ID) REFERENCES RL_MR_MATRICES(MRMAT_ID),
      CONSTRAINT FK_RL_MR_PLAN_RESULT FOREIGN KEY (MRPA_RESULTADO_ID) REFERENCES RL_MR_RESULTADOS(MRR_ID),
      CONSTRAINT CK_RL_MR_PLAN_EST CHECK (MRPA_ESTADO IN (''PENDIENTE'',''EN_PROCESO'',''CERRADO'',''VENCIDO'',''INACTIVO''))
    )'
  );

  create_table_if_missing('RL_MR_EVIDENCIAS',
    'CREATE TABLE RL_MR_EVIDENCIAS (
      MREV_ID                NUMBER(15) NOT NULL,
      MREV_MATRIZ_ID         NUMBER(15) NOT NULL,
      MREV_CONTROL_ID        NUMBER(15),
      MREV_PLAN_ID           NUMBER(15),
      MREV_NOMBRE_ORIGINAL   VARCHAR2(255) NOT NULL,
      MREV_NOMBRE_FISICO     VARCHAR2(255) NOT NULL,
      MREV_TIPO_MIME         VARCHAR2(120),
      MREV_EXTENSION         VARCHAR2(20),
      MREV_TAMANO_BYTES      NUMBER(15),
      MREV_RUTA_FISICA       VARCHAR2(1000) NOT NULL,
      MREV_HASH_SHA256       VARCHAR2(100),
      MREV_ESTADO_REGISTRO   NUMBER(1) DEFAULT 1 NOT NULL,
      MREV_MOTIVO_INACTIVO   VARCHAR2(1000),
      MREV_USR_CREACION_ID   NUMBER(10),
      MREV_FECHA_CREACION    DATE DEFAULT SYSDATE NOT NULL,
      MREV_USR_INACTIVO_ID   NUMBER(10),
      MREV_FECHA_INACTIVO    DATE,
      CONSTRAINT PK_RL_MR_EVIDENCIAS PRIMARY KEY (MREV_ID),
      CONSTRAINT FK_RL_MR_EVI_MATRIZ FOREIGN KEY (MREV_MATRIZ_ID) REFERENCES RL_MR_MATRICES(MRMAT_ID),
      CONSTRAINT FK_RL_MR_EVI_CONTROL FOREIGN KEY (MREV_CONTROL_ID) REFERENCES RL_MR_CONTROLES(MRCTRL_ID),
      CONSTRAINT FK_RL_MR_EVI_PLAN FOREIGN KEY (MREV_PLAN_ID) REFERENCES RL_MR_PLANES_ACCION(MRPA_ID),
      CONSTRAINT UQ_RL_MR_EVI_FISICO UNIQUE (MREV_NOMBRE_FISICO),
      CONSTRAINT CK_RL_MR_EVI_REG CHECK (MREV_ESTADO_REGISTRO IN (0,1))
    )'
  );

  create_table_if_missing('RL_MR_HISTORIAL',
    'CREATE TABLE RL_MR_HISTORIAL (
      MRH_ID                 NUMBER(20) NOT NULL,
      MRH_MATRIZ_ID          NUMBER(15),
      MRH_TABLA              VARCHAR2(60) NOT NULL,
      MRH_REGISTRO_ID        VARCHAR2(80) NOT NULL,
      MRH_ACCION             VARCHAR2(40) NOT NULL,
      MRH_ESTADO_ANTERIOR    VARCHAR2(60),
      MRH_ESTADO_NUEVO       VARCHAR2(60),
      MRH_MOTIVO             VARCHAR2(1500),
      MRH_DATOS_ANT          CLOB,
      MRH_DATOS_NVO          CLOB,
      MRH_USR_ID             NUMBER(10),
      MRH_USR_EMAIL          VARCHAR2(150),
      MRH_IP                 VARCHAR2(45),
      MRH_FECHA              DATE DEFAULT SYSDATE NOT NULL,
      CONSTRAINT PK_RL_MR_HISTORIAL PRIMARY KEY (MRH_ID),
      CONSTRAINT FK_RL_MR_HIS_MATRIZ FOREIGN KEY (MRH_MATRIZ_ID) REFERENCES RL_MR_MATRICES(MRMAT_ID)
    )'
  );

  create_table_if_missing('RL_MR_INTEGRACION_DNP',
    'CREATE TABLE RL_MR_INTEGRACION_DNP (
      MRDNP_ID               NUMBER(15) NOT NULL,
      MRDNP_MATRIZ_ID        NUMBER(15) NOT NULL,
      MRDNP_NUMERO_PATRONO   VARCHAR2(25),
      MRDNP_CALIFICACION     VARCHAR2(60) NOT NULL,
      MRDNP_PUNTAJE_RESIDUAL NUMBER(10,4),
      MRDNP_ESTADO_ENVIO     VARCHAR2(30) DEFAULT ''PENDIENTE'' NOT NULL,
      MRDNP_INTENTOS         NUMBER(5) DEFAULT 0 NOT NULL,
      MRDNP_RESPUESTA        CLOB,
      MRDNP_FECHA_CREACION   DATE DEFAULT SYSDATE NOT NULL,
      MRDNP_FECHA_ENVIO      DATE,
      CONSTRAINT PK_RL_MR_INTEGRACION_DNP PRIMARY KEY (MRDNP_ID),
      CONSTRAINT FK_RL_MR_DNP_MATRIZ FOREIGN KEY (MRDNP_MATRIZ_ID) REFERENCES RL_MR_MATRICES(MRMAT_ID),
      CONSTRAINT CK_RL_MR_DNP_EST CHECK (MRDNP_ESTADO_ENVIO IN (''PENDIENTE'',''ENVIADO'',''ERROR'',''ANULADO''))
    )'
  );

  create_index_if_missing('IDX_RL_MR_FAC_MODELO', 'CREATE INDEX IDX_RL_MR_FAC_MODELO ON RL_MR_FACTORES(MRF_MODELO_ID)');
  create_index_if_missing('IDX_RL_MR_VAR_FACTOR', 'CREATE INDEX IDX_RL_MR_VAR_FACTOR ON RL_MR_VARIABLES(MRV_FACTOR_ID)');
  create_index_if_missing('IDX_RL_MR_ESC_MODELO', 'CREATE INDEX IDX_RL_MR_ESC_MODELO ON RL_MR_ESCALAS(MRE_MODELO_ID, MRE_TIPO)');
  create_index_if_missing('IDX_RL_MR_MAT_MODELO', 'CREATE INDEX IDX_RL_MR_MAT_MODELO ON RL_MR_MATRICES(MRMAT_MODELO_ID)');
  create_index_if_missing('IDX_RL_MR_MAT_SUJETO', 'CREATE INDEX IDX_RL_MR_MAT_SUJETO ON RL_MR_MATRICES(MRMAT_SUJETO_TIPO, MRMAT_SUJETO_ID_EXT, MRMAT_DOCUMENTO)');
  create_index_if_missing('IDX_RL_MR_MAT_ESTADO', 'CREATE INDEX IDX_RL_MR_MAT_ESTADO ON RL_MR_MATRICES(MRMAT_ESTADO, MRMAT_ESTADO_REGISTRO)');
  create_index_if_missing('IDX_RL_MR_DET_MATRIZ', 'CREATE INDEX IDX_RL_MR_DET_MATRIZ ON RL_MR_DETALLE(MRD_MATRIZ_ID)');
  create_index_if_missing('IDX_RL_MR_RES_MATRIZ', 'CREATE INDEX IDX_RL_MR_RES_MATRIZ ON RL_MR_RESULTADOS(MRR_MATRIZ_ID)');
  create_index_if_missing(
    'UQ_RL_MR_RES_VIGENTE',
    'CREATE UNIQUE INDEX UQ_RL_MR_RES_VIGENTE ON RL_MR_RESULTADOS (
      CASE WHEN MRR_ES_VIGENTE = 1 THEN MRR_MATRIZ_ID END,
      CASE WHEN MRR_ES_VIGENTE = 1 THEN NVL(MRR_FACTOR_ID, -1) END,
      CASE WHEN MRR_ES_VIGENTE = 1 THEN MRR_TIPO_RESULTADO END
    )'
  );
  create_index_if_missing('IDX_RL_MR_CTRL_MATRIZ', 'CREATE INDEX IDX_RL_MR_CTRL_MATRIZ ON RL_MR_CONTROLES(MRCTRL_MATRIZ_ID)');
  create_index_if_missing('IDX_RL_MR_PLAN_MATRIZ', 'CREATE INDEX IDX_RL_MR_PLAN_MATRIZ ON RL_MR_PLANES_ACCION(MRPA_MATRIZ_ID)');
  create_index_if_missing('IDX_RL_MR_EVI_MATRIZ', 'CREATE INDEX IDX_RL_MR_EVI_MATRIZ ON RL_MR_EVIDENCIAS(MREV_MATRIZ_ID)');
  create_index_if_missing('IDX_RL_MR_HIS_MATRIZ', 'CREATE INDEX IDX_RL_MR_HIS_MATRIZ ON RL_MR_HISTORIAL(MRH_MATRIZ_ID, MRH_FECHA)');
  create_index_if_missing('IDX_RL_MR_DNP_ESTADO', 'CREATE INDEX IDX_RL_MR_DNP_ESTADO ON RL_MR_INTEGRACION_DNP(MRDNP_ESTADO_ENVIO, MRDNP_FECHA_CREACION)');
END;
/

COMMENT ON TABLE RL_MR_MODELOS IS 'Versiones metodológicas aprobables/aprobadas del módulo Matrices de Riesgos.';
COMMENT ON TABLE RL_MR_FACTORES IS 'Factores institucionales obligatorios: Proveedores, Clientes/Patronos y Empleados.';
COMMENT ON TABLE RL_MR_VARIABLES IS 'Variables internas por factor institucional, con ponderación interna totalizable al 100% por factor.';
COMMENT ON TABLE RL_MR_ESCALAS IS 'Rangos y niveles de calificación para variables, riesgo inherente, residual y controles.';
COMMENT ON TABLE RL_MR_CRITERIOS IS 'Criterios de calificación por variable y escala.';
COMMENT ON TABLE RL_MR_MATRICES IS 'Encabezado de matrices generadas por sujeto evaluado o matriz institucional.';
COMMENT ON TABLE RL_MR_DETALLE IS 'Detalle de variables evaluadas en una matriz, con snapshot de peso y puntaje.';
COMMENT ON TABLE RL_MR_CONTROLES IS 'Controles mitigantes asociados a la matriz y a factores cuando aplique.';
COMMENT ON TABLE RL_MR_RESULTADOS IS 'Resultados de riesgo inherente, mitigación y riesgo residual por factor e institucional.';
COMMENT ON TABLE RL_MR_PLANES_ACCION IS 'Planes de acción obligatorios o voluntarios asociados al resultado de la matriz.';
COMMENT ON TABLE RL_MR_EVIDENCIAS IS 'Metadatos de evidencias protegidas asociadas a matrices, controles o planes.';
COMMENT ON TABLE RL_MR_HISTORIAL IS 'Historial funcional del módulo; complementa RL_AUDITORIA para trazabilidad específica de matrices.';
COMMENT ON TABLE RL_MR_INTEGRACION_DNP IS 'Bandeja local para integración futura obligatoria hacia DNP, sin escritura directa hasta aprobación técnica.';

COMMENT ON COLUMN RL_MR_MODELOS.MRM_ID IS 'Identificador único del modelo metodológico de matrices de riesgos.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_NOMBRE IS 'Nombre del modelo metodológico.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_VERSION IS 'Versión funcional y técnica del modelo metodológico.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_DESCRIPCION IS 'Descripción general del alcance metodológico del modelo.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_ESTADO IS 'Estado del modelo: BORRADOR, EN_REVISION, APROBADO, CERRADO o INACTIVO.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_FECHA_VIGENCIA IS 'Fecha desde la cual la versión metodológica puede aplicarse.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_FECHA_CIERRE IS 'Fecha de cierre o retiro de la versión metodológica.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_APROBADO_POR IS 'Usuario responsable de aprobar la versión metodológica.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_FECHA_APROBACION IS 'Fecha de aprobación de la versión metodológica.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_MOTIVO_ESTADO IS 'Motivo funcional del cambio de estado del modelo.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_USR_CREACION_ID IS 'Usuario que registró el modelo.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_FECHA_CREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_USR_MODIF_ID IS 'Último usuario que modificó el registro.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_FECHA_MODIF IS 'Fecha de última modificación del registro.';
COMMENT ON COLUMN RL_MR_MODELOS.MRM_ESTADO_REGISTRO IS 'Indicador de registro activo o inactivo para eliminación lógica.';

COMMENT ON COLUMN RL_MR_FACTORES.MRF_ID IS 'Identificador único del factor institucional.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_MODELO_ID IS 'Modelo metodológico al que pertenece el factor.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_CODIGO IS 'Código funcional del factor institucional.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_NOMBRE IS 'Nombre del factor institucional.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_DESCRIPCION IS 'Descripción funcional del factor institucional.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_PESO_INSTITUCIONAL IS 'Peso institucional fijo del factor dentro del riesgo total.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_ORDEN IS 'Orden de presentación y cálculo del factor.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_ESTADO_REGISTRO IS 'Indicador de registro activo o inactivo para eliminación lógica.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_MOTIVO_INACTIVO IS 'Motivo obligatorio cuando el factor se inactive lógicamente.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_USR_CREACION_ID IS 'Usuario que registró el factor.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_FECHA_CREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_USR_MODIF_ID IS 'Último usuario que modificó el registro.';
COMMENT ON COLUMN RL_MR_FACTORES.MRF_FECHA_MODIF IS 'Fecha de última modificación del registro.';

COMMENT ON COLUMN RL_MR_VARIABLES.MRV_ID IS 'Identificador único de la variable interna.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_FACTOR_ID IS 'Factor institucional al que pertenece la variable.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_CODIGO IS 'Código funcional de la variable dentro del factor.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_NOMBRE IS 'Nombre de la variable de riesgo.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_DESCRIPCION IS 'Descripción funcional de la variable de riesgo.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_PESO_INTERNO IS 'Peso interno de la variable dentro del factor; debe totalizar 100% por factor.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_TIPO_DATO IS 'Tipo de dato esperado para capturar o calcular la variable.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_FUENTE_DATO IS 'Origen funcional del dato: captura, consulta o integración autorizada.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_OBLIGATORIA IS 'Indica si la variable es obligatoria para completar la matriz.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_ORDEN IS 'Orden de presentación y cálculo de la variable.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_ESTADO_REGISTRO IS 'Indicador de registro activo o inactivo para eliminación lógica.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_MOTIVO_INACTIVO IS 'Motivo obligatorio cuando la variable se inactive lógicamente.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_USR_CREACION_ID IS 'Usuario que registró la variable.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_FECHA_CREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_USR_MODIF_ID IS 'Último usuario que modificó el registro.';
COMMENT ON COLUMN RL_MR_VARIABLES.MRV_FECHA_MODIF IS 'Fecha de última modificación del registro.';

COMMENT ON COLUMN RL_MR_ESCALAS.MRE_ID IS 'Identificador único de la escala metodológica.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_MODELO_ID IS 'Modelo metodológico al que pertenece la escala.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_TIPO IS 'Tipo de escala: VARIABLE, INHERENTE, RESIDUAL o CONTROL.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_VALOR_MIN IS 'Valor mínimo del rango de la escala.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_VALOR_MAX IS 'Valor máximo del rango de la escala.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_NIVEL IS 'Nivel funcional asignado al rango de la escala.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_COLOR_HEX IS 'Color sugerido para representar visualmente el nivel.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_DESCRIPCION IS 'Descripción funcional del rango o nivel de escala.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_ORDEN IS 'Orden de presentación del nivel dentro de la escala.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_ESTADO_REGISTRO IS 'Indicador de registro activo o inactivo para eliminación lógica.';
COMMENT ON COLUMN RL_MR_ESCALAS.MRE_MOTIVO_INACTIVO IS 'Motivo obligatorio cuando la escala se inactive lógicamente.';

COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_ID IS 'Identificador único del criterio de calificación.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_VARIABLE_ID IS 'Variable de riesgo a la que pertenece el criterio.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_ESCALA_ID IS 'Escala relacionada con el criterio cuando aplique.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_VALOR_DESDE IS 'Valor inicial del rango del criterio.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_VALOR_HASTA IS 'Valor final del rango del criterio.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_PUNTAJE IS 'Puntaje asignado cuando el criterio se cumple.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_DESCRIPCION IS 'Descripción funcional del criterio de calificación.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_ESTADO_REGISTRO IS 'Indicador de registro activo o inactivo para eliminación lógica.';
COMMENT ON COLUMN RL_MR_CRITERIOS.MRC_MOTIVO_INACTIVO IS 'Motivo obligatorio cuando el criterio se inactive lógicamente.';

COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_ID IS 'Identificador único de la matriz generada.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_MODELO_ID IS 'Modelo metodológico usado por la matriz.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_SUJETO_TIPO IS 'Tipo de sujeto evaluado por la matriz.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_SUJETO_ID_EXT IS 'Identificador externo del sujeto evaluado cuando aplique.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_DOCUMENTO IS 'Documento, código o número de referencia del sujeto evaluado.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_NOMBRE_SUJETO IS 'Nombre o descripción del sujeto evaluado.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_ORIGEN_DATOS IS 'Origen de datos usado para construir la matriz.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_ESTADO IS 'Estado funcional de la matriz: BORRADOR, CALCULADA, EN_REVISION, OBSERVADA, APROBADA, CERRADA o INACTIVA.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_FECHA_EVALUACION IS 'Fecha en que se registra o calcula la evaluación.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_FECHA_CIERRE IS 'Fecha de cierre formal de la matriz.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_CERRADO_POR IS 'Usuario que cerró formalmente la matriz.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_MOTIVO_ESTADO IS 'Motivo funcional del cambio de estado de la matriz.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_SNAPSHOT_METODO IS 'Snapshot de la metodología usada para proteger matrices cerradas.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_USR_CREACION_ID IS 'Usuario que registró la matriz.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_FECHA_CREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_USR_MODIF_ID IS 'Último usuario que modificó el registro.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_FECHA_MODIF IS 'Fecha de última modificación del registro.';
COMMENT ON COLUMN RL_MR_MATRICES.MRMAT_ESTADO_REGISTRO IS 'Indicador de registro activo o inactivo para eliminación lógica.';

COMMENT ON COLUMN RL_MR_DETALLE.MRD_ID IS 'Identificador único del detalle evaluado.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_MATRIZ_ID IS 'Matriz a la que pertenece el detalle.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_VARIABLE_ID IS 'Variable evaluada dentro de la matriz.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_VALOR_CAPTURADO IS 'Valor capturado, consultado o calculado para la variable.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_PUNTAJE IS 'Puntaje asignado a la variable.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_PESO_SNAPSHOT IS 'Peso de la variable al momento del cálculo.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_PUNTAJE_PONDERADO IS 'Resultado ponderado de la variable.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_JUSTIFICACION IS 'Justificación funcional del valor o puntaje asignado.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_FUENTE_DATO IS 'Fuente del dato usado para evaluar la variable.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_SNAPSHOT_VARIABLE IS 'Snapshot de la variable y criterio usados en el cálculo.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_USR_CREACION_ID IS 'Usuario que registró el detalle.';
COMMENT ON COLUMN RL_MR_DETALLE.MRD_FECHA_CREACION IS 'Fecha de creación del detalle.';

COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_ID IS 'Identificador único del control mitigante.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_MATRIZ_ID IS 'Matriz a la que pertenece el control mitigante.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_FACTOR_ID IS 'Factor institucional al que se asocia el control cuando aplique.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_NOMBRE IS 'Nombre del control mitigante.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_DESCRIPCION IS 'Descripción funcional del control mitigante.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_PERIODICIDAD IS 'Periodicidad con la que opera o se revisa el control.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_OPORTUNIDAD IS 'Oportunidad del control respecto al evento de riesgo.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_AUTOMATIZACION IS 'Nivel de automatización del control.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_PROCEDIMIENTOS IS 'Nivel de formalización de procedimientos del control.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_CALIDAD IS 'Calidad general del control según metodología aprobada.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_EFECTIVIDAD_PCT IS 'Porcentaje de efectividad o mitigación calculada para el control.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_RESPONSABLE IS 'Responsable funcional del control.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_ESTADO IS 'Estado funcional del control.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_MOTIVO_INACTIVO IS 'Motivo obligatorio cuando el control se inactive lógicamente.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_EVIDENCIA_OBL IS 'Indica si el control requiere evidencia documental obligatoria.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_USR_CREACION_ID IS 'Usuario que registró el control.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_FECHA_CREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_USR_MODIF_ID IS 'Último usuario que modificó el registro.';
COMMENT ON COLUMN RL_MR_CONTROLES.MRCTRL_FECHA_MODIF IS 'Fecha de última modificación del registro.';

COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_ID IS 'Identificador único del resultado de cálculo.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_MATRIZ_ID IS 'Matriz a la que pertenece el resultado.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_FACTOR_ID IS 'Factor institucional asociado cuando el resultado es por factor.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_TIPO_RESULTADO IS 'Tipo de resultado: por factor o institucional.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_VERSION_CALCULO IS 'Versión del algoritmo o regla de cálculo usada.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_ES_VIGENTE IS 'Indica si el resultado es el vigente para la matriz, factor y tipo.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_PUNTAJE_INHERENTE IS 'Puntaje de riesgo inherente calculado.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_NIVEL_INHERENTE IS 'Nivel de riesgo inherente calculado.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_MITIGACION_PCT IS 'Porcentaje de mitigación aplicado por controles.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_PUNTAJE_RESIDUAL IS 'Puntaje de riesgo residual calculado.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_NIVEL_RESIDUAL IS 'Nivel de riesgo residual calculado.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_REQUIERE_PLAN IS 'Indica si el resultado exige plan de acción.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_MOTIVO_RECALCULO IS 'Motivo funcional cuando se genera un recálculo.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_RESULTADO_ANTERIOR_ID IS 'Resultado anterior relacionado con el recálculo.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_SNAPSHOT_CALCULO IS 'Snapshot de entradas, reglas y salida del cálculo.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_FECHA_CALCULO IS 'Fecha en que se generó el resultado.';
COMMENT ON COLUMN RL_MR_RESULTADOS.MRR_USR_CALCULO_ID IS 'Usuario que ejecutó o solicitó el cálculo.';

COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_ID IS 'Identificador único del plan de acción.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_MATRIZ_ID IS 'Matriz asociada al plan de acción.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_RESULTADO_ID IS 'Resultado que originó el plan de acción cuando aplique.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_ACTIVIDAD IS 'Actividad o acción correctiva definida.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_RESPONSABLE IS 'Responsable funcional de ejecutar la actividad.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_PERIODICIDAD IS 'Periodicidad de ejecución o seguimiento del plan.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_FECHA_INICIO IS 'Fecha planificada de inicio.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_FECHA_FIN IS 'Fecha planificada o real de finalización.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_MEDIO_PRUEBA IS 'Medio de prueba requerido para evidenciar cumplimiento.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_OBSERVACIONES IS 'Observaciones funcionales del plan de acción.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_ESTADO IS 'Estado funcional del plan de acción.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_MOTIVO_CIERRE IS 'Motivo o justificación del cierre del plan.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_USR_CREACION_ID IS 'Usuario que registró el plan de acción.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_FECHA_CREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_USR_CIERRE_ID IS 'Usuario que cerró el plan de acción.';
COMMENT ON COLUMN RL_MR_PLANES_ACCION.MRPA_FECHA_CIERRE IS 'Fecha de cierre del plan de acción.';

COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_ID IS 'Identificador único de la evidencia documental.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_MATRIZ_ID IS 'Matriz asociada a la evidencia.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_CONTROL_ID IS 'Control asociado a la evidencia cuando aplique.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_PLAN_ID IS 'Plan de acción asociado a la evidencia cuando aplique.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_NOMBRE_ORIGINAL IS 'Nombre original del archivo cargado por el usuario.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_NOMBRE_FISICO IS 'Nombre físico seguro asignado al archivo.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_TIPO_MIME IS 'Tipo MIME identificado para el archivo.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_EXTENSION IS 'Extensión validada del archivo.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_TAMANO_BYTES IS 'Tamaño del archivo en bytes.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_RUTA_FISICA IS 'Ruta protegida de almacenamiento físico.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_HASH_SHA256 IS 'Huella SHA-256 del archivo cuando aplique.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_ESTADO_REGISTRO IS 'Indicador de registro activo o inactivo para eliminación lógica.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_MOTIVO_INACTIVO IS 'Motivo obligatorio cuando la evidencia se inactive lógicamente.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_USR_CREACION_ID IS 'Usuario que cargó o registró la evidencia.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_FECHA_CREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_USR_INACTIVO_ID IS 'Usuario que realizó la eliminación lógica.';
COMMENT ON COLUMN RL_MR_EVIDENCIAS.MREV_FECHA_INACTIVO IS 'Fecha de eliminación lógica de la evidencia.';

COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_ID IS 'Identificador único del evento histórico funcional.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_MATRIZ_ID IS 'Matriz asociada al evento histórico cuando aplique.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_TABLA IS 'Tabla funcional sobre la que ocurrió el evento.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_REGISTRO_ID IS 'Identificador del registro afectado por el evento.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_ACCION IS 'Acción funcional registrada.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_ESTADO_ANTERIOR IS 'Estado anterior del registro cuando aplique.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_ESTADO_NUEVO IS 'Estado nuevo del registro cuando aplique.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_MOTIVO IS 'Motivo funcional del evento histórico.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_DATOS_ANT IS 'Snapshot de datos anteriores cuando aplique.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_DATOS_NVO IS 'Snapshot de datos nuevos cuando aplique.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_USR_ID IS 'Usuario responsable del evento.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_USR_EMAIL IS 'Correo del usuario responsable del evento.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_IP IS 'Dirección IP registrada para el evento.';
COMMENT ON COLUMN RL_MR_HISTORIAL.MRH_FECHA IS 'Fecha y hora del evento histórico.';

COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_ID IS 'Identificador único del registro de integración futura con DNP.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_MATRIZ_ID IS 'Matriz asociada a la calificación que se integrará.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_NUMERO_PATRONO IS 'Número de patrono relacionado cuando aplique.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_CALIFICACION IS 'Calificación de riesgo preparada para integración futura.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_PUNTAJE_RESIDUAL IS 'Puntaje residual asociado a la calificación.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_ESTADO_ENVIO IS 'Estado de la integración futura: PENDIENTE, ENVIADO, ERROR o ANULADO.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_INTENTOS IS 'Cantidad de intentos de envío registrados.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_RESPUESTA IS 'Respuesta técnica recibida de la integración cuando aplique.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_FECHA_CREACION IS 'Fecha de creación del registro de integración.';
COMMENT ON COLUMN RL_MR_INTEGRACION_DNP.MRDNP_FECHA_ENVIO IS 'Fecha de envío hacia la integración cuando aplique.';

COMMIT;
