SET PAGESIZE 100
SET LINESIZE 220
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SELECT m.MRMAT_ID, ri.MRR_NIVEL_RESIDUAL, UPPER(ri.MRR_NIVEL_RESIDUAL) AS NIVEL_UPPER,
       CASE WHEN UPPER(NVL(ri.MRR_NIVEL_RESIDUAL, '')) IN ('ALTO','CRITICO','CR?TICO') THEN 1 ELSE 0 END AS FLAG_SIMPLE,
       CASE WHEN UPPER(NVL(ri.MRR_NIVEL_RESIDUAL, '')) = 'ALTO' OR UPPER(NVL(ri.MRR_NIVEL_RESIDUAL, '')) LIKE 'CR%' THEN 1 ELSE 0 END AS FLAG_NORMALIZADO
  FROM RL_MR_MATRICES m
  JOIN RL_MR_RESULTADOS ri
    ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
   AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
   AND ri.MRR_ES_VIGENTE = 1
 WHERE m.MRMAT_ESTADO_REGISTRO = 1
 ORDER BY m.MRMAT_ID;
EXIT
