SET PAGESIZE 500
SET LINESIZE 260
SET FEEDBACK ON
SET VERIFY OFF
SET HEADING ON
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
PROMPT VALIDACION_FASE_12_3_MATRICES_RIESGOS_ORACLE
PROMPT RESUMEN_TOTALES
SELECT COUNT(DISTINCT m.MRMAT_ID) AS TOTAL_MATRICES_ACTIVAS,
       COUNT(DISTINCT CASE WHEN ri.MRR_ID IS NOT NULL THEN m.MRMAT_ID END) AS TOTAL_MATRICES_EVALUADAS,
       COUNT(DISTINCT CASE WHEN m.MRMAT_ESTADO = 'CERRADA' THEN m.MRMAT_ID END) AS TOTAL_MATRICES_CERRADAS,
       SUM(CASE WHEN (UPPER(NVL(ri.MRR_NIVEL_RESIDUAL, '')) = 'ALTO' OR UPPER(NVL(ri.MRR_NIVEL_RESIDUAL, '')) LIKE 'CR%') THEN 1 ELSE 0 END) AS TOTAL_ALTO_CRITICO,
       SUM(CASE WHEN ri.MRR_REQUIERE_PLAN = 1 THEN 1 ELSE 0 END) AS TOTAL_PLAN_REQUERIDO
  FROM RL_MR_MATRICES m
  LEFT JOIN RL_MR_RESULTADOS ri
    ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
   AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
   AND ri.MRR_ES_VIGENTE = 1
 WHERE m.MRMAT_ESTADO_REGISTRO = 1;
PROMPT PLANES_VENCIDOS
SELECT COUNT(*) AS TOTAL_PLANES_VENCIDOS
  FROM RL_MR_PLANES_ACCION pa
  JOIN RL_MR_MATRICES m ON m.MRMAT_ID = pa.MRPA_MATRIZ_ID
  LEFT JOIN RL_MR_RESULTADOS ri
    ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
   AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
   AND ri.MRR_ES_VIGENTE = 1
 WHERE m.MRMAT_ESTADO_REGISTRO = 1
   AND pa.MRPA_ESTADO <> 'CERRADO'
   AND pa.MRPA_FECHA_FIN < TRUNC(SYSDATE);
PROMPT DISTRIBUCION_ESTADO
SELECT CASE WHEN m.MRMAT_ESTADO = 'CALCULADA' THEN 'EN_REVISION' ELSE m.MRMAT_ESTADO END AS ESTADO,
       COUNT(*) AS TOTAL
  FROM RL_MR_MATRICES m
  LEFT JOIN RL_MR_RESULTADOS ri
    ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
   AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
   AND ri.MRR_ES_VIGENTE = 1
 WHERE m.MRMAT_ESTADO_REGISTRO = 1
 GROUP BY CASE WHEN m.MRMAT_ESTADO = 'CALCULADA' THEN 'EN_REVISION' ELSE m.MRMAT_ESTADO END
 ORDER BY ESTADO;
PROMPT DISTRIBUCION_INHERENTE
SELECT NVL(ri.MRR_NIVEL_INHERENTE, 'SIN_CALCULO') AS NIVEL_INHERENTE,
       COUNT(*) AS TOTAL,
       ROUND(AVG(NVL(ri.MRR_PUNTAJE_INHERENTE, 0)), 4) AS PROMEDIO_INHERENTE
  FROM RL_MR_MATRICES m
  LEFT JOIN RL_MR_RESULTADOS ri
    ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
   AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
   AND ri.MRR_ES_VIGENTE = 1
 WHERE m.MRMAT_ESTADO_REGISTRO = 1
 GROUP BY NVL(ri.MRR_NIVEL_INHERENTE, 'SIN_CALCULO')
 ORDER BY MIN(NVL(ri.MRR_PUNTAJE_INHERENTE, 0));
PROMPT DISTRIBUCION_RESIDUAL
SELECT NVL(ri.MRR_NIVEL_RESIDUAL, 'SIN_CALCULO') AS NIVEL_RESIDUAL,
       COUNT(*) AS TOTAL,
       ROUND(AVG(NVL(ri.MRR_PUNTAJE_RESIDUAL, 0)), 4) AS PROMEDIO_RESIDUAL
  FROM RL_MR_MATRICES m
  LEFT JOIN RL_MR_RESULTADOS ri
    ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
   AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
   AND ri.MRR_ES_VIGENTE = 1
 WHERE m.MRMAT_ESTADO_REGISTRO = 1
 GROUP BY NVL(ri.MRR_NIVEL_RESIDUAL, 'SIN_CALCULO')
 ORDER BY MIN(NVL(ri.MRR_PUNTAJE_RESIDUAL, 0));
PROMPT MAPA_TRANSICION_INHERENTE_RESIDUAL
SELECT NVL(ri.MRR_NIVEL_INHERENTE, 'SIN_CALCULO') AS NIVEL_INHERENTE,
       NVL(ri.MRR_NIVEL_RESIDUAL, 'SIN_CALCULO') AS NIVEL_RESIDUAL,
       COUNT(*) AS TOTAL,
       ROUND(AVG(NVL(ri.MRR_PUNTAJE_INHERENTE, 0)), 4) AS PROMEDIO_INHERENTE,
       ROUND(AVG(NVL(ri.MRR_PUNTAJE_RESIDUAL, 0)), 4) AS PROMEDIO_RESIDUAL
  FROM RL_MR_MATRICES m
  JOIN RL_MR_RESULTADOS ri
    ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
   AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
   AND ri.MRR_ES_VIGENTE = 1
 WHERE m.MRMAT_ESTADO_REGISTRO = 1
 GROUP BY NVL(ri.MRR_NIVEL_INHERENTE, 'SIN_CALCULO'), NVL(ri.MRR_NIVEL_RESIDUAL, 'SIN_CALCULO')
 ORDER BY MIN(ri.MRR_PUNTAJE_INHERENTE) DESC, MIN(ri.MRR_PUNTAJE_RESIDUAL);
PROMPT MUESTRA_RESULTADOS_INSTITUCIONALES_VIGENTES
SELECT *
  FROM (
        SELECT m.MRMAT_ID,
               m.MRMAT_NOMBRE_SUJETO,
               m.MRMAT_SUJETO_TIPO,
               m.MRMAT_ESTADO,
               ri.MRR_TIPO_RESULTADO,
               ri.MRR_ES_VIGENTE,
               ri.MRR_PUNTAJE_INHERENTE,
               ri.MRR_NIVEL_INHERENTE,
               ri.MRR_PUNTAJE_RESIDUAL,
               ri.MRR_NIVEL_RESIDUAL,
               ri.MRR_REQUIERE_PLAN
          FROM RL_MR_MATRICES m
          JOIN RL_MR_RESULTADOS ri
            ON ri.MRR_MATRIZ_ID = m.MRMAT_ID
           AND ri.MRR_TIPO_RESULTADO = 'INSTITUCIONAL'
           AND ri.MRR_ES_VIGENTE = 1
         WHERE m.MRMAT_ESTADO_REGISTRO = 1
         ORDER BY m.MRMAT_ID DESC
       )
 WHERE ROWNUM <= 10;
EXIT
