SET ECHO OFF
SET FEEDBACK ON
SET HEADING ON
SET PAGESIZE 500
SET LINESIZE 260
SPOOL C:\tmp\rl_comments_validate_20260703_142120\19_validate_comments_20260703_142120.log REPLACE
PROMPT === VALIDACION FINAL COMENTARIOS TABLAS ===
SELECT COUNT(*) AS TABLAS_TOTAL
  FROM USER_TABLES
 WHERE TABLE_NAME NOT LIKE 'BIN$%';

SELECT COUNT(*) AS TABLAS_SIN_COMENTARIO
  FROM USER_TAB_COMMENTS UTC
 WHERE UTC.TABLE_NAME IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT LIKE 'BIN$%')
   AND (UTC.COMMENTS IS NULL OR TRIM(UTC.COMMENTS) IS NULL);

PROMPT === VALIDACION FINAL COMENTARIOS COLUMNAS ===
SELECT COUNT(*) AS COLUMNAS_TOTAL
  FROM USER_TAB_COLUMNS C
 WHERE C.TABLE_NAME IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT LIKE 'BIN$%');

SELECT COUNT(*) AS COLUMNAS_SIN_COMENTARIO
  FROM USER_COL_COMMENTS CC
 WHERE CC.TABLE_NAME IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT LIKE 'BIN$%')
   AND (CC.COMMENTS IS NULL OR TRIM(CC.COMMENTS) IS NULL);

PROMPT === VALIDACION FINAL ENCODING COMENTARIOS ===
SELECT COUNT(*) AS TAB_COMMENTS_ENCODING_BAD
  FROM USER_TAB_COMMENTS UTC
 WHERE UTC.TABLE_NAME IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT LIKE 'BIN$%')
   AND (ASCIISTR(UTC.COMMENTS) LIKE '%\00BF%' OR UTC.COMMENTS LIKE '%?%');

SELECT COUNT(*) AS COL_COMMENTS_ENCODING_BAD
  FROM USER_COL_COMMENTS CC
 WHERE CC.TABLE_NAME IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT LIKE 'BIN$%')
   AND (ASCIISTR(CC.COMMENTS) LIKE '%\00BF%' OR CC.COMMENTS LIKE '%?%');

PROMPT === MUESTRAS DE COMENTARIOS AGREGADOS ===
SELECT TABLE_NAME, ASCIISTR(COMMENTS) AS COMMENTS_ASCIISTR
  FROM USER_TAB_COMMENTS
 WHERE TABLE_NAME IN ('RL_TIPOS_DOCUMENTO','RL_TIPOS_POSITIVO')
 ORDER BY TABLE_NAME;

SELECT TABLE_NAME, COLUMN_NAME, ASCIISTR(COMMENTS) AS COMMENTS_ASCIISTR
  FROM USER_COL_COMMENTS
 WHERE (TABLE_NAME = 'RL_AUDITORIA' AND COLUMN_NAME IN ('AUD_ID','AUD_IP','AUD_MODULO'))
    OR (TABLE_NAME = 'RL_USUARIOS' AND COLUMN_NAME IN ('USR_INTENTOS_FALLIDOS','USR_FECHA_BLOQUEO'))
    OR (TABLE_NAME = 'RL_CONFIG_SISTEMA' AND COLUMN_NAME IN ('SFS_NOMBRE_INSTITUCION','SFS_MAX_INTENTOS'))
 ORDER BY TABLE_NAME, COLUMN_NAME;
SPOOL OFF
EXIT
