-- DROP USER CONTROL_ALMACEN;

CREATE USER CONTROL_ALMACEN
-- IDENTIFIED BY <password>
;

CREATE TABLE "CONTROL_ALMACEN"."ACTA_MUESTREO" 
   (	"ACTA_MUESTREO_ID" NUMBER, 
	"NOMBRE_GENERICO" VARCHAR2(500), 
	"FORMA_DOSIFICADA" VARCHAR2(500), 
	"POTENCIA_UNIDAD" VARCHAR2(500), 
	"SOLICITUD_ADMINISTRATIVA_ID" NUMBER, 
	"NUMERO_MUESTRAS" VARCHAR2(500), 
	"LABORATORIO_FABRICANTE" VARCHAR2(500), 
	"PAIS_ORIGEN_ID" NUMBER, 
	"TAMANO_LOTE" VARCHAR2(500), 
	"TAMANO_PEQUENO_MUESTRA" VARCHAR2(500), 
	"TAMANO_MUESTRA" VARCHAR2(500), 
	"ENTREGA_ANALISIS" NUMBER, 
	"OBSERVACIONES" VARCHAR2(1000), 
	"DETALLE_MED_ID" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_CREO" DATE, 
	"FECHA_MODIFICO" DATE, 
	"SOLICITUD_ID" NUMBER, 
	 CONSTRAINT "ACTA_MUESTREO_PK" PRIMARY KEY ("ACTA_MUESTREO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."ACTA_MUESTREO" ADD CONSTRAINT "ACTAMUES_DETALLEMED_FK" FOREIGN KEY ("DETALLE_MED_ID")
	  REFERENCES "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL" ("DETALLE_MED_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."ACTA_MUESTREO" ADD CONSTRAINT "ACTAMUES_PAIS_FK" FOREIGN KEY ("PAIS_ORIGEN_ID")
	  REFERENCES "CONTROL_ALMACEN"."PAIS" ("PAIS_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."ACTA_MUESTREO_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.ACTA_MUESTREO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ACTA_MUESTREO_ID
  :new.ACTA_MUESTREO_ID := ACTA_MUESTREO_SEQ.nextval;
END ACTA_MUESTREO_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."ACTA_MUESTREO_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."BITACORA_ERROR" 
   (	"BITACORA_ERROR_ID" NUMBER, 
	"MENSAJE" VARCHAR2(4000), 
	"ACCION" VARCHAR2(15), 
	"ORIGEN" VARCHAR2(250), 
	"FECHA" DATE, 
	 CONSTRAINT "BITACORA_ERROR_PK" PRIMARY KEY ("BITACORA_ERROR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."BITACORA_IMPRESION" 
   (	"BITACORA_IMP_ID" NUMBER(*,0), 
	"SOLICITUD_ID" NUMBER, 
	"NOMBRE_REGENTE" VARCHAR2(500), 
	"NOMBRE_ENCARE" VARCHAR2(500), 
	"NOMBRE_JEFEALM" VARCHAR2(500), 
	"FECHA_IMPRIMIO" DATE, 
	"USUARIO_IMPRIMIO" NUMBER, 
	"ESTADO_DOIMP_ID" NUMBER, 
	"ORDEN_COMPRA" NUMBER, 
	"NOMBRE_PREINTERVENTOR" VARCHAR2(500), 
	"NOMBRE_SECRETARIA" VARCHAR2(500), 
	"NUMERO_OFICIO" VARCHAR2(500), 
	 CONSTRAINT "BITACORA_IMPRESION_PK" PRIMARY KEY ("BITACORA_IMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."BITACORA_IMPRESION" ADD CONSTRAINT "BITACORAIMP_DOCIMP_FK" FOREIGN KEY ("ESTADO_DOIMP_ID")
	  REFERENCES "CONTROL_ALMACEN"."ESTADO_DOCIMP" ("ESTADO_DOIMP_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."BITACORA_IMPRESION_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.BITACORA_IMPRESION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column BITACORA_IMP_ID
  :new.BITACORA_IMP_ID := BITACORA_IMPRESION_SEQ.nextval;
END BITACORA_IMPRESION_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."BITACORA_IMPRESION_TRG" ENABLE;

COMMENT ON COLUMN CONTROL_ALMACEN.BITACORA_IMPRESION.ESTADO_DOIMP_ID IS '1: Oficio de la cita para enviar a proveedor. 2: Hoja de recepcion almacenamiento y distribucion. 3: Opinion Tecnica. 4: Ficha de rechazo';

CREATE TABLE "CONTROL_ALMACEN"."CITA" 
   (	"CITA_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"ORDEN_COMPRA" NUMBER, 
	"FECHA_CITA" DATE, 
	"UBICACION_ID" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"ESTADO" NUMBER, 
	"HORA_CITA" VARCHAR2(1000), 
	 CONSTRAINT "CITA_PK" PRIMARY KEY ("CITA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."CITA" ADD CONSTRAINT "CITA_SOLICITUD_FK" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."CITA" ADD CONSTRAINT "CITA_UBICACION_FK" FOREIGN KEY ("UBICACION_ID")
	  REFERENCES "CONTROL_ALMACEN"."UBICACION" ("UBICACION_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_CITA" 
BEFORE INSERT ON CITA
FOR EACH ROW
BEGIN
    IF :new.CITA_ID IS NULL THEN
        SELECT CITA_SEQ.NEXTVAL INTO :new.CITA_ID FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_CITA" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL" 
   (	"DETALLE_MED_ID" NUMBER, 
	"ITEM" NUMBER, 
	"CODIGO" VARCHAR2(2000), 
	"DESCRIPCION" VARCHAR2(1500), 
	"UND" VARCHAR2(500), 
	"ENTREGA" VARCHAR2(500), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"SOLICITUD_ID" NUMBER, 
	"TOTAL" NUMBER, 
	 CONSTRAINT "DETALLE_MEDICAMENTO_SOL_PK" PRIMARY KEY ("DETALLE_MED_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL" ADD CONSTRAINT "DETALLE_MEDICAMENTO_SOL_FK01" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.DETALLE_MEDICAMENTO_SOL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DETALLE_MED_ID
  :new.DETALLE_MED_ID := DETALLE_MEDICAMENTO_SOL_SEQ.nextval;
END DETALLE_MEDICAMENTO_SOL_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."DETALLE_PARTIDA" 
   (	"DETALLE_PARTIDA_ID" NUMBER, 
	"PARTIDA" NUMBER, 
	"LOTES" NUMBER, 
	"NUMERO_LOTES" VARCHAR2(200), 
	"FECHA_VENCIMIENTO" VARCHAR2(500), 
	"FECHA_FABRICACION" DATE, 
	"REG_SANITARIO" VARCHAR2(500), 
	"DETALLE_BULTOS" VARCHAR2(1000), 
	"TOTAL_UNIDADES" NUMBER, 
	"TOTAL_BULTOS" NUMBER, 
	"TOTALES" NUMBER, 
	"SOLI_ADMIN_ID" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	 CONSTRAINT "DETALLE_PARTIDA_PK" PRIMARY KEY ("DETALLE_PARTIDA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."DETALLE_PARTIDA" ADD CONSTRAINT "DETALLEPAR_SOLADMIN_FK" FOREIGN KEY ("SOLI_ADMIN_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD_ADMINISTRATIVO" ("SOLI_ADMIN_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_ID_DETALLEPAR" 
BEFORE INSERT ON CONTROL_ALMACEN.DETALLE_PARTIDA
FOR EACH ROW
BEGIN
    IF :new.DETALLE_PARTIDA_ID IS NULL THEN
        SELECT SEQ_ID_DETALLEPARTIDA.NEXTVAL INTO :new.DETALLE_PARTIDA_ID FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_ID_DETALLEPAR" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."DETALLE_SOLICITUD" 
   (	"DETALLE_SOLI_ID" NUMBER, 
	"LOTE" VARCHAR2(500), 
	"VENCE" VARCHAR2(15), 
	"CANTIDAD" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"CANTIDAD_RECHAZADA" NUMBER, 
	"DETALLE_MED_ID" NUMBER, 
	 CONSTRAINT "DETALLE_SOLICITUD_PK" PRIMARY KEY ("DETALLE_SOLI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."DETALLE_SOLICITUD" ADD CONSTRAINT "DETALLE_SOL_MED_FK01" FOREIGN KEY ("DETALLE_MED_ID")
	  REFERENCES "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL" ("DETALLE_MED_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_ID_DETALLESOL" 
BEFORE INSERT ON DETALLE_SOLICITUD
FOR EACH ROW
BEGIN
    IF :new.DETALLE_SOLI_ID IS NULL THEN
        SELECT DETALLE_SOLICITUD_SEQ.NEXTVAL INTO :new.DETALLE_SOLI_ID FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_ID_DETALLESOL" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."DET_SOLI_FICHA_RECHAZO" 
   (	"DET_SOLI_FICHA_ID" NUMBER, 
	"DETALLE_SOLI_ID" NUMBER, 
	"FICHA_RECHAZO_ID" NUMBER, 
	 PRIMARY KEY ("DET_SOLI_FICHA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."DET_SOLI_FICHA_RECHAZO" ADD CONSTRAINT "FK_DET_DETA_SOLI" FOREIGN KEY ("DETALLE_SOLI_ID")
	  REFERENCES "CONTROL_ALMACEN"."DETALLE_SOLICITUD" ("DETALLE_SOLI_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."DET_SOLI_FICHA_RECHAZO" ADD CONSTRAINT "FK_DET_SOLI_FIC_REC" FOREIGN KEY ("FICHA_RECHAZO_ID")
	  REFERENCES "CONTROL_ALMACEN"."FICHAS_RECHAZO" ("FICHA_RECHAZO_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."DET_SOLI_FICHA_RECHAZO_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.DET_SOLI_FICHA_RECHAZO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DET_SOLI_FICHA_ID
  :new.DET_SOLI_FICHA_ID := DET_SOLI_FICHA_RECHAZO_SEQ.nextval;
END DET_SOLI_FICHA_RECHAZO_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."DET_SOLI_FICHA_RECHAZO_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."DET_SOLMUES_EXCEP" 
   (	"DET_SOLMUES_EXCEP_ID" NUMBER, 
	"SOLICITUD_MUESTREO_ID" NUMBER, 
	"PRUEBAS_EXCEP_FORLACT_ID" NUMBER, 
	"PRUEBAS_EXCEP_ID" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_CREO" NUMBER, 
	 CONSTRAINT "DET_SOLMUES_EXCEP_PK" PRIMARY KEY ("DET_SOLMUES_EXCEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."DET_SOLMUES_EXCEP" ADD CONSTRAINT "DET_SOLMUES_EXCEP_FK" FOREIGN KEY ("PRUEBAS_EXCEP_FORLACT_ID")
	  REFERENCES "CONTROL_ALMACEN"."PRUEBAS_EXCEP_FORLACT" ("PRUEBAS_EXCEP_FORLACT_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."DET_SOLMUES_EXCEP" ADD CONSTRAINT "DET_SOLMUES_EXCEP_FK1" FOREIGN KEY ("PRUEBAS_EXCEP_ID")
	  REFERENCES "CONTROL_ALMACEN"."PRUEBAS_SOL_EXCEPCIONES" ("PRUEBAS_EXCEP_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."DET_SOLMUES_EXCEP" ADD CONSTRAINT "DET_SOLMUES_EXCEP_FK2" FOREIGN KEY ("SOLICITUD_MUESTREO_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD_MUESTREO" ("SOLICITUD_MUESTREO_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."DET_SOLMUES_EXCEP_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.DET_SOLMUES_EXCEP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DET_SOLMUES_EXCEP_ID
  :new.DET_SOLMUES_EXCEP_ID := DET_SOLMUES_EXCEP_SEQ.nextval;
END DET_SOLMUES_EXCEP_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."DET_SOLMUES_EXCEP_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."DET_SOLMUES_SINEXCEP" 
   (	"DET_SOLMUES_SINEXCEP_ID" NUMBER, 
	"PRUEBAS_SOLICITADAS_ID" NUMBER, 
	"PRUEBAS_FORLACTEAS_ID" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_CREO" NUMBER, 
	"SOLICITUD_MUESTREO_ID" NUMBER, 
	 CONSTRAINT "DET_SOLMUES_SINEXCEP_PK" PRIMARY KEY ("DET_SOLMUES_SINEXCEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."DET_SOLMUES_SINEXCEP" ADD CONSTRAINT "DET_SOLMUES_SINEXCEP_FK" FOREIGN KEY ("SOLICITUD_MUESTREO_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD_MUESTREO" ("SOLICITUD_MUESTREO_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."DET_SOLMUES_SINEXCEP" ADD CONSTRAINT "DET_SOLMUES_SINEXCEP_FK2" FOREIGN KEY ("PRUEBAS_SOLICITADAS_ID")
	  REFERENCES "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS" ("PRUEBAS_SOLICITADAS_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."DET_SOLMUES_SINEXCEP" ADD CONSTRAINT "DET_SOLMUES_SINEXCEP_FK3" FOREIGN KEY ("PRUEBAS_FORLACTEAS_ID")
	  REFERENCES "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS_FORLACTEAS" ("PRUEBAS_FORLACTEAS_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."DET_SOLMUES_SINEXCEP_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.DET_SOLMUES_SINEXCEP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DET_SOLMUES_SINEXCEP_ID
  :new.DET_SOLMUES_SINEXCEP_ID := DET_SOLMUES_SINEXCEP_SEQ.nextval;
END DET_SOLMUES_SINEXCEP_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."DET_SOLMUES_SINEXCEP_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."DOCUMENTOS_PROVEEDOR" 
   (	"DOCUMENTOS_PROVEEDOR_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"TIPO_DOCUMENTO_ID" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"ESTADO_DOCPROV" NUMBER, 
	 CONSTRAINT "DOCUMENTOS_PROVEEDOR_PK" PRIMARY KEY ("DOCUMENTOS_PROVEEDOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."DOCUMENTOS_PROVEEDOR" ADD CONSTRAINT "DOCUMENTOS_PROVEEDOR_SOLI_ID" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."DOCUMENTOS_PROVEEDOR" ADD CONSTRAINT "DOCUPROV_TIPDOC_FK" FOREIGN KEY ("TIPO_DOCUMENTO_ID")
	  REFERENCES "CONTROL_ALMACEN"."TIPO_DOCUMENTO" ("TIPO_DOCUMENTO_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."DOCUMENTOS_PROVEEDOR_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.DOCUMENTOS_PROVEEDOR
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DOCUMENTOS_PROVEEDOR_ID
  :new.DOCUMENTOS_PROVEEDOR_ID := DOCUMENTOS_PROVEEDOR_SEQ.nextval;
END DOCUMENTOS_PROVEEDOR_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."DOCUMENTOS_PROVEEDOR_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."ESTADO_DOCIMP" 
   (	"ESTADO_DOIMP_ID" NUMBER, 
	"DESCRPCION_DOCIMP" VARCHAR2(500), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODFICIFO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	 CONSTRAINT "ESTADO_DOCIMP_PK" PRIMARY KEY ("ESTADO_DOIMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."ESTADO_SOLICITUD" 
   (	"ESTADO_SOL_ID" NUMBER, 
	"ESTADO_DESCRIPCION" VARCHAR2(1000), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	 CONSTRAINT "ESTADO_SOLICITUD_PK" PRIMARY KEY ("ESTADO_SOL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."FICHAS_RECHAZO" 
   (	"FICHA_RECHAZO_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"FICHA_TIPO" NUMBER, 
	"FABRICANTE" VARCHAR2(500), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"OBSERVACION" VARCHAR2(2500), 
	"FECHA" DATE, 
	 CONSTRAINT "FICHAS_RECHAZO_PK" PRIMARY KEY ("FICHA_RECHAZO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."FICHAS_RECHAZO" ADD CONSTRAINT "FICHAS_RECHAZO_SOLICITUD_FK" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."FICHAS_RECHAZO_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.FICHAS_RECHAZO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column FICHA_RECHAZO_ID
  :new.FICHA_RECHAZO_ID := FICHAS_RECHAZO_SEQ.nextval;
END FICHAS_RECHAZO_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."FICHAS_RECHAZO_TRG" ENABLE;

COMMENT ON COLUMN CONTROL_ALMACEN.FICHAS_RECHAZO.FICHA_TIPO IS '1: Ficha de rechazo Administrativo. 2: Ficha de rechazo Tecnica.';

CREATE TABLE "CONTROL_ALMACEN"."HORA" 
   (	"HORA_ID" NUMBER, 
	"HORA_DESCRIPCION" VARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."MATERIALES" 
   (	"CODIGO_PRODUCTO" VARCHAR2(2000), 
	"NOMBRE_PRODUCTO" VARCHAR2(2000), 
	"UNIDAD_PRESENTACION" VARCHAR2(2000), 
	"MATERIALES_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MATERIALES_PK" PRIMARY KEY ("MATERIALES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."MUESTREO_MEDICAMENTOS" 
   (	"MUESTREO_MED_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"PROCESO" VARCHAR2(500), 
	"TAMANO_MUESTRA" VARCHAR2(500), 
	"DETALLE_MED_ID" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	 CONSTRAINT "MUESTREO_MEDICAMENTOS_PK" PRIMARY KEY ("MUESTREO_MED_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."MUESTREO_MEDICAMENTOS" ADD CONSTRAINT "MUESMED_DETALLEMED_FK" FOREIGN KEY ("DETALLE_MED_ID")
	  REFERENCES "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL" ("DETALLE_MED_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."MUESTREO_MEDICAMENTOS" ADD CONSTRAINT "MUESMED_SOL_FK" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."MUESTREO_MEDICAMENTOS_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.MUESTREO_MEDICAMENTOS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column MUESTREO_MED_ID
  :new.MUESTREO_MED_ID := MUESTREO_MEDICAMENTOS_SEQ.nextval;
END MUESTREO_MEDICAMENTOS_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."MUESTREO_MEDICAMENTOS_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."PAIS" 
   (	"PAIS_ID" NUMBER, 
	"NOMBRE_PAIS" VARCHAR2(500), 
	 CONSTRAINT "PAIS_PK" PRIMARY KEY ("PAIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."PROVEEDOR" 
   (	"CODIGO_PROVEEDOR" VARCHAR2(4000), 
	"NOMBRE_PROVEEDOR" VARCHAR2(1000), 
	"CARGO_PROVEEDOR" VARCHAR2(1000), 
	"EMPRESA_PROVEEDOR" VARCHAR2(1000), 
	"CORREO_PROVEEDOR" VARCHAR2(1000), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"ESTADO" NUMBER, 
	"PROV_ID" NUMBER, 
	 CONSTRAINT "PROVEEDOR_PK" PRIMARY KEY ("PROV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."PROVEEDOR_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.PROVEEDOR
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PROV_ID
  :new.PROV_ID := PROVEEDOR_SEQ.nextval;
END PROVEEDOR_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."PROVEEDOR_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."PRUEBAS_EXCEP_FORLACT" 
   (	"PRUEBAS_EXCEP_FORLACT_ID" NUMBER, 
	"DESCRIPCION_EXCEP_FORLACT" VARCHAR2(500), 
	"QUMICOS" NUMBER, 
	"MICROBIOLOGICOS" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	 CONSTRAINT "PRUEBAS_EXCEP_FORLACT_PK" PRIMARY KEY ("PRUEBAS_EXCEP_FORLACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."PRUEBAS_EXCEP_FORLACT_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.PRUEBAS_EXCEP_FORLACT
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PRUEBAS_EXCEP_FORLACT_ID
  :new.PRUEBAS_EXCEP_FORLACT_ID := PRUEBAS_EXCEP_FORLACT_SEQ.nextval;
END PRUEBAS_EXCEP_FORLACT_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."PRUEBAS_EXCEP_FORLACT_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS" 
   (	"PRUEBAS_SOLICITADAS_ID" NUMBER, 
	"TIPO_MEDICAMENTO_ID" NUMBER, 
	"PRUEBAS_DESCRIPCION" VARCHAR2(500), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"ESTADO" NUMBER, 
	 CONSTRAINT "PRUEBAS_SOLICITADAS_PK" PRIMARY KEY ("PRUEBAS_SOLICITADAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS" ADD CONSTRAINT "PRUEBASOL_TPMEDIC_FK" FOREIGN KEY ("TIPO_MEDICAMENTO_ID")
	  REFERENCES "CONTROL_ALMACEN"."TIPO_MEDICAMENTO" ("TIPO_MEDICAMENTO_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.PRUEBAS_SOLICITADAS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PRUEBAS_SOLICITADAS_ID
  :new.PRUEBAS_SOLICITADAS_ID := PRUEBAS_SOLICITADAS_SEQ.nextval;
END PRUEBAS_SOLICITADAS_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS_FORLACTEAS" 
   (	"PRUEBAS_FORLACTEAS_ID" NUMBER, 
	"DESCRIPCION_PRUEBAS" VARCHAR2(500), 
	"QUIMICOS" NUMBER, 
	"MICROBIOLOGICOS" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"ESTADO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"TIPO_MEDICAMENTO_ID" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	 CONSTRAINT "PRUEBAS_SOLICITADAS_FORLACT_PK" PRIMARY KEY ("PRUEBAS_FORLACTEAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS_FORLAC_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.PRUEBAS_SOLICITADAS_FORLACTEAS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PRUEBAS_FORLACTEAS_ID
  :new.PRUEBAS_FORLACTEAS_ID := PRUEBAS_SOLICITADAS_FORLAC_SEQ.nextval;
END PRUEBAS_SOLICITADAS_FORLAC_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."PRUEBAS_SOLICITADAS_FORLAC_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."PRUEBAS_SOL_EXCEPCIONES" 
   (	"PRUEBAS_EXCEP_ID" NUMBER, 
	"DESCRIPCION_EXCEP" VARCHAR2(500), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	 CONSTRAINT "PRUEBAS_SOL_EXCEPCIONES_PK" PRIMARY KEY ("PRUEBAS_EXCEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."PRUEBAS_SOL_EXCEPCIONES_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.PRUEBAS_SOL_EXCEPCIONES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PRUEBAS_EXCEP_ID
  :new.PRUEBAS_EXCEP_ID := PRUEBAS_SOL_EXCEPCIONES_SEQ.nextval;
END PRUEBAS_SOL_EXCEPCIONES_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."PRUEBAS_SOL_EXCEPCIONES_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."REPORTES" 
   (	"REPORTE_ID" NUMBER, 
	"REPORTE_DESCRIPCION" VARCHAR2(250), 
	"HERENCIA" NUMBER, 
	"ORDEN" NUMBER, 
	 CONSTRAINT "REPORTES_PK" PRIMARY KEY ("REPORTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."REPORTE_USUARIO" 
   (	"REPORTE_ID" NUMBER, 
	"USUARIO_ID" NUMBER, 
	"REPORTE_USUARIO_ID" NUMBER, 
	 CONSTRAINT "REPORTE_USUARIO_PK" PRIMARY KEY ("REPORTE_USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."REPORTE_USUARIO" ADD CONSTRAINT "REPORTE_USUARIO_FK" FOREIGN KEY ("REPORTE_ID")
	  REFERENCES "CONTROL_ALMACEN"."REPORTES" ("REPORTE_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."REPORTE_USUARIO_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.REPORTE_USUARIO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column REPORTE_USUARIO_ID
  :new.REPORTE_USUARIO_ID := REPORTE_USUARIO_SEQ.nextval;
END REPORTE_USUARIO_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."REPORTE_USUARIO_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."SEGUIMIENTO_SOLICITUD" 
   (	"SEGUIMIENTO_SOL_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"ESTADO_SOL_ID" NUMBER, 
	"USUARIO_ACTUAL" NUMBER, 
	"USUARIO_ASIGNO" NUMBER, 
	"FECHA_ASIGNO" DATE, 
	"FECHA_CREO" DATE, 
	"ESTADO" NUMBER, 
	"OBSERVACIONES" VARCHAR2(4000), 
	 CONSTRAINT "SEGUIMIENTO_SOLICITUD_PK" PRIMARY KEY ("SEGUIMIENTO_SOL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."SEGUIMIENTO_SOLICITUD" ADD CONSTRAINT "SEGUIMIENTOSOL_ESTADOSOL_FK" FOREIGN KEY ("ESTADO_SOL_ID")
	  REFERENCES "CONTROL_ALMACEN"."ESTADO_SOLICITUD" ("ESTADO_SOL_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."SEGUIMIENTO_SOLICITUD" ADD CONSTRAINT "SEGUIMIENTOSOL_SOLICITUD_FK" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_ID_SEGUIMIENTOSOL" 
BEFORE INSERT ON SEGUIMIENTO_SOLICITUD
FOR EACH ROW
BEGIN
    IF :new.SEGUIMIENTO_SOL_ID IS NULL THEN
        SELECT SEGUIMIENTO_SOLICITUD_SEQ.NEXTVAL INTO :new.SEGUIMIENTO_SOL_ID FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_ID_SEGUIMIENTOSOL" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."SOLICITUD" 
   (	"SOLICITUD_ID" NUMBER, 
	"CODIGO_PROVEEDOR" NUMBER, 
	"LICITACION" VARCHAR2(1000), 
	"PO_UNOPS" VARCHAR2(500), 
	"USUARIO_ACTUAL" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"FECHA_SOLICITUD_CITA" DATE, 
	"SOLICITUD_FIRMADA" NUMBER, 
	"FECHA_FIRMA" DATE, 
	"ESTADO" NUMBER, 
	"TIPO_COMPRA" NUMBER, 
	"FINALIZADA" NUMBER, 
	 CONSTRAINT "SOLICITUD_PK" PRIMARY KEY ("SOLICITUD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_SOLICITUD" 
BEFORE INSERT ON SOLICITUD
FOR EACH ROW
BEGIN
    IF :new.SOLICITUD_ID IS NULL THEN
        SELECT SOLICITUD_SEQ.NEXTVAL INTO :new.SOLICITUD_ID FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_SOLICITUD" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."SOLICITUD_ADMINISTRATIVO" 
   (	"SOLI_ADMIN_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"CAJA" NUMBER, 
	"CANTIDAD_FACTURADA" NUMBER, 
	"HIELERAS" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_CREO" NUMBER, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"AREA" NUMBER, 
	"DETALLE_MED_ID" NUMBER, 
	 CONSTRAINT "SOLICITUD_ADMINISTRATIVO_PK" PRIMARY KEY ("SOLI_ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."SOLICITUD_ADMINISTRATIVO" ADD CONSTRAINT "SOLICITUDADMIN_SOLICITUD_FK" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_ID_SOLIADMIN" 
BEFORE INSERT ON CONTROL_ALMACEN.SOLICITUD_ADMINISTRATIVO
FOR EACH ROW
BEGIN
    IF :new.SOLI_ADMIN_ID IS NULL THEN
        SELECT SEQ_ID_SOLADMIN.NEXTVAL INTO :new.SOLI_ADMIN_ID FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_ID_SOLIADMIN" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."SOLICITUD_MUESTREO" 
   (	"SOLICITUD_MUESTREO_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"FECHA_CREO" DATE, 
	"NOMBRE_GENERICO" VARCHAR2(500), 
	"CONCENTRACION" VARCHAR2(500), 
	"CANTIDAD" VARCHAR2(500), 
	"SE_REQUIERE" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"TIPO_MEDICAMENTO_ID" NUMBER, 
	"PRESENTACION" VARCHAR2(500), 
	"EXONERACIONES" NUMBER, 
	"DETALLE_MED_ID" NUMBER, 
	 CONSTRAINT "SOLICITUD_MUESTREO_PK" PRIMARY KEY ("SOLICITUD_MUESTREO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."SOLICITUD_MUESTREO" ADD CONSTRAINT "SOLICITUDMUES_SOLI_FK" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."SOLICITUD_MUESTREO" ADD CONSTRAINT "SOLMUES_DETALLEMED_FK" FOREIGN KEY ("DETALLE_MED_ID")
	  REFERENCES "CONTROL_ALMACEN"."DETALLE_MEDICAMENTO_SOL" ("DETALLE_MED_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."SOLICITUD_MUESTREO_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.SOLICITUD_MUESTREO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column SOLICITUD_MUESTREO_ID
  :new.SOLICITUD_MUESTREO_ID := SOLICITUD_MUESTREO_SEQ.nextval;
END SOLICITUD_MUESTREO_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."SOLICITUD_MUESTREO_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."SOLICITUD_TECNICA" 
   (	"SOLICITUD_TECNICA_ID" NUMBER, 
	"SOLICITUD_ID" NUMBER, 
	"BODEGA" VARCHAR2(500), 
	"REGISTRO_SANITARIO" VARCHAR2(500), 
	"CANTIDAD_FACTURADA" NUMBER, 
	"PROCESO_COMPRA" VARCHAR2(500), 
	"MUESTREO" NUMBER, 
	"CARTA" NUMBER, 
	"NOMBRE_COMERCIAL" VARCHAR2(500), 
	"FABRICANTE" VARCHAR2(500), 
	"SOLICITUD_TECNICA_OBSERVACION" VARCHAR2(500), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"DETALLE_MED_ID" NUMBER, 
	"PAIS_FABRICANTE" VARCHAR2(500), 
	"CANTIDAD_VU" VARCHAR2(500), 
	 CONSTRAINT "SOLICITUD_TECNICA_PK" PRIMARY KEY ("SOLICITUD_TECNICA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."SOLICITUD_TECNICA" ADD CONSTRAINT "SOLICITEC_SOLICITUD_FK" FOREIGN KEY ("SOLICITUD_ID")
	  REFERENCES "CONTROL_ALMACEN"."SOLICITUD" ("SOLICITUD_ID") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."SOLICITUD_TECNICA_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.SOLICITUD_TECNICA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column SOLICITUD_TECNICA_ID
  :new.SOLICITUD_TECNICA_ID := SOLICITUD_TECNICA_SEQ.nextval;
END SOLICITUD_TECNICA_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."SOLICITUD_TECNICA_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"NOMBRE_DEPARTAMENTO" VARCHAR2(50), 
	"CODIGO_DEPARTAMENTO" VARCHAR2(10), 
	 CONSTRAINT "PK_TBL_DEPARTAMENTO" PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_DOMINIO" 
   (	"ID_DOMINIO" NUMBER(*,0), 
	"NOMBRE_DOMINIO" VARCHAR2(50), 
	"ID_USUARIO_CREO" NUMBER(*,0), 
	"ID_USUARIO_MODIFICO" NUMBER(*,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"ESTADO_ELIMINACION" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0), 
	 PRIMARY KEY ("ID_DOMINIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_DOMINIO" 
BEFORE INSERT ON tbl_dominio
FOR EACH ROW
BEGIN
    IF :new.id_dominio IS NULL THEN
        SELECT seq_id_dominio.NEXTVAL INTO :new.id_dominio FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_DOMINIO" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_MODULO" 
   (	"ID_MODULO" NUMBER(*,0), 
	"ID_MODULO_PADRE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50), 
	"RUTA" VARCHAR2(255), 
	"ICONO" VARCHAR2(255), 
	"ID_USUARIO_CREO" NUMBER(*,0), 
	"ID_USUARIO_MODIFICO" NUMBER(*,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"ESTADO_ELIMINACION" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0), 
	 PRIMARY KEY ("ID_MODULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_MODULO" 
BEFORE INSERT ON tbl_modulo
FOR EACH ROW
BEGIN
    IF :new.id_modulo IS NULL THEN
        SELECT seq_id_modulo.NEXTVAL INTO :new.id_modulo FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_MODULO" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_MUNICIPIO" 
   (	"ID_MUNICIPIO" NUMBER(*,0), 
	"NOMBRE_MUNICIPIO" VARCHAR2(50), 
	"CODIGO_MUNICIPIO" VARCHAR2(10), 
	"ID_DEPARTAMENTO" NUMBER(*,0), 
	 CONSTRAINT "PK_TBL_MUNICIPIO" PRIMARY KEY ("ID_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."TBL_MUNICIPIO" ADD CONSTRAINT "FK_MUNICIPIO_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "CONTROL_ALMACEN"."TBL_DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_PARAMETRO" 
   (	"ID_PARAMETRO" NUMBER(38,0), 
	"NOMBRE_PARAMETRO" VARCHAR2(100), 
	"VALOR" VARCHAR2(500), 
	"DESCRIPCION" VARCHAR2(4000 CHAR), 
	"FECHA_MODIFICACION" DATE, 
	"FECHA_CREACION" DATE, 
	"ID_USUARIO_CREO" NUMBER(38,0), 
	"ID_USUARIO_MODIFICO" NUMBER(38,0), 
	"ESTADO_ELIMINACION" NUMBER(38,0), 
	"ESTADO" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_PERMISO" 
   (	"ID_PERMISO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"ID_MODULO" NUMBER(*,0), 
	"VER" NUMBER(*,0), 
	"AGREGAR" NUMBER(*,0), 
	"EDITAR" NUMBER(*,0), 
	"ELIMINAR" NUMBER(*,0), 
	"ASIGNAR" NUMBER(*,0), 
	"REPORTE" NUMBER(*,0), 
	"ID_USUARIO_CREO" NUMBER(*,0), 
	"ID_USUARIO_MODIFICO" NUMBER(*,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"ESTADO_ELIMINACION" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0), 
	"CITA" NUMBER, 
	"ENVIAR_JEFE" NUMBER, 
	"APROBAR" NUMBER, 
	"FIRMAR" NUMBER, 
	"VISUALIZAR" NUMBER, 
	"CORREO" NUMBER, 
	"ENVIAR_SECRETARIA" NUMBER, 
	"CHECKLIST" NUMBER, 
	"HOJARECEPCION" NUMBER, 
	"FICHARECHAZO" NUMBER, 
	"DETALLEPARTIDA" NUMBER, 
	"OPINIONTECNICA" NUMBER, 
	"ACTAMUESTREO" NUMBER, 
	"MUESTREONED" NUMBER, 
	"REMISIONMUESTRA" NUMBER, 
	"REPORTEFRT" NUMBER, 
	"REPORTEFRA" NUMBER, 
	"FINALIZAR" NUMBER, 
	 PRIMARY KEY ("ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."TBL_PERMISO" ADD CONSTRAINT "FK_PERMISO_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "CONTROL_ALMACEN"."TBL_ROL" ("ID_ROL") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."TBL_PERMISO" ADD CONSTRAINT "PERMISO_MODULO_FK" FOREIGN KEY ("ID_MODULO")
	  REFERENCES "CONTROL_ALMACEN"."TBL_MODULO" ("ID_MODULO") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."TBL_PERMISO" ADD CONSTRAINT "PERMISO_USUARIO_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "CONTROL_ALMACEN"."TBL_USUARIO" ("ID_USUARIO") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_PERMISO" 
BEFORE INSERT ON tbl_permiso
FOR EACH ROW
BEGIN
    IF :new.id_permiso IS NULL THEN
        SELECT seq_id_permiso.NEXTVAL INTO :new.id_permiso FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_PERMISO" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_REGIONAL" 
   (	"ID_REGIONAL" NUMBER(*,0), 
	"NOMBRE_REGIONAL" VARCHAR2(100), 
	"RPT_DESCRIPCION" VARCHAR2(100), 
	 PRIMARY KEY ("ID_REGIONAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE_ROL" VARCHAR2(50), 
	"DESCRIPCION" VARCHAR2(255), 
	"ID_USUARIO_CREO" NUMBER(*,0), 
	"ID_USUARIO_MODIFICO" NUMBER(*,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"ESTADO_ELIMINACION" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0), 
	 PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_ROL" 
BEFORE INSERT ON tbl_rol
FOR EACH ROW
BEGIN
    IF :new.id_rol IS NULL THEN
        SELECT seq_id_rol.NEXTVAL INTO :new.id_rol FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_ROL" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TBL_USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255), 
	"USUARIO" VARCHAR2(20), 
	"CORREO" VARCHAR2(30), 
	"CONTRASENA" VARCHAR2(255), 
	"ID_DOMINIO" NUMBER(*,0), 
	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"ID_MUNICIPIO" NUMBER(*,0), 
	"FECHA_EXPIRACION" DATE, 
	"ID_USUARIO_DOMINIO" NUMBER(*,0), 
	"ID_REGIONAL" NUMBER(*,0), 
	"ID_USUARIO_CREO" NUMBER(*,0), 
	"ID_USUARIO_MODIFICO" NUMBER(*,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"ESTADO_ELIMINACION" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0), 
	"ID_ROL" NUMBER(38,0), 
	"CONTRASENA_SEGURA" NUMBER(38,0), 
	"CAMBIO_CONTRASENA" NUMBER(38,0), 
	 PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CONTROL_ALMACEN"."TBL_USUARIO" ADD CONSTRAINT "FK_USUARIO_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "CONTROL_ALMACEN"."TBL_DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."TBL_USUARIO" ADD CONSTRAINT "FK_USUARIO_DOMINIO" FOREIGN KEY ("ID_DOMINIO")
	  REFERENCES "CONTROL_ALMACEN"."TBL_DOMINIO" ("ID_DOMINIO") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."TBL_USUARIO" ADD CONSTRAINT "FK_USUARIO_MUNICIPIO" FOREIGN KEY ("ID_MUNICIPIO")
	  REFERENCES "CONTROL_ALMACEN"."TBL_MUNICIPIO" ("ID_MUNICIPIO") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."TBL_USUARIO" ADD CONSTRAINT "FK_USUARIO_REGIONAL" FOREIGN KEY ("ID_REGIONAL")
	  REFERENCES "CONTROL_ALMACEN"."TBL_REGIONAL" ("ID_REGIONAL") ENABLE;
 
  ALTER TABLE "CONTROL_ALMACEN"."TBL_USUARIO" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "CONTROL_ALMACEN"."TBL_ROL" ("ID_ROL") ENABLE;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_USUARIO" 
BEFORE INSERT ON tbl_usuario
FOR EACH ROW
BEGIN
    IF :new.id_usuario IS NULL THEN
        SELECT seq_id_usuario.NEXTVAL INTO :new.id_usuario FROM dual;
    END IF;
END;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TRG_AUTOINCREMENT_ID_USUARIO" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TIPO_DOCUMENTO" 
   (	"TIPO_DOCUMENTO_ID" NUMBER, 
	"TIPO_DOCUMENTO_DESCRIPCION" VARCHAR2(1000), 
	"USUARIO_CREO" NUMBER, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_CREO" DATE, 
	"FECHA_MODIFICO" DATE, 
	"ESTADO_TIPODOC" NUMBER, 
	 CONSTRAINT "TIPO_DOCUMENTO_PK" PRIMARY KEY ("TIPO_DOCUMENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TIPO_DOCUMENTO_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.TIPO_DOCUMENTO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column TIPO_DOCUMENTO_ID
  :new.TIPO_DOCUMENTO_ID := SEQ_ID_TIPODOC.nextval;
END TIPO_DOCUMENTO_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TIPO_DOCUMENTO_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."TIPO_MEDICAMENTO" 
   (	"TIPO_MEDICAMENTO_ID" NUMBER, 
	"TIPO_MEDICAMENTO_DESCRIPCION" VARCHAR2(1000), 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"ESTADO_TIPOMED" NUMBER(*,0), 
	 CONSTRAINT "TIPO_MEDICAMENTO_PK" PRIMARY KEY ("TIPO_MEDICAMENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."TIPO_MEDICAMENTO_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.TIPO_MEDICAMENTO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column TIPO_MEDICAMENTO_ID
  :new.TIPO_MEDICAMENTO_ID := TIPO_MEDICAMENTO_SEQ.nextval;
END TIPO_MEDICAMENTO_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."TIPO_MEDICAMENTO_TRG" ENABLE;
;

CREATE TABLE "CONTROL_ALMACEN"."UBICACION" 
   (	"UBICACION_ID" NUMBER, 
	"DESCRPCION_UBICACION" VARCHAR2(500), 
	"ESTADO" NUMBER, 
	"USUARIO_CREO" NUMBER, 
	"FECHA_CREO" DATE, 
	"USUARIO_MODIFICO" NUMBER, 
	"FECHA_MODIFICO" DATE, 
	"DIRECCION" VARCHAR2(500), 
	"TELEFONO" VARCHAR2(10), 
	 CONSTRAINT "UBICACION_PK" PRIMARY KEY ("UBICACION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "CONTROL_ALMACEN"."UBICACION_TRG" 
BEFORE INSERT
ON CONTROL_ALMACEN.UBICACION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID_UBICACION
  :new.UBICACION_ID := UBICACION_SEQ.nextval;
END UBICACION_TRG;


/
ALTER TRIGGER "CONTROL_ALMACEN"."UBICACION_TRG" ENABLE;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTALISTAPERMISOS" ("ID_PERMISO", "ID_USUARIO", "ID_MODULO", "ID_MODULO_PADRE", "NOMBRE_MODULO_HIJO", "NOMBRE_MODULO_PADRE", "RUTA", "ICONO_HIJO", "ICONO_PADRE", "ID_ROL", "NOMBRE_ROL", "VER", "AGREGAR", "EDITAR", "ELIMINAR", "ASIGNAR", "REPORTE", "CITA", "ENVIAR_JEFE", "APROBAR", "FIRMAR", "VISUALIZAR", "CORREO", "ENVIAR_SECRETARIA", "CHECKLIST", "HOJARECEPCION", "FICHARECHAZO", "DETALLEPARTIDA", "OPINIONTECNICA", "ACTAMUESTREO", "REMISIONMUESTRA", "MUESTREONED", "FINALIZAR", "REPORTEFRT", "REPORTEFRA", "ESTADO_ELIMINACION_PERMISO", "ESTADO_ELIMINACION_MODULO", "ESTADO_PERMISO", "ESTADO_MODULO", "ESTADO_ELIMINACION_ROL", "ESTADO_ROL") AS 
  SELECT tp.ID_PERMISO,
          tp.ID_USUARIO,
          tm.ID_MODULO,
          tm.ID_MODULO_PADRE,
          tm.NOMBRE AS NOMBRE_MODULO_HIJO,
          tm2.NOMBRE AS NOMBRE_MODULO_PADRE,
          tm.RUTA,
          tm.ICONO AS ICONO_HIJO,
          tm2.ICONO AS ICONO_PADRE,
          tr.ID_ROL,
          tr.NOMBRE_ROL,
          tp.VER,
          tp.AGREGAR,
          tp.EDITAR,
          tp.ELIMINAR,
          tp.ASIGNAR,
          tp.REPORTE,
          tp.CITA,
          tp.ENVIAR_JEFE,
          tp.APROBAR,
          tp.FIRMAR,
          tp.VISUALIZAR,
          tp.CORREO,
          tp.ENVIAR_SECRETARIA,
          tp.CHECKLIST,
          tp.HOJARECEPCION,
          tp.FICHARECHAZO,
          tp.DETALLEPARTIDA,
          tp.OPINIONTECNICA,
          TP.ACTAMUESTREO,
          TP.REMISIONMUESTRA,
          TP.MUESTREONED,
          TP.FINALIZAR, 
          TP.REPORTEFRT, 
          TP.REPORTEFRA,
          tp.ESTADO_ELIMINACION AS ESTADO_ELIMINACION_PERMISO,
          tm.ESTADO_ELIMINACION AS ESTADO_ELIMINACION_MODULO,
          tp.ESTADO AS ESTADO_PERMISO,
          tm.ESTADO AS ESTADO_MODULO,
          tr.ESTADO_ELIMINACION AS ESTADO_ELIMINACION_ROL,
          tr.ESTADO AS ESTADO_ROL
     FROM TBL_PERMISO tp
          INNER JOIN TBL_MODULO tm ON tp.ID_MODULO = tm.ID_MODULO
          INNER JOIN TBL_ROL tr ON tr.ID_ROL = tp.ID_ROL
          INNER JOIN TBL_MODULO tm2 ON tm2.ID_MODULO = tm.ID_MODULO_PADRE
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTALISTASOLIC" ("SOLICITUD_ID", "EMPRESA_PROVEEDOR", "LICITACION", "PO_UNOPS", "USUARIO_ACTUAL_S", "FECHACREO", "ESTADO_DESCRIPCION", "FECHA_SOLICITUD_CITA", "TIPO_COMPRA", "SOLICITUD_FIRMADA", "CITA_ID", "ESTADO", "ESTADO_SOL_ID", "FINALIZADA") AS 
  SELECT DISTINCT
          S.SOLICITUD_ID,
          P.EMPRESA_PROVEEDOR,
          S.LICITACION,
          S.PO_UNOPS,
          S.USUARIO_ACTUAL AS USUARIO_ACTUAL_S,
          TO_CHAR (S.FECHA_CREO, 'DD-MM-YYYY') AS FECHACREO,
          ES.ESTADO_DESCRIPCION AS ESTADO_DESCRIPCION,
          S.FECHA_SOLICITUD_CITA,
          DECODE (S.TIPO_COMPRA,
                  1, 'Compra Directa',
                  2, 'Licitación IHSS',
                  3, 'Licitación UNOPS')
             AS TIPO_COMPRA,
          S.SOLICITUD_FIRMADA,
          C.CITA_ID,
          S.ESTADO,
          ES.ESTADO_SOL_ID, 
          S.FINALIZADA
     FROM SOLICITUD S
          INNER JOIN PROVEEDOR P ON P.CODIGO_PROVEEDOR = S.CODIGO_PROVEEDOR
          LEFT JOIN
          (SELECT SOLICITUD_ID, ESTADO_SOL_ID
             FROM SEGUIMIENTO_SOLICITUD
            WHERE (SOLICITUD_ID, FECHA_CREO) IN (  SELECT SOLICITUD_ID,
                                                          MAX (FECHA_CREO)
                                                     FROM SEGUIMIENTO_SOLICITUD
                                                 GROUP BY SOLICITUD_ID))
          LAST_ESTADO_SS
             ON LAST_ESTADO_SS.SOLICITUD_ID = S.SOLICITUD_ID
          LEFT JOIN SEGUIMIENTO_SOLICITUD SS
             ON     SS.SOLICITUD_ID = S.SOLICITUD_ID
                AND SS.ESTADO_SOL_ID = LAST_ESTADO_SS.ESTADO_SOL_ID
          LEFT JOIN ESTADO_SOLICITUD ES
             ON ES.ESTADO_SOL_ID = SS.ESTADO_SOL_ID
          LEFT JOIN CITA C ON C.SOLICITUD_ID = S.SOLICITUD_ID
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTALISTASOLICREP" ("SOLICITUD_ID", "EMPRESA_PROVEEDOR", "LICITACION", "PO_UNOPS", "USUARIO_ACTUAL_S", "FECHA_CREO", "ESTADO_DESCRIPCION", "FECHA_SOLICITUD_CITA", "TIPO_COMPRA") AS 
  SELECT DISTINCT
          S.SOLICITUD_ID,
          P.EMPRESA_PROVEEDOR,
          S.LICITACION,
          S.PO_UNOPS,
          U.NOMBRE AS USUARIO_ACTUAL_S,
          S.FECHA_CREO,
          ES.ESTADO_DESCRIPCION AS ESTADO_DESCRIPCION,
          S.FECHA_SOLICITUD_CITA,
          DECODE (S.TIPO_COMPRA,
                  1, 'Compra Directa',
                  2, 'Licitación IHSS',
                  3, 'Licitación UNOPS')
             AS TIPO_COMPRA
     FROM SOLICITUD S
          INNER JOIN PROVEEDOR P ON P.CODIGO_PROVEEDOR = S.CODIGO_PROVEEDOR
          INNER JOIN TBL_USUARIO U ON S.USUARIO_ACTUAL = U.ID_USUARIO
          LEFT JOIN
          (SELECT SOLICITUD_ID, ESTADO_SOL_ID
             FROM SEGUIMIENTO_SOLICITUD
            WHERE (SOLICITUD_ID, FECHA_CREO) IN (  SELECT SOLICITUD_ID,
                                                          MAX (FECHA_CREO)
                                                     FROM SEGUIMIENTO_SOLICITUD
                                                 GROUP BY SOLICITUD_ID))
          LAST_ESTADO_SS
             ON LAST_ESTADO_SS.SOLICITUD_ID = S.SOLICITUD_ID
          LEFT JOIN SEGUIMIENTO_SOLICITUD SS
             ON     SS.SOLICITUD_ID = S.SOLICITUD_ID
                AND SS.ESTADO_SOL_ID = LAST_ESTADO_SS.ESTADO_SOL_ID
          LEFT JOIN ESTADO_SOLICITUD ES
             ON ES.ESTADO_SOL_ID = SS.ESTADO_SOL_ID
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTALISTAUSUARIOS" ("ID_USUARIO", "NOMBRE", "USUARIO", "CORREO", "NOMBRE_DOMINIO", "NOMBRE_DEPARTAMENTO", "NOMBRE_MUNICIPIO", "FECHA_EXPIRACION", "ID_USUARIO_DOMINIO", "NOMBRE_REGIONAL", "ESTADO_ELIMINACION", "ESTADO", "NOMBRE_ROL", "ID_ROL") AS 
  SELECT tu.ID_USUARIO, tu.NOMBRE, tu.USUARIO, tu.CORREO, td.NOMBRE_DOMINIO, tdp.NOMBRE_DEPARTAMENTO, tm.NOMBRE_MUNICIPIO, 
tu.FECHA_EXPIRACION, tu.ID_USUARIO_DOMINIO, tr.NOMBRE_REGIONAL,tu.ESTADO_ELIMINACION, tu.ESTADO,trl.NOMBRE_ROL ,trl.ID_ROL 
FROM TBL_USUARIO tu INNER JOIN TBL_DOMINIO td ON tu.ID_DOMINIO =td.ID_DOMINIO
INNER JOIN TBL_DEPARTAMENTO tdp ON tu.ID_DEPARTAMENTO=tdp.ID_DEPARTAMENTO 
INNER JOIN TBL_MUNICIPIO tm ON tu.ID_MUNICIPIO=tm.ID_MUNICIPIO 
INNER JOIN TBL_REGIONAL tr ON tu.ID_REGIONAL =tr.ID_REGIONAL
INNER JOIN TBL_ROL trl ON tu.ID_ROL =trl.ID_ROL
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTA_LISTASOLICITUDYDETALLE" ("SOLICITUD_ID", "EMPRESA_PROVEEDOR", "LICITACION", "PO_UNOPS", "FECHA_SOLICITUD_CITA", "ITEM", "CODIGO", "DESCRIPCION", "UND", "ENTREGA", "LOTE", "VENCE", "CANTIDAD", "TOTAL", "TIPO_COMPRA") AS 
  SELECT s.SOLICITUD_ID,
            p.EMPRESA_PROVEEDOR,
            s.LICITACION,
            s.PO_UNOPS,
            s.FECHA_SOLICITUD_CITA,
            DM.ITEM,
            DM.CODIGO,
            DM.DESCRIPCION,
            DM.UND,
            DM.ENTREGA,
            LISTAGG (DS.LOTE, ', ') WITHIN GROUP (ORDER BY DS.LOTE) AS LOTE,
            LISTAGG (DS.VENCE, ', ') WITHIN GROUP (ORDER BY DS.VENCE) AS VENCE,
            LISTAGG (DS.CANTIDAD, ', ') WITHIN GROUP (ORDER BY DS.CANTIDAD)
               AS CANTIDAD,
            DM.TOTAL,
            DECODE (S.TIPO_COMPRA,
                    1, 'Compra Directa',
                    2, 'Licitación IHSS',
                    3, 'Licitación UNOPS')
               AS TIPO_COMPRA
       FROM SOLICITUD s
            INNER JOIN DETALLE_MEDICAMENTO_SOL DM
               ON DM.SOLICITUD_ID = S.SOLICITUD_ID
            INNER JOIN DETALLE_SOLICITUD DS
               ON DS.DETALLE_MED_ID = DM.DETALLE_MED_ID
            INNER JOIN PROVEEDOR p ON P.CODIGO_PROVEEDOR = S.CODIGO_PROVEEDOR
   GROUP BY s.SOLICITUD_ID,
            p.EMPRESA_PROVEEDOR,
            s.LICITACION,
            s.PO_UNOPS,
            s.FECHA_SOLICITUD_CITA,
            DM.ITEM,
            DM.CODIGO,
            DM.DESCRIPCION,
            DM.UND,
            DM.ENTREGA,
            DM.TOTAL,
            S.TIPO_COMPRA
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTA_LSTDETALLECOMPLETO" ("ITEM", "CODIGO", "DESCRIPCION", "UND", "ENTREGA", "TOTAL", "LOTE", "VENCE", "CANTIDAD", "DETALLE_SOL_ID", "SOLICITUD_ID", "DETALLE_MED_ID") AS 
  SELECT DM.ITEM,
            DM.CODIGO,
            DM.DESCRIPCION,
            DM.UND,
            DM.ENTREGA,
            DM.TOTAL,
            LISTAGG (DS.LOTE, ', ') WITHIN GROUP (ORDER BY DS.LOTE) AS LOTE,
            LISTAGG (DS.VENCE, ', ') WITHIN GROUP (ORDER BY DS.VENCE) AS VENCE,
            LISTAGG (DS.CANTIDAD, ', ') WITHIN GROUP (ORDER BY DS.CANTIDAD)
               AS CANTIDAD,
            LISTAGG (DS.DETALLE_SOLI_ID, ', ')
               WITHIN GROUP (ORDER BY DS.DETALLE_SOLI_ID)
               AS DETALLE_SOL_ID,
            S.SOLICITUD_ID,
            DM.DETALLE_MED_ID
       FROM DETALLE_MEDICAMENTO_SOL DM
            INNER JOIN DETALLE_SOLICITUD DS
               ON DS.DETALLE_MED_ID = DM.DETALLE_MED_ID
            LEFT JOIN SOLICITUD S ON S.SOLICITUD_ID = DM.SOLICITUD_ID
   GROUP BY DM.ITEM,
            DM.CODIGO,
            DM.DESCRIPCION,
            DM.UND,
            DM.ENTREGA,
            DM.TOTAL,
            S.SOLICITUD_ID,
            DM.DETALLE_MED_ID
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTA_LSTSEGUIMIENTOSOLICITUD" ("USUARIO_ACTUAL", "USUARIO_ASIGNO", "ESTADO_DESCRIPCION", "OBSERVACIONES", "FECHA_CREO", "SOLICITUD_ID", "SEGUIMIENTO_SOL_ID") AS 
  SELECT UA.NOMBRE AS USUARIO_ACTUAL,
          UAS.NOMBRE AS USUARIO_ASIGNO,
          ES.ESTADO_DESCRIPCION,
          S.OBSERVACIONES,
          S.FECHA_CREO,
          SL.SOLICITUD_ID,
          S.SEGUIMIENTO_SOL_ID
     FROM SEGUIMIENTO_SOLICITUD S
          INNER JOIN ESTADO_SOLICITUD ES
             ON ES.ESTADO_SOL_ID = S.ESTADO_SOL_ID
          LEFT JOIN TBL_USUARIO UAS ON UAS.ID_USUARIO = S.USUARIO_ASIGNO
          LEFT JOIN SOLICITUD SL ON S.SOLICITUD_ID = SL.SOLICITUD_ID
          LEFT JOIN TBL_USUARIO UA ON UA.ID_USUARIO = S.USUARIO_ACTUAL
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTA_LSTSOLICOMPLETO" ("SOLICITUD_ID", "EMPRESA_PROVEEDOR", "LICITACION", "PO_UNOPS", "FECHA_SOLICITUD_CITA", "ORDEN_COMPRA", "FECHA_CITA", "HORA_CITA", "DESCRPCION_UBICACION", "TIPO_COMPRA", "CODIGO_PROVEEDOR", "TIPO_COMP") AS 
  SELECT s.SOLICITUD_ID,
            p.EMPRESA_PROVEEDOR,
            s.LICITACION,
            s.PO_UNOPS,
            s.FECHA_SOLICITUD_CITA,
            C.ORDEN_COMPRA,
            C.FECHA_CITA,
            C.HORA_CITA,
            U.DESCRPCION_UBICACION,
            DECODE (S.TIPO_COMPRA,
                    1, 'Compra Directa',
                    2, 'Licitación IHSS',
                    3, 'Licitación UNOPS')
               AS TIPO_COMPRA,
            S.CODIGO_PROVEEDOR,
            S.TIPO_COMPRA AS TIPO_COMP
       FROM SOLICITUD s
            INNER JOIN PROVEEDOR p ON P.CODIGO_PROVEEDOR = S.CODIGO_PROVEEDOR
            LEFT JOIN CITA c ON c.SOLICITUD_ID = S.SOLICITUD_ID
            LEFT JOIN UBICACION u ON U.UBICACION_ID = C.UBICACION_ID
   GROUP BY s.SOLICITUD_ID,
            p.EMPRESA_PROVEEDOR,
            s.LICITACION,
            s.PO_UNOPS,
            s.FECHA_SOLICITUD_CITA,
            C.ORDEN_COMPRA,
            C.FECHA_CITA,
            C.HORA_CITA,
            U.DESCRPCION_UBICACION,
            S.TIPO_COMPRA,
            S.CODIGO_PROVEEDOR
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTA_PADRE_HIJO" ("ID_MODULO_PADRE", "ID_MODULO_HIJO", "NOMBRE_MODULO_PADRE", "NOMBRE_MODULO_HIJO") AS 
  SELECT tm.ID_MODULO AS ID_MODULO_PADRE, tm2.ID_MODULO AS ID_MODULO_HIJO, tm.NOMBRE AS NOMBRE_MODULO_PADRE, tm2.NOMBRE AS NOMBRE_MODULO_HIJO
FROM TBL_MODULO tm
INNER JOIN TBL_MODULO tm2 ON tm.ID_MODULO =tm2.ID_MODULO_PADRE
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VISTA_TIPODOCPROVEEDOR" ("DOCUMENTOS_PROVEEDOR_ID", "TIPO_DOCUMENTO_ID", "TIPO_DOCUMENTO_DESCRIPCION", "ESTADO_DOCPROV", "SOLICITUD_ID") AS 
  SELECT  
   DP.DOCUMENTOS_PROVEEDOR_ID,
          TD.TIPO_DOCUMENTO_ID,
          TD.TIPO_DOCUMENTO_DESCRIPCION,
          DP.ESTADO_DOCPROV,
          DP.SOLICITUD_ID
     FROM TIPO_DOCUMENTO TD
          INNER JOIN DOCUMENTOS_PROVEEDOR DP
             ON DP.TIPO_DOCUMENTO_ID = TD.TIPO_DOCUMENTO_ID
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VMEDCONACTMPARASOLMUES" ("CODIGO", "DESCRIPCION", "UND", "SOLICITUD_ID", "DETALLE_MED_ID", "NOMBRE_GENERICO") AS 
  SELECT DM.CODIGO,
          DM.DESCRIPCION,
          DM.UND,
          DM.SOLICITUD_ID,
          DM.DETALLE_MED_ID,
          AM.NOMBRE_GENERICO
     FROM DETALLE_MEDICAMENTO_SOL DM
     JOIN ACTA_MUESTREO AM ON DM.DETALLE_MED_ID = AM.DETALLE_MED_ID
    WHERE DM.DETALLE_MED_ID IN (SELECT SA.DETALLE_MED_ID
                                  FROM ACTA_MUESTREO SA)
          AND DM.DETALLE_MED_ID NOT IN (SELECT DMS.DETALLE_MED_ID
                                          FROM DET_SOLI_FICHA_RECHAZO DFR
                                          INNER JOIN DETALLE_SOLICITUD DS
                                              ON DS.DETALLE_SOLI_ID = DFR.DETALLE_SOLI_ID
                                          INNER JOIN FICHAS_RECHAZO FR
                                              ON DFR.FICHA_RECHAZO_ID = FR.FICHA_RECHAZO_ID
                                          INNER JOIN DETALLE_MEDICAMENTO_SOL DMS
                                              ON DMS.DETALLE_MED_ID = DS.DETALLE_MED_ID)
          AND NOT EXISTS (SELECT 1
                            FROM SOLICITUD_MUESTREO SM
                           WHERE SM.DETALLE_MED_ID = DM.DETALLE_MED_ID)
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VMEDICAMENTOSCONACTM" ("CODIGO", "DESCRIPCION", "UND", "SOLICITUD_ID", "DETALLE_MED_ID") AS 
  SELECT DM.CODIGO,
          DM.DESCRIPCION,
          DM.UND,
          DM.SOLICITUD_ID,
          DM.DETALLE_MED_ID
     FROM DETALLE_MEDICAMENTO_SOL DM
    WHERE DM.DETALLE_MED_ID IN (SELECT SA.DETALLE_MED_ID
                                   FROM ACTA_MUESTREO SA)
      AND DM.DETALLE_MED_ID NOT IN (SELECT DMS.DETALLE_MED_ID
                                      FROM DET_SOLI_FICHA_RECHAZO DFR
                                           INNER JOIN DETALLE_SOLICITUD DS
                                              ON DS.DETALLE_SOLI_ID = DFR.DETALLE_SOLI_ID
                                           INNER JOIN FICHAS_RECHAZO FR
                                              ON DFR.FICHA_RECHAZO_ID = FR.FICHA_RECHAZO_ID
                                           INNER JOIN DETALLE_MEDICAMENTO_SOL DMS
                                              ON DMS.DETALLE_MED_ID = DS.DETALLE_MED_ID)
      AND NOT EXISTS (SELECT 1
                        FROM MUESTREO_MEDICAMENTOS MM
                       WHERE MM.DETALLE_MED_ID = DM.DETALLE_MED_ID)
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VMEDICAMENTOSCONMUESTREO" ("CODIGO", "DESCRIPCION", "UND", "SOLICITUD_ID", "DETALLE_MED_ID") AS 
  SELECT DM.CODIGO,
          DM.DESCRIPCION,
          DM.UND,
          DM.SOLICITUD_ID,
          DM.DETALLE_MED_ID
     FROM DETALLE_MEDICAMENTO_SOL DM
    WHERE     DM.DETALLE_MED_ID IN (SELECT SA.DETALLE_MED_ID
                                      FROM MUESTREO_MEDICAMENTOS SA)
          AND DM.DETALLE_MED_ID NOT IN (SELECT DMS.DETALLE_MED_ID
                                          FROM DET_SOLI_FICHA_RECHAZO DFR
                                               INNER JOIN
                                               DETALLE_SOLICITUD DS
                                                  ON DS.DETALLE_SOLI_ID =
                                                        DFR.DETALLE_SOLI_ID
                                               INNER JOIN FICHAS_RECHAZO FR
                                                  ON DFR.FICHA_RECHAZO_ID =
                                                        FR.FICHA_RECHAZO_ID
                                               INNER JOIN
                                               DETALLE_MEDICAMENTO_SOL DMS
                                                  ON DMS.DETALLE_MED_ID =
                                                        DS.DETALLE_MED_ID)
          AND NOT EXISTS
                 (SELECT 1
                    FROM SOLICITUD_MUESTREO MM
                   WHERE MM.DETALLE_MED_ID = DM.DETALLE_MED_ID)
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VMEDICAMENTOS_SIN_SOLA_FICR" ("CODIGO", "DESCRIPCION", "UND", "SOLICITUD_ID", "DETALLE_MED_ID") AS 
  SELECT 
    DM.CODIGO,
    DM.DESCRIPCION,
    DM.UND,
    DM.SOLICITUD_ID,
    DM.DETALLE_MED_ID
FROM 
    DETALLE_MEDICAMENTO_SOL DM
WHERE 
    DM.DETALLE_MED_ID NOT IN (
        SELECT SA.DETALLE_MED_ID
        FROM SOLICITUD_ADMINISTRATIVO SA
    )
    AND DM.DETALLE_MED_ID NOT IN (
        SELECT DMS.DETALLE_MED_ID
        FROM DET_SOLI_FICHA_RECHAZO DFR
        INNER JOIN DETALLE_SOLICITUD DS ON DS.DETALLE_SOLI_ID = DFR.DETALLE_SOLI_ID
        INNER JOIN FICHAS_RECHAZO FR ON DFR.FICHA_RECHAZO_ID = FR.FICHA_RECHAZO_ID
        INNER JOIN DETALLE_MEDICAMENTO_SOL DMS ON DMS.DETALLE_MED_ID = DS.DETALLE_MED_ID
    )
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VMEDSINACTM" ("CODIGO", "DESCRIPCION", "UND", "SOLICITUD_ID", "DETALLE_MED_ID") AS 
  SELECT DM.CODIGO,
          DM.DESCRIPCION,
          DM.UND,
          DM.SOLICITUD_ID,
          DM.DETALLE_MED_ID
     FROM DETALLE_MEDICAMENTO_SOL DM
    WHERE     DM.DETALLE_MED_ID NOT IN (SELECT SA.DETALLE_MED_ID
                                          FROM ACTA_MUESTREO SA)
          AND DM.DETALLE_MED_ID NOT IN (SELECT DMS.DETALLE_MED_ID
                                          FROM DET_SOLI_FICHA_RECHAZO DFR
                                               INNER JOIN
                                               DETALLE_SOLICITUD DS
                                                  ON DS.DETALLE_SOLI_ID =
                                                        DFR.DETALLE_SOLI_ID
                                               INNER JOIN FICHAS_RECHAZO FR
                                                  ON DFR.FICHA_RECHAZO_ID =
                                                        FR.FICHA_RECHAZO_ID
                                               INNER JOIN
                                               DETALLE_MEDICAMENTO_SOL DMS
                                                  ON DMS.DETALLE_MED_ID =
                                                        DS.DETALLE_MED_ID)
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."VMED_SIN_SOLOT_FICR" ("CODIGO", "DESCRIPCION", "UND", "SOLICITUD_ID", "DETALLE_MED_ID") AS 
  SELECT 
    DM.CODIGO,
    DM.DESCRIPCION,
    DM.UND,
    DM.SOLICITUD_ID,
    DM.DETALLE_MED_ID
FROM 
    DETALLE_MEDICAMENTO_SOL DM
WHERE 
    DM.DETALLE_MED_ID NOT IN (
        SELECT ST.DETALLE_MED_ID
        FROM SOLICITUD_TECNICA ST
    )
    AND DM.DETALLE_MED_ID NOT IN (
        SELECT DMS.DETALLE_MED_ID
        FROM DET_SOLI_FICHA_RECHAZO DFR
        INNER JOIN DETALLE_SOLICITUD DS ON DS.DETALLE_SOLI_ID = DFR.DETALLE_SOLI_ID
        INNER JOIN FICHAS_RECHAZO FR ON DFR.FICHA_RECHAZO_ID = FR.FICHA_RECHAZO_ID
        INNER JOIN DETALLE_MEDICAMENTO_SOL DMS ON DMS.DETALLE_MED_ID = DS.DETALLE_MED_ID
    )
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_PERMISOS_REPORTUS" ("REPORTE_USUARIO_ID", "REPORTE_ID", "REPORTE_DESCRIPCION", "USUARIO_ID", "HERENCIA", "ORDEN") AS 
  SELECT RU.REPORTE_USUARIO_ID,
          RU.REPORTE_ID,
          R.REPORTE_DESCRIPCION,
          RU.USUARIO_ID,
          R.HERENCIA,
          R.ORDEN
     FROM REPORTE_USUARIO ru
          INNER JOIN REPORTES r ON R.REPORTE_ID = RU.REPORTE_ID
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_PERMISOS_USUARIO_HIJO" ("REPORTE_ID", "REPORTE_USUARIO_ID", "REPORTE_DESCRIPCION", "ORDEN", "HERENCIA", "HERENCIA_PADRE", "USUARIO_ID", "REPORTE_DESCRIPCION_PADRE") AS 
  SELECT R.REPORTE_ID,
            RU.REPORTE_USUARIO_ID,
            R.REPORTE_DESCRIPCION,
            R.ORDEN,
            R1.HERENCIA,
            R.HERENCIA AS HERENCIA_PADRE,
            RU.USUARIO_ID,
            r1.REPORTE_DESCRIPCION AS REPORTE_DESCRIPCION_PADRE
       FROM reportes r
            INNER JOIN REPORTE_USUARIO ru ON R.REPORTE_ID = RU.REPORTE_ID
            INNER JOIN REPORTES r1 ON r.HERENCIA = r1.REPORTE_ID
   ORDER BY R.HERENCIA, R.ORDEN
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_PRUEBASFORLACT" ("PRUEBAS_FORLACTEAS_ID", "DESCRIPCION_PRUEBAS", "TIPO_MEDICAMENTO_DESCRIPCION", "ESTADO", "QUIMICOS", "MICROBIOLOGICOS") AS 
  SELECT PSFL.PRUEBAS_FORLACTEAS_ID,
          PSFL.DESCRIPCION_PRUEBAS,
          TM.TIPO_MEDICAMENTO_DESCRIPCION,
          PSFL.ESTADO, 
          PSFL.QUIMICOS,
          PSFL.MICROBIOLOGICOS
     FROM PRUEBAS_SOLICITADAS_FORLACTEAS PSFL
          INNER JOIN TIPO_MEDICAMENTO TM
             ON TM.TIPO_MEDICAMENTO_ID = PSFL.TIPO_MEDICAMENTO_ID
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_PRUEBASSOL" ("PRUEBAS_SOLICITADAS_ID", "PRUEBAS_DESCRIPCION", "TIPO_MEDICAMENTO_DESCRIPCION", "ESTADO") AS 
  SELECT PS.PRUEBAS_SOLICITADAS_ID,
          PS.PRUEBAS_DESCRIPCION,
          TM.TIPO_MEDICAMENTO_DESCRIPCION, 
          PS.ESTADO
     FROM PRUEBAS_SOLICITADAS PS
          INNER JOIN TIPO_MEDICAMENTO TM
             ON TM.TIPO_MEDICAMENTO_ID = PS.TIPO_MEDICAMENTO_ID
   UNION ALL
   SELECT PSFL.PRUEBAS_FORLACTEAS_ID,
          PSFL.DESCRIPCION_PRUEBAS,
          TM.TIPO_MEDICAMENTO_DESCRIPCION, 
          PSFL.ESTADO
     FROM PRUEBAS_SOLICITADAS_FORLACTEAS PSFL
          INNER JOIN TIPO_MEDICAMENTO TM
             ON TM.TIPO_MEDICAMENTO_ID = PSFL.TIPO_MEDICAMENTO_ID
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_REPORTES_USUARIO" ("REPORTE_ID", "REPORTE_USUARIO_ID", "REPORTE_DESCRIPCION", "ORDEN", "HERENCIA", "USUARIO_ID") AS 
  SELECT R.REPORTE_ID,
            RU.REPORTE_USUARIO_ID,
            R.REPORTE_DESCRIPCION,
            R.ORDEN,
            R.HERENCIA,
            RU.USUARIO_ID
       FROM reportes r
            INNER JOIN REPORTE_USUARIO ru ON R.REPORTE_ID = RU.REPORTE_ID
   ORDER BY R.HERENCIA, R.ORDEN
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_SOLADMINDETXACTAMUES" ("DETALLE_MED_ID", "NUMERO_LOTES", "FECHA_FABRICACION", "FECHA_VENCIMIENTO", "REG_SANITARIO", "TOTAL_UNIDADES") AS 
  WITH CTE_Max_Lote AS (
    SELECT 
        DM.DETALLE_MED_ID,
        DP.NUMERO_LOTES,
        TO_CHAR(DP.FECHA_FABRICACION, 'dd/mm/yyyy') AS FECHA_FABRICACION,
        DP.FECHA_VENCIMIENTO,
        DP.REG_SANITARIO,
        DP.TOTAL_UNIDADES,
        ROW_NUMBER() OVER (
            PARTITION BY DM.DETALLE_MED_ID 
            ORDER BY DP.TOTAL_UNIDADES DESC
        ) AS rn
    FROM 
        CONTROL_ALMACEN.DETALLE_PARTIDA DP
        INNER JOIN CONTROL_ALMACEN.SOLICITUD_ADMINISTRATIVO SA ON DP.SOLI_ADMIN_ID = SA.SOLI_ADMIN_ID
        INNER JOIN CONTROL_ALMACEN.DETALLE_MEDICAMENTO_SOL DM ON DM.DETALLE_MED_ID = SA.DETALLE_MED_ID
)
SELECT 
    DETALLE_MED_ID,
    NUMERO_LOTES,
    FECHA_FABRICACION,
    FECHA_VENCIMIENTO,
    REG_SANITARIO,
    TOTAL_UNIDADES
FROM 
    CTE_Max_Lote
WHERE 
    rn = 1
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_SOLXACTAMUES" ("LICITACION", "SOLICITUD_ID", "ORDEN_COMPRA", "DESCRPCION_UBICACION", "DIRECCION", "TELEFONO", "EMPRESA_PROVEEDOR") AS 
  SELECT S.LICITACION,
          S.SOLICITUD_ID,
          C.ORDEN_COMPRA,
          U.DESCRPCION_UBICACION,
          U.DIRECCION,
          U.TELEFONO, 
          P.EMPRESA_PROVEEDOR
     FROM SOLICITUD S
          INNER JOIN CITA C ON C.SOLICITUD_ID = S.SOLICITUD_ID
          INNER JOIN UBICACION U ON U.UBICACION_ID = C.UBICACION_ID
          INNER JOIN PROVEEDOR P ON P.CODIGO_PROVEEDOR = S.CODIGO_PROVEEDOR
 
 ;
;

CREATE OR REPLACE FORCE VIEW "CONTROL_ALMACEN"."V_USU_SIN_CONTRASENA" ("ID_USUARIO", "NOMBRE", "USUARIO", "CORREO", "ID_DOMINIO", "ID_DEPARTAMENTO", "ID_MUNICIPIO", "FECHA_EXPIRACION", "ID_USUARIO_DOMINIO", "ID_REGIONAL", "ID_USUARIO_CREO", "ID_USUARIO_MODIFICO", "FECHA_CREACION", "FECHA_MODIFICACION", "ESTADO_ELIMINACION", "ESTADO", "ID_ROL", "CONTRASENA_SEGURA", "CAMBIO_CONTRASENA") AS 
  SELECT ID_USUARIO,
          NOMBRE,
          USUARIO,
          CORREO,
          ID_DOMINIO,
          ID_DEPARTAMENTO,
          ID_MUNICIPIO,
          FECHA_EXPIRACION,
          ID_USUARIO_DOMINIO,
          ID_REGIONAL,
          ID_USUARIO_CREO,
          ID_USUARIO_MODIFICO,
          FECHA_CREACION,
          FECHA_MODIFICACION,
          ESTADO_ELIMINACION,
          ESTADO,
          ID_ROL,
          CONTRASENA_SEGURA,
          CAMBIO_CONTRASENA
     FROM TBL_USUARIO
 
 ;
;

CREATE SEQUENCE CONTROL_ALMACEN.ACTA_MUESTREO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.BITACORA_IMPRESION_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.CITA_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.DETALLE_MEDICAMENTO_SOL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.DETALLE_SOLICITUD_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.DET_SOLI_FICHA_RECHAZO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.DET_SOLMUES_EXCEP_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.DET_SOLMUES_SINEXCEP_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.DOCUMENTOS_PROVEEDOR_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.FICHAS_RECHAZO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.MUESTREO_MEDICAMENTOS_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.PROVEEDOR_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.PRUEBAS_EXCEP_FORLACT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.PRUEBAS_SOL_EXCEPCIONES_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.PRUEBAS_SOLICITADAS_FORLAC_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.PRUEBAS_SOLICITADAS_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.REPORTE_USUARIO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEGUIMIENTO_SOLICITUD_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_DETALLEPARTIDA INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_DOMINIO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_MODULO INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_PERMISO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_PRUEBAASSOLI INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_ROL INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_SOLADMIN INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_SOLMUESTREO INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_TIPODOC INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_TIPOMED INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_UBICACION INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SEQ_ID_USUARIO INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SOLICITUDMUE_PRUEBASSOL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SOLICITUD_MUESTREO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SOLICITUD_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SOLICITUD_TECNICA_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.SOLMUES_PRUEBASFORLACT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.TIPO_MEDICAMENTO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE CONTROL_ALMACEN.UBICACION_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

