using System.Text.RegularExpressions;

namespace RL.API.Features.MatricesRiesgos.Domain;

/// <summary>Detecta y repara patrones conocidos de texto visible corrupto.</summary>
public static class TextoVisibleUtf8Normalizer
{
    private static readonly (string From, string To)[] ReemplazosMojibake =
    {
        ("\u00C3\u00A1", "\u00E1"), ("\u00C3\u00A9", "\u00E9"),
        ("\u00C3\u00AD", "\u00ED"), ("\u00C3\u00B3", "\u00F3"),
        ("\u00C3\u00BA", "\u00FA"), ("\u00C3\u00B1", "\u00F1"),
        ("\u00C3\u0081", "\u00C1"), ("\u00C3\u0089", "\u00C9"),
        ("\u00C3\u008D", "\u00CD"), ("\u00C3\u0093", "\u00D3"),
        ("\u00C3\u009A", "\u00DA"), ("\u00C3\u0091", "\u00D1"),
        ("\u00C2\u00BF", "\u00BF"), ("\u00C2\u00A1", "\u00A1"),
        ("\u00C2\u00B0", "\u00B0"), ("\u00C2\u00BA", "\u00BA"),
        ("\u00C2\u00AA", "\u00AA")
    };

    private static readonly (string From, string To)[] ReparacionesContextuales =
    {
        ("Identificaci\u00EF\u00BF\u00BDn", "Identificación"), ("informaci\u00EF\u00BF\u00BDn", "información"),
        ("Evaluaci\u00EF\u00BF\u00BDn", "Evaluación"), ("t\u00EF\u00BF\u00BDcnica", "técnica"),
        ("\u00EF\u00BF\u00BDrea", "Área"), ("Due\u00EF\u00BF\u00BDo", "Dueño"),
        ("Cr\u00EF\u00BF\u00BDtico", "Crítico"),
        ("estrat\u00EF\u00BF\u00BDgico", "estratégico"), ("R\u00EF\u00BF\u00BDgimen", "Régimen"),
        ("interrelaci\u00EF\u00BF\u00BDn", "interrelación"),
        ("Catastr\u00EF\u00BF\u00BDfico", "Catastrófico"),
        ("informaci\u00BFn", "informaci\u00F3n"), ("evaluaci\u00BFn", "evaluaci\u00F3n"),
        ("gesti\u00BFn", "gesti\u00F3n"), ("aprobaci\u00BFn", "aprobaci\u00F3n"),
        ("adjudicaci\u00BFn", "adjudicaci\u00F3n"), ("contrataci\u00BFn", "contrataci\u00F3n"),
        ("licitaci\u00BFn", "licitaci\u00F3n"), ("pensi\u00BFn", "pensi\u00F3n"),
        ("prestaci\u00BFn", "prestaci\u00F3n"), ("definici\u00BFn", "definici\u00F3n"),
        ("ejecuci\u00BFn", "ejecuci\u00F3n"), ("supervisi\u00BFn", "supervisi\u00F3n"),
        ("prevenci\u00BFn", "prevenci\u00F3n"), ("Due\u00BFo", "Due\u00F1o"),
        ("due\u00BFo", "due\u00F1o"), ("Due\u00EF\u00BFo", "Due\u00F1o"),
        ("due\u00EF\u00BFo", "due\u00F1o"), ("v\u00BFnculo", "v\u00EDnculo"),
        ("t\u00BFrmin", "t\u00E9rmin"), ("t\u00BFcnica", "t\u00E9cnica"),
        ("p\u00BAblica", "p\u00FAblica"), ("m\u00BFs", "m\u00E1s"),
        ("Descripci\u00BFn", "Descripción"), ("descripci\u00BFn", "descripción"),
        ("vinculaci\u00BFn", "vinculación"), ("P\u00BFrdidas", "Pérdidas"),
        ("p\u00BFrdidas", "pérdidas"), ("econ\u00BFmicas", "económicas"),
        ("verificaci\u00BFn", "verificación"), ("validaci\u00BFn", "validación"),
        ("instituci\u00BFn", "institución"), ("autom\u00BFticos", "automáticos"),
        ("il\u00BFcitas", "ilícitas"), ("capacitaci\u00BFn", "capacitación"),
        ("documentaci\u00BFn", "documentación"), ("organizaci\u00BFn", "organización"),
        ("operaci\u00BFn", "operación"), ("protecci\u00BFn", "protección"),
        ("situaci\u00BFn", "situación"), ("funci\u00BFn", "función"),
        ("administraci\u00BFn", "administración"), ("identificaci\u00BFn", "identificación"),
        ("calificaci\u00BFn", "calificación"), ("relaci\u00BFn", "relación"),
        ("Secci\u00BFn", "Sección"), ("secci\u00BFn", "sección"),
        ("Afiliaci\u00BFn", "Afiliación"), ("afiliaci\u00BFn", "afiliación"),
        ("\u00EF\u00BFo", "\u00F1o"),
        ("Descripci\u00BFn", "Descripci\u00F3n"),
        ("descripci\u00BFn", "descripci\u00F3n"),
        ("informaci\u00BFn", "informaci\u00F3n"),
        ("vinculaci\u00BFn", "vinculaci\u00F3n"),
        ("P\u00BFrdidas", "P\u00E9rdidas"),
        ("p\u00BFrdidas", "p\u00E9rdidas"),
        ("econ\u00BFmicas", "econ\u00F3micas"),
        ("verificaci\u00BFn", "verificaci\u00F3n"),
        ("validaci\u00BFn", "validaci\u00F3n"),
        ("instituci\u00BFn", "instituci\u00F3n"),
        ("autom\u00BFticos", "autom\u00E1ticos"),
        ("il\u00BFcitas", "il\u00EDcitas"),
        ("evaluaci\u00BFn", "evaluaci\u00F3n"),
        ("gesti\u00BFn", "gesti\u00F3n"),
        ("aprobaci\u00BFn", "aprobaci\u00F3n"),
        ("adjudicaci\u00BFn", "adjudicaci\u00F3n"),
        ("contrataci\u00BFn", "contrataci\u00F3n"),
        ("licitaci\u00BFn", "licitaci\u00F3n"),
        ("pensi\u00BFn", "pensi\u00F3n"),
        ("prestaci\u00BFn", "prestaci\u00F3n"),
        ("definici\u00BFn", "definici\u00F3n"),
        ("ejecuci\u00BFn", "ejecuci\u00F3n"),
        ("supervisi\u00BFn", "supervisi\u00F3n"),
        ("prevenci\u00BFn", "prevenci\u00F3n"),
        ("documentaci\u00BFn", "documentaci\u00F3n"),
        ("capacitaci\u00BFn", "capacitaci\u00F3n"),
        ("operaci\u00BFn", "operaci\u00F3n"),
        ("organizaci\u00BFn", "organizaci\u00F3n"),
        ("funci\u00BFn", "funci\u00F3n"),
        ("situaci\u00BFn", "situaci\u00F3n"),
        ("administraci\u00BFn", "administraci\u00F3n"),
        ("identificaci\u00BFn", "identificaci\u00F3n"),
        ("protecci\u00BFn", "protecci\u00F3n"),
        ("calificaci\u00BFn", "calificaci\u00F3n"),
        ("relaci\u00BFn", "relaci\u00F3n"),
        ("p\u00BAblica", "p\u00FAblica"),
        ("m\u00BFs", "m\u00E1s"),
        ("t\u00BFrmin", "t\u00E9rmin"),
        ("t\u00BFcnica", "t\u00E9cnica"),
        ("Due\u00BFo", "Due\u00F1o"),
        ("due\u00BFo", "due\u00F1o"),
        ("v\u00BFnculo", "v\u00EDnculo"),
        ("\u00BFreas", "\u00E1reas"),
        ("\u00BFtica", "\u00E9tica"),
        ("Acci\u00BFn", "Acci\u00F3n"),
        ("Aceptaci\u00BFn", "Aceptaci\u00F3n"),
        ("actualizaci\u00BFn", "actualizaci\u00F3n"),
        ("admisi\u00BFn", "admisi\u00F3n"),
        ("adquisici\u00BFn", "adquisici\u00F3n"),
        ("Afectaci\u00BFn", "Afectaci\u00F3n"),
        ("afectaci\u00BFn", "afectaci\u00F3n"),
        ("afiliaci\u00BFn", "afiliaci\u00F3n"),
        ("Ampliaci\u00BFn", "Ampliaci\u00F3n"),
        ("an\u00BFlisis", "an\u00E1lisis"),
        ("anal\u00BFtica", "anal\u00EDtica"),
        ("anticorrupci\u00BFn", "anticorrupci\u00F3n"),
        ("aplicaci\u00BFn", "aplicaci\u00F3n"),
        ("apropiaci\u00BFn", "apropiaci\u00F3n"),
        ("asesor\u00BFas", "asesor\u00EDas"),
        ("atenci\u00BFn", "atenci\u00F3n"),
        ("auditor\u00BFa", "auditor\u00EDa"),
        ("auditor\u00BFas", "auditor\u00EDas"),
        ("autenticaci\u00BFn", "autenticaci\u00F3n"),
        ("autom\u00BFticas", "autom\u00E1ticas"),
        ("biom\u00BFtrica", "biom\u00E9trica"),
        ("c\u00BFclicos", "c\u00EDclicos"),
        ("c\u00BFdigo", "c\u00F3digo"),
        ("c\u00BFnyuge", "c\u00F3nyuge"),
        ("Calificaci\u00BFn", "Calificaci\u00F3n"),
        ("canalizaci\u00BFn", "canalizaci\u00F3n"),
        ("cancelaci\u00BFn", "cancelaci\u00F3n"),
        ("ciudadan\u00BFa", "ciudadan\u00EDa"),
        ("cl\u00BFnicas", "cl\u00EDnicas"),
        ("cl\u00BFnico", "cl\u00EDnico"),
        ("clasificaci\u00BFn", "clasificaci\u00F3n"),
        ("Colusi\u00BFn", "Colusi\u00F3n"),
        ("colusi\u00BFn", "colusi\u00F3n"),
        ("comercializaci\u00BFn", "comercializaci\u00F3n"),
        ("comit\u00BF", "comit\u00E9"),
        ("comit\u00BFs", "comit\u00E9s"),
        ("Comunicaci\u00BFn", "Comunicaci\u00F3n"),
        ("comunicaci\u00BFn", "comunicaci\u00F3n"),
        ("Concentraci\u00BFn", "Concentraci\u00F3n"),
        ("concesi\u00BFn", "concesi\u00F3n"),
        ("conciliaci\u00BFn", "conciliaci\u00F3n"),
        ("condici\u00BFn", "condici\u00F3n"),
        ("confirmaci\u00BFn", "confirmaci\u00F3n"),
        ("conformaci\u00BFn", "conformaci\u00F3n"),
        ("contin\u00BFe", "contin\u00FAe"),
        ("Contrataci\u00BFn", "Contrataci\u00F3n"),
        ("correcci\u00BFn", "correcci\u00F3n"),
        ("corrupci\u00BFn", "corrupci\u00F3n"),
        ("cotizaci\u00BFn", "cotizaci\u00F3n"),
        ("cr\u00BFtica", "cr\u00EDtica"),
        ("cr\u00BFticas", "cr\u00EDticas"),
        ("cr\u00BFticos", "cr\u00EDticos"),
        ("creaci\u00BFn", "creaci\u00F3n"),
        ("D\u00BFbil", "D\u00E9bil"),
        ("d\u00BFbil", "d\u00E9bil"),
        ("d\u00BFbiles", "d\u00E9biles"),
        ("d\u00BFdivas", "d\u00E1divas"),
        ("da\u00BFo", "da\u00F1o"),
        ("decisi\u00BFn", "decisi\u00F3n"),
        ("Declaraci\u00BFn", "Declaraci\u00F3n"),
        ("depuraci\u00BFn", "depuraci\u00F3n"),
        ("designaci\u00BFn", "designaci\u00F3n"),
        ("despu\u00BFs", "despu\u00E9s"),
        ("digitalizaci\u00BFn", "digitalizaci\u00F3n"),
        ("dise\u00BFen", "dise\u00F1en"),
        ("dise\u00BFo", "dise\u00F1o"),
        ("dispensaci\u00BFn", "dispensaci\u00F3n"),
        ("distorsi\u00BFn", "distorsi\u00F3n"),
        ("distribuci\u00BFn", "distribuci\u00F3n"),
        ("econ\u00BFmica", "econ\u00F3mica"),
        ("econ\u00BFmicos", "econ\u00F3micos"),
        ("efect\u00BFen", "efect\u00FAen"),
        ("elaboraci\u00BFn", "elaboraci\u00F3n"),
        ("espec\u00BFfico", "espec\u00EDfico"),
        ("espec\u00BFficos", "espec\u00EDficos"),
        ("estandarizaci\u00BFn", "estandarizaci\u00F3n"),
        ("f\u00BFsica", "f\u00EDsica"),
        ("f\u00BFsicamente", "f\u00EDsicamente"),
        ("f\u00BFsicos", "f\u00EDsicos"),
        ("facturaci\u00BFn", "facturaci\u00F3n"),
        ("Falsificaci\u00BFn", "Falsificaci\u00F3n"),
        ("falsificaci\u00BFn", "falsificaci\u00F3n"),
        ("filtraci\u00BFn", "filtraci\u00F3n"),
        ("financiaci\u00BFn", "financiaci\u00F3n"),
        ("formalizaci\u00BFn", "formalizaci\u00F3n"),
        ("garant\u00BFa", "garant\u00EDa"),
        ("garant\u00BFas", "garant\u00EDas"),
        ("gu\u00BFas", "gu\u00EDas"),
        ("id\u00BFneos", "id\u00F3neos"),
        ("il\u00BFcito", "il\u00EDcito"),
        ("il\u00BFcitos", "il\u00EDcitos"),
        ("implementaci\u00BFn", "implementaci\u00F3n"),
        ("Infiltraci\u00BFn", "Infiltraci\u00F3n"),
        ("inform\u00BFticos", "inform\u00E1ticos"),
        ("ingenier\u00BFa", "ingenier\u00EDa"),
        ("inspecci\u00BFn", "inspecci\u00F3n"),
        ("integraci\u00BFn", "integraci\u00F3n"),
        ("Intenci\u00BFn", "Intenci\u00F3n"),
        ("inter\u00BFs", "inter\u00E9s"),
        ("interacci\u00BFn", "interacci\u00F3n"),
        ("interpretaci\u00BFn", "interpretaci\u00F3n"),
        ("Interrupci\u00BFn", "Interrupci\u00F3n"),
        ("interrupci\u00BFn", "interrupci\u00F3n"),
        ("Intervenci\u00BFn", "Intervenci\u00F3n"),
        ("inversi\u00BFn", "inversi\u00F3n"),
        ("investigaci\u00BFn", "investigaci\u00F3n"),
        ("jer\u00BFrquica", "jer\u00E1rquica"),
        ("jur\u00BFdicas", "jur\u00EDdicas"),
        ("leg\u00BFtimo", "leg\u00EDtimo"),
        ("m\u00BFdica", "m\u00E9dica"),
        ("m\u00BFdicas", "m\u00E9dicas"),
        ("m\u00BFdicos", "m\u00E9dicos"),
        ("m\u00BFltiples", "m\u00FAltiples"),
        ("Manipulaci\u00BFn", "Manipulaci\u00F3n"),
        ("manipulaci\u00BFn", "manipulaci\u00F3n"),
        ("materializaci\u00BFn", "materializaci\u00F3n"),
        ("medi\u00BFtica", "medi\u00E1tica"),
        ("medi\u00BFticos", "medi\u00E1ticos"),
        ("Metodolog\u00BFa", "Metodolog\u00EDa"),
        ("modificaci\u00BFn", "modificaci\u00F3n"),
        ("n\u00BFmero", "n\u00FAmero"),
        ("n\u00BFmina", "n\u00F3mina"),
        ("obligaci\u00BFn", "obligaci\u00F3n"),
        ("Omisi\u00BFn", "Omisi\u00F3n"),
        ("omisi\u00BFn", "omisi\u00F3n"),
        ("p\u00BFblica", "p\u00FAblica"),
        ("p\u00BFblicas", "p\u00FAblicas"),
        ("p\u00BFblico", "p\u00FAblico"),
        ("p\u00BFblicos", "p\u00FAblicos"),
        ("p\u00BFlizas", "p\u00F3lizas"),
        ("P\u00BFrdida", "P\u00E9rdida"),
        ("p\u00BFrdida", "p\u00E9rdida"),
        ("Parametrizaci\u00BFn", "Parametrizaci\u00F3n"),
        ("per\u00BFodos", "per\u00EDodos"),
        ("Percepci\u00BFn", "Percepci\u00F3n"),
        ("peri\u00BFdica", "peri\u00F3dica"),
        ("peri\u00BFdicas", "peri\u00F3dicas"),
        ("peri\u00BFdico", "peri\u00F3dico"),
        ("planificaci\u00BFn", "planificaci\u00F3n"),
        ("podr\u00BFa", "podr\u00EDa"),
        ("pol\u00BFtica", "pol\u00EDtica"),
        ("Pol\u00BFticamente", "Pol\u00EDticamente"),
        ("Pol\u00BFticas", "Pol\u00EDticas"),
        ("pol\u00BFticas", "pol\u00EDticas"),
        ("Pr\u00BFcticas", "Pr\u00E1cticas"),
        ("pr\u00BFcticas", "pr\u00E1cticas"),
        ("pr\u00BFrrogas", "pr\u00F3rrogas"),
        ("Presi\u00BFn", "Presi\u00F3n"),
        ("presi\u00BFn", "presi\u00F3n"),
        ("prop\u00BFsito", "prop\u00F3sito"),
        ("qu\u00BF", "qu\u00E9"),
        ("r\u00BFpidamente", "r\u00E1pidamente"),
        ("realizaci\u00BFn", "realizaci\u00F3n"),
        ("recepci\u00BFn", "recepci\u00F3n"),
        ("revisi\u00BFn", "revisi\u00F3n"),
        ("rotaci\u00BFn", "rotaci\u00F3n"),
        ("s\u00BF", "s\u00ED"),
        ("sanci\u00BFn", "sanci\u00F3n"),
        ("se\u00BFalamientos", "se\u00F1alamientos"),
        ("Secci\u00BFn", "Secci\u00F3n"),
        ("secci\u00BFn", "secci\u00F3n"),
        ("segregaci\u00BFn", "segregaci\u00F3n"),
        ("selecci\u00BFn", "selecci\u00F3n"),
        ("simulaci\u00BFn", "simulaci\u00F3n"),
        ("simult\u00BFneamente", "simult\u00E1neamente"),
        ("sobrevaloraci\u00BFn", "sobrevaloraci\u00F3n"),
        ("suplantaci\u00BFn", "suplantaci\u00F3n"),
        ("sustracci\u00BFn", "sustracci\u00F3n"),
        ("t\u00BFcnicos", "t\u00E9cnicos"),
        ("tecnol\u00BFgicas", "tecnol\u00F3gicas"),
        ("tecnolog\u00BFa", "tecnolog\u00EDa"),
        ("Tesorer\u00BFa", "Tesorer\u00EDa"),
        ("tr\u00BFmites", "tr\u00E1mites"),
        ("trav\u00BFs", "trav\u00E9s"),
        ("uni\u00BFn", "uni\u00F3n"),
        ("utilizaci\u00BFn", "utilizaci\u00F3n"),
        ("Vinculaci\u00BFn", "Vinculaci\u00F3n"),
        ("violaci\u00BFn", "violaci\u00F3n"),
    };

    private static readonly Regex SignoPreguntaIncrustado =
        new("(?i)(?<=\\p{L})\\u00BF(?=\\p{L})", RegexOptions.CultureInvariant, TimeSpan.FromMilliseconds(100));

    public static bool ContieneMojibake(string? valor)
    {
        if (string.IsNullOrEmpty(valor)) return false;
        return valor.Contains('\uFFFD')
            || valor.Contains("\u00EF\u00BF\u00BD", StringComparison.Ordinal)
            || valor.Contains("\u00EF\u00BFo", StringComparison.Ordinal)
            || valor.Contains('\u00C3') || valor.Contains('\u00C2')
            || valor.Contains("\u00E2\u20AC", StringComparison.Ordinal)
            || valor.Contains("\u00F0\u0178", StringComparison.Ordinal)
            || SignoPreguntaIncrustado.IsMatch(valor);
    }

    public static string Normalizar(string valor)
    {
        if (string.IsNullOrEmpty(valor)) return valor;
        string resultado = valor;
        foreach ((string from, string to) in ReemplazosMojibake)
            resultado = resultado.Replace(from, to, StringComparison.Ordinal);
        foreach ((string from, string to) in ReparacionesContextuales)
            resultado = resultado.Replace(from, to, StringComparison.OrdinalIgnoreCase);
        return resultado;
    }

    public static string? NormalizarNullable(string? valor) => valor is null ? null : Normalizar(valor);
}
